// AUTO-GENERATED by cpp_docstrings_from_json.py — DO NOT EDIT
// Package: SMDS_3
#ifndef CGAL_PYTHON_DOCSTRINGS_SMDS_3_H
#define CGAL_PYTHON_DOCSTRINGS_SMDS_3_H

namespace cgalpy {
namespace docstrings {
namespace SMDS_3 {

constexpr const char* CGAL_Compact_simplicial_mesh_cell_3_Has_timestamp = "For the determinism of Compact_container iterators.

Returns: Tag_true";
constexpr const char* CGAL_Compact_simplicial_mesh_cell_3_surface_index_table = "Stores surface_index for each facet of the cell.

Returns: std::array< Surface_patch_index, 4 >";
constexpr const char* CGAL_Compact_simplicial_mesh_cell_3_set_surface_patch_index = "Set surface index of facet to index .

Parameters
----------
facet : const int
index : const Surface_patch_index &";
constexpr const char* CGAL_Compact_simplicial_mesh_cell_3_surface_patch_index = "Returns surface index of facet facet .

Parameters
----------
facet : const int

Returns: Surface_patch_index";
constexpr const char* CGAL_Compact_simplicial_mesh_cell_3_is_facet_on_surface = "Returns true if facet lies on a surface patch.

Parameters
----------
facet : const int

Returns: bool";
constexpr const char* CGAL_Compact_simplicial_mesh_cell_3_surface_index = "Returns surface index of facet facet .

Parameters
----------
facet : const int

Returns: Surface_index";

// CGAL::Compact_simplicial_mesh_cell_base_3
constexpr const char* CGAL_Compact_simplicial_mesh_cell_base_3__class__ = "The class Compact_simplicial_mesh_cell_base_3 is a model of the concept SimplicialMeshCellBase_3 .";






















// CGAL::Mesh_complex_3_in_triangulation_3
constexpr const char* CGAL_Mesh_complex_3_in_triangulation_3__class__ = "A data structure to represent and maintain a 3D complex embedded in a 3D triangulation.";

constexpr const char* CGAL_Mesh_complex_3_in_triangulation_3_Index = "Index type.

Returns: Tr::Vertex::Index";
constexpr const char* CGAL_Mesh_complex_3_in_triangulation_3_Surface_patch_index = "Surface index type.

Returns: Tr::Cell::Surface_patch_index";
constexpr const char* CGAL_Mesh_complex_3_in_triangulation_3_Subdomain_index = "Subdomain index type.

Returns: Tr::Cell::Subdomain_index";
constexpr const char* CGAL_Mesh_complex_3_in_triangulation_3_Corner_index = "Corner index type.

Returns: CornerIndex";
constexpr const char* CGAL_Mesh_complex_3_in_triangulation_3_Curve_index = "Curve index type.

Returns: CurveIndex";
constexpr const char* CGAL_Mesh_complex_3_in_triangulation_3_Cells_in_complex_iterator = "Iterator type to visit the cells of the 3D complex.

Returns: unspecified_type";
constexpr const char* CGAL_Mesh_complex_3_in_triangulation_3_Facets_in_complex_iterator = "Iterator type to visit the facets of the 2D complex.

Returns: unspecified_type";
constexpr const char* CGAL_Mesh_complex_3_in_triangulation_3_Edges_in_complex_iterator = "Iterator type to visit the edges of the 1D complex.

Returns: unspecified_type";
constexpr const char* CGAL_Mesh_complex_3_in_triangulation_3_Vertices_in_complex_iterator = "Iterator type to visit the vertices of the 0D complex.

Returns: unspecified_type";
constexpr const char* CGAL_Mesh_complex_3_in_triangulation_3_Cells_in_complex = "Range type for iterating over all cells of the 3D complex, with a nested type iterator that has as value type Cell_handle .

Returns: Iterator_range< unspecified_type >";
constexpr const char* CGAL_Mesh_complex_3_in_triangulation_3_Facets_in_complex = "Range type for iterating over all facets of the 2D complex, with a nested type iterator that has as value type Facet .

Returns: Iterator_range< unspecified_type >";
constexpr const char* CGAL_Mesh_complex_3_in_triangulation_3_Edges_in_complex = "Range type for iterating over all cells of the 1D complex, with a nested type iterator that has as value type Edge .

Returns: Iterator_range< unspecified_type >";
constexpr const char* CGAL_Mesh_complex_3_in_triangulation_3_Vertices_in_complex = "Range type for iterating over all vertices of the 0D complex, with a nested type iterator that has as value type Vertex_handle .

Returns: Iterator_range< unspecified_type >";
constexpr const char* CGAL_Mesh_complex_3_in_triangulation_3_Mesh_complex_3_in_triangulation_3 = "Constructor builds an empty 3D complex.";
constexpr const char* CGAL_Mesh_complex_3_in_triangulation_3_Mesh_complex_3_in_triangulation_3_1 = "Copy constructor.

Parameters
----------
rhs : const Self &";
constexpr const char* CGAL_Mesh_complex_3_in_triangulation_3_Mesh_complex_3_in_triangulation_3_2 = "Move constructor.

Parameters
----------
rhs : Self &&";
constexpr const char* CGAL_Mesh_complex_3_in_triangulation_3_operator = "Assignment operator, also serves as move-assignment.

Parameters
----------
rhs : Self

Returns: Self &";
constexpr const char* CGAL_Mesh_complex_3_in_triangulation_3_swap = "swaps this and rhs

Parameters
----------
rhs : Self &";
constexpr const char* CGAL_Mesh_complex_3_in_triangulation_3_triangulation = "returns a const reference to the triangulation

Returns: const Triangulation &";
constexpr const char* CGAL_Mesh_complex_3_in_triangulation_3_clear = "clears data of the complex";
constexpr const char* CGAL_Mesh_complex_3_in_triangulation_3_set_triangulation = "sets the internal triangulation to tr

Parameters
----------
tr : const Triangulation &";
constexpr const char* CGAL_Mesh_complex_3_in_triangulation_3_set_triangulation_1 = "sets the internal triangulation to tr

Parameters
----------
tr : Triangulation &&";
constexpr const char* CGAL_Mesh_complex_3_in_triangulation_3_add_to_complex = "adds cell cell to the 3D complex, with subdomain index index

Parameters
----------
cell : const Cell_handle &
index : const Subdomain_index &";
constexpr const char* CGAL_Mesh_complex_3_in_triangulation_3_add_to_complex_1 = "adds facet facet to the 2D complex, with surface index index

Parameters
----------
facet : const Facet &
index : const Surface_patch_index &";
constexpr const char* CGAL_Mesh_complex_3_in_triangulation_3_add_to_complex_2 = "adds facet( cell , i ) to the 2D complex, with surface index index

Parameters
----------
cell : const Cell_handle &
i : const int
index : const Surface_patch_index &";
constexpr const char* CGAL_Mesh_complex_3_in_triangulation_3_add_to_complex_3 = "adds edge e to complex, with curve index index

Parameters
----------
e : const Edge &
index : const Curve_index &";
constexpr const char* CGAL_Mesh_complex_3_in_triangulation_3_add_to_complex_4 = "adds edge ( v1 , v2 ) to the 1D complex, with Curve_index index

Parameters
----------
v1 : const Vertex_handle &
v2 : const Vertex_handle &
index : const Curve_index &";
constexpr const char* CGAL_Mesh_complex_3_in_triangulation_3_add_to_complex_5 = "marks vertex v as a corner of the complex

Parameters
----------
v : const Vertex_handle &
index : const Corner_index &";
constexpr const char* CGAL_Mesh_complex_3_in_triangulation_3_remove_from_complex = "removes cell cell from the 3D complex

Parameters
----------
cell : const Cell_handle &";
constexpr const char* CGAL_Mesh_complex_3_in_triangulation_3_remove_from_complex_1 = "removes facet facet from the 2D complex

Parameters
----------
facet : const Facet &";
constexpr const char* CGAL_Mesh_complex_3_in_triangulation_3_remove_from_complex_2 = "removes facet( cell , i ) from the 2D complex

Parameters
----------
c : const Cell_handle &
i : const int";
constexpr const char* CGAL_Mesh_complex_3_in_triangulation_3_remove_from_complex_3 = "removes edge e from the 1D complex

Parameters
----------
e : const Edge &";
constexpr const char* CGAL_Mesh_complex_3_in_triangulation_3_remove_from_complex_4 = "removes edge (v1,v2) from the 1D complex

Parameters
----------
v1 : const Vertex_handle &
v2 : const Vertex_handle &";
constexpr const char* CGAL_Mesh_complex_3_in_triangulation_3_remove_from_complex_5 = "removes vertex v from the complex

Parameters
----------
v : const Vertex_handle &";
constexpr const char* CGAL_Mesh_complex_3_in_triangulation_3_set_index = "sets the index of vertex vertex to index

Parameters
----------
vertex : const Vertex_handle &
index : const Index &";
constexpr const char* CGAL_Mesh_complex_3_in_triangulation_3_set_surface_patch_index = "sets the surface index of facet facet to index

Parameters
----------
f : const Facet &
index : const Surface_patch_index &";
constexpr const char* CGAL_Mesh_complex_3_in_triangulation_3_set_surface_patch_index_1 = "sets the surface index of facet( cell , i ) to index

Parameters
----------
cell : const Cell_handle &
i : const int
index : const Surface_patch_index &";
constexpr const char* CGAL_Mesh_complex_3_in_triangulation_3_set_subdomain_index = "sets the subdomain index of cell cell to index

Parameters
----------
cell : const Cell_handle &
index : const Subdomain_index &";
constexpr const char* CGAL_Mesh_complex_3_in_triangulation_3_set_dimension = "sets the dimension of vertex vertex to dimension

Parameters
----------
vertex : const Vertex_handle &
dimension : int";
constexpr const char* CGAL_Mesh_complex_3_in_triangulation_3_index = "returns the index of vertex v

Parameters
----------
v : const Vertex_handle &

Returns: Index";
constexpr const char* CGAL_Mesh_complex_3_in_triangulation_3_subdomain_index = "returns the subdomain index of cell cell

Parameters
----------
cell : const Cell_handle &

Returns: Subdomain_index";
constexpr const char* CGAL_Mesh_complex_3_in_triangulation_3_surface_patch_index = "returns the surface index of facet f

Parameters
----------
f : const Facet &

Returns: Surface_patch_index";
constexpr const char* CGAL_Mesh_complex_3_in_triangulation_3_surface_patch_index_1 = "returns the surface index of facet( cell , i )

Parameters
----------
cell : const Cell_handle &
i : const int

Returns: Surface_patch_index";
constexpr const char* CGAL_Mesh_complex_3_in_triangulation_3_in_dimension = "returns the dimension of the lowest dimensional face of the input 3D complex that contains the vertex

Parameters
----------
v : const Vertex_handle &

Returns: int";
constexpr const char* CGAL_Mesh_complex_3_in_triangulation_3_curve_index = "returns the curve index of edge e

Parameters
----------
e : const Edge &

Returns: Curve_index";
constexpr const char* CGAL_Mesh_complex_3_in_triangulation_3_curve_index_1 = "returns the curve index of the edge formed by v1 and v2

Parameters
----------
v1 : const Vertex_handle &
v2 : const Vertex_handle &

Returns: Curve_index";
constexpr const char* CGAL_Mesh_complex_3_in_triangulation_3_corner_index = "returns the corner index of vertex v

Parameters
----------
v : const Vertex_handle &

Returns: Corner_index";
constexpr const char* CGAL_Mesh_complex_3_in_triangulation_3_number_of_cells_in_complex = "returns the number of cells which belong to the 3D complex

Returns: size_type";
constexpr const char* CGAL_Mesh_complex_3_in_triangulation_3_number_of_cells = "returns the number of cells which belong to the 3D complex

Returns: size_type";
constexpr const char* CGAL_Mesh_complex_3_in_triangulation_3_number_of_facets_in_complex = "returns the number of surface facets of the complex

Returns: size_type";
constexpr const char* CGAL_Mesh_complex_3_in_triangulation_3_number_of_facets = "returns the number of surface facets of the complex

Returns: size_type";
constexpr const char* CGAL_Mesh_complex_3_in_triangulation_3_number_of_edges_in_complex = "returns the number of edges of the complex

Returns: size_type";
constexpr const char* CGAL_Mesh_complex_3_in_triangulation_3_number_of_edges = "returns the number of edges of the complex

Returns: size_type";
constexpr const char* CGAL_Mesh_complex_3_in_triangulation_3_number_of_vertices_in_complex = "returns the number of corners of the complex

Returns: size_type";
constexpr const char* CGAL_Mesh_complex_3_in_triangulation_3_number_of_corners = "returns the number of corners of the complex

Returns: size_type";
constexpr const char* CGAL_Mesh_complex_3_in_triangulation_3_is_in_complex = "returns true if cell cell belongs to the 3D complex

Parameters
----------
cell : const Cell_handle &

Returns: bool";
constexpr const char* CGAL_Mesh_complex_3_in_triangulation_3_is_in_complex_1 = "returns true if facet facet belongs to the 2D complex

Parameters
----------
facet : const Facet &

Returns: bool";
constexpr const char* CGAL_Mesh_complex_3_in_triangulation_3_is_in_complex_2 = "returns true if facet ( cell , i ) belongs to the 2D complex

Parameters
----------
cell : const Cell_handle &
i : const int

Returns: bool";
constexpr const char* CGAL_Mesh_complex_3_in_triangulation_3_is_in_complex_3 = "returns true if edge e belongs to the 1D complex

Parameters
----------
e : const Edge &

Returns: bool";
constexpr const char* CGAL_Mesh_complex_3_in_triangulation_3_is_in_complex_4 = "returns true if edge (v1,v2) belongs to the 1D complex

Parameters
----------
v1 : const Vertex_handle &
v2 : const Vertex_handle &

Returns: bool";
constexpr const char* CGAL_Mesh_complex_3_in_triangulation_3_is_in_complex_5 = "returns true if v is a 0-dimensional feature in the complex

Parameters
----------
v : const Vertex_handle &

Returns: bool";
constexpr const char* CGAL_Mesh_complex_3_in_triangulation_3_output_boundary_to_off = "outputs the outer boundary of the entire domain, with facets oriented outward.

Parameters
----------
out : std::ostream &

Returns: std::ostream &";
constexpr const char* CGAL_Mesh_complex_3_in_triangulation_3_output_boundary_to_off_1 = "outputs the outer boundary of the selected subdomain, with facets oriented outward.

Parameters
----------
out : std::ostream &
subdomain : Subdomain_index

Returns: std::ostream &";
constexpr const char* CGAL_Mesh_complex_3_in_triangulation_3_output_facets_in_complex_to_off = "outputs the surface facets, with a consistent orientation at the interface of two subdomains.

Parameters
----------
out : std::ostream &

Returns: std::ostream &";
constexpr const char* CGAL_Mesh_complex_3_in_triangulation_3_output_to_medit = "outputs the mesh to os in Medit format.

Parameters
----------
os : std::ostream &";
constexpr const char* CGAL_Mesh_complex_3_in_triangulation_3_cells_in_complex_begin = "returns a Cells_in_complex_iterator to the first cell of the 3D complex

Returns: Cells_in_complex_iterator";
constexpr const char* CGAL_Mesh_complex_3_in_triangulation_3_cells_in_complex_begin_1 = "returns a Cells_in_complex_iterator to the first cell of the 3D complex

Parameters
----------
index : const Subdomain_index &

Returns: Cells_in_complex_iterator";
constexpr const char* CGAL_Mesh_complex_3_in_triangulation_3_cells_in_complex_end = "returns the past-the-end iterator for the cells of the 3D complex

Returns: Cells_in_complex_iterator";
constexpr const char* CGAL_Mesh_complex_3_in_triangulation_3_facets_in_complex_begin = "returns a Facets_in_complex_iterator to the first facet of the 2D complex

Returns: Facets_in_complex_iterator";
constexpr const char* CGAL_Mesh_complex_3_in_triangulation_3_facets_in_complex_begin_1 = "returns a Facets_in_complex_iterator to the first facet of the 2D complex

Parameters
----------
index : const Surface_patch_index &

Returns: Facets_in_complex_iterator";
constexpr const char* CGAL_Mesh_complex_3_in_triangulation_3_facets_in_complex_end = "returns past-the-end iterator on facet of the 2D complex

Parameters
----------
 : const Surface_patch_index

Returns: Facets_in_complex_iterator";
constexpr const char* CGAL_Mesh_complex_3_in_triangulation_3_edges_in_complex_begin = "returns a Edges_in_complex_iterator to the first edge of the 1D complex

Returns: Edges_in_complex_iterator";
constexpr const char* CGAL_Mesh_complex_3_in_triangulation_3_edges_in_complex_begin_1 = "returns a Edges_in_complex_iterator to the first edge of the 1D complex

Parameters
----------
index : const Curve_index &

Returns: Edges_in_complex_iterator";
constexpr const char* CGAL_Mesh_complex_3_in_triangulation_3_edges_in_complex_end = "returns past-the-end iterator on edges of the 1D complex

Parameters
----------
 : const Curve_index &

Returns: Edges_in_complex_iterator";
constexpr const char* CGAL_Mesh_complex_3_in_triangulation_3_vertices_in_complex_begin = "returns a Vertices_in_complex_iterator to the first vertex of the 0D complex

Returns: Vertices_in_complex_iterator";
constexpr const char* CGAL_Mesh_complex_3_in_triangulation_3_vertices_in_complex_begin_1 = "returns a Vertices_in_complex_iterator to the first vertex of the 0D complex

Parameters
----------
index : const Corner_index &

Returns: Vertices_in_complex_iterator";
constexpr const char* CGAL_Mesh_complex_3_in_triangulation_3_vertices_in_complex_end = "returns past-the-end iterator on vertices of the 0D complex

Returns: Vertices_in_complex_iterator";
constexpr const char* CGAL_Mesh_complex_3_in_triangulation_3_vertices_in_complex = "returns a range of iterators over vertices of the 0D complex

The value type of Vertices_in_complex::iterator is Vertex_handle .

Returns: Vertices_in_complex";
constexpr const char* CGAL_Mesh_complex_3_in_triangulation_3_edges_in_complex = "returns a range of iterators over the edges of the 1D complex, starting at an arbitrary edge.

Returns an empty range when t.dimension() < 2 .

Returns: Edges_in_complex";
constexpr const char* CGAL_Mesh_complex_3_in_triangulation_3_facets_in_complex = "returns a range of iterators over the facets of the 2D complex, starting at an arbitrary facet.

Returns an empty range when t.dimension() < 2 .

Returns: Facets_in_complex";
constexpr const char* CGAL_Mesh_complex_3_in_triangulation_3_cells_in_complex = "returns a range of iterators over cells of the 3D complex.

Returns an empty range when triangulation() . number_of_cells() == 0 or
complex is empty. The value type of Cells_in_complex::iterator is Cell_handle
.

Returns: Cells_in_complex";
constexpr const char* CGAL_Mesh_complex_3_in_triangulation_3_remove_isolated_vertices = "The tetrahedral mesh generation algorithm implemented in CGAL::make_mesh_3() and CGAL::refine_mesh_3() does not guarantee that all the points inserted by the algorithm are actually present in the final mesh.

In most cases, all points are used, but if the geometry of the object has
small features compared to the size of the simplices (triangles and
tetrahedra), it might be that the Delaunay facets that are selected in the
restricted Delaunay triangulation miss some vertices of the triangulation. The
concurrent version of the tetrahedral mesh generation algorithm also inserts a
small set of auxiliary vertices that belong to the triangulation but are
isolated from the complex at the end of the meshing process. This function
removes these so-called isolated vertices, that belong to the triangulation
but not to any simplex of the C3T3 , from the triangulation.";
constexpr const char* CGAL_Mesh_complex_3_in_triangulation_3_adjacent_vertices_in_complex = "fills out with incident edges (1-dimensional features of v ).

OutputIterator value type is std::pair<Vertex_handle,Curve_index> v->
in_dimension() < 2

Parameters
----------
v : const Vertex_handle &
out : OutputIterator

Returns: OutputIterator";
constexpr const char* CGAL_Mesh_complex_3_in_triangulation_3_has_incident_facets_in_complex = "Returns true if the vertex v has is incident to at least a facet of the complex.

Parameters
----------
v : const Vertex_handle &

Returns: bool";
constexpr const char* CGAL_Mesh_complex_3_in_triangulation_3_union_find_of_incident_facets = "Extract the subset F of facets of the complex incident to v and return the number of connected component of the adjacency graph of F .

Parameters
----------
v : const Vertex_handle

Returns: std::size_t";

// CGAL::Mesh_complex_3_in_triangulation_3::Cell_not_in_complex
constexpr const char* CGAL_Mesh_complex_3_in_triangulation_3_Cell_not_in_complex__class__ = "A class to filter cells which do not belong to the complex.";









// CGAL::Simplicial_mesh_cell_base_3
constexpr const char* CGAL_Simplicial_mesh_cell_base_3__class__ = "The class Simplicial_mesh_cell_base_3 is a model of the concept SimplicialMeshCellBase_3 .";

constexpr const char* CGAL_Simplicial_mesh_cell_base_3_Has_timestamp = "For the determinism of Compact_container iterators.

Returns: Tag_true";
constexpr const char* CGAL_Simplicial_mesh_cell_base_3_surface_index_table = "Stores surface_index for each facet of the cell.

Returns: std::array< Surface_patch_index, 4 >";
constexpr const char* CGAL_Simplicial_mesh_cell_base_3_set_surface_patch_index = "Set surface index of facet to index .

Parameters
----------
facet : const int
index : const Surface_patch_index &";
constexpr const char* CGAL_Simplicial_mesh_cell_base_3_surface_patch_index = "Returns surface index of facet facet .

Parameters
----------
facet : const int

Returns: Surface_patch_index";
constexpr const char* CGAL_Simplicial_mesh_cell_base_3_is_facet_on_surface = "Returns true if facet lies on a surface patch.

Parameters
----------
facet : const int

Returns: bool";
constexpr const char* CGAL_Simplicial_mesh_cell_base_3_surface_index = "Returns surface index of facet facet .

Parameters
----------
facet : const int

Returns: Surface_index";


// CGAL::Simplicial_mesh_vertex_base_3
constexpr const char* CGAL_Simplicial_mesh_vertex_base_3__class__ = "The class Simplicial_mesh_vertex_base_3 is a model of the concept SimplicialMeshVertexBase_3 .";

constexpr const char* CGAL_Simplicial_mesh_vertex_base_3_Has_timestamp = "For the determinism of Compact_container iterators.

Returns: Tag_true";













// MeshComplex_3InTriangulation_3
constexpr const char* MeshComplex_3InTriangulation_3__class__ = "The concept MeshComplex_3InTriangulation_3 describes a data structure to represent and maintain a 3D complex embedded in a 3D triangulation. More precisely, the concept MeshComplex_3InTriangulation_3 is a minimal version designed to represent 3D complexes that have only faces with dimension $ 2$ and $ 3$ . Embedded 3D complexes with faces of dimension $ 0$ , $ 1$ , $ 2$ and $ 3$ , are more conveniently represented by the refined concept MeshComplexWithFeatures_3InTriangulation_3 .";

constexpr const char* MeshComplex_3InTriangulation_3_Triangulation = "The type of the embedding 3D triangulation.

It is required to be the nested type CGAL::Mesh_triangulation_3::type ,
provided by the class CGAL::Mesh_triangulation_3<MD, GT, Concurrency_tag,
Vertex_base, Cell_base> where the Vertex_base and Cell_base template
parameters are respectively instantiated with models of the concepts
MeshVertexBase_3 and MeshCellBase_3 . The provided triangulation type is then
a CGAL::Regular_triangulation_3 with Vertex_base and Cell_base for
respectively vertex and cell base types.

Returns: unspecified_type";
constexpr const char* MeshComplex_3InTriangulation_3_Vertex_handle = "Type Vertex_handle type of the triangulation.

Returns: Triangulation::Vertex_handle";
constexpr const char* MeshComplex_3InTriangulation_3_Cell_handle = "The Cell_handle type of the triangulation.

Returns: Triangulation::Cell_handle";
constexpr const char* MeshComplex_3InTriangulation_3_Facet = "The Facet type of the triangulation.

Returns: Triangulation::Facet";
constexpr const char* MeshComplex_3InTriangulation_3_Edge = "The Edge type of the triangulation.

Returns: Triangulation::Edge";
constexpr const char* MeshComplex_3InTriangulation_3_size_type = "Size type (unsigned integral type).

Returns: Triangulation::size_type";
constexpr const char* MeshComplex_3InTriangulation_3_Subdomain_index = "A type for indices of subdomains.

This type must match the type MeshDomain_3::Subdomain_index when the concept
is used for mesh generation.

Returns: unspecified_type";
constexpr const char* MeshComplex_3InTriangulation_3_Surface_patch_index = "A type for indices of surface patches.

This type must match the type MeshDomain_3::Surface_patch_index when the
concept is used for mesh generation.

Returns: unspecified_type";
constexpr const char* MeshComplex_3InTriangulation_3_Index = "A type for indexing vertices that belong to some surface patches or subdomains.

This type must match the type MeshDomain_3::Index when the concept is used for
mesh generation.

Returns: unspecified_type";
constexpr const char* MeshComplex_3InTriangulation_3_Cells_in_complex_iterator = "An iterator type to visit the cells of the triangulation belonging to the 3D complex.

Returns: unspecified_type";
constexpr const char* MeshComplex_3InTriangulation_3_Facets_in_complex_iterator = "An iterator type to visit the surface facets.

Returns: unspecified_type";
constexpr const char* MeshComplex_3InTriangulation_3_MeshComplex_3InTriangulation_3 = "Builds an empty 3D complex.";
constexpr const char* MeshComplex_3InTriangulation_3_MeshComplex_3InTriangulation_3_1 = "Copy constructor.

Embedded triangulation is duplicated.

Parameters
----------
rhs : const MeshComplex_3InTriangulation_3 &";
constexpr const char* MeshComplex_3InTriangulation_3_operator = "Assignment operator.

Embedded triangulation is duplicated, and the former triangulation of the 3D
complex is deleted.

Parameters
----------
rhs : const MeshComplex_3InTriangulation_3 &

Returns: MeshComplex_3InTriangulation_3 &";
constexpr const char* MeshComplex_3InTriangulation_3_swap = "Swaps the 3D complex and rhs .

Parameters
----------
rhs : MeshComplex_3InTriangulation_3 &";
constexpr const char* MeshComplex_3InTriangulation_3_triangulation = "Returns a const reference to the triangulation.

Returns: const Triangulation &";
constexpr const char* MeshComplex_3InTriangulation_3_triangulation_1 = "Returns a reference to the triangulation.

Returns: Triangulation &";
constexpr const char* MeshComplex_3InTriangulation_3_add_to_complex = "Sets the cell c as a cell of the subdomain index .

Parameters
----------
c : Cell_handle
index : Subdomain_index";
constexpr const char* MeshComplex_3InTriangulation_3_add_to_complex_1 = "Adds the facet f as a facet of the surface patch index .

Parameters
----------
f : Facet
index : Surface_patch_index";
constexpr const char* MeshComplex_3InTriangulation_3_add_to_complex_2 = "Same as above with f=(c,i) .

Parameters
----------
c : Cell_handle
i : int
index : Surface_patch_index";
constexpr const char* MeshComplex_3InTriangulation_3_remove_from_complex = "Removes cell c from the embedded complex.

Parameters
----------
c : Cell_handle";
constexpr const char* MeshComplex_3InTriangulation_3_remove_from_complex_1 = "Removes facet f from the embedded complex.

Parameters
----------
f : Facet";
constexpr const char* MeshComplex_3InTriangulation_3_remove_from_complex_2 = "Same as above with f=(c,i) .

Parameters
----------
c : Cell_handle
i : int";
constexpr const char* MeshComplex_3InTriangulation_3_set_dimension = "Sets the dimension of vertex v .

The dimension is an integer attached to the vertex. When the concept
MeshComplex_3InTriangulation_3 is used for mesh generation this integer is
used to store the dimension of the lowest dimensional face of the input
complex including the vertex.

Parameters
----------
v : Vertex_handle
dimension : int";
constexpr const char* MeshComplex_3InTriangulation_3_set_index = "Sets the index of a vertex.

Parameters
----------
v : Vertex_handle
index : Index";
constexpr const char* MeshComplex_3InTriangulation_3_number_of_cells = "Returns the number of cells that belong to the embedded complex.

Returns: size_type";
constexpr const char* MeshComplex_3InTriangulation_3_number_of_cells_1 = "Returns the number of cells that belong to the subdomain of the embedded complex with index index .

Parameters
----------
index : Subdomain_index

Returns: size_type";
constexpr const char* MeshComplex_3InTriangulation_3_number_of_facets = "Returns the number of facets that are surface facets, i.

e. belong to some surface patch of the embedded complex.

Returns: size_type";
constexpr const char* MeshComplex_3InTriangulation_3_number_of_facets_1 = "Returns the number of facets that belong to the surface patch of the embedded complex with index index .

Parameters
----------
index : Surface_patch_index

Returns: size_type";
constexpr const char* MeshComplex_3InTriangulation_3_is_in_complex = "Returns true iff the cell c belongs to the 3D complex.

Parameters
----------
c : Cell_handle

Returns: bool";
constexpr const char* MeshComplex_3InTriangulation_3_is_in_complex_1 = "Returns true iff the facet f belongs to the boundary 2D complex.

Parameters
----------
f : Facet

Returns: bool";
constexpr const char* MeshComplex_3InTriangulation_3_is_in_complex_2 = "Same as above with f=(c,i) .

Parameters
----------
c : Cell_handle
i : int

Returns: bool";
constexpr const char* MeshComplex_3InTriangulation_3_subdomain_index = "Returns the index of the subdomain containing the cell c .

The default subdomain index is returned if the cell c does not belong to the
embedded complex.

Parameters
----------
c : Cell_handle

Returns: Subdomain_index";
constexpr const char* MeshComplex_3InTriangulation_3_surface_patch_index = "For a surface facet, returns the index of the surface patch containing the facet.

The default Surface_patch_index value is returned if the facet is not a
surface facet.

Parameters
----------
f : Facet

Returns: Surface_patch_index";
constexpr const char* MeshComplex_3InTriangulation_3_surface_patch_index_1 = "Same as above with f=(c,i) .

Parameters
----------
c : Cell_handle
i : int

Returns: Surface_patch_index";
constexpr const char* MeshComplex_3InTriangulation_3_in_dimension = "Returns the dimension of the vertex v .

Parameters
----------
v : Vertex_handle

Returns: int";
constexpr const char* MeshComplex_3InTriangulation_3_index = "Returns the index of the vertex v .

Parameters
----------
v : Vertex_handle

Returns: Index";
constexpr const char* MeshComplex_3InTriangulation_3_cells_in_complex_begin = "Returns a Cell_in_complex_iterator to visit the cells of the triangulation contained in the embedded complex.

Returns: Cells_in_complex_iterator";
constexpr const char* MeshComplex_3InTriangulation_3_cells_in_complex_end = "Returns the past-the-end iterator for the above iterator.

Returns: Cells_in_complex_iterator";
constexpr const char* MeshComplex_3InTriangulation_3_cells_in_complex_begin_1 = "Returns a Cell_in_complex_iterator to visit the cells of the triangulation which belong to the approximation of subdomain of index index .

Parameters
----------
index : Subdomain_index

Returns: Cells_in_complex_iterator";
constexpr const char* MeshComplex_3InTriangulation_3_cells_in_complex_end_1 = "Returns the past-the-end iterator for the above iterator.

Parameters
----------
index : Subdomain_index

Returns: Cells_in_complex_iterator";
constexpr const char* MeshComplex_3InTriangulation_3_facets_in_complex_begin = "Returns a Facet_in_complex_iterator to visit the facets in the surface patches of the embedded complexes.

Returns: Facets_in_complex_iterator";
constexpr const char* MeshComplex_3InTriangulation_3_facets_in_complex_end = "Returns the past-the-end iterator for the above iterator.

Returns: Facets_in_complex_iterator";
constexpr const char* MeshComplex_3InTriangulation_3_facets_in_complex_begin_1 = "Returns a Facet_in_complex_iterator to visit the facets of the triangulation which belong to the approximation of surface patch of index index .

Parameters
----------
index : Surface_patch_index

Returns: Facets_in_complex_iterator";
constexpr const char* MeshComplex_3InTriangulation_3_facets_in_complex_end_1 = "Returns the past-the-end iterator for the above iterator.

Parameters
----------
index : Surface_patch_index

Returns: Facets_in_complex_iterator";

// MeshComplexWithFeatures_3InTriangulation_3
constexpr const char* MeshComplexWithFeatures_3InTriangulation_3__class__ = "The concept MeshComplexWithFeatures_3InTriangulation_3 describes a data structure to represent and maintain a 3D complex embedded in a 3D triangulation. The concept MeshComplexWithFeatures_3InTriangulation_3 refines the minimal concept MeshComplex_3InTriangulation_3 , designed to represent 3D complexes having only faces with dimension 2 and 3. Therefore, the concept MeshComplexWithFeatures_3InTriangulation_3 may represent embedded complexes including features , i.e. faces with dimension $ 0$ and $ 1$ .";

constexpr const char* MeshComplexWithFeatures_3InTriangulation_3_Curve_index = "A type for indexes of curve.

The type must match the type MeshDomainWithFeatures_3::Curve_index when the
concept is used for mesh generation.

Returns: unspecified_type";
constexpr const char* MeshComplexWithFeatures_3InTriangulation_3_Corner_index = "A type for indexes of corners.

The type must match the type MeshDomainWithFeatures_3::Corner_index when the
concept is used for mesh generation.

Returns: unspecified_type";
constexpr const char* MeshComplexWithFeatures_3InTriangulation_3_Edges_in_complex_iterator = "An iterator type to visit the edges of the triangulation belonging to curves.

Returns: unspecified_type";
constexpr const char* MeshComplexWithFeatures_3InTriangulation_3_Vertices_in_complex_iterator = "An iterator type to visit the vertices of the triangulation that are corners of the embedded complex.

Returns: unspecified_type";
constexpr const char* MeshComplexWithFeatures_3InTriangulation_3_add_to_complex = "Adds edge e as an element of the curve with index index .

Parameters
----------
e : Edge
index : const Curve_index &";
constexpr const char* MeshComplexWithFeatures_3InTriangulation_3_add_to_complex_1 = "Same as above with e=(v1,v2) .

Parameters
----------
v1 : const Vertex_handle &
v2 : const Vertex_handle &
index : const Curve_index &";
constexpr const char* MeshComplexWithFeatures_3InTriangulation_3_add_to_complex_2 = "Marks vertex v as a corner with index index .

Parameters
----------
v : const Vertex_handle &
index : const Corner_index &";
constexpr const char* MeshComplexWithFeatures_3InTriangulation_3_remove_from_complex = "Removes edge e from the embedded complex.

Parameters
----------
e : const Edge &";
constexpr const char* MeshComplexWithFeatures_3InTriangulation_3_remove_from_complex_1 = "Same as above with e=(v1,v2) .

Parameters
----------
v1 : const Vertex_handle &
v2 : const Vertex_handle &";
constexpr const char* MeshComplexWithFeatures_3InTriangulation_3_remove_from_complex_2 = "Removes vertex v from the embedded complex.

Parameters
----------
v : const Vertex_handle &";
constexpr const char* MeshComplexWithFeatures_3InTriangulation_3_number_of_edges = "Returns the number of edges which belong to curves.

Returns: size_type";
constexpr const char* MeshComplexWithFeatures_3InTriangulation_3_number_of_corners = "Returns the number of vertices which are corners of the complex.

Returns: size_type";
constexpr const char* MeshComplexWithFeatures_3InTriangulation_3_is_in_complex = "Returns true iff edge e belongs to some curve.

Parameters
----------
e : const Edge &

Returns: bool";
constexpr const char* MeshComplexWithFeatures_3InTriangulation_3_is_in_complex_1 = "Same as above with e=(v1,v2) .

Parameters
----------
v1 : const Vertex_handle &
v2 : const Vertex_handle &

Returns: bool";
constexpr const char* MeshComplexWithFeatures_3InTriangulation_3_is_in_complex_2 = "Returns true if vertex v is a corner.

Parameters
----------
v : const Vertex_handle &

Returns: bool";
constexpr const char* MeshComplexWithFeatures_3InTriangulation_3_curve_index = "Returns Curve_index of edge e .

The default Curve_index value is returned if edge e does not belong to any
curve.

Parameters
----------
e : const Edge &

Returns: Curve_index";
constexpr const char* MeshComplexWithFeatures_3InTriangulation_3_curve_index_1 = "Same as above with e=(v1,v2) .

Parameters
----------
v1 : const Vertex_handle &
v2 : const Vertex_handle &

Returns: Curve_index";
constexpr const char* MeshComplexWithFeatures_3InTriangulation_3_corner_index = "Returns Corner_index of vertex v .

The default Corner_index value is returned if vertex v is not a corner of the
complex.

Parameters
----------
v : const Vertex_handle &

Returns: Corner_index";
constexpr const char* MeshComplexWithFeatures_3InTriangulation_3_edges_in_complex_begin = "Returns an Edges_in_complex_iterator to visit the edges of the triangulation belonging to curves.

Returns: Edges_in_complex_iterator";
constexpr const char* MeshComplexWithFeatures_3InTriangulation_3_edges_in_complex_end = "Returns the past-the-end iterator for the above iterator.

Returns: Edges_in_complex_iterator";
constexpr const char* MeshComplexWithFeatures_3InTriangulation_3_edges_in_complex_begin_1 = "Returns an Edges_in_complex_iterator to visit the edges of the triangulation belonging to curves of index index .

Parameters
----------
index : Curve_index

Returns: Edges_in_complex_iterator";
constexpr const char* MeshComplexWithFeatures_3InTriangulation_3_edges_in_complex_end_1 = "Returns the past-the-end iterator for the above iterator.

Parameters
----------
index : Curve_index

Returns: Edges_in_complex_iterator";
constexpr const char* MeshComplexWithFeatures_3InTriangulation_3_adjacent_vertices_in_complex = "Fills out with the vertices of the triangulation that are adjacent to vertex v through an edge belonging to some curve.

The value type of out must be std::pair<Vertex_handle, Curve_index > .
c3t3.in_dimension(v) < 2

Parameters
----------
v : const Vertex_handle &
out : OutputIterator

Returns: OutputIterator";
constexpr const char* MeshComplexWithFeatures_3InTriangulation_3_vertices_in_complex_begin = "Returns a Vertices_in_complex_iterator to visit the vertices of the triangulation that are corners.

Returns: Vertices_in_complex_iterator";
constexpr const char* MeshComplexWithFeatures_3InTriangulation_3_vertices_in_complex_end = "Returns the past-the-end iterator for the above iterator.

Returns: Vertices_in_complex_iterator";
constexpr const char* MeshComplexWithFeatures_3InTriangulation_3_vertices_in_complex_begin_1 = "Returns a Vertices_in_complex_iterator to visit the vertices of the triangulation that are corners of index index .

Parameters
----------
index : Corner_index

Returns: Vertices_in_complex_iterator";
constexpr const char* MeshComplexWithFeatures_3InTriangulation_3_vertices_in_complex_end_1 = "Returns the past-the-end iterator for the above iterator.

Parameters
----------
index : Corner_index

Returns: Vertices_in_complex_iterator";

// SimplicialMeshCellBase_3
constexpr const char* SimplicialMeshCellBase_3__class__ = "The concept SimplicialMeshCellBase_3 describes the requirements for the TriangulationDataStructure_3::Cell type of the triangulation used in a 3D simplicial mesh data structure.";

constexpr const char* SimplicialMeshCellBase_3_Subdomain_index = "Type of indices for cells of the mesh complex.

Must match the type MeshDomain_3::Subdomain_index in the context of mesh
generation.

Returns: unspecified_type";
constexpr const char* SimplicialMeshCellBase_3_Surface_patch_index = "Type of indices for surface patches of the mesh complex.

Must match the type MeshDomain_3::Surface_patch_index in the context of mesh
generation.

Returns: unspecified_type";
constexpr const char* SimplicialMeshCellBase_3_subdomain_index = "returns the index of the input subdomain that contains the cell.

Returns: Subdomain_index";
constexpr const char* SimplicialMeshCellBase_3_set_subdomain_index = "Sets the subdomain index of the cell.

Parameters
----------
index : Subdomain_index";
constexpr const char* SimplicialMeshCellBase_3_is_facet_on_surface = "returns true iff facet(i) is a surface facet.

Parameters
----------
i : int

Returns: bool";
constexpr const char* SimplicialMeshCellBase_3_surface_patch_index = "returns Surface_patch_index of facet i .

Parameters
----------
i : int

Returns: Surface_patch_index";
constexpr const char* SimplicialMeshCellBase_3_set_surface_patch_index = "sets Surface_patch_index of facet i to index .

Parameters
----------
i : int
index : Surface_patch_index";

// SimplicialMeshVertexBase_3
constexpr const char* SimplicialMeshVertexBase_3__class__ = "The concept SimplicialMeshVertexBase_3 describes the requirements for the Vertex type of the triangulation used in a 3D simplicial mesh data structure. The type SimplicialMeshVertexBase_3 refines the concept TriangulationVertexBase_3 . It provides additional members to store and retrieve information about the location of the vertex with respect to the input domain describing the discretized domain. More specifically, the concept SimplicialMeshVertexBase_3 provides read-write access to an integer representing the dimension of the lowest dimensional face of the input 3D complex on which the vertex lies, and to an index characteristic of this face.";

constexpr const char* SimplicialMeshVertexBase_3_Index = "Index type.

Returns: unspecified_type";
constexpr const char* SimplicialMeshVertexBase_3_in_dimension = "Returns the dimension of the lowest dimensional face of the input 3D complex that contains the vertex.

Returns: int";
constexpr const char* SimplicialMeshVertexBase_3_set_dimension = "Sets the dimension of the lowest dimensional face of the input 3D complex that contains the vertex.

Parameters
----------
 : int";
constexpr const char* SimplicialMeshVertexBase_3_index = "Returns the index of the lowest dimensional face of the input 3D complex that contains the vertex.

Returns: Index";
constexpr const char* SimplicialMeshVertexBase_3_set_index = "Sets the index of the lowest dimensional face of the input 3D complex that contains the vertex.

Parameters
----------
 : Index";
constexpr const char* SimplicialMeshVertexBase_3_is_c2t3_cache_valid = "Returns true if the cache is valid.

Returns: bool";
constexpr const char* SimplicialMeshVertexBase_3_set_c2t3_cache = "Sets the cache.

Invalidates the cache.

Parameters
----------
i : std::size_t
j : std::size_t";
constexpr const char* SimplicialMeshVertexBase_3_cached_number_of_incident_facets = "Returns the cached number of facets of the complex incident to the vertex.

Returns: std::size_t";
constexpr const char* SimplicialMeshVertexBase_3_cached_number_of_components = "This method concerns the adjacency graph of the facets of the complex incident to the vertex and returns a cached value for the number of connected components this graph.

Returns: std::size_t";

constexpr const char* CGAL_output_to_medit = "outputs a mesh complex to the medit ( .mesh ) file format. See [1] for a comprehensive description of this file format.

Deprecated This function is deprecated. Users should instead use
CGAL::IO::write_MEDIT() os the output stream c3t3 the mesh complex
renumber_subdomain_indices if true , labels of cells are renumbered into
[1..nb_of_labels] show_patches if true , patches are labeled with different
labels than cells. If false , each surface facet is written twice, using the
label of each adjacent cell. IOStreamMedit

Parameters
----------
os : std::ostream &
c3t3 : const C3T3 &
renumber_subdomain_indices : bool
show_patches : bool";
constexpr const char* CGAL_output_to_tetgen = "exports a mesh complex to tetgen format

filename the path to the output files, without the extension. c3t3 the mesh
complex rebind if true , labels of cells are rebound into [1..nb_of_labels]
show_patches if true , patches are labeled with different labels than cells.
If false , each surface facet is written twice, using the label of each
adjacent cell. IOStreamTetgen

Parameters
----------
filename : std::string
c3t3 : const C3T3 &
rebind : bool
show_patches : bool";
constexpr const char* CGAL_output_to_vtu = "exports a tetrahedral mesh complex using the UnstructuredGrid XML format.

C3T3 a model of MeshComplexWithFeatures_3InTriangulation_3 . os the stream
used for writing c3t3 the mesh complex mode decides if the data should be
written in binary ( IO::BINARY ) or in ASCII ( IO::ASCII ). If the mode is
binary, then the stream os must be opened in binary mode. IOStreamVTK

Parameters
----------
os : std::ostream &
c3t3 : const C3T3 &
mode : Mode";

constexpr const char* CGAL_IO_output_to_avizo = "exports a mesh complex to the Avizo ( .am ) file format

C3T3 a class model of MeshComplex_3InTriangulation_3 os the output stream c3t3
the mesh complex IOStreamAvizo

Parameters
----------
os : std::ostream &
c3t3 : const C3T3 &";

constexpr const char* CGAL_Mesh_3_save_binary_file = "outputs a mesh complex to the CGAL binary file format ( .binary.cgal ).

C3T3 Type of mesh complex, model of MeshComplex_3InTriangulation_3 os the
output stream, opened in binary mode c3t3 the mesh complex
CGAL::IO::load_binary_file()

Parameters
----------
os : std::ostream &
c3t3 : const C3T3 &

Returns: bool";
constexpr const char* CGAL_Mesh_3_load_binary_file = "loads a mesh complex from a file written in CGAL binary file format ( .binary.cgal ).

C3T3 Type of mesh complex, model of MeshComplex_3InTriangulation_3 is the
input stream, opened in binary mode c3t3 the mesh complex
CGAL::IO::save_binary_file()

Parameters
----------
is : std::istream &
c3t3 : C3T3 &

Returns: bool";


// std
constexpr const char* std__class__ = "STL namespace.";

} // namespace SMDS_3
} // namespace docstrings
} // namespace cgalpy

#endif // CGAL_PYTHON_DOCSTRINGS_SMDS_3_H
