from typing import Iterator, overload


class FT(): ...
class RT(): ...

class Point_2():
    @overload
    def __init__(self): ...
    @overload
    def __init__(self, x: float, y: float): ...
    @overload
    def __init__(self, x: FT, y: FT): ...
    @overload
    def __init__(self, x: RT, y: RT): ...
    @overload
    def __init__(self, p: Point_2): ...
    def x(self) -> FT: ...
    def y(self) -> FT: ...
    def hx(self) -> RT: ...
    def hy(self) -> RT: ...
    def hw(self) -> RT: ...
    def bbox(self) -> Bbox_2: ...
    def dimension(self) -> int: ...
    def cartesian(self) -> Iterator[FT]: ...
    def coordinates(self) -> Iterator[FT]: ...
    def __getitem__(self, i: int) -> FT: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...

class Segment_2():
    def __init__(self, p: Point_2, q: Point_2) -> None: ...
    def source(self) -> Point_2: ...
    def target(self) -> Point_2: ...
    def __getitem__(self, i: int) -> Point_2: ...
    def vertex(self, i: int) -> Point_2: ...
    def point(self, i: int) -> Point_2:...
    def min(self) -> Point_2:...
    def max(self) -> Point_2:...
    def opposite(self) -> Segment_2:...
    def to_vector(self) -> Vector_2:...
    def supporting_line(self) -> Line_2:...
    def squared_length(self) -> FT:...
    def direction(self) -> Direction_2:...
    def has_on(self, Point_2) -> bool:...
    def collinear_has_on(self, Point_2) -> bool:...
    def is_degenerate(self) -> bool:...
    def is_horizontal(self) -> bool:...
    def is_vertical(self) -> bool:...
    def bbox(self) -> Bbox_2: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...

class Line_2():
    @overload
    def __init__(self, a: RT, b: RT, c: RT) -> None: ...
    @overload
    def __init__(self, p: Point_2, q: Point_2) -> None: ...
    @overload
    def __init__(self, p: Point_2, d: Direction_2) -> None: ...
    @overload
    def __init__(self, p: Point_2, v: Vector_2) -> None: ...
    @overload
    def __init__(self, s: Segment_2) -> None: ...
    @overload
    def __init__(self, r: Ray_2) -> None: ...
    def a(self) -> FT: ...
    def b(self) -> FT: ...
    def c(self) -> FT: ...
    def is_degenerate(self) -> bool: ...
    def is_horizontal(self) -> bool: ...
    def is_vertical(self) -> bool: ...
    def oriented_side(self, Point_2) -> Oriented_side: ...
    def has_on(self, Point_2) -> bool: ...
    def has_on_boundary(self, Point_2) -> bool: ...
    def has_on_negative_side(self, Point_2) -> bool: ...
    def has_on_positive_side(self, Point_2) -> bool: ...
    def projection(self, p: Point_2) -> Point_2: ...
    def direction(self) -> Direction_2: ...
    def to_vector(self) -> Vector_2: ...
    def opposite(self) -> Line_2: ...
    def perpendicular(self, Point_2) -> Line_2: ...
    def transform(self, Aff_transformation_2) -> Line_2: ...
    def x_at_y(self, FT) -> FT: ...
    def y_at_x(self, FT) -> FT: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...