pipelines:
  default:
    - parallel:
        - step:
            name: Test
            image: ubuntu:latest
            script:
              - apt-get update
              - apt-get install -y g++ cmake
              - mkdir build
              - cd build
              - cmake -C ../src/cmake/tests/release/aos3_epec_fixed_release.cmake src
              - make -j4
              - pip install src/dist/CGALPY-1.0.0-cp38-cp38-linux_x86_64.whl

        # - step:
        #     name: Lint
        #     script:
        #       # apt update && apt -y install cppcheck && cppcheck .
        #       - make lint
        # - step:
        #     name: Build and Run
        #     script:
        #       - make compile
        #       # Execute your C++ application after compilation to check success
        #       - make distcheck
        #