
pipelines:
  default:
    - step: # sequential step
        image: ubuntu:latest
        script:
          - export DEBIAN_FRONTEND=noninteractive
          - export TZ=Asia/Kolkata
          - apt-get update
          - apt-get install -yq cmake g++ python3-pip python3 git python3.12-venv make libgmp3-dev libboost-all-dev libmpfr-dev qt6-base-dev libeigen3-dev
          - git clone https://github.com/CGAL/cgal.git
          - cd cgal
          - mkdir build
          - cd build
          - cmake ..
          - make install
          - cd ../..
          - python3 -m venv venv
          - source venv/bin/activate
          - python -m pip install build
          - git clone https://github.com/wjakob/nanobind.git
          - cd nanobind
          - git submodule update --init --recursive
          - export nanobind_DIR=$(pwd)
          - cd ..
          - mkdir build
          - cd build
    - parallel:
      steps:
      - step:
        name: Test bso2_seg_epec examples
        script:
          - cmake -C ../cmake/tests/release/bso2_seg_epec_release.cmake ../
          - make
          - pip install src/libs/cgalpy/dist/*.whl
          - cd ../src/python_scripts # go to examples
          - ./compare_examples.sh sequence.py # run examples
      
      - step:
        name: Test ms2_cs_epec examples
        script:
          - cmake -C ../cmake/tests/release/ms2_cs_epec_release.cmake ../
          - make
          - pip install src/libs/cgalpy/dist/*.whl
          - cd ../src/python_scripts # go to examples
          - ./compare_examples.sh approx_offset.py approx_inset.py # run examples
      
      - step:
        name: Test ms2_conic_ccr examples
        script:
          - cmake -C ../cmake/tests/release/ms2_conic_ccr_release.cmake ../
          - make
          - pip install src/libs/cgalpy/dist/*.whl
          - cd ../src/python_scripts # go to examples
          - ./compare_examples.sh exact_offset.py # run examples
      
      - step:
        name: Test aos2_seg_epec examples
        script:
          - cmake -C ../cmake/tests/release/aos2_seg_epec_release.cmake ../
          - make
          - pip install src/libs/cgalpy/dist/*.whl
          - cd ../src/python_scripts # go to examples
          - ./compare_examples.sh batched_point_location.py incremental_insertion.py point_location.py # run examples
      
      - step:
        name: Test aos2_conic_epec examples
        script:
          - cmake -C ../cmake/tests/release/aos2_conic_epec_release.cmake ../
          - make
          - pip install src/libs/cgalpy/dist/*.whl
          - cd ../src/python_scripts # go to examples
          - ./compare_examples.sh conic_multiplicities.py conics.py # run examples
      
      - step:
        name: Test aos2_seg_ae_epec examples
        script:
          - cmake -C ../cmake/tests/release/aos2_seg_ae_epec_release.cmake ../
          - make
          - pip install src/libs/cgalpy/dist/*.whl
          - cd ../src/python_scripts # go to examples
          - ./compare_examples.sh dcel_extension.py dcel_extension_io.py face_extension.py face_extension_overlay.py overlay_color.py # run examples
      
      - step:
        name: Test aos2_linear_epec examples
        script:
          - cmake -C ../cmake/tests/release/aos2_linear_epec_release.cmake ../
          - make
          - pip install src/libs/cgalpy/dist/*.whl
          - cd ../src/python_scripts # go to examples
          - ./compare_examples.sh io_unbounded.py # run examples
      
      - step:
        name: Test aos2_alg_epec examples
        script:
          - cmake -C ../cmake/tests/release/aos2_alg_epec_release.cmake ../
          - make
          - pip install src/libs/cgalpy/dist/*.whl
          - cd ../src/python_scripts # go to examples
          - ./compare_examples.sh algebraic_segments.py algebraic_curves.py # run examples
      
