pipelines:
  default:
    - parallel:
        - step:
            name: Test
            image: ubuntu:latest
            script:
              - export DEBIAN_FRONTEND=noninteractive
              - export TZ=Asia/Kolkata
              - apt-get update
              - apt-get install -yq --no-install-recommends g++ cmake python3-pip python3 libcgal-dev git python3-venv
              - python3 -m venv venv
              - source venv/bin/activate
              - git clone https://github.com/wjakob/nanobind.git
              - export nanobind_DIR=$(pwd)/nanobind
              - mkdir build
              - cd build
              - cmake -C ../src/cmake/tests/release/aos2_epec_fixed_release.cmake ../
              - make -j4
              - pip install ../src/dist/CGALPY-1.0.0-cp38-cp38-linux_x86_64.whl

        # - step:
        #     name: Lint
        #     script:
        #       # apt update && apt -y install cppcheck && cppcheck .
        #       - make lint
        # - step:
        #     name: Build and Run
        #     script:
        #       - make compile
        #       # Execute your C++ application after compilation to check success
        #       - make distcheck
        #
