set(CGALPY_USE_SHARED_LIBS ON  cache BOOL "" force)
set(CGALPY_KERNEL_NAME "epec" cache string "" force)
set(CGALPY_KERNEL_INTERSECTION_BINDINGS on cache bool "with intersections" force)
set(CGALPY_ARRANGEMENT_ON_SURFACE_2_BINDINGS on cache bool "" force)
set(CGALPY_AOS2_GEOMETRY_TRAITS_NAME "geodesicOnSphere" cache string "" force)
set(CGALPY_AOS2_POINT_LOCATION_BINDINGS on cache bool "" force)
