set(CGALPY_USE_SHARED_LIBS on cache bool "" force)
set(CGALPY_KERNEL_NAME "epic" cache string "" force)
set(CGALPY_ARRANGEMENT_ON_SURFACE_2_BINDINGS on cache bool "" force)
set(CGALPY_AOS2_GEOMETRY_TRAITS_NAME "segment" cache string "Segments" force)
set(CGALPY_AOS2_POINT_LOCATION_BINDINGS on cache bool "" force)
