set(CGALPY_USE_SHARED_LIBS ON  cache BOOL "use shared libs" force)
set(CGALPY_KERNEL_NAME "epec" cache string "use EPEC kernel" force)
set(CGALPY_KERNEL_INTERSECTION_BINDINGS on cache bool "with intersections" force)
set(CGALPY_ARRANGEMENT_ON_SURFACE_2_BINDINGS on cache bool "2D AOS" force)
set(CGALPY_AOS2_GEOMETRY_TRAITS_NAME "circleSegment" cache string "use circle-segments" force)
set(CGALPY_AOS2_VERTEX_EXTENDED on cache bool "extend vertex type" force)
