set(CGALPY_USE_SHARED_LIBS on cache bool "" force)
set(CGALPY_KERNEL_NAME "epec" cache string "" force)
set(CGALPY_KERNEL_INTERSECTION_BINDINGS on cache bool "with intersections" force)
set(CGALPY_ARRANGEMENT_ON_SURFACE_2_BINDINGS on cache bool "" force)
set(CGALPY_AOS2_GEOMETRY_TRAITS_NAME "segment" cache string "Segments" force)
set(CGALPY_AOS2_WITH_HISTORY on cache bool "" force)
set(CGALPY_AOS2_CONSOLIDATED_CURVE_DATA on cache bool "" force)
set(CGALPY_AOS2_CURVE_DATA on cache bool "" force)
set(CGALPY_AOS2_POINT_LOCATION_BINDINGS on cache bool "" force)
set(CGALPY_AOS2_FACE_EXTENDED on cache bool "extend face type" force)
