set(CGALPY_USE_SHARED_LIBS on CACHE BOOL "use shared libs" FORCE)
set(CGALPY_KERNEL_NAME "epic" CACHE STRING "use EPIC kernel" FORCE)
set(CGALPY_TRIANGULATION_2_BINDINGS on CACHE BOOL "2D Triangulations" FORCE)
set(CGALPY_TRI2_NAME "delaunay" CACHE STRING "" FORCE)
set(CGALPY_ALPHA_SHAPE_2_BINDINGS on CACHE BOOL "" FORCE)

# set(CMAKE_VERBOSE_MAKEFILE on CACHE BOOL "" FORCE)
# set(CMAKE_INSTALL_PREFIX ${SNAPFIXT_RELEASE_ROOT} CACHE STRING "" FORCE)
