set(CGALPY_USE_SHARED_LIBS on cache bool "" force)
set(CGALPY_KERNEL_NAME "epic" cache string "use EPIC kernel" force)
set(CGALPY_TRIANGULATION_3_BINDINGS on cache bool "" force)
set(CGALPY_TRI3_NAME "delaunay" cache string "" force)
set(CGALPY_TRI3_LOCATION_POLICY_NAME "compact" cache string "" force)
set(CGALPY_ALPHA_SHAPE_3_BINDINGS on cache bool "" force)
set(CGALPY_AS3_EXACT_COMPARISON on cache bool "" force)
