set(CGALPY_USE_SHARED_LIBS ON                        CACHE BOOL "" FORCE)
set(CGALPY_KERNEL_NAME "epic"                        CACHE STRING "" FORCE)
set(CGALPY_TRIANGULATION_3_BINDINGS ON               CACHE BOOL "" FORCE)
set(CGALPY_TRI3_NAME "regular"                       CACHE STRING "" FORCE)
set(CGALPY_ALPHA_SHAPE_3_BINDINGS ON                 CACHE BOOL "" FORCE)

# set(CMAKE_VERBOSE_MAKEFILE ON CACHE BOOL "" FORCE)
# set(CMAKE_INSTALL_PREFIX ${SNAPFIXT_RELEASE_ROOT} CACHE STRING "" FORCE)
