set(CGALPY_USE_SHARED_LIBS on cache bool "use shared libs" force)
set(CGALPY_KERNEL_NAME "epic" cache string "use EPIC kernel" force)
set(CGALPY_TRIANGULATION_3_BINDINGS on cache bool "3D Triangulations" force)
set(CGALPY_TRI3_NAME "delaunay" cache string "Use Delaunay" force)
set(CGALPY_TRI3_LOCATION_POLICY_NAME "compact" cache string "Preserve space" force)
set(CGALPY_TRI3_CONCURRENCY_NAME "parallel" cache string "Concurrent" force)
set(CGALPY_ALPHA_SHAPE_3_BINDINGS on cache bool "3D Alpha Shapes" force)
