set(CGALPY_USE_SHARED_LIBS on cache bool "" force)
set(CGALPY_KERNEL_NAME "cartesianCoreRational" cache string "use kernel" force)
set(CGALPY_KERNEL_INTERSECTION_BINDINGS on cache bool "with intersections" force)
set(CGALPY_ARRANGEMENT_ON_SURFACE_2_BINDINGS on cache bool "" force)
set(CGALPY_AOS2_GEOMETRY_TRAITS_NAME "bezier" cache string "use Bezier" force)
set(CGALPY_BOOLEAN_SET_OPERATIONS_2_BINDINGS on cache bool "" force)
