set(CGALPY_USE_SHARED_LIBS on cache bool "" force)
set(CGALPY_KERNEL_NAME "epec" cache string "use EPEC kernel" force)
set(CGALPY_ARRANGEMENT_ON_SURFACE_2_BINDINGS on cache bool "" force)
set(CGALPY_AOS2_FACE_EXTENDED on cache bool "extend face type" force)
set(CGALPY_AOS2_GEOMETRY_TRAITS_NAME "conic" cache string "use conic arcs" force)
set(CGALPY_BOOLEAN_SET_OPERATIONS_2_BINDINGS on cache bool "" force)
set(CGALPY_KERNEL_INTERSECTION_BINDINGS on cache bool "with intersections" force)
set(CGALPY_POLYGON_2_BINDINGS on cache bool "" force)
