set(CGALPY_USE_SHARED_LIBS on cache bool "" force)
set(CGALPY_KERNEL_NAME "epec" cache string "use EPEC kernel" force)
set(CGALPY_POLYGON_2_BINDINGS on cache bool "" force)
set(CGALPY_ARRANGEMENT_ON_SURFACE_2_BINDINGS on cache bool "" force)
set(CGALPY_AOS2_GEOMETRY_TRAITS_NAME "segment" cache string "use Segments" force)
set(CGALPY_BOOLEAN_SET_OPERATIONS_2_BINDINGS on cache bool "" force)
