set(CGALPY_USE_SHARED_LIBS on CACHE BOOL "" FORCE)
set(CGALPY_KERNEL_NAME "epic" CACHE STRING "use EPIC kernel" FORCE)
set(CGALPY_KERNEL_D_BINDINGS on CACHE BOOL "" FORCE)
set(CGALPY_KERNEL_INTERSECTION_BINDINGS on CACHE BOOL "" FORCE)
set(CGALPY_KERNEL_D_NAME "epicd" CACHE STRING "" FORCE)

set(CGALPY_TRIANGULATION_2_BINDINGS on CACHE BOOL "" FORCE)
set(CGALPY_TRIANGULATION_3_BINDINGS on CACHE BOOL "" FORCE)
set(CGALPY_TRIANGULATION_D_BINDINGS on CACHE BOOL "" FORCE)

set(CGALPY_TRI2_NAME "delaunay" CACHE STRING "" FORCE)
set(CGALPY_TRI2_VERTEX_WITH_INFO on CACHE BOOL "" FORCE)
set(CGALPY_TRI2_FACE_WITH_INFO on CACHE BOOL "" FORCE)

set(CGALPY_TRI3_NAME "delaunay" CACHE STRING "" FORCE)
set(CGALPY_TRI3_VERTEX_WITH_INFO on CACHE BOOL "" FORCE)
set(CGALPY_TRI3_CELL_WITH_INFO on CACHE BOOL "" FORCE)

set(CGALPY_TRID_NAME "delaunay" CACHE STRING "" FORCE)
set(CGALPY_TRID_VERTEX_WITH_DATA on CACHE BOOL "" FORCE)
set(CGALPY_TRID_FULL_CELL_WITH_DATA on CACHE BOOL "" FORCE)

set(CGALPY_CONVEX_HULL_2_BINDINGS on CACHE BOOL "" FORCE)
set(CGALPY_CONVEX_HULL_3_BINDINGS on CACHE BOOL "" FORCE)
set(CGALPY_GEOMETRIC_OBJECT_GENERATORS_BINDINGS on CACHE BOOL "" FORCE)
set(CGALPY_SPATIAL_SORTING_BINDINGS on CACHE BOOL "" FORCE)
