set(CGALPY_USE_SHARED_LIBS on CACHE BOOL "" FORCE)
set(CGALPY_KERNEL_BINDINGS OFF CACHE BOOL "Disable kernel" FORCE)
set(CGALPY_KERNEL_D_BINDINGS on CACHE BOOL "Enable dD kernel" FORCE)
set(CGALPY_KERNEL_D_NAME "cartesiandDouble" CACHE STRING "use EPICD kernel" FORCE)
