set(CGALPY_USE_SHARED_LIBS on CACHE BOOL "" FORCE)
set(CGALPY_KERNEL_BINDINGS OFF CACHE BOOL "disable kernel" FORCE)
set(CGALPY_KERNEL_D_BINDINGS on CACHE BOOL "enable dD kernel" FORCE)
set(CGALPY_KERNEL_D_NAME "cartesiandLazyGmpq" CACHE STRING "dD kernel" FORCE)
