set(CGALPY_USE_SHARED_LIBS ON              CACHE BOOL "" FORCE)
set(CGALPY_KERNEL_NAME "epic"              CACHE STRING "use EPIC kernel" FORCE)
set(CGALPY_KERNEL_INTERSECTION_BINDINGS ON CACHE BOOL "with intersections" FORCE)
set(CGALPY_CONVEX_HULL_2_BINDINGS ON       CACHE BOOL "2D convex hull bindings" FORCE)
