set(CGALPY_USE_SHARED_LIBS on cache bool "" force)
set(CGALPY_KERNEL_NAME "epec" cache string "" force)
set(CGALPY_KERNEL_INTERSECTION_BINDINGS on cache bool "with intersections" force)
set(CGALPY_ENVELOPE_3_BINDINGS on cache bool "" force)
set(CGALPY_ENV3_GEOMETRY_TRAITS_NAME "sphere" cache string "Spheres" force)
