set(CGALPY_USE_SHARED_LIBS on cache bool "" force)
set(CGALPY_KERNEL_NAME "epec" cache string "" force)
set(CGALPY_KERNEL_INTERSECTION_BINDINGS on cache bool "with intersections" force)
set(CGALPY_ARRANGEMENT_ON_SURFACE_2_BINDINGS on cache bool "" force)
set(CGALPY_AOS2_GEOMETRY_TRAITS_NAME "segment" cache string "" force)
set(CGALPY_AOS2_POINT_LOCATION_BINDINGS on cache bool "" force)
set(CGALPY_ENVELOPE_3_BINDINGS on cache bool "" force)
set(CGALPY_ENV3_GEOMETRY_TRAITS_NAME "triangle" cache string "Triangles" force)
set(CGALPY_ENV3_SURFACE_DATA on cache bool "" force)
