set(CGALPY_USE_SHARED_LIBS on CACHE BOOLean "" FORCE)
set(CGALPY_KERNEL_NAME "epec" CACHE STRING "use EPEC kernel" FORCE)
set(CGALPY_KERNEL_INTERSECTION_BINDINGS on CACHE BOOLean "with intersections" FORCE)
