set(CGALPY_USE_SHARED_LIBS on cache bool "" force)
set(CGALPY_KERNEL_NAME "epec" cache string "use EPEC kernel" force)
set(CGALPY_KERNEL_INTERSECTION_BINDINGS on cache bool "with intersections" force)
set(CGALPY_3D_POINT_SET_BINDINGS on cache bool "" force)
# set(CGALPY_KINETIC_SURFACE_RECONSTRUCTION_BINDINGS on cache bool "" force) # does not work with epec
set(CGALPY_ARRANGEMENT_ON_SURFACE_2_BINDINGS on cache bool "" force)
set(CGALPY_AOS2_POINT_LOCATION_BINDINGS on cache bool "" force)
set(CGALPY_AOS2_VERTEX_EXTENDED on cache bool "" force)
set(CGALPY_AOS2_HALFEDGE_EXTENDED on cache bool "" force)
set(CGALPY_AOS2_FACE_EXTENDED on cache bool "" force)
set(CGALPY_POLYGON_2_BINDINGS on cache bool "" force)
set(CGALPY_BOOLEAN_SET_OPERATIONS_2_BINDINGS on cache bool "" force)
set(CGALPY_MINKOWSKI_SUM_2_BINDINGS on cache bool "" force)
set(CGALPY_CONVEX_HULL_2_BINDINGS on cache bool "" force)
set(CGALPY_SURFACE_MESH_BINDINGS on cache bool "" force)
set(CGALPY_POLYGON_MESH_PROCESSING_BINDINGS on cache bool "" force)
set(CGALPY_TRIANGULATED_SURFACE_MESH_SEGMENTATION_BINDINGS on cache bool "" force)
set(CGALPY_TRIANGULATED_SURFACE_MESH_SIMPLIFICATION_BINDINGS on cache bool "" force)
set(CGALPY_TRIANGULATED_SURFACE_MESH_SKELETONIZATION_BINDINGS on cache bool "" force)
set(CGALPY_PMP_POLYGONAL_MESH_NAME "surfaceMesh" cache string "" force)
set(CGALPY_SPATIAL_SEARCHING_BINDINGS OFF cache BOOL "Not supported with epec_d" force)
set(CGALPY_SHAPE_DETECTION_BINDINGS on cache bool "" force)
# set(CGALPY_SPATIAL_SEARCHING_DIMENSION 2 cache string "2 dimensions" force)
set(CGALPY_KERNEL_D_BINDINGS on cache bool "" force)
set(CGALPY_KERNEL_D_NAME "epecd" cache string "" force)
# set(CGALPY_KERNEL_D_DIMENSION 2 cache string "2 dimensions" force)
set(CGALPY_TRIANGULATION_2_BINDINGS on cache bool "" force)
set(CGALPY_TRI2_VERTEX_WITH_INFO on cache bool "" force)
set(CGALPY_TRI2_FACE_WITH_INFO on cache bool "" force)
set(CGALPY_TRI2_HIERARCHY on cache bool "" force)
set(CGALPY_TRIANGULATION_3_BINDINGS on cache bool "" force)
set(CGALPY_TRI3_NAME "delaunay" cache BOOL "" force)
