set(CGALPY_USE_SHARED_LIBS ON CACHE Boolean "" FORCE)
set(CGALPY_KERNEL_NAME "epec" CACHE String "use EPEC kernel" FORCE)
set(CGALPY_KERNEL_INTERSECTION_BINDINGS ON CACHE Boolean "with intersections" FORCE)
