set(CMAKE_BUILD_TYPE "Release"   CACHE STRING "" FORCE)
set(CGALPY_USE_SHARED_LIBS ON    CACHE BOOL "" FORCE)
set(CGALPY_FIXED_LIBRARY_NAME ON CACHE BOOL "" FORCE)
set(CGALPY_KERNEL_NAME "epec"    CACHE STRING "" FORCE)
