set(CGALPY_USE_SHARED_LIBS on CACHE BOOL "" FORCE)
set(CGALPY_KERNEL_NAME "epic" CACHE STRING "use EPIC kernel" FORCE)
set(CGALPY_GEOMETRIC_OBJECT_GENERATORS_BINDINGS on CACHE BOOL "Enable geometric object generators" FORCE)
