set(CGALPY_KINETIC_SURFACE_RECONSTRUCTION_BINDINGS on cache bool "" force)
set(CGALPY_KERNEL_NAME "epic" cache string "use EPIC kernel" force)
set(CMAKE_CXX_STANDARD 23)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
