set(CGALPY_KINETIC_SURFACE_RECONSTRUCTION_BINDINGS ON CACHE BOOL "" FORCE)
set(CGALPY_KERNEL_NAME "epic" CACHE STRING "use EPIC kernel" FORCE)
set(CMAKE_CXX_STANDARD 23)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
