set(CGALPY_USE_SHARED_LIBS on CACHE BOOL "" FORCE)
set(CGALPY_KERNEL_NAME "cartesianCoreRational" CACHE STRING "use kernel" FORCE)
set(CGALPY_KERNEL_INTERSECTION_BINDINGS on CACHE BOOL "with intersections" FORCE)
set(CGALPY_POLYGON_2_BINDINGS on CACHE BOOL "" FORCE)
# Until the Partitiontraits_2 is fixed, suppress the polygon partition module
set(CGALPY_POLYGON_PARTITIONING_BINDINGS OFF CACHE BOOL "" FORCE)
set(CGALPY_ARRANGEMENT_ON_SURFACE_2_BINDINGS on CACHE BOOL "" FORCE)
set(CGALPY_AOS2_GEOMETRY_TRAITS_NAME "conic" CACHE STRING "use conics" FORCE)
set(CGALPY_MINKOWSKI_SUM_2_BINDINGS on CACHE BOOL "" FORCE)
