set(CGALPY_USE_SHARED_LIBS ON CACHE BOOL "" FORCE)
set(CGALPY_KERNEL_NAME "epec" CACHE STRING "use EPEC kernel" FORCE)
set(CGALPY_KERNEL_INTERSECTION_BINDINGS ON CACHE BOOL "with intersections" FORCE)
set(CGALPY_POLYGON_2_BINDINGS ON CACHE BOOL "" FORCE)
# Until the Partitiontraits_2 is fixed, suppress the polygon partition module
set(CGALPY_POLYGON_PARTITIONING_BINDINGS OFF CACHE BOOL "" FORCE)
set(CGALPY_ARRANGEMENT_ON_SURFACE_2_BINDINGS ON CACHE BOOL "" FORCE)
set(CGALPY_AOS2_GEOMETRY_TRAITS_NAME "circleSegment" CACHE STRING "use segments" FORCE)
set(CGALPY_MINKOWSKI_SUM_2_BINDINGS ON CACHE BOOL "" FORCE)
