set(CGALPY_USE_SHARED_LIBS on cache bool "" force)
set(CGALPY_KERNEL_NAME "epec" cache string "use EPEC kernel" force)
set(CGALPY_KERNEL_INTERSECTION_BINDINGS on cache bool "with intersections" force)
set(CGALPY_POLYHEDRON_3_BINDINGS on cache bool "" force)
set(CGALPY_POL3_GEOMETRY_TRAITS_NAME "withNormals" cache string "with normals" force)
set(CGALPY_BOOLEAN_SET_OPERATIONS_2_BINDINGS on cache bool "" force)
set(CGALPY_POLYGON_2_BINDINGS on cache bool "" force)
