set(CGALPY_USE_SHARED_LIBS on cache bool "" force)
set(CGALPY_KERNEL_NAME "epic" cache string "use EPIC kernel" force)
set(CGALPY_POLYHEDRON_3_BINDINGS on cache bool "" force)
set(CGALPY_POL3_FACE_EXTENDED on cache bool "" force)
set(CGALPY_POLYGON_MESH_PROCESSING_BINDINGS on cache bool "" force)
set(CGALPY_PMP_POLYGONAL_MESH_NAME "polyhedron" cache string "" force)
