set(CGALPY_USE_SHARED_LIBS on cache bool "" force)
set(CGALPY_KERNEL_NAME "epec" cache string "use EPEC kernel" force)
set(CGALPY_POLYHEDRON_3_BINDINGS on cache bool "" force)
set(CGALPY_CONVEX_HULL_3_BINDINGS on cache bool "" force)
set(CGALPY_CH3_POLYGONAL_MESH_NAME "polyhedron" cache string "" force)
