set(CGALPY_USE_SHARED_LIBS ON CACHE BOOL "" FORCE)
set(CGALPY_KERNEL_NAME "epecWithSqrt" CACHE STRING "use EPEC kernel" FORCE)
set(CGALPY_POINT_SET_PROCESSING_PACKAGE_BINDINGS ON CACHE BOOL "" FORCE)
