set(CGALPY_USE_SHARED_LIBS on cache bool "" force)
set(CGALPY_KERNEL_NAME "epic" cache string "use EPIC kernel" force)
set(CGALPY_SURFACE_MESH_BINDINGS on cache bool "" force)
set(CGALPY_PMP_POLYGONAL_MESH_NAME "surfaceMesh" cache string "" force)
set(CGALPY_POLYGON_MESH_PROCESSING_BINDINGS on cache bool "" force)
set(CGALPY_TRIANGULATED_SURFACE_MESH_SEGMENTATION_BINDINGS on cache bool "" force)
