set(CGALPY_USE_SHARED_LIBS on CACHE BOOL "use shared libs" FORCE)
set(CGALPY_KERNEL_NAME "epic" CACHE STRING "use EPIC kernel" FORCE)
set(CGALPY_STRAIGHT_SKELETON_2_BINDINGS on CACHE BOOL "2D Straight Skeleton" FORCE)
set(CGALPY_POLYGON_2_BINDINGS on CACHE BOOL "" FORCE)
