set(CMAKE_BUILD_TYPE "Release"                           CACHE STRING "build type" FORCE)
set(CGALPY_USE_SHARED_LIBS ON                            CACHE BOOL "use shared libs" FORCE)
set(CGALPY_FIXED_LIBRARY_NAME OFF                        CACHE BOOL "use name CGALPY" FORCE)
set(CGALPY_KERNEL_NAME "filteredSimpleCartesianLazyGmpq" CACHE STRING "used kernel" FORCE)
set(CGALPY_SPATIAL_SEARCHING_BINDINGS ON                 CACHE BOOL "Spatial Searching" FORCE)
set(CGALPY_SPATIAL_SEARCHING_DIMENSION 2                 CACHE STRING "2 dimensions" FORCE)
