set(CGALPY_USE_SHARED_LIBS on cache bool "use shared libs" force)
set(CGALPY_KERNEL_BINDINGS off cache bool "2,3 Kernel" force)
set(CGALPY_KERNEL_D_BINDINGS on cache bool "dD Kernel" force)
set(CGALPY_KERNEL_D_NAME "cartesiandLazyGmpq" cache string "used dD kernel" force)
set(CGALPY_KERNEL_D_DIMENSION_TAG "static" cache string "fixed dimension" force)
set(CGALPY_KERNEL_D_DIMENSION 2 cache string "2 dimensions" force)
set(CGALPY_SPATIAL_SEARCHING_BINDINGS on cache bool "Spatial Searching" force)
set(CGALPY_SPATIAL_SEARCHING_DIMENSION 2 cache string "2 dimensions" force)
