set(CGALPY_USE_SHARED_LIBS on cache bool "use shared libs" force)
set(CGALPY_KERNEL_NAME "epic" cache string "use EPIC kernel" force)
set(CGALPY_TRIANGULATION_2_BINDINGS on cache bool "2D Triangulations" force)
set(CGALPY_TRI2_NAME "constrainedDelaunay" cache string "Const. Tri." force)
set(CGALPY_TRI2_VERTEX_WITH_INFO on cache bool "vertex with info" force)
set(CGALPY_TRI2_FACE_WITH_INFO on cache bool "cell with info" force)
