set(CGALPY_TRIANGULATION_2_BINDINGS on CACHE BOOL "2D Triangulations" FORCE)
set(CGALPY_2D_RANGE_AND_NEIGHBOR_SEARCH_BINDINGS on CACHE BOOL "" FORCE)
set(CGALPY_KERNEL_NAME "epic" CACHE STRING "use EPIC kernel" FORCE)
