// AUTO-GENERATED by cpp_docstrings_from_json.py — DO NOT EDIT
// Package: Polynomial
#ifndef CGAL_PYTHON_DOCSTRINGS_POLYNOMIAL_H
#define CGAL_PYTHON_DOCSTRINGS_POLYNOMIAL_H

namespace cgalpy {
namespace docstrings {
namespace Polynomial {

// CGAL::Exponent_vector
constexpr const char* Exponent_vector__class__ = "For a given (multivariate) monomial the vector of its exponents is called the exponent vector.";

constexpr const char* Exponent_vector_Exponent_vector = "Default constructor.";
constexpr const char* Exponent_vector_Exponent_vector_1 = "The copy constructor.

Parameters
----------
ev_ : const Exponent_vector &";
constexpr const char* Exponent_vector_Exponent_vector_2 = "Creates a vector containing the given element.

Parameters
----------
e1 : int";
constexpr const char* Exponent_vector_Exponent_vector_3 = "Creates a vector containing the given elements.

Parameters
----------
e1 : int
e2 : int";
constexpr const char* Exponent_vector_Exponent_vector_4 = "Creates a vector containing the given elements.

Parameters
----------
e1 : int
e2 : int
e3 : int";
constexpr const char* Exponent_vector_Exponent_vector_5 = "Creates a vector containing the given elements.

Parameters
----------
e1 : int
e2 : int
e3 : int
e4 : int";
constexpr const char* Exponent_vector_Exponent_vector_6 = "Creates a vector with a copy of the given range.

InputIterator must allow the value type int .

Parameters
----------
begin : InputIterator
end : InputIterator";
constexpr const char* Exponent_vector_operator = "
ev1.size() == ev2.size().

Parameters
----------
ev1 : const Exponent_vector &
ev2 : const Exponent_vector &

Returns: Exponent_vector";
constexpr const char* Exponent_vector_operator_1 = "
ev1.size() == ev2.size()

Parameters
----------
ev1 : const Exponent_vector &
ev2 : const Exponent_vector &

Returns: Exponent_vector";
constexpr const char* Exponent_vector_operator_2 = "
fo .size() == ev2.size()

Parameters
----------
ev2 : const Exponent_vector &

Returns: Exponent_vector";
constexpr const char* Exponent_vector_operator_3 = "
fo .size() == ev2.size()

Parameters
----------
ev2 : const Exponent_vector &

Returns: Exponent_vector";
constexpr const char* Exponent_vector_operator_4 = "Lexicographic compare, starting with the last variable.

Parameters
----------
ev1 : const Exponent_vector &
ev2 : const Exponent_vector &

Returns: bool";
constexpr const char* Exponent_vector_is_valid = "Returns true if all entries of exponent vector ev are not negative.

Parameters
----------
ev : const Exponent_vector &

Returns: bool";

// CGAL::Polynomial
constexpr const char* Polynomial__class__ = "An instance of the data type Polynomial represents a polynomial $ p = a_0 + a_1*x + ...a_i*x^i$ from the ring $ \\mathrm{Coeff}[x]$ .";

constexpr const char* Polynomial_Polynomial = "Introduces an variable initialized with 0.";
constexpr const char* Polynomial_Polynomial_1 = "copy constructor.

Parameters
----------
x : const Polynomial &";
constexpr const char* Polynomial_Polynomial_2 = "Constructor from int.

Parameters
----------
i : const int &";
constexpr const char* Polynomial_Polynomial_3 = "Constructor from type Coeff.

Parameters
----------
x : const Coeff &";
constexpr const char* Polynomial_Polynomial_4 = "Constructor from iterator range with value type Coeff.

Parameters
----------
first : Forward_iterator
last : Forward_iterator";
constexpr const char* Polynomial_begin = "A const random access iterator pointing to the constant coefficient.

Returns: const_iterator";
constexpr const char* Polynomial_end = "A const random access iterator pointing beyond the leading coefficient.

Returns: const_iterator";
constexpr const char* Polynomial_degree = "The degree of the polynomial in $ x$ .

The degree of the zero polynomial is 0.

Returns: int";
constexpr const char* Polynomial_operator = "Const access to the coefficient of $ x^i$ .

Parameters
----------
i : unsigned int

Returns: const NT &";
constexpr const char* Polynomial_lcoeff = "Const access to the leading coefficient.

Returns: const NT &";
constexpr const char* Polynomial_operator_1 = "Writes poly to ostream os .

The format depends on the CGAL::IO::MODE of os . In case the mode is
CGAL::IO::ASCII the format is $ P[d(0,a_0)(1,a_1)\\dots(d,a_d)]$ , where $ d$
is the degree of the polynomial. The format is output sensitive, that is,
coefficients that are zero are not reported. In case the mode is
CGAL::IO::PRETTY the format is human readable.

Parameters
----------
os : std::ostream &
poly : const Polynomial < Coeff > &

Returns: std::ostream &";
constexpr const char* Polynomial_operator_2 = "Reads poly from istream is in format $ P[d(0,a_0)(1,a_1)\\dots(d,a_d)]$ , the output format in mode CGAL::IO::ASCII .

Parameters
----------
is : std::istream &
poly : const Polynomial < Coeff > &

Returns: std::istream &";

// CGAL::Polynomial_traits_d
constexpr const char* Polynomial_traits_d__class__ = "A model of concept PolynomialTraits_d .";

// CGAL::Polynomial_type_generator
constexpr const char* Polynomial_type_generator__class__ = "This class template provides a convenient way to obtain the type representing a multivariate polynomial with d variables, where T is the innermost coefficient type.";

constexpr const char* Polynomial_type_generator_Type = "The generated type.

Returns: unspecified_type";

// Polynomial_d
constexpr const char* Polynomial_d__class__ = "A model of Polynomial_d is representing a multivariate polynomial in $ d \\geq 1$ variables over some basic ring $ R$ . This type is denoted as the innermost coefficient. A model of Polynomial_d must be accompanied by a traits class CGAL::Polynomial_traits_d < Polynomial_d > , which is a model of PolynomialTraits_d . Please have a look at the concept PolynomialTraits_d , since nearly all functionality related to polynomials is provided by the traits.";

// PolynomialTraits_d
constexpr const char* PolynomialTraits_d__class__ = "A model of PolynomialTraits_d is associated with a type Polynomial_d . The type Polynomial_d represents a multivariate polynomial. The number of variables is denoted as the dimension $ d$ of the polynomial, it is arbitrary but fixed for a certain model of this concept. Note that univariate polynomials are not excluded by this concept. In this case $ d$ is just set to one.";

constexpr const char* PolynomialTraits_d_Polynomial_d = "Type representing $ R[x_0,\\dots,x_{d-1}]$ .

Returns: unspecified_type";
constexpr const char* PolynomialTraits_d_Coefficient_type = "Type representing $ R[x_0,\\dots,x_{d-2}]$ .

Returns: unspecified_type";
constexpr const char* PolynomialTraits_d_Innermost_coefficient_type = "Type representing the base ring $ R$ .

Returns: unspecified_type";
constexpr const char* PolynomialTraits_d_Coefficient_const_iterator = "Const iterator used to iterate through all coefficients of the polynomial.

Returns: unspecified_type";
constexpr const char* PolynomialTraits_d_Innermost_coefficient_const_iterator = "Const iterator used to iterate through all innermost coefficients of the polynomial.

Returns: unspecified_type";
constexpr const char* PolynomialTraits_d_Rebind = "This template class has to define a type Rebind <T, d >::Other which is a model of the concept PolynomialTraits_d , where d is the number of variables and T the Innermost_coefficient_type .

It can be implemented using a nested template class.

Returns: unspecified_type";
constexpr const char* PolynomialTraits_d_Construct_polynomial = "A model of PolynomialTraits_d::ConstructPolynomial .

Returns: unspecified_type";
constexpr const char* PolynomialTraits_d_Get_coefficient = "A model of PolynomialTraits_d::GetCoefficient .

Returns: unspecified_type";
constexpr const char* PolynomialTraits_d_Get_innermost_coefficient = "A model of PolynomialTraits_d::GetInnermostCoefficient .

Returns: unspecified_type";
constexpr const char* PolynomialTraits_d_Construct_coefficient_const_iterator_range = "A model of PolynomialTraits_d::ConstructCoefficientConstIteratorRange .

Returns: unspecified_type";
constexpr const char* PolynomialTraits_d_Construct_innermost_coefficient_const_iterator_range = "A model of PolynomialTraits_d::ConstructInnermostCoefficientConstIteratorRange .

Returns: unspecified_type";
constexpr const char* PolynomialTraits_d_Swap = "A model of PolynomialTraits_d::Swap .

Returns: unspecified_type";
constexpr const char* PolynomialTraits_d_Move = "A model of PolynomialTraits_d::Move .

Returns: unspecified_type";
constexpr const char* PolynomialTraits_d_Degree = "A model of PolynomialTraits_d::Degree .

Returns: unspecified_type";
constexpr const char* PolynomialTraits_d_Total_degree = "A model of PolynomialTraits_d::TotalDegree .

Returns: unspecified_type";
constexpr const char* PolynomialTraits_d_Degree_vector = "A model of PolynomialTraits_d::DegreeVector .

Returns: unspecified_type";
constexpr const char* PolynomialTraits_d_Leading_coefficient = "A model of PolynomialTraits_d::LeadingCoefficient .

Returns: unspecified_type";
constexpr const char* PolynomialTraits_d_Innermost_leading_coefficient = "A model of PolynomialTraits_d::InnermostLeadingCoefficient .

Returns: unspecified_type";
constexpr const char* PolynomialTraits_d_Canonicalize = "A model of PolynomialTraits_d::Canonicalize .

Returns: unspecified_type";
constexpr const char* PolynomialTraits_d_Differentiate = "A model of PolynomialTraits_d::Differentiate .

Returns: unspecified_type";
constexpr const char* PolynomialTraits_d_Evaluate = "A model of PolynomialTraits_d::Evaluate .

Returns: unspecified_type";
constexpr const char* PolynomialTraits_d_Evaluate_homogeneous = "A model of PolynomialTraits_d::EvaluateHomogeneous .

Returns: unspecified_type";
constexpr const char* PolynomialTraits_d_Substitute = "A model of PolynomialTraits_d::Substitute .

Returns: unspecified_type";
constexpr const char* PolynomialTraits_d_Substitute_homogeneous = "A model of PolynomialTraits_d::SubstituteHomogeneous .

Returns: unspecified_type";
constexpr const char* PolynomialTraits_d_Is_zero_at = "A model of PolynomialTraits_d::IsZeroAt .

Returns: unspecified_type";
constexpr const char* PolynomialTraits_d_Is_zero_at_homogeneous = "A model of PolynomialTraits_d::IsZeroAtHomogeneous .

Returns: unspecified_type";
constexpr const char* PolynomialTraits_d_Sign_at = "A model of PolynomialTraits_d::SignAt .

In case Innermost_coefficient_type is not RealEmbeddable this is
CGAL::Null_functor .

Returns: unspecified_type";
constexpr const char* PolynomialTraits_d_Sign_at_homogeneous = "A model of PolynomialTraits_d::SignAtHomogeneous .

In case Innermost_coefficient_type is not RealEmbeddable this is
CGAL::Null_functor .

Returns: unspecified_type";
constexpr const char* PolynomialTraits_d_Compare = "A model of PolynomialTraits_d::Compare .

In case Innermost_coefficient_type is not RealEmbeddable this is
CGAL::Null_functor .

Returns: unspecified_type";
constexpr const char* PolynomialTraits_d_Univariate_content = "In case PolynomialTraits_d::Coefficient_type is not a model of UniqueFactorizationDomain , this is CGAL::Null_functor , otherwise this is a model of PolynomialTraits_d::UnivariateContent .

Returns: unspecified_type";
constexpr const char* PolynomialTraits_d_Multivariate_content = "In case PolynomialTraits_d::Innermost_coefficient_type is not a model of UniqueFactorizationDomain , this is CGAL::Null_functor , otherwise this is a model of PolynomialTraits_d::MultivariateContent .

Returns: unspecified_type";
constexpr const char* PolynomialTraits_d_Shift = "A model of PolynomialTraits_d::Shift .

Returns: unspecified_type";
constexpr const char* PolynomialTraits_d_Negate = "A model of PolynomialTraits_d::Negate .

Returns: unspecified_type";
constexpr const char* PolynomialTraits_d_Invert = "A model of PolynomialTraits_d::Invert .

Returns: unspecified_type";
constexpr const char* PolynomialTraits_d_Translate = "A model of PolynomialTraits_d::Translate .

Returns: unspecified_type";
constexpr const char* PolynomialTraits_d_Translate_homogeneous = "A model of PolynomialTraits_d::TranslateHomogeneous .

Returns: unspecified_type";
constexpr const char* PolynomialTraits_d_Scale = "A model of PolynomialTraits_d::Scale .

Returns: unspecified_type";
constexpr const char* PolynomialTraits_d_Scale_homogeneous = "A model of PolynomialTraits_d::ScaleHomogeneous .

Returns: unspecified_type";
constexpr const char* PolynomialTraits_d_Make_square_free = "A model of PolynomialTraits_d::MakeSquareFree .

Returns: unspecified_type";
constexpr const char* PolynomialTraits_d_Square_free_factorize = "In case PolynomialTraits::Polynomial_d is not a model of UniqueFactorizationDomain , this is of type CGAL::Null_functor , otherwise this is a model of PolynomialTraits_d::SquareFreeFactorize .

Returns: unspecified_type";
constexpr const char* PolynomialTraits_d_Pseudo_division = "A model of PolynomialTraits_d::PseudoDivision .

Returns: unspecified_type";
constexpr const char* PolynomialTraits_d_Pseudo_division_remainder = "A model of PolynomialTraits_d::PseudoDivisionRemainder .

Returns: unspecified_type";
constexpr const char* PolynomialTraits_d_Pseudo_division_quotient = "A model of PolynomialTraits_d::PseudoDivisionQuotient .

Returns: unspecified_type";
constexpr const char* PolynomialTraits_d_Gcd_up_to_constant_factor = "A model of PolynomialTraits_d::GcdUpToConstantFactor .

Returns: unspecified_type";
constexpr const char* PolynomialTraits_d_Integral_division_up_to_constant_factor = "A model of PolynomialTraits_d::IntegralDivisionUpToConstantFactor .

Returns: unspecified_type";
constexpr const char* PolynomialTraits_d_Content_up_to_constant_factor = "A model of PolynomialTraits_d::UnivariateContentUpToConstantFactor .

Returns: unspecified_type";
constexpr const char* PolynomialTraits_d_Square_free_factorize_up_to_constant_factor = "A model of PolynomialTraits_d::SquareFreeFactorizeUpToConstantFactor .

Returns: unspecified_type";
constexpr const char* PolynomialTraits_d_Resultant = "A model of PolynomialTraits_d::Resultant .

Returns: unspecified_type";
constexpr const char* PolynomialTraits_d_Polynomial_subresultants = "Either CGAL::Null_functor or a model of PolynomialTraits_d::PolynomialSubresultants .

Returns: unspecified_type";
constexpr const char* PolynomialTraits_d_Polynomial_subresultants_with_cofactors = "Either CGAL::Null_functor or a model of PolynomialTraits_d::PolynomialSubresultants_with_cofactors .

Returns: unspecified_type";
constexpr const char* PolynomialTraits_d_Principal_subresultants = "Either CGAL::Null_functor or a model of PolynomialTraits_d::PrincipalSubresultants .

Returns: unspecified_type";
constexpr const char* PolynomialTraits_d_Sturm_habicht_sequence = "Either CGAL::Null_functor or a model of PolynomialTraits_d::SturmHabichtSequence .

Returns: unspecified_type";
constexpr const char* PolynomialTraits_d_Sturm_habicht_sequence_with_cofactors = "Either CGAL::Null_functor or a model of PolynomialTraits_d::SturmHabichtSequenceWithCofactors .

Returns: unspecified_type";
constexpr const char* PolynomialTraits_d_Principal_sturm_habicht_sequence = "Either CGAL::Null_functor or a model of PolynomialTraits_d::PrincipalSturmHabichtSequence .

Returns: unspecified_type";
constexpr const char* PolynomialTraits_d_d = "The dimension and the number of variables respectively.

Returns: const int";

// PolynomialTraits_d::Canonicalize
constexpr const char* PolynomialTraits_d_Canonicalize__class__ = "For a given polynomial $ p$ this AdaptableUnaryFunction computes the unique representative of the set.";

constexpr const char* PolynomialTraits_d_Canonicalize_operator = "Returns the canonical representative of $ p$ .

Parameters
----------
p : first_argument_type

Returns: result_type";

// PolynomialTraits_d::Compare
constexpr const char* PolynomialTraits_d_Compare__class__ = "This AdaptableBinaryFunction compares two polynomials, with respect to the lexicographic order with preference to the outermost variable.";

constexpr const char* PolynomialTraits_d_Compare_operator = "Compares two polynomials.

Parameters
----------
f : first_argument_type
g : second_argument_type

Returns: result_type";

// PolynomialTraits_d::ConstructCoefficientConstIteratorRange
constexpr const char* PolynomialTraits_d_ConstructCoefficientConstIteratorRange__class__ = "This AdaptableUnaryFunction returns a const iterator range over the coefficients of the given polynomial, with respect to the outermost variable, $ x_{d-1}$ . The range starts with the coefficient for $ x_{d-1}^0$ .";

constexpr const char* PolynomialTraits_d_ConstructCoefficientConstIteratorRange_operator = "Returns a const iterator range over the coefficients of $ p$ .

Parameters
----------
p : argument_type

Returns: result_type";

// PolynomialTraits_d::ConstructInnermostCoefficientConstIteratorRange
constexpr const char* PolynomialTraits_d_ConstructInnermostCoefficientConstIteratorRange__class__ = "This AdaptableUnaryFunction returns a const iterator range over all innermost coefficients of the given polynomial.";

constexpr const char* PolynomialTraits_d_ConstructInnermostCoefficientConstIteratorRange_operator = "Returns a const iterator range over all innermost coefficients of $ p$ .

Parameters
----------
p : argument_type

Returns: result_type";

// PolynomialTraits_d::ConstructPolynomial
constexpr const char* PolynomialTraits_d_ConstructPolynomial__class__ = "This AdaptableFunctor provides several operators to construct objects of type PolynomialTraits_d::Polynomial_d .";

constexpr const char* PolynomialTraits_d_ConstructPolynomial_operator = "Construct the zero polynomial.

Returns: result_type";
constexpr const char* PolynomialTraits_d_ConstructPolynomial_operator_1 = "Construct the constant polynomial equal to $ i$ .

Parameters
----------
i : int

Returns: result_type";
constexpr const char* PolynomialTraits_d_ConstructPolynomial_operator_2 = "Construct the constant polynomial equal to $ a$ .

Parameters
----------
a : PolynomialTraits_d::Innermost_coefficient_type

Returns: result_type";
constexpr const char* PolynomialTraits_d_ConstructPolynomial_operator_3 = "Construct the polynomial equal to $ a$ .

Parameters
----------
a : PolynomialTraits_d::Coefficient_type

Returns: result_type";
constexpr const char* PolynomialTraits_d_ConstructPolynomial_operator_4 = "
The value type of InputIterator is PolynomialTraits_d::Coefficient_type . The
operator constructs the a polynomial from the iterator range, with respect to
the outermost variable, $ x_{d-1}$ . The range starts with the coefficient for
$ x_{d-1}^0$ . In case the range is empty, the zero polynomial is constructed.

Parameters
----------
begin : InputIterator
end : InputIterator

Returns: result_type";
constexpr const char* PolynomialTraits_d_ConstructPolynomial_operator_5 = "Constructs a Polynomial_d from a given iterator range of std::pair< CGAL::Exponent_vector , PolynomialTraits_d::Innermost_coefficient_type > .

The optional parameter is_sorted indicates whether the given iterator range is
already sorted. The value type of InputIterator is std::pair<
CGAL::Exponent_vector , PolynomialTraits_d::Innermost_coefficient_type > .
Each CGAL::Exponent_vector must have size $ d$ . All appearing
CGAL::Exponent_vector s are different.

Parameters
----------
begin : InputIterator
end : InputIterator
is_sorted : bool

Returns: result_type";

// PolynomialTraits_d::Degree
constexpr const char* PolynomialTraits_d_Degree__class__ = "This AdaptableUnaryFunction computes the degree of a PolynomialTraits_d::Polynomial_d with respect to a certain variable.";

constexpr const char* PolynomialTraits_d_Degree_operator = "Computes the degree of $ p$ with respect to the outermost variable $ x_{d-1}$ .

Parameters
----------
p : argument_type

Returns: result_type";
constexpr const char* PolynomialTraits_d_Degree_operator_1 = "Computes the degree of $ p$ with respect to variable $ x_i$ .

$ 0 \\leq i < d$ .

Parameters
----------
p : argument_type
i : int

Returns: result_type";

// PolynomialTraits_d::DegreeVector
constexpr const char* PolynomialTraits_d_DegreeVector__class__ = "For a given PolynomialTraits_d::Polynomial_d $ p$ this AdaptableUnaryFunction returns the degree vector, that is, it returns the exponent vector of the monomial of highest order in $ p$ , where the monomial order is the lexicographic order giving outer variables a higher priority. In particular, this is the monomial that belongs to the innermost leading coefficient of $ p$ .";

constexpr const char* PolynomialTraits_d_DegreeVector_operator = "Returns the degree vector.

Parameters
----------
p : argument_type

Returns: result_type";

// PolynomialTraits_d::Differentiate
constexpr const char* PolynomialTraits_d_Differentiate__class__ = "This AdaptableUnaryFunction computes the derivative of a PolynomialTraits_d::Polynomial_d with respect to one variable.";

constexpr const char* PolynomialTraits_d_Differentiate_operator = "Returns $ p'$ , with respect to the outermost variable.

Parameters
----------
p : argument_type

Returns: result_type";
constexpr const char* PolynomialTraits_d_Differentiate_operator_1 = "Returns $ p'$ , with respect to variable $ x_i$ .

$ 0 \\leq i < d$ .

Parameters
----------
p : argument_type
i : int

Returns: result_type";

// PolynomialTraits_d::Evaluate
constexpr const char* PolynomialTraits_d_Evaluate__class__ = "This AdaptableBinaryFunction evaluates PolynomialTraits_d::Polynomial_d with respect to one variable.";

constexpr const char* PolynomialTraits_d_Evaluate_operator = "Returns $ p(x)$ , with respect to the outermost variable.

Parameters
----------
p : first_argument_type
x : second_argument_type

Returns: result_type";

// PolynomialTraits_d::EvaluateHomogeneous
constexpr const char* PolynomialTraits_d_EvaluateHomogeneous__class__ = "This AdaptableFunctor provides evaluation of a PolynomialTraits_d::Polynomial_d interpreted as a homogeneous polynomial in one variable .";

constexpr const char* PolynomialTraits_d_EvaluateHomogeneous_operator = "Returns $ p(u,v)$ , with respect to the outermost variable.

Parameters
----------
p : PolynomialTraits_d::Polynomial_d
u : PolynomialTraits_d::Coefficient_type
v : PolynomialTraits_d::Coefficient_type

Returns: result_type";

// PolynomialTraits_d::GcdUpToConstantFactor
constexpr const char* PolynomialTraits_d_GcdUpToConstantFactor__class__ = "This AdaptableBinaryFunction computes the $ gcd$ up to a constant factor (utcf) of two polynomials of type PolynomialTraits_d::Polynomial_d .";

constexpr const char* PolynomialTraits_d_GcdUpToConstantFactor_operator = "Computes $ gcd(f,g)$ up to a constant factor.

Parameters
----------
f : first_argument_type
g : second_argument_type

Returns: result_type";

// PolynomialTraits_d::GetCoefficient
constexpr const char* PolynomialTraits_d_GetCoefficient__class__ = "This AdaptableBinaryFunction provides access to coefficients of a PolynomialTraits_d::Polynomial_d .";

constexpr const char* PolynomialTraits_d_GetCoefficient_operator = "For given polynomial $ p$ this operator returns the coefficient of $ x_{d-1}^e$ , where $ x_{d-1}$ is the outermost variable.

Parameters
----------
p : first_argument_type
e : second_argument_type

Returns: result_type";

// PolynomialTraits_d::GetInnermostCoefficient
constexpr const char* PolynomialTraits_d_GetInnermostCoefficient__class__ = "For the given PolynomialTraits_d::Polynomial_d this AdaptableBinaryFunction returns the coefficient of the (multivariate) monomial specified by the given CGAL::Exponent_vector .";

constexpr const char* PolynomialTraits_d_GetInnermostCoefficient_operator = "For given polynomial $ p$ this operator returns the innermost coefficient of the monomial corresponding to the given CGAL::Exponent_vector $ v$ .

Parameters
----------
p : first_argument_type
v : second_argument_type

Returns: result_type";

// PolynomialTraits_d::InnermostLeadingCoefficient
constexpr const char* PolynomialTraits_d_InnermostLeadingCoefficient__class__ = "This AdaptableUnaryFunction computes the innermost leading coefficient of a PolynomialTraits_d::Polynomial_d $ p$ . The innermost leading coefficient is recursively defined as the innermost leading coefficient of the leading coefficient of $ p$ . In case $ p$ is univariate it coincides with the leading coefficient.";

constexpr const char* PolynomialTraits_d_InnermostLeadingCoefficient_operator = "Computes the innermost leading coefficient of $ p$ .

Parameters
----------
p : argument_type

Returns: result_type";

// PolynomialTraits_d::IntegralDivisionUpToConstantFactor
constexpr const char* PolynomialTraits_d_IntegralDivisionUpToConstantFactor__class__ = "This AdaptableBinaryFunction computes the integral division of two polynomials of type PolynomialTraits_d::Polynomial_d up to a constant factor (utcf) .";

constexpr const char* PolynomialTraits_d_IntegralDivisionUpToConstantFactor_operator = "Computes $ f/g$ up to a constant factor.

Parameters
----------
f : first_argument_type
g : second_argument_type

Returns: result_type";

// PolynomialTraits_d::Invert
constexpr const char* PolynomialTraits_d_Invert__class__ = "This AdaptableUnaryFunction inverts one variable in a given PolynomialTraits_d::Polynomial_d , that is, for a given polynomial $ p$ it computes $ x^{degree(p)}p(1/x)$ .";

constexpr const char* PolynomialTraits_d_Invert_operator = "Returns $ x^{degree(p)}p(1/x)$ , where x refers to the outermost variable $ x_{d-1}$ .

Parameters
----------
p : argument_type

Returns: result_type";
constexpr const char* PolynomialTraits_d_Invert_operator_1 = "Return $ x^{degree(p,i)}p(1/x)$ , where x refers to the variable $ x_{i}$ .

$ 0 \\leq i < d$ .

Parameters
----------
p : argument_type
i : int

Returns: result_type";

// PolynomialTraits_d::IsSquareFree
constexpr const char* PolynomialTraits_d_IsSquareFree__class__ = "This AdaptableUnaryFunction computes whether the given a polynomial of type PolynomialTraits_d::Polynomial_d is square free.";

constexpr const char* PolynomialTraits_d_IsSquareFree_operator = "Returns whether the $ p$ is square free.

Parameters
----------
p : argument_type

Returns: result_type";

// PolynomialTraits_d::IsZeroAt
constexpr const char* PolynomialTraits_d_IsZeroAt__class__ = "This AdaptableFunctor returns whether a PolynomialTraits_d::Polynomial_d $ p$ is zero at a given Cartesian point, which is represented as an iterator range.";

constexpr const char* PolynomialTraits_d_IsZeroAt_operator = "Computes whether $ p$ is zero at the Cartesian point given by the iterator range, where begin is referring to the innermost variable.

(end-begin == PolynomialTraits_d::d ) std::iterator_traits< InputIterator
>::value_type is ExplicitInteroperable with
PolynomialTraits_d::Innermost_coefficient_type .

Parameters
----------
p : PolynomialTraits_d::Polynomial_d
begin : InputIterator
end : InputIterator

Returns: result_type";

// PolynomialTraits_d::IsZeroAtHomogeneous
constexpr const char* PolynomialTraits_d_IsZeroAtHomogeneous__class__ = "This AdaptableFunctor returns whether a PolynomialTraits_d::Polynomial_d $ p$ is zero at a given homogeneous point, which is given by an iterator range.";

constexpr const char* PolynomialTraits_d_IsZeroAtHomogeneous_operator = "Computes whether $ p$ is zero at the homogeneous point given by the iterator range, where begin is referring to the innermost variable.

(end-begin== PolynomialTraits_d::d +1) std::iterator_traits< InputIterator
>::value_type is ExplicitInteroperable with
PolynomialTraits_d::Innermost_coefficient_type .

Parameters
----------
p : PolynomialTraits_d::Polynomial_d
begin : InputIterator
end : InputIterator

Returns: result_type";

// PolynomialTraits_d::LeadingCoefficient
constexpr const char* PolynomialTraits_d_LeadingCoefficient__class__ = "This AdaptableUnaryFunction computes the leading coefficient of a PolynomialTraits_d::Polynomial_d .";

constexpr const char* PolynomialTraits_d_LeadingCoefficient_operator = "Computes the leading coefficient of $ p$ with respect to the outermost variable $ x_{d-1}$ .

Parameters
----------
p : argument_type

Returns: result_type";

// PolynomialTraits_d::MakeSquareFree
constexpr const char* PolynomialTraits_d_MakeSquareFree__class__ = "This AdaptableUnaryFunction computes the square-free part of a polynomial of type PolynomialTraits_d::Polynomial_d up to a constant factor .";

constexpr const char* PolynomialTraits_d_MakeSquareFree_operator = "Returns the square-free part of $ p$ .

Parameters
----------
p : argument_type

Returns: result_type";

// PolynomialTraits_d::MonomialRepresentation
constexpr const char* PolynomialTraits_d_MonomialRepresentation__class__ = "This Functor outputs the monomial representation of the given polynomial, that is, it writes all non zero terms of the polynomial as std::pair< CGAL::Exponent_vector , PolynomialTraits_d::Innermost_coefficient_type > into the given output iterator.";

constexpr const char* PolynomialTraits_d_MonomialRepresentation_operator = "Writes the monom representation of $ p$ into the given output iterator $ it$ .

std::iterator_traits< OutputIterator >::value_type must be constructible from
std::pair< CGAL::Exponent_vector ,
PolynomialTraits_d::Innermost_coefficient_type > .

Parameters
----------
p : PolynomialTraits_d::Polynomial_d
it : OutputIterator

Returns: OutputIterator";

// PolynomialTraits_d::Move
constexpr const char* PolynomialTraits_d_Move__class__ = "This AdaptableFunctor moves a variable at position $ i$ to a new position $ j$ . The relative order of the other variables is preserved, that is, the variables between $ x_i$ and $ x_j$ (including $ x_j$ ) are moved by one position while $ x_i$ is moved to the former position of $ x_j$ .";

constexpr const char* PolynomialTraits_d_Move_operator = "This function moves the variable at position $ i$ to its new position $ j$ and returns the new polynomial.

The relative order of the other variables is preserved. $ 0 \\leq i < d$ . $ 0
\\leq j < d$ .

Parameters
----------
 : PolynomialTraits_d::Polynomial_d
i : int
j : int

Returns: result_type";

// PolynomialTraits_d::MultivariateContent
constexpr const char* PolynomialTraits_d_MultivariateContent__class__ = "This AdaptableUnaryFunction computes the content of a PolynomialTraits_d::Polynomial_d with respect to the symmetric view on the polynomial, that is, it computes the gcd of all innermost coefficients.";

constexpr const char* PolynomialTraits_d_MultivariateContent_operator = "Computes the $ gcd$ of all innermost coefficients of $ p$ .

Parameters
----------
p : argument_type

Returns: result_type";

// PolynomialTraits_d::Negate
constexpr const char* PolynomialTraits_d_Negate__class__ = "This AdaptableUnaryFunction computes $ p(-x)$ for a given polynomial $ p$ .";

constexpr const char* PolynomialTraits_d_Negate_operator = "Returns $ p(-x)$ , with respect to the outermost variable.

Parameters
----------
p : argument_type

Returns: result_type";
constexpr const char* PolynomialTraits_d_Negate_operator_1 = "Returns $ p(-x)$ , with respect to variable $ x_i$ .

$ 0 \\leq i < d$ .

Parameters
----------
p : argument_type
i : int

Returns: result_type";

// PolynomialTraits_d::Permute
constexpr const char* PolynomialTraits_d_Permute__class__ = "This AdaptableFunctor permutes the variables of the given polynomial with respect to a permutation $ \\sigma$ , that is, each monomial $ \\prod x_i^{e_i}$ will be mapped to the monomial $ \\prod x_{\\sigma(i)}^{e_i}$ . The permutation $ \\sigma$ is given by the iterator range of length PolynomialTraits_d::d , which is supposed to contain the second row of the permutation.";

constexpr const char* PolynomialTraits_d_Permute_operator = "Returns $ p$ with interchanged variables as defined by the iterator range.

(end-begin == PolynomialTraits_d::d ) std::iterator_traits< InputIterator
>::value_type is convertible to int. The iterator range contains each value in
$ \\{0,\\dots,d-1\\}$ exactly once.

Parameters
----------
p : PolynomialTraits_d::Polynomial_d
begin : Input_iterator
end : Input_iterator

Returns: result_type";

// PolynomialTraits_d::PolynomialSubresultants
constexpr const char* PolynomialTraits_d_PolynomialSubresultants__class__ = "Computes the polynomial subresultant of two polynomials $ p$ and $ q$ of type PolynomialTraits_d::Polynomial_d with respect to outermost variable. Let $ p=\\ccSum{i=0,\\ldots,n}{} p_i x^i$ and $ q=\\ccSum{i=0,\\ldots,m}{} q_i x^i$ , where $ x$ is the outermost variable. The $ i$ -th subresultant (with $ i=0,\\ldots,\\min\\{n,m\\}$ ) is defined by.";

constexpr const char* PolynomialTraits_d_PolynomialSubresultants_operator = "computes the polynomial subresultants of $ p$ and $ q$ , with respect to the outermost variable.

Each element is of type PolynomialTraits_d::Polynomial_d .

Parameters
----------
p : Polynomial_d
q : Polynomial_d
out : OutputIterator

Returns: OutputIterator";
constexpr const char* PolynomialTraits_d_PolynomialSubresultants_operator_1 = "computes the polynomial subresultants of $ p$ and $ q$ , with respect to the variable $ x_i$ .

Parameters
----------
p : Polynomial_d
q : Polynomial_d
out : OutputIterator
i : int

Returns: OutputIterator";

// PolynomialTraits_d::PolynomialSubresultantsWithCofactors
constexpr const char* PolynomialTraits_d_PolynomialSubresultantsWithCofactors__class__ = "Computes the polynomial subresultant of two polynomials $ p$ and $ q$ of degree $ n$ and $ m$ , respectively, as defined in the documentation of PolynomialTraits_d::PolynomialSubresultants . Moreover, for $ \\mathrm{Sres}_i(p,q)$ , polynomials $ u_i$ and $ v_i$ with $ \\deg u_i\\leq m-i-1$ and $ \\deg v_i\\leq n-i-1$ are computed such that $ \\mathrm{Sres}_i(p,q)=u_i p + v_i q$ . $ u_i$ and $ v_i$ are called the cofactors of $ \\mathrm{Sres}_i(p,q)$ .";

constexpr const char* PolynomialTraits_d_PolynomialSubresultantsWithCofactors_operator = "computes the subresultants of $ p$ and $ q$ , and the cofactors, with respect to the outermost variable.

Each element is of type PolynomialTraits_d::Polynomial_d .

Parameters
----------
p : Polynomial_d
q : Polynomial_d
sres : OutputIterator1
co_p : OutputIterator2
co_q : OutputIterator3

Returns: OutputIterator1";
constexpr const char* PolynomialTraits_d_PolynomialSubresultantsWithCofactors_operator_1 = "computes the subresultants of $ p$ and $ q$ , and the cofactors, with respect to $ x_i$ .

Each element is of type PolynomialTraits_d::Polynomial_d .

Parameters
----------
p : Polynomial_d
q : Polynomial_d
sres : OutputIterator1
co_p : OutputIterator2
co_q : OutputIterator3
i : int

Returns: OutputIterator1";

// PolynomialTraits_d::PrincipalSturmHabichtSequence
constexpr const char* PolynomialTraits_d_PrincipalSturmHabichtSequence__class__ = "Computes the principal leading coefficients of the Sturm-Habicht sequence of a polynomials $ f$ of type PolynomialTraits_d::Polynomial_d with respect a certain variable $ x_i$ . This means that for the $ j$ -th Sturm-Habicht polynomial, this methods returns the coefficient of $ x_i^j$ .";

constexpr const char* PolynomialTraits_d_PrincipalSturmHabichtSequence_operator = "computes the principal coefficients of the Sturm-Habicht sequence of $ f$ , with respect to the outermost variable.

Each element is of type PolynomialTraits_d::Coefficient_type .

Parameters
----------
f : Polynomial_d
out : OutputIterator

Returns: OutputIterator";
constexpr const char* PolynomialTraits_d_PrincipalSturmHabichtSequence_operator_1 = "computes the principal coefficients of the Sturm-Habicht sequence of $ f$ with respect to the variable $ x_i$ .

Parameters
----------
f : Polynomial_d
out : OutputIterator
i : int

Returns: OutputIterator";

// PolynomialTraits_d::PrincipalSubresultants
constexpr const char* PolynomialTraits_d_PrincipalSubresultants__class__ = "Computes the principal subresultant of two polynomials $ p$ and $ q$ of type PolynomialTraits_d::Coefficient_type with respect to the outermost variable. The $ i$ -th principal subresultant, $ \\mathrm{sres}_i(p,q)$ , is defined as the coefficient at $ t^i$ of the $ i$ -th polynomial subresultant $ \\mathrm{Sres}_i(p,q)$ . Thus, it is either the leading coefficient of $ \\mathrm{Sres}_i$ , or zero in the case where its degree is below $ i$ .";

constexpr const char* PolynomialTraits_d_PrincipalSubresultants_operator = "computes the principal subresultants of $ p$ and $ q$ , with respect to the outermost variable.

Each element is of type PolynomialTraits_d::Coefficient_type .

Parameters
----------
p : Polynomial_d
q : Polynomial_d
out : OutputIterator

Returns: OutputIterator";
constexpr const char* PolynomialTraits_d_PrincipalSubresultants_operator_1 = "computes the principal subresultants of $ p$ and $ q$ , with respect to the variable $ x_i$ .

Parameters
----------
p : Polynomial_d
q : Polynomial_d
out : OutputIterator
i : int

Returns: OutputIterator";

// PolynomialTraits_d::PseudoDivision
constexpr const char* PolynomialTraits_d_PseudoDivision__class__ = "This AdaptableFunctor computes the pseudo division of two polynomials $ f$ and $ g$ .";

constexpr const char* PolynomialTraits_d_PseudoDivision_operator = "Computes the pseudo division with respect to the outermost variable $ x_{d-1}$ .

Parameters
----------
f : PolynomialTraits_d::Polynomial_d
g : PolynomialTraits_d::Polynomial_d
q : PolynomialTraits_d::Polynomial_d &
r : PolynomialTraits_d::Polynomial_d &
D : PolynomialTraits_d::Coefficient_type &

Returns: result_type";

// PolynomialTraits_d::PseudoDivisionQuotient
constexpr const char* PolynomialTraits_d_PseudoDivisionQuotient__class__ = "This AdaptableBinaryFunction computes the quotient of the pseudo division of two polynomials $ f$ and $ g$ .";

constexpr const char* PolynomialTraits_d_PseudoDivisionQuotient_operator = "Returns the quotient $ q$ of the pseudo division of $ f$ and $ g$ with respect to the outermost variable $ x_{d-1}$ .

Parameters
----------
f : first_argument_type
g : second_argument_type

Returns: result_type";

// PolynomialTraits_d::PseudoDivisionRemainder
constexpr const char* PolynomialTraits_d_PseudoDivisionRemainder__class__ = "This AdaptableBinaryFunction computes the remainder of the pseudo division of two polynomials $ f$ and $ g$ .";

constexpr const char* PolynomialTraits_d_PseudoDivisionRemainder_operator = "Returns the remainder $ r$ of the pseudo division of $ f$ and $ g$ with respect to the outermost variable $ x_{d-1}$ .

Parameters
----------
f : first_argument_type
g : second_argument_type

Returns: result_type";

// PolynomialTraits_d::Resultant
constexpr const char* PolynomialTraits_d_Resultant__class__ = "This AdaptableBinaryFunction computes the resultant of two polynomials $ f$ and $ g$ of type PolynomialTraits_d::Polynomial_d with respect to a certain variable.";

constexpr const char* PolynomialTraits_d_Resultant_operator = "Computes the resultant of $ f$ and $ g$ , with respect to the outermost variable.

Parameters
----------
f : first_argument_type
g : second_argument_type

Returns: result_type";

// PolynomialTraits_d::Scale
constexpr const char* PolynomialTraits_d_Scale__class__ = "Given a constant $ c$ this AdaptableBinaryFunction scales a PolynomialTraits_d::Polynomial_d $ p$ with respect to one variable, that is, it computes $ p(c\\cdot x)$ .";

constexpr const char* PolynomialTraits_d_Scale_operator = "Returns $ p(c\\cdot x)$ , with respect to the outermost variable.

Parameters
----------
p : first_argument_type
c : second_argument_type

Returns: result_type";
constexpr const char* PolynomialTraits_d_Scale_operator_1 = "Same as first operator but for variable $ x_i$ .

$ 0 \\leq i < d$ .

Parameters
----------
p : first_argument_type
c : second_argument_type
i : int

Returns: result_type";

// PolynomialTraits_d::ScaleHomogeneous
constexpr const char* PolynomialTraits_d_ScaleHomogeneous__class__ = "Given a numerator $ a$ and a denominator $ b$ this AdaptableFunctor scales a PolynomialTraits_d::Polynomial_d $ p$ with respect to one variable, that is, it computes $ b^{degree(p)}\\cdot p(a/b\\cdot x)$ .";

constexpr const char* PolynomialTraits_d_ScaleHomogeneous_operator = "Returns $ b^{degree}\\cdot p(a/b\\cdot x)$ , with respect to the outermost variable.

Parameters
----------
p : PolynomialTraits_d::Polynomial_d
a : PolynomialTraits_d::Innermost_coefficient_type
b : PolynomialTraits_d::Innermost_coefficient_type

Returns: result_type";
constexpr const char* PolynomialTraits_d_ScaleHomogeneous_operator_1 = "Same as first operator but for variable $ x_i$ .

$ 0 \\leq i < d$ .

Parameters
----------
p : PolynomialTraits_d::Polynomial_d
a : PolynomialTraits_d::Innermost_coefficient_type
b : PolynomialTraits_d::Innermost_coefficient_type
i : int

Returns: result_type";

// PolynomialTraits_d::Shift
constexpr const char* PolynomialTraits_d_Shift__class__ = "This AdaptableBinaryFunction multiplies a PolynomialTraits_d::Polynomial_d by the given power of the specified variable.";

constexpr const char* PolynomialTraits_d_Shift_operator = "Returns $ p * x_{d-1}^e$ .

$ 0 \\leq e$ .

Parameters
----------
p : first_argument_type
e : second_argument_type

Returns: result_type";
constexpr const char* PolynomialTraits_d_Shift_operator_1 = "Returns $ p * x_{i}^e$ .

$ 0 \\leq e$ . $ 0 \\leq i < d$ .

Parameters
----------
p : first_argument_type
e : second_argument_type
i : int

Returns: result_type";

// PolynomialTraits_d::SignAt
constexpr const char* PolynomialTraits_d_SignAt__class__ = "This AdaptableFunctor returns the sign of a PolynomialTraits_d::Polynomial_d $ p$ at given Cartesian point represented as an iterator range.";

constexpr const char* PolynomialTraits_d_SignAt_operator = "Returns the sign of $ p$ at the given Cartesian point, where begin is referring to the innermost variable.

( end-begin == PolynomialTraits_d::d ) std::iterator_traits< InputIterator
>::value_type is ExplicitInteroperable with
PolynomialTraits_d::Innermost_coefficient_type .

Parameters
----------
p : PolynomialTraits_d::Polynomial_d
begin : InputIterator
end : InputIterator

Returns: result_type";

// PolynomialTraits_d::SignAtHomogeneous
constexpr const char* PolynomialTraits_d_SignAtHomogeneous__class__ = "This AdaptableFunctor returns the sign of a PolynomialTraits_d::Polynomial_d $ p$ at a given homogeneous point, which is given by an iterator range.";

constexpr const char* PolynomialTraits_d_SignAtHomogeneous_operator = "Returns the sign of $ p$ at the given homogeneous point, where begin is referring to the innermost variable.

( end-begin == PolynomialTraits_d::d +1) std::iterator_traits< InputIterator
>::value_type is ExplicitInteroperable with
PolynomialTraits_d::Innermost_coefficient_type .

Parameters
----------
p : PolynomialTraits_d::Polynomial_d
begin : InputIterator
end : InputIterator

Returns: result_type";

// PolynomialTraits_d::SquareFreeFactorize
constexpr const char* PolynomialTraits_d_SquareFreeFactorize__class__ = "This Functor computes a square-free factorization of a PolynomialTraits_d::Polynomial_d .";

constexpr const char* PolynomialTraits_d_SquareFreeFactorize_operator = "Computes the square-free factorization of $ p$ and returns the past-the-end iterator of the written range.

std::iterator_traits< OutputIterator >::value_type must be constructible from
std::pair< PolynomialTraits_d::Polynomial_d ,int> .

Parameters
----------
p : PolynomialTraits_d::Polynomial_d
it : OutputIterator
a : PolynomialTraits_d::Innermost_coefficient_type &

Returns: OutputIterator";
constexpr const char* PolynomialTraits_d_SquareFreeFactorize_operator_1 = "As the first operator, just not computing the factor $ a$ .

Parameters
----------
p : PolynomialTraits_d::Polynomial_d
it : OutputIterator

Returns: OutputIterator";

// PolynomialTraits_d::SquareFreeFactorizeUpToConstantFactor
constexpr const char* PolynomialTraits_d_SquareFreeFactorizeUpToConstantFactor__class__ = "This AdaptableFunctor computes a square-free factorization up to a constant factor (utcf) of a PolynomialTraits_d::Polynomial_d .";

constexpr const char* PolynomialTraits_d_SquareFreeFactorizeUpToConstantFactor_operator = "Computes the square-free factorization of $ p$ and returns the past-the-end iterator of the written range.

std::iterator_traits< OutputIterator >::value_type must be constructible from
std::pair< PolynomialTraits_d::Polynomial_d ,int> .

Parameters
----------
p : PolynomialTraits_d::Polynomial_d
it : OutputIterator

Returns: OutputIterator";

// PolynomialTraits_d::SturmHabichtSequence
constexpr const char* PolynomialTraits_d_SturmHabichtSequence__class__ = "Computes the Sturm-Habicht sequence (aka the signed subresultant sequence) of a polynomial $ f$ of type PolynomialTraits_d::Polynomial_d with respect to a certain variable $ x_i$ . The Sturm-Habicht sequence is similar to the polynomial subresultant sequence of $ f$ and its derivative $ f':=\\frac{\\partial f}{\\partial x_i}$ with respect to $ x_i$ . The implementation is based on the following definition:";

constexpr const char* PolynomialTraits_d_SturmHabichtSequence_operator = "computes the Sturm-Habicht sequence of $ f$ , with respect to the outermost variable.

Each element is of type PolynomialTraits_d::Polynomial_d .

Parameters
----------
f : Polynomial_d
out : OutputIterator

Returns: OutputIterator";
constexpr const char* PolynomialTraits_d_SturmHabichtSequence_operator_1 = "computes the Sturm-Habicht sequence of $ f$ with respect to the variable $ x_i$ .

Parameters
----------
f : Polynomial_d
out : OutputIterator
i : int

Returns: OutputIterator";

// PolynomialTraits_d::SturmHabichtSequenceWithCofactors
constexpr const char* PolynomialTraits_d_SturmHabichtSequenceWithCofactors__class__ = "Computes the Sturm-Habicht polynomials of a polynomial $ f$ of degree $ n$ , as defined in the documentation of PolynomialTraits_d::SturmHabichtSequence . Moreover, for $ \\mathrm{Stha}_i(f)$ , polynomials $ u_i$ and $ v_i$ with $ \\deg u_i\\leq n-i-2$ and $ \\deg v_i\\leq n-i-1$ are computed such that $ \\mathrm{Sres}_i(p,q)=u_i f + v_i f'$ . $ u_i$ and $ v_i$ are called the cofactors of $ \\mathrm{Stha}_i(f)$ .";

constexpr const char* PolynomialTraits_d_SturmHabichtSequenceWithCofactors_operator = "computes the Sturm-Habicht sequence of $ f$ , and the cofactors, with respect to the outermost variable.

Each element is of type PolynomialTraits_d::Polynomial_d .

Parameters
----------
f : Polynomial_d
stha : OutputIterator1
co_f : OutputIterator2
co_fx : OutputIterator3

Returns: OutputIterator1";
constexpr const char* PolynomialTraits_d_SturmHabichtSequenceWithCofactors_operator_1 = "computes the Sturm-Habicht sequence of $ f$ , and the cofactors, with respect to $ x_i$ .

Each element is of type PolynomialTraits_d::Polynomial_d .

Parameters
----------
f : Polynomial_d
stha : OutputIterator1
co_f : OutputIterator2
co_fx : OutputIterator3
i : int

Returns: OutputIterator1";

// PolynomialTraits_d::Substitute
constexpr const char* PolynomialTraits_d_Substitute__class__ = "This Functor substitutes all variables of a given multivariate PolynomialTraits_d::Polynomial_d by the values given in the iterator range, where begin refers the value for the innermost variable.";

constexpr const char* PolynomialTraits_d_Substitute_operator = "Substitutes each variable of $ p$ by the values given in the iterator range, where begin refers to the innermost variable $ x_0$ .

( end-begin == PolynomialTraits_d::d )

Parameters
----------
p : PolynomialTraits_d::Polynomial_d
begin : Input_iterator
end : Input_iterator

Returns: result_type";

// PolynomialTraits_d::SubstituteHomogeneous
constexpr const char* PolynomialTraits_d_SubstituteHomogeneous__class__ = "This Functor substitutes all variables of a given multivariate PolynomialTraits_d::Polynomial_d $ p$ by the values given in the iterator range, where begin refers the value for the innermost variable. In contrast to PolynomialTraits_d::Substitute the given polynomial $ p$ is interpreted as a homogeneous polynomial. Hence the iterator range is required to be of length PolynomialTraits_d::d +1 .";

constexpr const char* PolynomialTraits_d_SubstituteHomogeneous_operator = "Substitutes each variable of $ p$ by the values given in the iterator range, where $ p$ is interpreted as a homogeneous polynomial in all variables.

The begin iterator refers to the innermost variable $ x_0$ . ( end-begin ==
PolynomialTraits_d::d )+1

Parameters
----------
p : PolynomialTraits_d::Polynomial_d
begin : Input_iterator
end : Input_iterator

Returns: result_type";

// PolynomialTraits_d::Swap
constexpr const char* PolynomialTraits_d_Swap__class__ = "This AdaptableFunctor swaps two variables of a multivariate polynomial.";

constexpr const char* PolynomialTraits_d_Swap_operator = "Returns polynomial $ p$ with interchanged variables $ x_i$ , $ x_j$ .

$ 0 \\leq i < d$ . $ 0 \\leq j < d$ .

Parameters
----------
p : PolynomialTraits_d::Polynomial_d
i : int
j : int

Returns: result_type";

// PolynomialTraits_d::TotalDegree
constexpr const char* PolynomialTraits_d_TotalDegree__class__ = "This AdaptableUnaryFunction computes the total degree of a PolynomialTraits_d::Polynomial_d .";

constexpr const char* PolynomialTraits_d_TotalDegree_operator = "Computes the total degree of $ p$ .

Parameters
----------
p : argument_type

Returns: result_type";

// PolynomialTraits_d::Translate
constexpr const char* PolynomialTraits_d_Translate__class__ = "This AdaptableBinaryFunction translates a PolynomialTraits_d::Polynomial_d with respect to one variable, that is, for a given polynomial $ p$ and constant $ c$ it computes $ p(x+c)$ .";

constexpr const char* PolynomialTraits_d_Translate_operator = "Returns $ p(x+c)$ , with respect to the outermost variable.

Parameters
----------
p : first_argument_type
c : second_argument_type

Returns: result_type";
constexpr const char* PolynomialTraits_d_Translate_operator_1 = "Same as first operator but for variable $ x_i$ .

$ 0 \\leq i < d$ .

Parameters
----------
p : first_argument_type
c : second_argument_type
i : int

Returns: result_type";

// PolynomialTraits_d::TranslateHomogeneous
constexpr const char* PolynomialTraits_d_TranslateHomogeneous__class__ = "Given numerator $ a$ and denominator $ b$ this AdaptableFunctor translates a PolynomialTraits_d::Polynomial_d $ p$ with respect to one variable by $ a/b$ , that is, it computes $ b^{degree(p)}\\cdot p(x+a/b)$ .";

constexpr const char* PolynomialTraits_d_TranslateHomogeneous_operator = "Returns $ b^{degree(p)}\\cdot p(x+a/b)$ , with respect to the outermost variable.

Parameters
----------
p : PolynomialTraits_d::Polynomial_d
a : PolynomialTraits_d::Innermost_coefficient_type
b : PolynomialTraits_d::Innermost_coefficient_type

Returns: result_type";
constexpr const char* PolynomialTraits_d_TranslateHomogeneous_operator_1 = "Same as first operator but for variable $ x_i$ .

$ 0 \\leq i < d$ .

Parameters
----------
p : PolynomialTraits_d::Polynomial_d
a : PolynomialTraits_d::Innermost_coefficient_type
b : PolynomialTraits_d::Innermost_coefficient_type
i : int

Returns: result_type";

// PolynomialTraits_d::UnivariateContent
constexpr const char* PolynomialTraits_d_UnivariateContent__class__ = "This AdaptableUnaryFunction computes the content of a PolynomialTraits_d::Polynomial_d with respect to the univariate (recursive) view on the polynomial, that is, it computes the gcd of all coefficients with respect to one variable.";

constexpr const char* PolynomialTraits_d_UnivariateContent_operator = "Computes the content of $ p$ with respect to the outermost variable $ x_{d-1}$ .

Parameters
----------
p : argument_type

Returns: result_type";

// PolynomialTraits_d::UnivariateContentUpToConstantFactor
constexpr const char* PolynomialTraits_d_UnivariateContentUpToConstantFactor__class__ = "This AdaptableUnaryFunction computes the content of a PolynomialTraits_d::Polynomial_d with respect to the univariate (recursive) view on the polynomial up to a constant factor (utcf) , that is, it computes the $ \\mathrm{gcd\\_utcf}$ of all coefficients with respect to one variable.";

constexpr const char* PolynomialTraits_d_UnivariateContentUpToConstantFactor_operator = "Computes the content up to a constant factor of $ p$ with respect to the outermost variable $ x_{d-1}$ .

Parameters
----------
p : first_argument_type

Returns: result_type";

constexpr const char* Exponent_vector_is_valid_1 = "Returns true if all entries of exponent vector ev are not negative.

Parameters
----------
ev : const Exponent_vector &

Returns: bool";
constexpr const char* Polynomial_operator_3 = "Writes poly to ostream os .

The format depends on the CGAL::IO::MODE of os . In case the mode is
CGAL::IO::ASCII the format is $ P[d(0,a_0)(1,a_1)\\dots(d,a_d)]$ , where $ d$
is the degree of the polynomial. The format is output sensitive, that is,
coefficients that are zero are not reported. In case the mode is
CGAL::IO::PRETTY the format is human readable.

Parameters
----------
os : std::ostream &
poly : const Polynomial < Coeff > &

Returns: std::ostream &";
constexpr const char* Polynomial_operator_4 = "Reads poly from istream is in format $ P[d(0,a_0)(1,a_1)\\dots(d,a_d)]$ , the output format in mode CGAL::IO::ASCII .

Parameters
----------
is : std::istream &
poly : const Polynomial < Coeff > &

Returns: std::istream &";

// std
constexpr const char* std__class__ = "STL namespace.";

} // namespace Polynomial
} // namespace docstrings
} // namespace cgalpy

#endif // CGAL_PYTHON_DOCSTRINGS_POLYNOMIAL_H
