#!/usr/bin/env python3
"""
cpp_docstrings_from_json.py  —  CGAL GSoC 2026: Python Bindings Enhancement
Converts structured JSON (from json_from_xml.py) into C++ header files
containing constexpr char arrays for use as nanobind docstrings.

Output layout:
    <out_dir>/<Package>/docstrings.h
    e.g. docstrings/Arrangement_on_surface_2/docstrings.h

Usage:
    python3 cpp_docstrings_from_json.py <input.json> <out_dir>

Example:
    python3 cpp_docstrings_from_json.py \
        ~/build/cgal_doc/aos2_docs.json \
        ~/trees/cgal-python-bindings/src/libs/cgalpy/lib/docstrings/Arrangement_on_surface_2
"""

import sys
import json
import re
from pathlib import Path


def escape_cpp(s):
    """Escape a string for use inside a C++ raw string literal."""
    # Replace )--" sequences that would break R"--( delimiters
    return s.replace('\\', '\\\\').replace('"', '\\"')


def make_identifier(name):
    """Convert a C++ qualified name to a valid C identifier."""
    s = re.sub(r'[^A-Za-z0-9_]', '_', name)
    s = re.sub(r'_+', '_', s)
    return s.strip('_')


def format_docstring(compound_name, member):
    """Format a single member's docstring as a constexpr C string."""
    ident = make_identifier(
        member.get("qualified_name") or
        f"{compound_name}__{member.get('name', 'unknown')}"
    )
    brief = member.get("brief", "").strip()
    detailed = member.get("detailed", "").strip()

    lines = []
    if brief:
        lines.append(brief)
    if detailed and detailed != brief:
        lines.append("")
        # Word-wrap detailed at ~78 chars
        words = detailed.split()
        line = ""
        for w in words:
            if len(line) + len(w) + 1 > 78:
                lines.append(line)
                line = w
            else:
                line = (line + " " + w).strip()
        if line:
            lines.append(line)

    # Build param section
    params = [p for p in member.get("params", []) if p.get("name") or p.get("type")]
    if params:
        lines.append("")
        lines.append("Parameters")
        lines.append("----------")
        for p in params:
            pname = p.get("name", "").strip()
            ptype = p.get("type", "").strip()
            pbrief = p.get("brief", "").strip()
            entry = f"{pname} : {ptype}" if ptype else pname
            if pbrief:
                entry += f"  —  {pbrief}"
            lines.append(entry)

    ret = member.get("return_type", "").strip()
    if ret and ret not in ("void", ""):
        lines.append("")
        lines.append(f"Returns: {ret}")

    doc_text = escape_cpp("\n".join(lines))
    return ident, doc_text


def generate_header(package_name, data, out_path):
    """Generate a single C++ header with all docstrings for a package."""
    guard = f"CGAL_PYTHON_DOCSTRINGS_{make_identifier(package_name).upper()}_H"

    lines = [
        f"// AUTO-GENERATED by cpp_docstrings_from_json.py — DO NOT EDIT",
        f"// Package: {package_name}",
        f"#ifndef {guard}",
        f"#define {guard}",
        f"",
        f"namespace cgalpy {{",
        f"namespace docstrings {{",
        f"namespace {make_identifier(package_name)} {{",
        f"",
    ]

    count = 0
    seen_idents = {}
    for compound_name, compound in data.items():
        members = compound.get("members", [])
        if compound.get("brief"):
            ident = make_identifier(compound_name) + "__class__"
            doc_text = escape_cpp(compound["brief"].strip())
            lines.append(f"// {compound_name}")
            lines.append(f'constexpr const char* {ident} = "{doc_text}";')
            lines.append("")
            count += 1

        for member in members:
            brief = member.get("brief", "").strip()
            detailed = member.get("detailed", "").strip()
            if not brief and not detailed:
                continue
            try:
                ident, doc_text = format_docstring(compound_name, member)
            except Exception:
                continue
            # Disambiguate duplicate identifiers (overloads)
            if ident in seen_idents:
                seen_idents[ident] += 1
                ident = f"{ident}_{seen_idents[ident]}"
            else:
                seen_idents[ident] = 0
            lines.append(f'constexpr const char* {ident} = "{doc_text}";')
            count += 1

        if members:
            lines.append("")

    lines += [
        f"}} // namespace {make_identifier(package_name)}",
        f"}} // namespace docstrings",
        f"}} // namespace cgalpy",
        f"",
        f"#endif // {guard}",
        "",
    ]

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines), encoding="utf-8")
    return count


def main():
    if len(sys.argv) != 3:
        print(__doc__)
        sys.exit(1)

    json_file = Path(sys.argv[1])
    out_dir   = Path(sys.argv[2])

    if not json_file.exists():
        print(f"ERROR: JSON file not found: {json_file}", file=sys.stderr)
        sys.exit(1)

    data = json.loads(json_file.read_text(encoding="utf-8"))
    package_name = out_dir.name

    out_path = out_dir / "docstrings.h"
    count = generate_header(package_name, data, out_path)

    print(f"Written: {out_path}", file=sys.stderr)
    print(f"  {count} docstring entries for package '{package_name}'", file=sys.stderr)


if __name__ == "__main__":
    main()
