#!/bin/bash

pip_cmd=pip3
pip_parms="install --user --force-reinstall --quiet"
make_parms="-j4 --quiet --no-print-directory"
whl_dirname="./src/libs/cgalpy/dist"
mode="release"
prefix="CGALPY"
# use pure wheel for now
suffix="1.0.10-cp310-cp310-linux_x86_64.whl"

declare -i i=0
item="item$i"
# eval "declare -a $item=('aos2_epec_fixed'     '')";                            ((i++)); item="item$i"
# eval "declare -a $item=('ch2_epic_fixed '     '')";                            ((i++)); item="item$i"
# eval "declare -a $item=('epec_fixed'          '')";                            ((i++)); item="item$i"

eval "declare -a $item=('aos2_alg_epec'       'kerEpecInt_aos2AlgPl')";                  ((i++)); item="item$i"
eval "declare -a $item=('aos2_bezier_epec'    'kerEpecInt_aos2BezPl')";                  ((i++)); item="item$i"
eval "declare -a $item=('aos2_conic_epec'     'kerEpecInt_aos2ConicPl')";                ((i++)); item="item$i"
eval "declare -a $item=('aos2_ccd_seg_epec'   'kerEpecInt_aos2SegCdCcdPl')";             ((i++)); item="item$i"
eval "declare -a $item=('aos2_cd_pos_epec'    'kerEpecInt_aos2PosCdPl')";                ((i++)); item="item$i"
eval "declare -a $item=('aos2_cs_epec'        'kerEpecInt_aos2CsPl')";                   ((i++)); item="item$i"
eval "declare -a $item=('aos2_cs_ve_epec'     'kerEpecInt_aos2CsVe')";                   ((i++)); item="item$i"
eval "declare -a $item=('aos2_epic'           'kerEpic_aos2SegPl')";                     ((i++)); item="item$i"
eval "declare -a $item=('aos2_geodesic_epec'  'kerEpecInt_aos2GosPl')";                  ((i++)); item="item$i"
eval "declare -a $item=('aos2_geodesic_pol3_pmp_epec' 'kerEpecInt_aos2GosPl_pol3Wn_pmpPol3')"; ((i++)); item="item$i"
eval "declare -a $item=('aos2_linear_epec'    'kerEpecInt_aos2LinearPl')";               ((i++)); item="item$i"
eval "declare -a $item=('aos2_linear_fe_epec' 'kerEpecInt_aos2LinearFe')";               ((i++)); item="item$i"
eval "declare -a $item=('aos2_ncseg_epec'     'kerEpecInt_aos2NcsegPl')";                ((i++)); item="item$i"
eval "declare -a $item=('aos2_ncseg_epic'     'kerEpic_aos2NcsegPl')";                   ((i++)); item="item$i"
eval "declare -a $item=('aos2_pos_epec'       'kerEpecInt_aos2PosPl')";                  ((i++)); item="item$i"
eval "declare -a $item=('aos2_rational_epec'  'kerEpecInt_aos2RatPl')";                  ((i++)); item="item$i"
eval "declare -a $item=('aos2_seg_ae_epec'    'kerEpecInt_aos2SegVeHeFePl')";            ((i++)); item="item$i"
eval "declare -a $item=('aos2_seg_bvr_epec'   'kerEpecInt_aos2SegPl_bvArr2')";           ((i++)); item="item$i"
eval "declare -a $item=('aos2_seg_epec'       'kerEpecInt_aos2SegPl')";                  ((i++)); item="item$i"
eval "declare -a $item=('aos2_seg_epic'       'kerEpic_aos2SegPl')";                     ((i++)); item="item$i"
# eval "declare -a $item=('aos2_trc_cnt_geodesic_epec' 'kerEpecInt_aos2TrcCntGos')";       ((i++)); item="item$i"
# eval "declare -a $item=('aos2_trc_cnt_seg_epec' 'kerEpic_aos2TrcCntSeg')";               ((i++)); item="item$i"
eval "declare -a $item=('aos2_wh_seg_epec'    'kerEpecInt_aos2SegCdCcdWhPl')";           ((i++)); item="item$i"
eval "declare -a $item=('aos2_wh_cs_epec'     'kerEpecInt_aos2CsCdCcdWhPl')";            ((i++)); item="item$i"
eval "declare -a $item=('aos2_wh_seg_fe_epec' 'kerEpecInt_aos2SegCdCcdFeWhPl')";         ((i++)); item="item$i"
eval "declare -a $item=('as2_del_epic'        'kerEpic_as2_tri2DelNci')";                ((i++)); item="item$i"
# eval "declare -a $item=('as3_del_fast_epic'   'kerEpic_as3Plain_tri3DelFasSeq')";        ((i++)); item="item$i"
eval "declare -a $item=('bso2_bezier_ccr'     'kerCcrInt_aos2Bez_bso2')";                ((i++)); item="item$i"
eval "declare -a $item=('bso2_cs_epec'        'kerEpecInt_aos2Cs_bso2')";                ((i++)); item="item$i"
eval "declare -a $item=('bso2_seg_epec'       'kerEpecInt_aos2Seg_bso2_pol2')";          ((i++)); item="item$i"
eval "declare -a $item=('cdlg'                'kerdCdlgDynamic')";                       ((i++)); item="item$i"
eval "declare -a $item=('ch2_epec'            'kerEpecInt_ch2')";                        ((i++)); item="item$i"
eval "declare -a $item=('ch2_epic'            'kerEpicInt_ch2')";                        ((i++)); item="item$i"
eval "declare -a $item=('env2_linear_cd_epec' 'kerEpecInt_aos2LinearCdPl_env2')";        ((i++)); item="item$i"
eval "declare -a $item=('env2_rat_cd_ccr'     'kerCcrInt_aos2RatCdPl_env2')";            ((i++)); item="item$i"
eval "declare -a $item=('env2_seg_cd_epec'    'kerEpecInt_aos2SegCdPl_env2')";           ((i++)); item="item$i"
eval "declare -a $item=('env3_plane_epec'     'kerEpecInt_aos2LinearPl_env3Plane')";     ((i++)); item="item$i"
eval "declare -a $item=('env3_plane_sd_epec'  'kerEpecInt_aos2LinearPl_env3PlaneSd')";   ((i++)); item="item$i"
eval "declare -a $item=('env3_sphere_ccr'     'kerCcrInt_aos2ConicPl_env3Sphere')";      ((i++)); item="item$i"
# eval "declare -a $item=('env3_tri_epec'       'kerEpecInt_aos2SegPl_env3Tri')";        ((i++)); item="item$i"
eval "declare -a $item=('env3_tri_sd_epec'    'kerEpecInt_aos2SegPl_env3TriSd')";        ((i++)); item="item$i"
eval "declare -a $item=('epecd'               'kerdEpecdDynamic')";                      ((i++)); item="item$i"
eval "declare -a $item=('epec'                'kerEpecInt')";                            ((i++)); item="item$i"
eval "declare -a $item=('epicd'               'kerdEpicdDynamic')";                      ((i++)); item="item$i"
eval "declare -a $item=('epic'                'kerEpic')";                               ((i++)); item="item$i"
eval "declare -a $item=('ms2_conic_ccr'       'kerCcrInt_aos2Conic_pol2_ms2')";          ((i++)); item="item$i"
eval "declare -a $item=('ms2_cs_epec'         'kerEpecInt_aos2Cs_pol2_ms2')";            ((i++)); item="item$i"
eval "declare -a $item=('ms2_seg_epec'        'kerEpecInt_aos2SegPl_bso2_pol2_ms2_pp')"; ((i++)); item="item$i"
eval "declare -a $item=('pol3_bso2_epec'      'kerEpecInt_bso2_pol3Wn_pol2')";           ((i++)); item="item$i"
eval "declare -a $item=('pol3_ch3_epec'       'kerEpec_ch3Pol3_pol3Ker')";               ((i++)); item="item$i"
eval "declare -a $item=('pol3_ch3_epic'       'kerEpic_ch3Pol3_pol3Ker')";               ((i++)); item="item$i"
eval "declare -a $item=('sm_pmp_epic'         'kerEpic_sm_pmpSm')";                      ((i++)); item="item$i"
eval "declare -a $item=('ss_2_clg'            'kerdCdlgDynamic_ss2')";                   ((i++)); item="item$i"
eval "declare -a $item=('ss2_seg_epec'        'kerEpecInt_aos2SegPl_ss2')";              ((i++)); item="item$i"
eval "declare -a $item=('tri2_ct_wi_epic'     'kerEpic_tri2CdelNciWiWi')";               ((i++)); item="item$i"
eval "declare -a $item=('tri2_wi_hi_epic'     'kerEpic_tri2PlainNciWiWiHi')";            ((i++)); item="item$i"
eval "declare -a $item=('tri3_del_epic'       'kerEpic_tri3DelComSeq')";                 ((i++)); item="item$i"
eval "declare -a $item=('vis2_rg_epec'        'kerEpec_aos2SegPl_vis2Rg')";              ((i++)); item="item$i"
eval "declare -a $item=('vis2_nr_epec'        'kerEpec_aos2SegPl_vis2Nr')";              ((i++)); item="item$i"

((i--))
arr=()
for j in $(seq 0 $i);
do
  item="item$j"
  eval "arr+=(${item})"
done

for elm in "${arr[@]}"; do
  dir_p=$elm[0]
  dir=${!dir_p}_$mode
  cmd="../run_$dir"
  whl_basename_p=$elm[1]
  whl_basename=${!whl_basename_p}
  whl=$whl_dirname'/'${prefix}_$whl_basename-${suffix}
  echo "======== $dir ========"
  eval "(mkdir -p $dir && cd $dir && $cmd && make $make_parms && pip3 $pip_parms $whl)"
done
