#!/usr/bin/env python3
# Author(s): Utkarsh Khajuria <utkarshkhajuria55@gmail.com>

"""Cross-platform build-variant runner entry point."""

from build_variants.main import main


if __name__ == "__main__":
    raise SystemExit(main())
