from collections.abc import Callable, Sequence
from typing import overload

import CGALPY.CGALPY as CGALPY


class Adaptive_sizing_field:
    def __init__(self, tol: float, edge_len_min_max: tuple[float, float], face_range: Sequence[CGALPY.Sm.Face_index], pmesh: CGALPY.Sm.Surface_mesh_3, np: dict = {}) -> None: ...

    def at(self, arg0: CGALPY.Sm.Vertex_index, arg1: CGALPY.Sm.Surface_mesh_3, /) -> float: ...

    def split_placement(self, arg0: CGALPY.Sm.Halfedge_index, arg1: CGALPY.Sm.Surface_mesh_3, /) -> CGALPY.Ker.Kernel.Point_3: ...

    def register_split_vertex(self, arg0: CGALPY.Sm.Vertex_index, arg1: CGALPY.Sm.Surface_mesh_3, /) -> None: ...

class Autorefinement_visitor:
    def __init__(self) -> None: ...

    def set_number_of_output_triangles(self, arg: Callable[[int], None], /) -> None: ...

    def set_verbatim_triangle_copy(self, arg: Callable[[int, int], None], /) -> None: ...

    def set_new_subtriangle(self, arg: Callable[[int, int], None], /) -> None: ...

class Corefine_visitor:
    def __init__(self) -> None: ...

class Default_orientation_visitor:
    def __init__(self) -> None: ...

class Default_visitor:
    def __init__(self) -> None: ...

class Hole_filling_default_visitor:
    def __init__(self) -> None: ...

class Named_function_parameters:
    def __init__(self) -> None: ...

class Non_manifold_output_visitor:
    def __init__(self, arg0: CGALPY.Sm.Surface_mesh_3, arg1: CGALPY.Sm.Surface_mesh_3, /) -> None: ...

    def extract_intersection(self) -> tuple: ...

class Polyhedral_envelope:
    @overload
    def __init__(self, tmesh: CGALPY.Sm.Surface_mesh_3, epsilon: float, np: dict = {}) -> None: ...

    @overload
    def __init__(self, face_range: Sequence[CGALPY.Sm.Face_index], tmesh: CGALPY.Sm.Surface_mesh_3, epsilon: float, np: dict = {}) -> None: ...

    @overload
    def __init__(self, points: Sequence[CGALPY.Ker.Kernel.Point_3], polygons: Sequence[Sequence[int]], epsilon: float, np: dict = {}) -> None: ...

    def is_empty(self) -> bool: ...

    @overload
    def inside(self, query: CGALPY.Ker.Kernel.Point_3) -> bool: ...

    @overload
    def inside(self, source: CGALPY.Ker.Kernel.Point_3, target: CGALPY.Ker.Kernel.Point_3) -> bool: ...

    @overload
    def inside(self, t0: CGALPY.Ker.Kernel.Point_3, t1: CGALPY.Ker.Kernel.Point_3, t2: CGALPY.Ker.Kernel.Point_3) -> bool: ...

    @overload
    def inside(self, tmesh: CGALPY.Sm.Surface_mesh_3, np: dict = {}) -> bool: ...

class Principal_curvatures_and_directions:
    def __init__(self, arg0: float, arg1: float, arg2: CGALPY.Ker.Kernel.Vector_3, arg3: CGALPY.Ker.Kernel.Vector_3, /) -> None: ...

    @property
    def min_curvature(self) -> float: ...

    @property
    def max_curvature(self) -> float: ...

    @property
    def min_direction(self) -> CGALPY.Ker.Kernel.Vector_3: ...

    @property
    def max_direction(self) -> CGALPY.Ker.Kernel.Vector_3: ...

class Uniform_sizing_field:
    def __init__(self, arg0: float, arg1: CGALPY.Sm.Surface_mesh_3, /) -> None: ...

    def at(self, arg0: CGALPY.Sm.Vertex_index, arg1: CGALPY.Sm.Surface_mesh_3, /) -> float: ...

    def split_placement(self, arg0: CGALPY.Sm.Halfedge_index, arg1: CGALPY.Sm.Surface_mesh_3, /) -> CGALPY.Ker.Kernel.Point_3: ...

    def register_split_vertex(self, arg0: CGALPY.Sm.Vertex_index, arg1: CGALPY.Sm.Surface_mesh_3, /) -> None: ...

def add_bbox(pmesh: CGALPY.Sm.Surface_mesh_3, np: dict = {}) -> None: ...

@overload
def angle_and_area_smoothing(faces: Sequence[CGALPY.Sm.Face_index], tmesh: CGALPY.Sm.Surface_mesh_3, np: dict = {}) -> None: ...

@overload
def angle_and_area_smoothing(pmesh: CGALPY.Sm.Surface_mesh_3, np: dict = {}) -> None: ...

def approximate_Hausdorff_distance(tm1: CGALPY.Sm.Surface_mesh_3, tm2: CGALPY.Sm.Surface_mesh_3, np1: dict = {}, np2: dict = {}) -> float: ...

def approximate_max_distance_to_point_set(tm: CGALPY.Sm.Surface_mesh_3, points: Sequence[CGALPY.Ker.Kernel.Point_3], precision: float, np: dict = {}) -> float: ...

def approximate_symmetric_Hausdorff_distance(tm1: CGALPY.Sm.Surface_mesh_3, tm2: CGALPY.Sm.Surface_mesh_3, np1: dict = {}, np2: dict = {}) -> float: ...

@overload
def area(tmesh: CGALPY.Sm.Surface_mesh_3, np: dict = {}) -> float: ...

@overload
def area(face_range: Sequence[CGALPY.Sm.Face_index], tmesh: CGALPY.Sm.Surface_mesh_3, np: dict = {}) -> float: ...

def autorefine(tm: CGALPY.Sm.Surface_mesh_3, np: dict = {}) -> None: ...

def autorefine_triangle_soup(soup_points: Sequence[CGALPY.Ker.Kernel.Point_3], soup_triangles: Sequence[Sequence[int]], np: dict = {}) -> tuple[list[CGALPY.Ker.Kernel.Point_3], list[list[int]]]: ...

def barycentic_coordinates(p: CGALPY.Ker.Kernel.Point_3, q: CGALPY.Ker.Kernel.Point_3, r: CGALPY.Ker.Kernel.Point_3, query: CGALPY.Ker.Kernel.Point_3) -> list[float]: ...

def bbox(pmesh: CGALPY.Sm.Surface_mesh_3, np: dict = {}) -> CGALPY.Bbox_3: ...

def border_halfedges(face_range: Sequence[CGALPY.Sm.Face_index], pm: CGALPY.Sm.Surface_mesh_3, np: dict = {}) -> list[CGALPY.Sm.Halfedge_index]: ...

def bounded_error_Hausdorff_distance(tm1: CGALPY.Sm.Surface_mesh_3, tm2: CGALPY.Sm.Surface_mesh_3, error_bound: float = 0.0001, np1: dict = {}, np2: dict = {}) -> float: ...

def centroid(tmesh: CGALPY.Sm.Surface_mesh_3, np: dict = {}) -> CGALPY.Ker.Kernel.Point_3: ...

@overload
def clip(tm: CGALPY.Sm.Surface_mesh_3, iso_cuboid: CGALPY.Ker.Kernel.Iso_cuboid_3, np: dict = {}) -> bool: ...

@overload
def clip(tm: CGALPY.Sm.Surface_mesh_3, plane: CGALPY.Ker.Kernel.Plane_3, np: dict = {}) -> bool: ...

@overload
def clip(tm: CGALPY.Sm.Surface_mesh_3, clipper: CGALPY.Sm.Surface_mesh_3, np_tm: dict = {}, np_c: dict = {}) -> bool: ...

def compatible_orientations(pm: CGALPY.Sm.Surface_mesh_3, face_bit_map: CGALPY.Sm.Face_bool_map, np: dict = {}) -> bool: ...

def compute_face_normal(f: CGALPY.Sm.Face_index, pmesh: CGALPY.Sm.Surface_mesh_3, np: dict = {}) -> CGALPY.Ker.Kernel.Vector_3: ...

def compute_face_normals(pmesh: CGALPY.Sm.Surface_mesh_3, face_normals: CGALPY.Sm.Face_vector_3_map, np: dict = {}) -> None: ...

def compute_normals(vnormals: CGALPY.Sm.Surface_mesh_3, fnormals: CGALPY.Sm.Vertex_vector_3_map, pmesh: CGALPY.Sm.Face_vector_3_map, np: dict = {}) -> None: ...

def compute_vertex_normal(v: CGALPY.Sm.Vertex_index, pmesh: CGALPY.Sm.Surface_mesh_3, np: dict = {}) -> CGALPY.Ker.Kernel.Vector_3: ...

def compute_vertex_normals(pmesh: CGALPY.Sm.Surface_mesh_3, vertex_normals: CGALPY.Sm.Vertex_vector_3_map, np: dict = {}) -> None: ...

def connected_components(pm: CGALPY.Sm.Surface_mesh_3, fcm: CGALPY.Sm.Face_size_t_map, np: dict = {}) -> int: ...

def corefine(pm1: CGALPY.Sm.Surface_mesh_3, pm2: CGALPY.Sm.Surface_mesh_3, np1: dict = {}, np2: dict = {}) -> None: ...

def corefine_and_compute_boolean_operations(pm1: CGALPY.Sm.Surface_mesh_3, pm2: CGALPY.Sm.Surface_mesh_3, np1: dict = {}, np2: dict = {}, np_out: tuple = ()) -> tuple: ...

def corefine_and_compute_difference(tm1: CGALPY.Sm.Surface_mesh_3, tm2: CGALPY.Sm.Surface_mesh_3, np1: dict = {}, np2: dict = {}, np_out: dict = {}) -> CGALPY.Sm.Surface_mesh_3: ...

def corefine_and_compute_intersection(pm1: CGALPY.Sm.Surface_mesh_3, pm2: CGALPY.Sm.Surface_mesh_3, np1: dict = {}, np2: dict = {}, np_out: dict = {}) -> CGALPY.Sm.Surface_mesh_3: ...

def corefine_and_compute_union(pm1: CGALPY.Sm.Surface_mesh_3, pm2: CGALPY.Sm.Surface_mesh_3, np1: dict = {}, np2: dict = {}, np_out: dict = {}) -> CGALPY.Sm.Surface_mesh_3: ...

@overload
def degenerate_edges(edges: Sequence[CGALPY.Sm.Edge_index], tm: CGALPY.Sm.Surface_mesh_3, np: dict = {}) -> list[CGALPY.Sm.Edge_index]: ...

@overload
def degenerate_edges(tm: CGALPY.Sm.Surface_mesh_3, np: dict = {}) -> list[CGALPY.Sm.Edge_index]: ...

@overload
def degenerate_faces(faces: Sequence[CGALPY.Sm.Face_index], tm: CGALPY.Sm.Surface_mesh_3, np: dict = {}) -> list[CGALPY.Sm.Face_index]: ...

@overload
def degenerate_faces(tm: CGALPY.Sm.Surface_mesh_3, np: dict = {}) -> list[CGALPY.Sm.Face_index]: ...

def detect_corners_of_regions(pmesh: CGALPY.Sm.Surface_mesh_3, region_map: CGALPY.Sm.Face_size_t_map, nb_regions: int, corner_id_map: CGALPY.Sm.Vertex_size_t_map, np: dict = {}) -> int: ...

def detect_sharp_edges(pm: CGALPY.Sm.Surface_mesh_3, angle_in_deg: float, edge_is_feature_map: CGALPY.Sm.Edge_bool_map, np: dict = {}) -> None: ...

def detect_vertex_incident_patches(pmesh: CGALPY.Sm.Surface_mesh_3, patch_id_map: CGALPY.Sm.Face_int_map, vertex_incident_patches_map: CGALPY.Sm.Edge_bool_map, np: dict = {}) -> CGALPY.Sm.Vertex_set_map: ...

@overload
def do_intersect(arg0: Sequence[CGALPY.Ker.Kernel.Point_3], arg1: Sequence[CGALPY.Ker.Kernel.Point_3], /) -> bool: ...

@overload
def do_intersect(pm1: CGALPY.Sm.Surface_mesh_3, pm2: CGALPY.Sm.Surface_mesh_3, np1: dict = {}, np2: dict = {}) -> bool: ...

@overload
def do_intersect(pm: CGALPY.Sm.Surface_mesh_3, lst: Sequence[CGALPY.Ker.Kernel.Point_3], np: dict = {}) -> bool: ...

def do_intersect_polyline_range(pm: CGALPY.Sm.Surface_mesh_3, lst: Sequence[Sequence[CGALPY.Ker.Kernel.Point_3]], np: dict = {}) -> bool: ...

def do_intersect_polyline_ranges(arg0: Sequence[Sequence[CGALPY.Ker.Kernel.Point_3]], arg1: Sequence[Sequence[CGALPY.Ker.Kernel.Point_3]], /) -> bool: ...

def does_bound_a_volume(tm: CGALPY.Sm.Surface_mesh_3, np: dict = {}) -> bool: ...

@overload
def does_self_intersect(face_range: Sequence[CGALPY.Sm.Face_index], tmesh: CGALPY.Sm.Surface_mesh_3, np: dict = {}) -> bool: ...

@overload
def does_self_intersect(pm: CGALPY.Sm.Surface_mesh_3, np: dict = {}) -> bool: ...

def does_triangle_soup_self_intersect(points: Sequence[CGALPY.Ker.Kernel.Point_3], triangles: Sequence[Sequence[int]], np: dict = {}) -> bool: ...

def duplicate_non_manifold_edges_in_polygon_soup(points: Sequence[CGALPY.Ker.Kernel.Point_3], polygons: Sequence[Sequence[int]]) -> tuple[list[CGALPY.Ker.Kernel.Point_3], list[list[int]], bool]: ...

def duplicate_non_manifold_vertices(pmesh: CGALPY.Sm.Surface_mesh_3, np: dict = {}) -> tuple[int, list[list[CGALPY.Sm.Vertex_index]]]: ...

def edge_bbox(ed: CGALPY.Sm.Edge_index, pmesh: CGALPY.Sm.Surface_mesh_3, np: dict = {}) -> CGALPY.Bbox_3: ...

def edge_length(h: CGALPY.Sm.Halfedge_index, tmesh: CGALPY.Sm.Surface_mesh_3, np: dict = {}) -> float: ...

def extract_boundary_cycles(pmesh: CGALPY.Sm.Surface_mesh_3) -> list[CGALPY.Sm.Halfedge_index]: ...

def extrude_mesh(imesh: CGALPY.Sm.Surface_mesh_3, omesh: CGALPY.Sm.Surface_mesh_3, v: CGALPY.Ker.Kernel.Vector_3, np_in: dict = {}, np_out: dict = {}) -> None: ...

def face_area(f: CGALPY.Sm.Face_index, tmesh: CGALPY.Sm.Surface_mesh_3, np: dict = {}) -> float: ...

def face_aspect_ratio(f: CGALPY.Sm.Face_index, tmesh: CGALPY.Sm.Surface_mesh_3, np: dict = {}) -> float: ...

def face_bbox(f: CGALPY.Sm.Face_index, pmesh: CGALPY.Sm.Surface_mesh_3, np: dict = {}) -> CGALPY.Bbox_3: ...

def face_border_length(f: CGALPY.Sm.Halfedge_index, tmesh: CGALPY.Sm.Surface_mesh_3, np: dict = {}) -> float: ...

def get_descriptor_from_location(loc: tuple[CGALPY.Sm.Face_index, Sequence[float]], tm: CGALPY.Sm.Surface_mesh_3) -> object: ...

@overload
def interpolated_corrected_curvatures(pm: CGALPY.Sm.Surface_mesh_3, np: dict = {}) -> None: ...

@overload
def interpolated_corrected_curvatures(v: CGALPY.Sm.Vertex_index, pm: CGALPY.Sm.Surface_mesh_3, np: dict = {}) -> tuple[float, float, Principal_curvatures_and_directions]: ...

def intersecting_meshes(range: Sequence[CGALPY.Sm.Surface_mesh_3], np: dict = {}, nps: Sequence[dict] = []) -> list[tuple[int, int]]: ...

def is_Hausdorff_distance_larger(tm1: CGALPY.Sm.Surface_mesh_3, tm2: CGALPY.Sm.Surface_mesh_3, distance_bound: float, error_bound: float, np1: dict = {}, np2: dict = {}) -> bool: ...

def is_cap_triangle_face(f: CGALPY.Sm.Face_index, tm: CGALPY.Sm.Surface_mesh_3, threshold: float, np: dict = {}) -> CGALPY.Sm.Halfedge_index: ...

def is_degenerate_edge(e: CGALPY.Sm.Edge_index, pm: CGALPY.Sm.Surface_mesh_3, np: dict = {}) -> bool: ...

def is_degenerate_triangle_face(f: CGALPY.Sm.Face_index, tm: CGALPY.Sm.Surface_mesh_3, np: dict = {}) -> bool: ...

def is_in_face(bar: Sequence[float], tm: CGALPY.Sm.Surface_mesh_3) -> bool: ...

def is_needle_triangle_face(f: CGALPY.Sm.Face_index, tm: CGALPY.Sm.Surface_mesh_3, threshold: float, np: dict = {}) -> CGALPY.Sm.Halfedge_index: ...

def is_non_manifold_vertex(v: CGALPY.Sm.Vertex_index, pm: CGALPY.Sm.Surface_mesh_3) -> bool: ...

def is_on_face_border(loc: tuple[CGALPY.Sm.Face_index, Sequence[float]], tm: CGALPY.Sm.Surface_mesh_3) -> bool: ...

def is_on_halfedge(loc: tuple[CGALPY.Sm.Face_index, Sequence[float]], hd: CGALPY.Sm.Halfedge_index, tm: CGALPY.Sm.Surface_mesh_3) -> bool: ...

def is_on_mesh_border(loc: tuple[CGALPY.Sm.Face_index, Sequence[float]], tm: CGALPY.Sm.Surface_mesh_3) -> bool: ...

def is_on_vertex(loc: tuple[CGALPY.Sm.Face_index, Sequence[float]], vd: CGALPY.Sm.Vertex_index, tm: CGALPY.Sm.Surface_mesh_3) -> bool: ...

def is_outward_oriented(tm: CGALPY.Sm.Surface_mesh_3, np: dict = {}) -> bool: ...

def is_polygon_soup_a_polygon_mesh(polygons: Sequence[Sequence[int]]) -> bool: ...

@overload
def isotropic_remeshing(faces: Sequence[CGALPY.Sm.Face_index], sizing: Adaptive_sizing_field, pmesh: CGALPY.Sm.Surface_mesh_3, np: dict = {}) -> None: ...

@overload
def isotropic_remeshing(faces: Sequence[CGALPY.Sm.Face_index], target_edge_length: Uniform_sizing_field, pmesh: CGALPY.Sm.Surface_mesh_3, np: dict = {}) -> None: ...

@overload
def keep_connected_components(pm: CGALPY.Sm.Surface_mesh_3, components_to_keep: Sequence[int], fcm: CGALPY.Sm.Face_uint32_t_map, np: dict = {}) -> None: ...

@overload
def keep_connected_components(pm: CGALPY.Sm.Surface_mesh_3, components_to_keep: Sequence[CGALPY.Sm.Face_index], np: dict = {}) -> None: ...

@overload
def keep_large_connected_components(pm: CGALPY.Sm.Surface_mesh_3, min_size: int, np: dict = {}) -> int: ...

@overload
def keep_large_connected_components(pm: CGALPY.Sm.Surface_mesh_3, min_size: float, np: dict = {}) -> int: ...

def keep_largest_connected_components(pm: CGALPY.Sm.Surface_mesh_3, nb_components_to_keep: int, np: dict = {}) -> int: ...

def longest_border(tmesh: CGALPY.Sm.Surface_mesh_3, np: dict = {}) -> tuple[CGALPY.Sm.Halfedge_index, float]: ...

def match_faces(m1: CGALPY.Sm.Surface_mesh_3, m2: CGALPY.Sm.Surface_mesh_3, np1: dict = {}, np2: dict = {}) -> tuple[list[tuple[CGALPY.Sm.Face_index, CGALPY.Sm.Face_index]], list[CGALPY.Sm.Face_index], list[CGALPY.Sm.Face_index]]: ...

def max_distance_to_triangle_mesh(tm: Sequence[CGALPY.Ker.Kernel.Point_3], point: CGALPY.Sm.Surface_mesh_3, np: dict = {}) -> float: ...

def merge_duplicate_points_in_polygon_soup(points: Sequence[CGALPY.Ker.Kernel.Point_3], polygons: Sequence[Sequence[int]], np: dict = {}) -> int: ...

def merge_duplicate_polygons_in_polygon_soup(points: Sequence[CGALPY.Ker.Kernel.Point_3], polygons: Sequence[Sequence[int]], np: dict = {}) -> int: ...

def merge_duplicated_vertices_in_boundary_cycle(h: CGALPY.Sm.Halfedge_index, pm: CGALPY.Sm.Surface_mesh_3, np: dict = {}) -> None: ...

def merge_duplicated_vertices_in_boundary_cycles(pm: CGALPY.Sm.Surface_mesh_3, np: dict = {}) -> None: ...

def merge_reversible_connected_components(pm: CGALPY.Sm.Surface_mesh_3, np: dict = {}) -> None: ...

def non_manifold_vertices(pm: CGALPY.Sm.Surface_mesh_3) -> list[CGALPY.Sm.Halfedge_index]: ...

def orient(tm: CGALPY.Sm.Surface_mesh_3, np: dict = {}) -> None: ...

def orient_polygon_soup(points: Sequence[CGALPY.Ker.Kernel.Point_3], polygons: Sequence[Sequence[int]], np: dict = {}) -> tuple[list[CGALPY.Ker.Kernel.Point_3], list[list[int]]]: ...

def orient_to_bound_a_volume(tm: CGALPY.Sm.Surface_mesh_3, np: dict = {}) -> None: ...

def orient_triangle_soup_with_reference_triangle_mesh(tm_ref: CGALPY.Sm.Surface_mesh_3, points: Sequence[CGALPY.Ker.Kernel.Point_3], triangles: Sequence[Sequence[int]], np1: dict = {}, np2: dict = {}) -> tuple[list[CGALPY.Ker.Kernel.Point_3], list[list[int]]]: ...

def polygon_mesh_to_polygon_soup(pm: CGALPY.Sm.Surface_mesh_3, np: dict = {}) -> tuple[list[CGALPY.Ker.Kernel.Point_3], list[list[int]]]: ...

def polygon_soup_to_polygon_mesh(points: Sequence[CGALPY.Ker.Kernel.Point_3], polygons: Sequence[Sequence[int]], np_ps: dict = {}, np_pm: dict = {}) -> tuple[CGALPY.Sm.Surface_mesh_3, list[tuple[int, CGALPY.Sm.Vertex_index]], list[tuple[int, CGALPY.Sm.Face_index]]]: ...

@overload
def random_perturbation(tmesh: CGALPY.Sm.Surface_mesh_3, perturbation_max_size: float, np: dict = {}) -> None: ...

@overload
def random_perturbation(vertices: Sequence[CGALPY.Sm.Vertex_index], tmesh: CGALPY.Sm.Surface_mesh_3, perturbation_max_size: float, np: dict = {}) -> None: ...

def refine(tmesh: CGALPY.Sm.Surface_mesh_3, faces: Sequence[CGALPY.Sm.Face_index], np: dict = {}) -> tuple[list[CGALPY.Sm.Face_index], list[CGALPY.Sm.Vertex_index]]: ...

def refine_mesh_at_isolevel(pm: CGALPY.Sm.Surface_mesh_3, value_map: CGALPY.Sm.Vertex_FT_map, isovalue: float, np: dict = {}) -> None: ...

def region_growing_of_planes_on_faces(pmesh: CGALPY.Sm.Surface_mesh_3, region_map: CGALPY.Sm.Face_size_t_map, np: dict = {}) -> int: ...

def remesh_almost_planar_patches(tm_in: CGALPY.Sm.Surface_mesh_3, nb_patches: int, nb_corners: int, face_patch_map: CGALPY.Sm.Face_size_t_map, vertex_corner_map: CGALPY.Sm.Vertex_size_t_map, ecm: CGALPY.Sm.Edge_bool_map, np_in: dict = {}, np_out: dict = {}) -> CGALPY.Sm.Surface_mesh_3: ...

def remesh_planar_patches(pm: CGALPY.Sm.Surface_mesh_3, np_in: dict = {}, np_out: dict = {}) -> CGALPY.Sm.Surface_mesh_3: ...

@overload
def remove_almost_degenerate_faces(face_range: Sequence[CGALPY.Sm.Face_index], tmesh: CGALPY.Sm.Surface_mesh_3, np: dict = {}) -> bool: ...

@overload
def remove_almost_degenerate_faces(tmesh: CGALPY.Sm.Surface_mesh_3, np: dict = {}) -> bool: ...

@overload
def remove_connected_components(pm: CGALPY.Sm.Surface_mesh_3, components_to_remove: Sequence[int], fccmap: CGALPY.Sm.Face_uint32_t_map, np: dict = {}) -> None: ...

@overload
def remove_connected_components(pm: CGALPY.Sm.Surface_mesh_3, components_to_remove: Sequence[CGALPY.Sm.Face_index], np: dict = {}) -> None: ...

def remove_connected_components_of_negligible_size(tmesh: CGALPY.Sm.Surface_mesh_3, np: dict = {}) -> int: ...

def remove_isolated_points_in_polygon_soup(points: Sequence[CGALPY.Ker.Kernel.Point_3], polygons: Sequence[Sequence[int]]) -> int: ...

def remove_isolated_vertices(pmesh: CGALPY.Sm.Surface_mesh_3) -> int: ...

def repair_polygon_soup(points: Sequence[CGALPY.Ker.Kernel.Point_3], polygons: Sequence[Sequence[int]], np: dict = {}) -> tuple[list[CGALPY.Ker.Kernel.Point_3], list[list[int]]]: ...

@overload
def reverse_face_orientations(face_range: Sequence[CGALPY.Sm.Face_index], pmesh: CGALPY.Sm.Surface_mesh_3) -> None: ...

@overload
def reverse_face_orientations(pmesh: CGALPY.Sm.Surface_mesh_3) -> None: ...

def sample_triangle_mesh(tm: CGALPY.Sm.Surface_mesh_3, np: dict = {}) -> list[CGALPY.Ker.Kernel.Point_3]: ...

def sample_triangle_soup(points: Sequence[CGALPY.Ker.Kernel.Point_3], triangles: Sequence[Sequence[int]], np: dict = {}) -> list[CGALPY.Ker.Kernel.Point_3]: ...

@overload
def self_intersections(pm: CGALPY.Sm.Surface_mesh_3, np: dict = {}) -> list[tuple[CGALPY.Sm.Face_index, CGALPY.Sm.Face_index]]: ...

@overload
def self_intersections(face_range: Sequence[CGALPY.Sm.Face_index], pm: CGALPY.Sm.Surface_mesh_3, np: dict = {}) -> list[tuple[CGALPY.Sm.Face_index, CGALPY.Sm.Face_index]]: ...

def set_add_retriangulation_edge(arg0: Corefine_visitor, arg1: Callable[[CGALPY.Sm.Halfedge_index, CGALPY.Sm.Surface_mesh_3], None], /) -> None: ...

def set_after_edge_copy(arg0: Corefine_visitor, arg1: Callable[[CGALPY.Sm.Halfedge_index, CGALPY.Sm.Surface_mesh_3, CGALPY.Sm.Halfedge_index, CGALPY.Sm.Surface_mesh_3], None], /) -> None: ...

def set_after_edge_duplicated(arg0: Corefine_visitor, arg1: Callable[[CGALPY.Sm.Halfedge_index, CGALPY.Sm.Halfedge_index, CGALPY.Sm.Surface_mesh_3], None], /) -> None: ...

def set_after_edge_split(arg0: Corefine_visitor, arg1: Callable[[], None], /) -> None: ...

def set_after_face_copy(arg0: Corefine_visitor, arg1: Callable[[CGALPY.Sm.Face_index, CGALPY.Sm.Surface_mesh_3, CGALPY.Sm.Face_index, CGALPY.Sm.Surface_mesh_3], None], /) -> None: ...

def set_after_subface_created(arg0: Corefine_visitor, arg1: Callable[[CGALPY.Sm.Face_index, CGALPY.Sm.Surface_mesh_3], None], /) -> None: ...

def set_after_subface_creations(arg0: Corefine_visitor, arg1: Callable[[CGALPY.Sm.Surface_mesh_3], None], /) -> None: ...

def set_after_vertex_copy(arg0: Corefine_visitor, arg1: Callable[[CGALPY.Sm.Vertex_index, CGALPY.Sm.Surface_mesh_3, CGALPY.Sm.Vertex_index, CGALPY.Sm.Surface_mesh_3], None], /) -> None: ...

def set_before_edge_copy(arg0: Corefine_visitor, arg1: Callable[[CGALPY.Sm.Halfedge_index, CGALPY.Sm.Surface_mesh_3, CGALPY.Sm.Surface_mesh_3], None], /) -> None: ...

def set_before_edge_duplicated(arg0: Corefine_visitor, arg1: Callable[[CGALPY.Sm.Halfedge_index, CGALPY.Sm.Surface_mesh_3], None], /) -> None: ...

def set_before_edge_split(arg0: Corefine_visitor, arg1: Callable[[CGALPY.Sm.Halfedge_index, CGALPY.Sm.Surface_mesh_3], None], /) -> None: ...

def set_before_face_copy(arg0: Corefine_visitor, arg1: Callable[[CGALPY.Sm.Face_index, CGALPY.Sm.Surface_mesh_3, CGALPY.Sm.Surface_mesh_3], None], /) -> None: ...

def set_before_subface_created(arg0: Corefine_visitor, arg1: Callable[[CGALPY.Sm.Surface_mesh_3], None], /) -> None: ...

def set_before_subface_creations(arg0: Corefine_visitor, arg1: Callable[[CGALPY.Sm.Face_index, CGALPY.Sm.Surface_mesh_3], None], /) -> None: ...

def set_before_vertex_copy(arg0: Corefine_visitor, arg1: Callable[[CGALPY.Sm.Vertex_index, CGALPY.Sm.Surface_mesh_3, CGALPY.Sm.Surface_mesh_3], None], /) -> None: ...

def set_classify_intersection_free_patches(arg0: Corefine_visitor, arg1: Callable[[CGALPY.Sm.Surface_mesh_3], None], /) -> None: ...

def set_classify_patches(arg0: Corefine_visitor, arg1: Callable[[], None], /) -> None: ...

def set_cubic_step(arg0: Hole_filling_default_visitor, arg1: Callable[[], None], /) -> None: ...

def set_detect_patches(arg0: Corefine_visitor, arg1: Callable[[], None], /) -> None: ...

def set_duplicated_vertex(arg0: Default_orientation_visitor, arg1: Callable[[int, int], None], /) -> None: ...

def set_edge_face_intersections_step(arg0: Corefine_visitor, arg1: Callable[[], None], /) -> None: ...

def set_edge_split(arg0: Corefine_visitor, arg1: Callable[[CGALPY.Sm.Halfedge_index, CGALPY.Sm.Surface_mesh_3], None], /) -> None: ...

def set_end_building_output(arg0: Corefine_visitor, arg1: Callable[[], None], /) -> None: ...

def set_end_cubic_phase(arg0: Hole_filling_default_visitor, arg1: Callable[[], None], /) -> None: ...

def set_end_fair_phase(arg0: Hole_filling_default_visitor, arg1: Callable[[], None], /) -> None: ...

def set_end_filtering_intersections(arg0: Corefine_visitor, arg1: Callable[[], None], /) -> None: ...

def set_end_handling_edge_face_intersections(arg0: Corefine_visitor, arg1: Callable[[], None], /) -> None: ...

def set_end_handling_intersection_of_coplanar_faces(arg0: Corefine_visitor, arg1: Callable[[], None], /) -> None: ...

def set_end_planar_phase(arg0: Hole_filling_default_visitor, arg1: Callable[[bool], None], /) -> None: ...

def set_end_quadratic_phase(arg0: Hole_filling_default_visitor, arg1: Callable[[bool], None], /) -> None: ...

def set_end_refine_phase(arg0: Hole_filling_default_visitor, arg1: Callable[[], None], /) -> None: ...

def set_end_triangulating_faces(arg0: Corefine_visitor, arg1: Callable[[], None], /) -> None: ...

def set_filter_coplanar_edges(arg0: Corefine_visitor, arg1: Callable[[], None], /) -> None: ...

def set_in_place_operation(arg0: Corefine_visitor, arg1: Callable[[int], None], /) -> None: ...

def set_in_place_operations(arg0: Corefine_visitor, arg1: Callable[[int, int], None], /) -> None: ...

def set_intersection_edge_copy(arg0: Corefine_visitor, arg1: Callable[[CGALPY.Sm.Halfedge_index, CGALPY.Sm.Surface_mesh_3, CGALPY.Sm.Halfedge_index, CGALPY.Sm.Surface_mesh_3, CGALPY.Sm.Halfedge_index, CGALPY.Sm.Surface_mesh_3], None], /) -> None: ...

def set_intersection_of_coplanar_faces_step(arg0: Corefine_visitor, arg1: Callable[[], None], /) -> None: ...

def set_intersection_point_detected(arg0: Corefine_visitor, arg1: Callable[[int, int, CGALPY.Sm.Halfedge_index, CGALPY.Sm.Halfedge_index, CGALPY.Sm.Surface_mesh_3, CGALPY.Sm.Surface_mesh_3, bool, bool], None], /) -> None: ...

def set_link_connected_polygons(arg0: Default_orientation_visitor, arg1: Callable[[int, Sequence[int]], None], /) -> None: ...

def set_new_vertex_added(arg0: Corefine_visitor, arg1: Callable[[int, CGALPY.Sm.Vertex_index, CGALPY.Sm.Surface_mesh_3], None], /) -> None: ...

def set_non_manifold_edge(arg0: Default_orientation_visitor, arg1: Callable[[int, int, int], None], /) -> None: ...

def set_non_manifold_vertex(arg0: Default_orientation_visitor, arg1: Callable[[int, int], None], /) -> None: ...

def set_out_of_place_operation(arg0: Corefine_visitor, arg1: Callable[[int], None], /) -> None: ...

def set_polygon_orientation_reversed(arg0: Default_orientation_visitor, arg1: Callable[[int], None], /) -> None: ...

def set_progress_filtering_intersections(arg0: Corefine_visitor, arg1: Callable[[float], None], /) -> None: ...

def set_quadratic_step(arg0: Hole_filling_default_visitor, arg1: Callable[[], None], /) -> None: ...

def set_start_building_output(arg0: Corefine_visitor, arg1: Callable[[], None], /) -> None: ...

def set_start_cubic_phase(arg0: Hole_filling_default_visitor, arg1: Callable[[int], None], /) -> None: ...

def set_start_fair_phase(arg0: Hole_filling_default_visitor, arg1: Callable[[], None], /) -> None: ...

def set_start_filtering_intersections(arg0: Corefine_visitor, arg1: Callable[[], None], /) -> None: ...

def set_start_handling_edge_face_intersections(arg0: Corefine_visitor, arg1: Callable[[int], None], /) -> None: ...

def set_start_handling_intersection_of_coplanar_faces(arg0: Corefine_visitor, arg1: Callable[[int], None], /) -> None: ...

def set_start_planar_phase(arg0: Hole_filling_default_visitor, arg1: Callable[[], None], /) -> None: ...

def set_start_quadratic_phase(arg0: Hole_filling_default_visitor, arg1: Callable[[int], None], /) -> None: ...

def set_start_refine_phase(arg0: Hole_filling_default_visitor, arg1: Callable[[], None], /) -> None: ...

def set_start_triangulating_faces(arg0: Corefine_visitor, arg1: Callable[[int], None], /) -> None: ...

def set_triangulating_faces_step(arg0: Corefine_visitor, arg1: Callable[[], None], /) -> None: ...

def set_vertex_id_in_polygon_replaced(arg0: Default_orientation_visitor, arg1: Callable[[int, int, int], None], /) -> None: ...

def sharp_edges_segmentation(pmesh: CGALPY.Sm.Surface_mesh_3, angle_in_deg: float, edge_is_feature_map: CGALPY.Sm.Edge_bool_map, patch_id_map: CGALPY.Sm.Face_int_map, np: dict = {}) -> int: ...

def smooth_shape(pm: CGALPY.Sm.Surface_mesh_3, time: float, np: dict = {}) -> None: ...

@overload
def split(tm: CGALPY.Sm.Surface_mesh_3, iso_cuboid: CGALPY.Ker.Kernel.Iso_cuboid_3, np: dict = {}) -> None: ...

@overload
def split(tm: CGALPY.Sm.Surface_mesh_3, plane: CGALPY.Ker.Kernel.Plane_3, np: dict = {}) -> None: ...

@overload
def split(tm: CGALPY.Sm.Surface_mesh_3, splitter: CGALPY.Sm.Surface_mesh_3, np_tm: dict = {}, np_s: dict = {}) -> None: ...

def split_connected_components(pmesh: CGALPY.Sm.Surface_mesh_3, cc_meshes: Sequence[CGALPY.Sm.Surface_mesh_3], np: dict = {}) -> list[CGALPY.Sm.Surface_mesh_3]: ...

def split_long_edges(edge_range: Sequence[CGALPY.Sm.Edge_index], max_length: float, pmesh: CGALPY.Sm.Surface_mesh_3, np: dict = {}) -> list[CGALPY.Sm.Edge_index]: ...

def squared_edge_length(h: CGALPY.Sm.Edge_index, tmesh: CGALPY.Sm.Surface_mesh_3, np: dict = {}) -> float: ...

def squared_face_area(f: CGALPY.Sm.Face_index, tmesh: CGALPY.Sm.Surface_mesh_3, np: dict = {}) -> float: ...

@overload
def stitch_borders(boundary_cycle_representatives: Sequence[CGALPY.Sm.Halfedge_index], pmesh: CGALPY.Sm.Surface_mesh_3, np: dict = {}) -> int: ...

@overload
def stitch_borders(pmesh: CGALPY.Sm.Surface_mesh_3, hedge_pairs_to_stitch: Sequence[tuple[CGALPY.Sm.Halfedge_index, CGALPY.Sm.Halfedge_index]], np: dict = {}) -> int: ...

@overload
def stitch_borders(pmesh: CGALPY.Sm.Surface_mesh_3, np: dict = {}) -> int: ...

def stitch_boundary_cycle(h: CGALPY.Sm.Halfedge_index, pmesh: CGALPY.Sm.Surface_mesh_3, np: dict = {}) -> int: ...

def stitch_boundary_cycles(boundary_cycle_representatives: Sequence[CGALPY.Sm.Halfedge_index], pmesh: CGALPY.Sm.Surface_mesh_3, np: dict = {}) -> int: ...

def surface_intersection(tm1: CGALPY.Sm.Surface_mesh_3, tm2: CGALPY.Sm.Surface_mesh_3, np1: dict = {}, np2: dict = {}) -> list[list[CGALPY.Ker.Kernel.Point_3]]: ...

def triangle(f: CGALPY.Sm.Face_index, tmesh: CGALPY.Sm.Surface_mesh_3, np: dict = {}) -> CGALPY.Ker.Kernel.Triangle_3: ...

def triangle_soup_self_intersections(points: Sequence[CGALPY.Ker.Kernel.Point_3], triangles: Sequence[Sequence[int]], np: dict = {}) -> list[tuple[int, int]]: ...

def triangulate_and_refine_hole(pm: CGALPY.Sm.Surface_mesh_3, hole_boundary: CGALPY.Sm.Halfedge_index, np: dict = {}) -> list[CGALPY.Sm.Face_index]: ...

@overload
def triangulate_faces(pm: CGALPY.Sm.Surface_mesh_3, np: dict = {}) -> bool: ...

@overload
def triangulate_faces(face_range: Sequence[CGALPY.Sm.Face_index], pm: CGALPY.Sm.Surface_mesh_3, np: dict = {}) -> bool: ...

def triangulate_hole(pmesh: CGALPY.Sm.Surface_mesh_3, border_halfedge: CGALPY.Sm.Halfedge_index, np: dict = {}) -> None: ...

@overload
def triangulate_hole_polyline(points: Sequence[CGALPY.Ker.Kernel.Point_3], np: dict = {}) -> list[int]: ...

@overload
def triangulate_hole_polyline(points: Sequence[CGALPY.Ker.Kernel.Point_3], third_points: Sequence[CGALPY.Ker.Kernel.Point_3], np: dict = {}) -> list[int]: ...

def triangulate_polygons(points: Sequence[CGALPY.Ker.Kernel.Point_3], polygons: Sequence[Sequence[int]], np: dict = {}) -> tuple[list[CGALPY.Ker.Kernel.Point_3], list[list[int]]]: ...

def triangulate_refine_and_fair_hole(pmesh: CGALPY.Sm.Surface_mesh_3, border_halfedge: CGALPY.Sm.Halfedge_index, np: dict = {}) -> tuple: ...

def vertex_bbox(vd: CGALPY.Sm.Vertex_index, pmesh: CGALPY.Sm.Surface_mesh_3, np: dict = {}) -> CGALPY.Bbox_3: ...

def volume(tmesh: CGALPY.Sm.Surface_mesh_3, np: dict = {}) -> float: ...

def volume_connected_components(tm: CGALPY.Sm.Surface_mesh_3, volume_id_map: CGALPY.Sm.Face_uint32_t_map, np: dict = {}) -> tuple[int, list[int], list[int], list[bool], list[list[int]], list[tuple[int, int]]]: ...
