// AUTO-GENERATED by cpp_docstrings_from_json.py — DO NOT EDIT
// Package: Visibility_2
#ifndef CGAL_PYTHON_DOCSTRINGS_VISIBILITY_2_H
#define CGAL_PYTHON_DOCSTRINGS_VISIBILITY_2_H

namespace cgalpy {
namespace docstrings {
namespace Visibility_2 {

// CGAL::Rotational_sweep_visibility_2
constexpr const char* CGAL_Rotational_sweep_visibility_2__class__ = "This class is a model of the concept Visibility_2 can answer visibility queries within a polygon that may have holes.";

constexpr const char* CGAL_Rotational_sweep_visibility_2_Arrangement_2 = "The type of the input arrangement.

Returns: Arrangement_2";
constexpr const char* CGAL_Rotational_sweep_visibility_2_Regularization_category = "identifies whether the regularized visibility area is computed (either #Tag_true or #Tag_false ).

Returns: RegularizationCategory";
constexpr const char* CGAL_Rotational_sweep_visibility_2_Supports_general_polygon_category = "See Visibility_2::Supports_general_polygon_category .

Returns: Tag_true";
constexpr const char* CGAL_Rotational_sweep_visibility_2_Supports_simple_polygon_category = "See Visibility_2::Supports_simple_polygon_category .

Returns: Tag_true";
constexpr const char* CGAL_Rotational_sweep_visibility_2_attach = "Attaches the given arrangement to the visibility object.

This operation takes $O(1)$ as the class does no preprocessing. In case the
object is already attached to another arrangement, the visibility object gets
detached before being attached to arr .

Parameters
----------
arr : const Arrangement_2 &";

// CGAL::Simple_polygon_visibility_2
constexpr const char* CGAL_Simple_polygon_visibility_2__class__ = "This class is a model of the concept Visibility_2 can answer visibility queries within a simple polygon with no holes.";

constexpr const char* CGAL_Simple_polygon_visibility_2_Arrangement_2 = "The arrangement type is used for input.

Returns: Arrangement_2";
constexpr const char* CGAL_Simple_polygon_visibility_2_Regularization_category = "identifies whether the regularized visibility area is computed (either #Tag_true or #Tag_false ).

Returns: RegularizationCategory";
constexpr const char* CGAL_Simple_polygon_visibility_2_Supports_general_polygon_category = "See Visibility_2::Supports_general_polygon_category .

Returns: Tag_false";
constexpr const char* CGAL_Simple_polygon_visibility_2_Supports_simple_polygon_category = "See Visibility_2::Supports_simple_polygon_category .

Returns: Tag_true";
constexpr const char* CGAL_Simple_polygon_visibility_2_attach = "Attaches the given arrangement to the visibility object.

This operation takes $O(1)$ as the class does no preprocessing. In case the
object is already attached to another arrangement, the visibility object gets
detached before being attached to arr .

Parameters
----------
arr : const Arrangement_2 &";

// CGAL::Triangular_expansion_visibility_2
constexpr const char* CGAL_Triangular_expansion_visibility_2__class__ = "This class is a model of the concept Visibility_2 can answer visibility queries within a polygon that may have holes.";

constexpr const char* CGAL_Triangular_expansion_visibility_2_Arrangement_2 = "The type of the input arrangement.

Returns: Arrangement_2_";
constexpr const char* CGAL_Triangular_expansion_visibility_2_Regularization_category = "identifies whether the regularized visibility area is computed (either #Tag_true or #Tag_false ).

Returns: RegularizationCategory";
constexpr const char* CGAL_Triangular_expansion_visibility_2_Supports_general_polygon_category = "See Visibility_2::Supports_general_polygon_category .

Returns: Tag_true";
constexpr const char* CGAL_Triangular_expansion_visibility_2_Supports_simple_polygon_category = "See Visibility_2::Supports_simple_polygon_category .

Returns: Tag_true";
constexpr const char* CGAL_Triangular_expansion_visibility_2_attach = "Attaches the given arrangement to the visibility object and computes the restricted triangulation.

This takes $O(n)$ $ time, where $ n $ is the number of vertices. From this
moment on the class observes changes in the arrangement. If the arrangement
changes a new restricted triangulation is computed. Re-attaching forces
re-computation. In case the object is already attached to another arrangement,
the visibility object gets detached before being attached to arr .

Parameters
----------
arr : const Arrangement_2 &";

// Visibility_2
constexpr const char* Visibility_2__class__ = "A model of the Visibility_2 concept can be attached to an Arrangement_2 instance to answer visibility queries within the faces of this arrangement.";

constexpr const char* Visibility_2_Arrangement_2 = "The arrangement type of the input.

Returns: unspecified_type";
constexpr const char* Visibility_2_Point_2 = "The 2D point type used for the queries.

Returns: Arrangement_2::Point_2";
constexpr const char* Visibility_2_Face_const_handle = "The face handle type of the input arrangement.

Returns: Arrangement_2::Face_const_handle";
constexpr const char* Visibility_2_Halfedge_const_handle = "The halfedge handle type of the input arrangement.

Returns: Arrangement_2::Halfedge_const_handle";
constexpr const char* Visibility_2_Regularization_category = "identifies whether the regularized visibility area is computed (either #Tag_true or #Tag_false ).

Returns: unspecified_type";
constexpr const char* Visibility_2_Supports_general_polygon_category = "identifies whether general polygons (with holes) are supported (either #Tag_true or #Tag_false ).

A general polygon is represented by a face $ f $ with no isolated vertex and
any edge of $ f $ separates $ f $ from another face. Note that this allows $ f
$ to touch a vertex from several sides.

Returns: unspecified_type";
constexpr const char* Visibility_2_Supports_simple_polygon_category = "identifies whether simple polygons are supported (either #Tag_true or #Tag_false ).

A simple polygon is represented by a face $ f $ with no holes, no isolated
vertex and any edge of $ f $ separates $ f $ from another face. Note that this
allows $ f $ to touch a vertex from several sides.

Returns: unspecified_type";
constexpr const char* Visibility_2_Visibility_2 = "Default constructor creates an empty Visibility_2 object that is not attached to any arrangement yet.";
constexpr const char* Visibility_2_Visibility_2_1 = "Constructs a Visibility_2 object that is attached to arr .

Parameters
----------
arr : const Arrangement_2 &";
constexpr const char* Visibility_2_is_attached = "Returns whether an arrangement is attached to the visibility object.

Returns: bool";
constexpr const char* Visibility_2_attach = "Attaches the given arrangement arr to the visibility object.

In case the object is already attached to another arrangement, the visibility
object gets detached before being attached to arr .

Parameters
----------
arr : const Arrangement_2 &";
constexpr const char* Visibility_2_detach = "Detaches the arrangement from the visibility object it is currently attached to.";
constexpr const char* Visibility_2_arrangement_2 = "Access to the attached arrangement.

Returns: const Arrangement_2 &";
constexpr const char* Visibility_2_compute_visibility = "Computes the visibility region for the given query point q in the face $ f $ of the arrangement that is attached to the visibility object.

The visibility region of q is stored in out_arr , that is, all features but
the unbounded face of out_arr represent the visibility region.
VisibilityArrangement_2 is the type of the output arrangement representing the
visibility polygon. It must be an instance of CGAL::Arrangement_2 , where its
CGAL::Arrangement_2::Traits_2 must be mutual convertible to
VisibilityArrangement_2::Traits_2 . q is the query point f is the face of the
arrangement in which the visibility region is computed out_arr is the output
arrangement f is a face of this-> arrangement_2() q is in the interior of the
given face f the face handle to the face in out_arr that represents interior
of the visibility region

Parameters
----------
q : const Point_2 &
f : const Face_const_handle
out_arr : VisibilityArrangement_2 &

Returns: Visibility_arrangement_2::Face_handle";
constexpr const char* Visibility_2_compute_visibility_1 = "Computes the visibility region in e->face() for the given query point q which must be located on e .

If q is an interior point of e , the computed visibility region is restricted
to the side indicated by the halfedge e . If q is an endpoint of e , the
visibility region is restricted by e and e->next() . The visibility region of
q is stored in out_arr , that is, all features but the unbounded face of
out_arr represent the visibility region. VisibilityArrangement_2 is the type
of the output arrangement representing the visibility polygon. It must be an
instance of CGAL::Arrangement_2 , where its CGAL::Arrangement_2::Traits_2 must
be mutual convertible to VisibilityArrangement_2::Traits_2 . q is the query
point e the halfedge on which q is located out_arr is the output arrangement e
is a halfedge of this-> arrangement_2() q is on e q equals to
e->target()->point() if q is an endpoint of e a handle to the face in out_arr
that represents the interior of the visibility region

Parameters
----------
q : const Point_2 &
e : const Halfedge_const_handle
out_arr : Visibility_arrangement_2 &

Returns: Visibility_arrangement_2::Face_handle";

// std
constexpr const char* std__class__ = "STL namespace.";

} // namespace Visibility_2
} // namespace docstrings
} // namespace cgalpy

#endif // CGAL_PYTHON_DOCSTRINGS_VISIBILITY_2_H
