// AUTO-GENERATED by cpp_docstrings_from_json.py — DO NOT EDIT
// Package: Minkowski_sum_3
#ifndef CGAL_PYTHON_DOCSTRINGS_MINKOWSKI_SUM_3_H
#define CGAL_PYTHON_DOCSTRINGS_MINKOWSKI_SUM_3_H

namespace cgalpy {
namespace docstrings {
namespace Minkowski_sum_3 {












// std
constexpr const char* std__class__ = "STL namespace.";

} // namespace Minkowski_sum_3
} // namespace docstrings
} // namespace cgalpy

#endif // CGAL_PYTHON_DOCSTRINGS_MINKOWSKI_SUM_3_H
