// Copyright (c) 2019 Israel.
// All rights reserved to Tel Aviv University.
//
// This file is private property of Tel Aviv University.
//
// Author(s): Nir Goren         <nirgoren@mail.tau.ac.il>
//            Efi Fogel         <efifogel@gmail.com>

#ifndef CGALPY_ALPHA_SHAPE_3_CONFIG_HPP
#define CGALPY_ALPHA_SHAPE_3_CONFIG_HPP

#include "CGALPY/triangulation_3_config.hpp"

#define CGALPY_AS3_PLAIN                                0
#define CGALPY_AS3_FIXED                                1

#if ((CGALPY_TRI3_VERTEX_BASE != CGALPY_TRI3_VERTEX_BASE_ALPHA_SHAPE) && \
     (CGALPY_TRI3_VERTEX_BASE != CGALPY_TRI3_VERTEX_BASE_ALPHA_SHAPE_WITH_INFO) && \
     (CGALPY_TRI3_VERTEX_BASE != CGALPY_TRI3_VERTEX_BASE_ALPHA_SHAPE_REGULAR) && \
     (CGALPY_TRI3_VERTEX_BASE != CGALPY_TRI3_VERTEX_BASE_ALPHA_SHAPE_REGULAR_WITH_INFO) && \
     (CGALPY_TRI3_VERTEX_BASE != CGALPY_TRI3_VERTEX_BASE_FIXED_ALPHA_SHAPE) && \
     (CGALPY_TRI3_VERTEX_BASE != CGALPY_TRI3_VERTEX_BASE_FIXED_ALPHA_SHAPE_WITH_INFO) && \
     (CGALPY_TRI3_VERTEX_BASE != CGALPY_TRI3_VERTEX_BASE_FIXED_ALPHA_SHAPE_REGULAR) && \
     (CGALPY_TRI3_VERTEX_BASE != CGALPY_TRI3_VERTEX_BASE_FIXED_ALPHA_SHAPE_REGULAR_WITH_INFO))
BOOST_STATIC_ASSERT_MSG(false, "CGALPY_TRI3_VERTEX_BASE");
#endif

#if ((CGALPY_TRI3_CELL_BASE != CGALPY_TRI3_CELL_BASE_ALPHA_SHAPE) && \
     (CGALPY_TRI3_CELL_BASE != CGALPY_TRI3_CELL_BASE_ALPHA_SHAPE_WITH_INFO) && \
     (CGALPY_TRI3_CELL_BASE != CGALPY_TRI3_CELL_BASE_ALPHA_SHAPE_REGULAR) && \
     (CGALPY_TRI3_CELL_BASE != CGALPY_TRI3_CELL_BASE_ALPHA_SHAPE_REGULAR_WITH_INFO) && \
     (CGALPY_TRI3_CELL_BASE != CGALPY_TRI3_CELL_BASE_FIXED_ALPHA_SHAPE) && \
     (CGALPY_TRI3_CELL_BASE != CGALPY_TRI3_CELL_BASE_FIXED_ALPHA_SHAPE_WITH_INFO) && \
     (CGALPY_TRI3_CELL_BASE != CGALPY_TRI3_CELL_BASE_FIXED_ALPHA_SHAPE_REGULAR) && \
     (CGALPY_TRI3_CELL_BASE != CGALPY_TRI3_CELL_BASE_FIXED_ALPHA_SHAPE_REGULAR_WITH_INFO))
BOOST_STATIC_ASSERT_MSG(false, "CGALPY_TRI3_CELL_BASE");
#endif

#endif //CGALPY_ALPHA_SHAPE_3_CONFIG_HPP
