// Copyright (c) 2019 Israel.
// All rights reserved to Tel Aviv University.
//
// This file is private property of Tel Aviv University.
//
// Author(s): Nir Goren         <nirgoren@mail.tau.ac.il>
//            Efi Fogel         <efifogel@gmail.com>

#ifndef CGALPY_CONFIG_HPP
#define CGALPY_CONFIG_HPP

#include <CGALPY/kernel_config.hpp>
#include <CGALPY/arrangement_2_config.hpp>
#include <CGALPY/spatial_searching_config.hpp>
#include <CGALPY/convex_hull_2_config.hpp>

#define CGAL_HEADER_ONLY 1
#define BOOST_PYTHON_STATIC_LIB 1
#define CGAL_DO_NOT_USE_BOOST_MP 1

#if CGALPY_KERNEL == CGALPY_KERNEL_EPEC
#define CGALPY_KERNEL_SHORT_NAME epec
#elif CGALPY_KERNEL == CGALPY_KERNEL_EPIC
#define CGALPY_KERNEL_SHORT_NAME epic
#endif

#if CGALPY_ARR2_GEOMETRY_TRAITS == CGALPY_ARR2_LINEAR_GEOMETRY_TRAITS
#define CGALPY_ARR2_GEOMETRY_TRAITS_SHORT_NAME linear
#elif CGALPY_ARR2_GEOMETRY_TRAITS == CGALPY_ARR2_SEGMENT_GEOMETRY_TRAITS
#define CGALPY_ARR2_GEOMETRY_TRAITS_SHORT_NAME seg
#elif CGALPY_ARR2_GEOMETRY_TRAITS == CGALPY_ARR2_NON_CACHING_SEGMENT_GEOMETRY_TRAITS
#define CGALPY_ARR2_GEOMETRY_TRAITS_SHORT_NAME ncseg
#elif CGALPY_ARR2_GEOMETRY_TRAITS == CGALPY_ARR2_CONIC_GEOMETRY_TRAITS
#define CGALPY_ARR2_GEOMETRY_TRAITS_SHORT_NAME conic
#elif CGALPY_ARR2_GEOMETRY_TRAITS == CGALPY_ARR2_ALGEBRAIC_SEGMENT_GEOMETRY_TRAITS
#define CGALPY_ARR2_GEOMETRY_TRAITS_SHORT_NAME alg
#elif CGALPY_ARR2_GEOMETRY_TRAITS == CGALPY_ARR2_CIRCLE_SEGMENT_GEOMETRY_TRAITS
#define CGALPY_ARR2_GEOMETRY_TRAITS_SHORT_NAME cs
#endif

#endif //CONFIG_HPP
