// Copyright (c) 2019 Israel.
// All rights reserved to Tel Aviv University.
//
// This file is private property of Tel Aviv University.
//
// Author(s): Nir Goren         <nirgoren@mail.tau.ac.il>
//            Efi Fogel         <efifogel@gmail.com>

#ifndef CGALPY_CONFIG_HPP
#define CGALPY_CONFIG_HPP

#include "kernel_config.hpp"
#include "arrangement_2_config.hpp"

#define CGAL_HEADER_ONLY 1
#define BOOST_PYTHON_STATIC_LIB 1
#define CGAL_DO_NOT_USE_BOOST_MP 1

#ifndef CGALPY_SPATIAL_SEARCHING_DIMENSION
#define CGALPY_SPATIAL_SEARCHING_DIMENSION 2
#endif

#if CGALPY_KERNEL == CGALPY_KERNEL_EPEC
#define CGALPY_KERNEL_SHORT_NAME epec
#elif CGALPY_KERNEL == CGALPY_KERNEL_EPIC
#define CGALPY_KERNEL_SHORT_NAME epic
#endif

#if CGALPY_ARR2_GEOMETRY_TRAITS == CGALPY_ARR2_LINEAR_GEOMETRY_TRAITS
#define CGALPY_ARR2_GEOMETRY_TRAITS_SHORT_NAME linear
#elif CGALPY_ARR2_GEOMETRY_TRAITS == CGALPY_ARR2_SEGMENT_GEOMETRY_TRAITS
#define CGALPY_ARR2_GEOMETRY_TRAITS_SHORT_NAME seg
#elif CGALPY_ARR2_GEOMETRY_TRAITS == CGALPY_ARR2_NON_CACHING_SEGMENT_GEOMETRY_TRAITS
#define CGALPY_ARR2_GEOMETRY_TRAITS_SHORT_NAME ncseg
#elif CGALPY_ARR2_GEOMETRY_TRAITS == CGALPY_ARR2_CONIC_GEOMETRY_TRAITS
#define CGALPY_ARR2_GEOMETRY_TRAITS_SHORT_NAME conic
#elif CGALPY_ARR2_GEOMETRY_TRAITS == CGALPY_ARR2_ALGEBRAIC_SEGMENT_GEOMETRY_TRAITS
#define CGALPY_ARR2_GEOMETRY_TRAITS_SHORT_NAME alg
#elif CGALPY_ARR2_GEOMETRY_TRAITS == CGALPY_ARR2_CIRCLE_SEGMENT_GEOMETRY_TRAITS
#define CGALPY_ARR2_GEOMETRY_TRAITS_SHORT_NAME cs
#endif

#define CONCAT_3(a, b, c) a ## _ ## b ## _ ## c
#define SET_MODULE_NAME(a, b, c) CONCAT_3(a, b, c)

#define CONCAT_4(a, b, c, d) a ## _ ## b ## _ ## c ## _ ## d
#define SET_MODULE_NAME_EX(a, b, c, d) CONCAT_4(a, b, c, d)

#if CGALPY_ARR2_DCEL == CGALPY_ARR2_DEFAULT_DCEL
#define CGALPY_MODULE_NAME SET_MODULE_NAME(arr2, CGALPY_KERNEL_SHORT_NAME, CGALPY_ARR2_GEOMETRY_TRAITS_SHORT_NAME)
#endif
#if CGALPY_ARR2_DCEL == CGALPY_ARR2_FACE_EXTENDED_DCEL
#define CGALPY_MODULE_NAME SET_MODULE_NAME_EX(arr2, CGALPY_KERNEL_SHORT_NAME, CGALPY_ARR2_GEOMETRY_TRAITS_SHORT_NAME, fex)
#endif
#if CGALPY_ARR2_DCEL == CGALPY_ARR2_EXTENDED_DCEL
#define CGALPY_MODULE_NAME SET_MODULE_NAME_EX(arr2, CGALPY_KERNEL_SHORT_NAME, CGALPY_ARR2_GEOMETRY_TRAITS_SHORT_NAME, ex)
#endif

#endif //CONFIG_HPP
