// AUTO-GENERATED by cpp_docstrings_from_json.py — DO NOT EDIT
// Package: Subdivision_method_3
#ifndef CGAL_PYTHON_DOCSTRINGS_SUBDIVISION_METHOD_3_H
#define CGAL_PYTHON_DOCSTRINGS_SUBDIVISION_METHOD_3_H

namespace cgalpy {
namespace docstrings {
namespace Subdivision_method_3 {

// CGAL::CatmullClark_mask_3
constexpr const char* CatmullClark_mask_3__class__ = "The geometry mask of Catmull-Clark subdivision.";

constexpr const char* CatmullClark_mask_3_CatmullClark_mask_3 = "Constructor.

The default vertex point property map, get(vertex_point, pmesh) , is used.

Parameters
----------
pmesh : Mesh *";
constexpr const char* CatmullClark_mask_3_CatmullClark_mask_3_1 = "Constructor with a custom vertex point property map.

Parameters
----------
pmesh : Mesh *
vpmap : VertexPointMap";
constexpr const char* CatmullClark_mask_3_edge_node = "computes the Catmull-Clark edge-point pt of the edge edge .

Parameters
----------
edge : halfedge_descriptor
pt : Point &";
constexpr const char* CatmullClark_mask_3_vertex_node = "computes the Catmull-Clark vertex-point pt of the vertex vertex .

Parameters
----------
vertex : vertex_descriptor
pt : Point &";
constexpr const char* CatmullClark_mask_3_border_node = "computes the Catmull-Clark edge-point ept and the Catmull-Clark vertex-point vpt of the border edge edge .

Parameters
----------
edge : halfedge_descriptor
ept : Point &
vpt : Point &";

// CGAL::DooSabin_mask_3
constexpr const char* DooSabin_mask_3__class__ = "The geometry mask of Doo-Sabin subdivision.";

constexpr const char* DooSabin_mask_3_DooSabin_mask_3 = "Constructor.

The default vertex point property map, get(vertex_point, pmesh) , is used.

Parameters
----------
pmesh : Mesh *";
constexpr const char* DooSabin_mask_3_DooSabin_mask_3_1 = "Constructor with a custom vertex point property map.

Parameters
----------
pmesh : Mesh *
vpmap : VertexPointMap";
constexpr const char* DooSabin_mask_3_corner_node = "computes the Doo-Sabin point pt of the vertex pointed by the halfedge he .

Parameters
----------
he : halfedge_descriptor
pt : Point &";

// CGAL::DQQ_stencil_3
constexpr const char* DQQ_stencil_3__class__ = "The stencil of the Dual-Quadrilateral-Quadrisection.";


// CGAL::Linear_mask_3
constexpr const char* Linear_mask_3__class__ = "Bi-linear geometry mask for PQQ, PTQ, and Sqrt(3) schemes.";


// CGAL::Loop_mask_3
constexpr const char* Loop_mask_3__class__ = "The geometry mask of Loop subdivision.";

constexpr const char* Loop_mask_3_Loop_mask_3 = "Constructor.

The default vertex point property map, get(vertex_point, pmesh) , is used.

Parameters
----------
pmesh : Mesh *";
constexpr const char* Loop_mask_3_Loop_mask_3_1 = "Constructor with a custom vertex point property map.

Parameters
----------
pmesh : Mesh *
vpmap : VertexPointMap";
constexpr const char* Loop_mask_3_edge_node = "computes the Loop edge-point pt of the edge edge .

Parameters
----------
edge : halfedge_descriptor
pt : Point &";
constexpr const char* Loop_mask_3_vertex_node = "computes the Loop vertex-point pt of the vertex vertex .

Parameters
----------
vertex : vertex_descriptor
pt : Point &";
constexpr const char* Loop_mask_3_border_node = "computes the Loop edge-point ept and the Loop vertex-point vpt of the border edge edge .

Parameters
----------
edge : halfedge_descriptor
ept : Point &
vpt : Point &";

// CGAL::PQQ_stencil_3
constexpr const char* PQQ_stencil_3__class__ = "The stencil of the Primal-Quadrilateral-Quadrisection.";


// CGAL::Sqrt3_mask_3
constexpr const char* Sqrt3_mask_3__class__ = "The geometry mask of Sqrt(3) subdivision.";

constexpr const char* Sqrt3_mask_3_Sqrt3_mask_3 = "Constructor.

The default vertex point property map, get(vertex_point, pmesh) , is used.

Parameters
----------
pmesh : Mesh *";
constexpr const char* Sqrt3_mask_3_Sqrt3_mask_3_1 = "Constructor with a custom vertex point property map.

Parameters
----------
pmesh : Mesh *
vpmap : VertexPointMap";
constexpr const char* Sqrt3_mask_3_vertex_node = "computes the $ \\sqrt{3}$ vertex-point pt of the vertex vd .

Parameters
----------
vertex : vertex_descriptor
pt : Point &";
constexpr const char* Sqrt3_mask_3_border_node = "computes the $ \\sqrt{3}$ edge-points ept1 and ept2 of the halfedge hd .

The updated point coordinates for the target vertex of hd is also computed and
put in vpt . Border subdivision only happens every second step of a single
successive $ \\sqrt{3}$ subdivision (thus requiring a depth larger than 1).

Parameters
----------
hd : halfedge_descriptor
ept1 : Point &
ept2 : Point &
vpt : Point &";

// DQQMask_3
constexpr const char* DQQMask_3__class__ = "Required member functions for the DQQMask_3 concept. This policy concept of geometric computations is used in CGAL::Subdivision_method_3::DQQ < PolygonMesh , Mask, NamedParameters> .";

constexpr const char* DQQMask_3_PolygonMesh = "The polygon mesh must be triangulated.

Returns: unspecified_type";
constexpr const char* DQQMask_3_DQQMask_3 = "Constructor.

The default vertex point property map is used.

Parameters
----------
pmesh : PolygonMesh *";
constexpr const char* DQQMask_3_DQQMask_3_1 = "Constructor.

Parameters
----------
pmesh : PolygonMesh *
vpmap : VertexPointMap";
constexpr const char* DQQMask_3_corner_node = "computes the subdivided point pt based on the neighborhood of the vertex pointed by the halfedge hd .

Parameters
----------
hd : halfedge_descriptor
pt : Point &";

// PQQMask_3
constexpr const char* PQQMask_3__class__ = "Required member functions for the PQQMask_3 concept. This policy concept of geometric computations is used in CGAL::Subdivision_method_3::PQQ < PolygonMesh , Mask, NamedParameters> .";

constexpr const char* PQQMask_3_PolygonMesh = "The polygon mesh must be triangulated.

Returns: unspecified_type";
constexpr const char* PQQMask_3_PQQMask_3 = "Constructor.

The default vertex point property map is used.

Parameters
----------
pmesh : PolygonMesh *";
constexpr const char* PQQMask_3_PQQMask_3_1 = "Constructor.

Parameters
----------
pmesh : PolygonMesh *
vpmap : VertexPointMap";
constexpr const char* PQQMask_3_face_node = "computes the face-point pt based on the neighborhood of the face fd .

Parameters
----------
fd : face_descriptor
pt : Point_3 &";
constexpr const char* PQQMask_3_edge_node = "computes the edge-point pt based on the neighborhood of the edge hd .

Parameters
----------
hd : halfedge_descriptor
pt : Point_3 &";
constexpr const char* PQQMask_3_vertex_node = "computes the vertex-point pt based on the neighborhood of the vertex vd .

Parameters
----------
vd : vertex_descriptor
pt : Point_3 &";
constexpr const char* PQQMask_3_border_node = "computes the edge-point ept and the vertex-point vpt based on the neighborhood of the border edge of hd .

hd is not a border halfedge (its opposite is) and vpt corresponds to the
target vertex of hd .

Parameters
----------
hd : halfedge_descriptor
ept : Point_3 &
vpt : Point_3 &";

// PTQMask_3
constexpr const char* PTQMask_3__class__ = "Required member functions for the PTQMask_3 concept. This policy concept of geometric computations is used in CGAL::Subdivision_method_3::PTQ < PolygonMesh , Mask, NamedParameters> .";

constexpr const char* PTQMask_3_PolygonMesh = "The polygon mesh must be triangulated.

Returns: unspecified_type";
constexpr const char* PTQMask_3_PTQMask_3 = "Constructor.

The default vertex point property map is used.

Parameters
----------
pmesh : PolygonMesh *";
constexpr const char* PTQMask_3_PTQMask_3_1 = "Constructor.

Parameters
----------
pmesh : PolygonMesh *
vpmap : VertexPointMap";
constexpr const char* PTQMask_3_edge_node = "computes the edge-point pt based on the neighborhood of the edge hd .

Parameters
----------
hd : halfedge_descriptor
pt : Point_3 &";
constexpr const char* PTQMask_3_vertex_node = "computes the vertex-point pt based on the neighborhood of the vertex vd .

Parameters
----------
vd : vertex_descriptor
pt : Point_3 &";
constexpr const char* PTQMask_3_border_node = "computes the edge-point ept and the vertex-point vpt based on the neighborhood of the border edge of hd .

hd is not a border halfedge (its opposite is) and vpt corresponds to the
target vertex of hd .

Parameters
----------
hd : halfedge_descriptor
ept : Point_3 &
vpt : Point_3 &";

// Sqrt3Mask_3
constexpr const char* Sqrt3Mask_3__class__ = "Required member functions for the Sqrt3Mask_3 concept. This policy concept of geometric computations is used in CGAL::Subdivision_method_3::Sqrt3 < PolygonMesh , Mask, NamedParameters> .";

constexpr const char* Sqrt3Mask_3_PolygonMesh = "The polygon mesh must be triangulated.

Returns: unspecified_type";
constexpr const char* Sqrt3Mask_3_Sqrt3Mask_3 = "Constructor.

The default vertex point property map is used.

Parameters
----------
pmesh : PolygonMesh *";
constexpr const char* Sqrt3Mask_3_Sqrt3Mask_3_1 = "Constructor.

Parameters
----------
pmesh : PolygonMesh *
vpmap : VertexPointMap";
constexpr const char* Sqrt3Mask_3_face_node = "computes the subdivided point pt based on the neighborhood of the face fd .

Parameters
----------
fd : face_descriptor
pt : Point_3 &";
constexpr const char* Sqrt3Mask_3_vertex_node = "computes the subdivided point pt based on the neighborhood of the vertex vd .

Parameters
----------
vd : vertex_descriptor
pt : Point &";
constexpr const char* Sqrt3Mask_3_border_node = "computes the subdivided points ept1 and ept2 based on the neighborhood of the halfedge hd (whose opposite is on the border).

Along hd , ept1 comes before ept2 . vpt is the updated point for the target
vertex of hd .

Parameters
----------
hd : halfedge_descriptor
ept1 : Point &
ept2 : Point &
vpt : Point &";

// SubdivisionMask_3
constexpr const char* SubdivisionMask_3__class__ = "This concept defines types used by the mask concepts.";


// CGAL::Subdivision_method_3
constexpr const char* Subdivision_method_3__class__ = "The namespace containing the subdivision methods.";

// std
constexpr const char* std__class__ = "STL namespace.";

} // namespace Subdivision_method_3
} // namespace docstrings
} // namespace cgalpy

#endif // CGAL_PYTHON_DOCSTRINGS_SUBDIVISION_METHOD_3_H
