// AUTO-GENERATED by cpp_docstrings_from_json.py — DO NOT EDIT
// Package: Cone_spanners_2
#ifndef CGAL_PYTHON_DOCSTRINGS_CONE_SPANNERS_2_H
#define CGAL_PYTHON_DOCSTRINGS_CONE_SPANNERS_2_H

namespace cgalpy {
namespace docstrings {
namespace Cone_spanners_2 {

// CGAL::Compute_cone_boundaries_2
constexpr const char* Compute_cone_boundaries_2__class__ = "The functor for computing the directions of cone boundaries with a given cone number and a given initial direction.";

constexpr const char* Compute_cone_boundaries_2_Direction_2 = "the direction type.

Returns: Traits::Direction_2";
constexpr const char* Compute_cone_boundaries_2_operator = "The operator().

The direction of the first ray can be specified by the parameter
initial_direction , which allows the first ray to start at any direction. This
operator first places the initial_direction at the position pointed by result
. Then, it calculates the remaining directions (cone boundaries) and output
them to result in the counterclockwise order. Finally, the past-the-end
iterator for the resulting directions is returned. DirectionOutputIterator an
OutputIterator with value type Direction_2 . cone_number The number of cones
initial_direction The direction of the first ray result The output iterator

Parameters
----------
cone_number : const unsigned int
initial_direction : const Direction_2 &
result : DirectionOutputIterator

Returns: DirectionOutputIterator";

// CGAL::Construct_theta_graph_2
constexpr const char* Construct_theta_graph_2__class__ = "A template functor for constructing Theta graphs with a given set of 2D points and a given initial direction for the cone boundaries.";

constexpr const char* Construct_theta_graph_2_Graph = "the specific type of boost::adjacency_list .

Returns: Graph_";
constexpr const char* Construct_theta_graph_2_Point_2 = "the point type

Returns: Traits::Point_2";
constexpr const char* Construct_theta_graph_2_Direction_2 = "the direction type

Returns: Traits::Direction_2";
constexpr const char* Construct_theta_graph_2_Construct_theta_graph_2 = "Constructor.

k Number of cones to divide space into initial_direction A direction denoting
one of the rays dividing the cones. This allows arbitrary rotations of the
rays that divide the plane. (default: positive x-axis) cones_selected
Indicates whether even, odd or all cones are selected to construct graph.

Parameters
----------
k : unsigned int
initial_direction : Direction_2
cones_selected : Cones_selected";
constexpr const char* Construct_theta_graph_2_operator = "Function operator to construct a Theta graph.

For the details of this algorithm, please refer to the User Manual.
PointInputIterator an InputIterator with value type Point_2 . start An
iterator pointing to the first vertex of the input. end An iterator pointing
to the past-the-end location of the input. g The constructed graph object.

Parameters
----------
start : const PointInputIterator &
end : const PointInputIterator &
g : Graph_ &

Returns: Graph_ &";
constexpr const char* Construct_theta_graph_2_number_of_cones = "returns the number of cones.

Returns: unsigned int";
constexpr const char* Construct_theta_graph_2_directions = "outputs the set of directions to the iterator result .

DirectionOutputIterator an OutputIterator with value type Direction_2 . result

Parameters
----------
result : DirectionOutputIterator

Returns: DirectionOutputIterator";

// CGAL::Construct_yao_graph_2
constexpr const char* Construct_yao_graph_2__class__ = "A template functor for constructing Yao graphs with a given set of 2D points and a given initial direction for the cone boundaries.";

constexpr const char* Construct_yao_graph_2_Graph = "the specific type of boost::adjacency_list .

Returns: Graph_";
constexpr const char* Construct_yao_graph_2_Point_2 = "the point type

Returns: Traits::Point_2";
constexpr const char* Construct_yao_graph_2_Direction_2 = "the direction type

Returns: Traits::Direction_2";
constexpr const char* Construct_yao_graph_2_Construct_yao_graph_2 = "Constructor.

k Number of cones to divide space into initial_direction A direction denoting
one of the rays dividing the cones. This allows arbitrary rotations of the
rays that divide the plane. (default: positive x-axis) cones_selected
Indicates whether even, odd or all cones are selected to construct graph.

Parameters
----------
k : unsigned int
initial_direction : Direction_2
cones_selected : Cones_selected";
constexpr const char* Construct_yao_graph_2_operator = "Function operator to construct a Yao graph.

For the details of this algorithm, please refer to the User Manual.
PointInputIterator an InputIterator with value type Point_2 . start An
iterator pointing to the first vertex of the input. end An iterator pointing
to the past-the-end location of the input. g The constructed graph object.

Parameters
----------
start : const PointInputIterator &
end : const PointInputIterator &
g : Graph_ &

Returns: Graph_ &";
constexpr const char* Construct_yao_graph_2_number_of_cones = "returns the number of cones.

Returns: unsigned int";
constexpr const char* Construct_yao_graph_2_directions = "outputs the set of directions to the iterator result .

DirectionOutputIterator an OutputIterator with value type Direction_2 . result

Parameters
----------
result : DirectionOutputIterator

Returns: DirectionOutputIterator";





// std
constexpr const char* std__class__ = "STL namespace.";

} // namespace Cone_spanners_2
} // namespace docstrings
} // namespace cgalpy

#endif // CGAL_PYTHON_DOCSTRINGS_CONE_SPANNERS_2_H
