// AUTO-GENERATED by cpp_docstrings_from_json.py — DO NOT EDIT
// Package: Heat_method_3
#ifndef CGAL_PYTHON_DOCSTRINGS_HEAT_METHOD_3_H
#define CGAL_PYTHON_DOCSTRINGS_HEAT_METHOD_3_H

namespace cgalpy {
namespace docstrings {
namespace Heat_method_3 {

// CGAL::Heat_method_3::Direct
constexpr const char* Heat_method_3_Direct__class__ = "A tag class used to specify that the heat method is applied to the input mesh.";

// CGAL::Heat_method_3::Intrinsic_Delaunay
constexpr const char* Heat_method_3_Intrinsic_Delaunay__class__ = "A tag class used to specify that the heat method applies the intrinsic Delaunay triangulation to the input mesh.";

// CGAL::Heat_method_3::Surface_mesh_geodesic_distances_3
constexpr const char* Heat_method_3_Surface_mesh_geodesic_distances_3__class__ = "Class Surface_mesh_geodesic_distances_3 computes estimated geodesic distances for a set of source vertices where sources can be added and removed.";

constexpr const char* Heat_method_3_Surface_mesh_geodesic_distances_3_vertex_descriptor = "Vertex descriptor type.

Returns: boost::graph_traits< TriangleMesh >::vertex_descriptor";
constexpr const char* Heat_method_3_Surface_mesh_geodesic_distances_3_Vertex_const_range = "a model of ConstRange with an iterator that is model of ForwardIterator with vertex_descriptor as value type.

Returns: unspecified_type";
constexpr const char* Heat_method_3_Surface_mesh_geodesic_distances_3_Vertex_point_map = "Vertex point map type derived from VertexPointMap .

Returns: unspecified_type";
constexpr const char* Heat_method_3_Surface_mesh_geodesic_distances_3_Surface_mesh_geodesic_distances_3 = "Constructor.

Parameters
----------
tm : const TriangleMesh &";
constexpr const char* Heat_method_3_Surface_mesh_geodesic_distances_3_Surface_mesh_geodesic_distances_3_1 = "Constructor.

Parameters
----------
tm : const TriangleMesh &
vpm : Vertex_point_map";
constexpr const char* Heat_method_3_Surface_mesh_geodesic_distances_3_triangle_mesh = "returns the triangle mesh the algorithm is running on.

Returns: const TriangleMesh &";
constexpr const char* Heat_method_3_Surface_mesh_geodesic_distances_3_add_source = "adds vd to the source set, returning false if vd is already in the set.

Parameters
----------
vd : vertex_descriptor

Returns: bool";
constexpr const char* Heat_method_3_Surface_mesh_geodesic_distances_3_add_sources = "adds the range of vertices to the source set.

VertexConstRange a model of the concept ConstRange with value type
boost::graph_traits<TriangleMesh>::vertex_descriptor

Parameters
----------
vrange : const VertexConstRange &";
constexpr const char* Heat_method_3_Surface_mesh_geodesic_distances_3_remove_source = "removes vd from the source set, returning true if vd was in the set.

Parameters
----------
vd : vertex_descriptor

Returns: bool";
constexpr const char* Heat_method_3_Surface_mesh_geodesic_distances_3_clear_sources = "clears the current source set.";
constexpr const char* Heat_method_3_Surface_mesh_geodesic_distances_3_sources = "returns the source set.

Returns: const Vertex_const_range &";
constexpr const char* Heat_method_3_Surface_mesh_geodesic_distances_3_estimate_geodesic_distances = "fills the distance property map with the estimated geodesic distance of each vertex to the closest source vertex.

VertexDistanceMap a property map model of WritablePropertyMap with
vertex_descriptor as key type and double as value type. vdm the vertex
distance map to be filled If Mode is Direct , the support triangle mesh does
not have any degenerate faces The key type is double even when used with an
exact kernel.

Parameters
----------
vdm : VertexDistanceMap";

// HeatMethodTraits_3
constexpr const char* HeatMethodTraits_3__class__ = "The concept HeatMethodTraits_3 describes the types, predicates, and constructions required by the traits class parameter of CGAL::Heat_method_3::Surface_mesh_geodesic_distances_3 .";

constexpr const char* HeatMethodTraits_3_Point_3 = "The 3D point type.

It must be CopyConstructible and DefaultConstructible , and have a constructor
with three parameters of a type constructibe from double .

Returns: unspecified_type";
constexpr const char* HeatMethodTraits_3_Vector_3 = "The 3D vector type.

It must be CopyConstructible and DefaultConstructible , and have a constructor
with three parameters of a type constructibe from double .

Returns: unspecified_type";
constexpr const char* HeatMethodTraits_3_Construct_vector_3 = "Functor with operator: Vector_3 operator()(const Point_3 & from, const Point_3 & to) const , which constructs the vector from to - from .

Returns: unspecified_type";
constexpr const char* HeatMethodTraits_3_Construct_sum_of_vectors_3 = "Functor with operator: Vector_3 operator()(const Vector_3 & v, const Vector_3 & w) const , which constructs the vector v + w .

Returns: unspecified_type";
constexpr const char* HeatMethodTraits_3_Construct_scaled_vector_3 = "Functor with operator: Vector_3 operator()(const Vector_3 & v, double d) const , which constructs the vector d * v .

Returns: unspecified_type";
constexpr const char* HeatMethodTraits_3_Construct_cross_product_vector_3 = "Functor with operator: Vector_3 operator()(const Vector_3 & v, const Vector_3 & w) const , which constructs the cross product of v and w .

Returns: unspecified_type";
constexpr const char* HeatMethodTraits_3_Compute_scalar_product_3 = "Functor with operator: FT operator()(const Vector_3 & v, const Vector_3 & w) const , which constructs the scalar product of v and w .

Returns: unspecified_type";
constexpr const char* HeatMethodTraits_3_Compute_squared_distance_3 = "Functor with operator: FT operator()(const Point_3 & p, const Point_3 & q) const which computes the squared distance between p and q .

Returns: unspecified_type";
constexpr const char* HeatMethodTraits_3_Compute_squared_length_3 = "Functor with operator: FT operator()(const Vector_3 & v) const which computes the squared length of v .

Returns: unspecified_type";

// std
constexpr const char* std__class__ = "STL namespace.";

} // namespace Heat_method_3
} // namespace docstrings
} // namespace cgalpy

#endif // CGAL_PYTHON_DOCSTRINGS_HEAT_METHOD_3_H
