// AUTO-GENERATED by cpp_docstrings_from_json.py — DO NOT EDIT
// Package: Skin_surface_3
#ifndef CGAL_PYTHON_DOCSTRINGS_SKIN_SURFACE_3_H
#define CGAL_PYTHON_DOCSTRINGS_SKIN_SURFACE_3_H

namespace cgalpy {
namespace docstrings {
namespace Skin_surface_3 {

// CGAL::Skin_surface_3
constexpr const char* CGAL_Skin_surface_3__class__ = "The Skin_surface_3 is the main class in this package.";

// CGAL::Skin_surface_polyhedral_items_3
constexpr const char* CGAL_Skin_surface_polyhedral_items_3__class__ = "An items class for the Polyhedron_3 that stores information in faces instead of an auxiliary data structure.";

// CGAL::Skin_surface_traits_3
constexpr const char* CGAL_Skin_surface_traits_3__class__ = "The class Skin_surface_traits_3 is designed as a default traits class for the class Skin_surface_3 < SkinSurfaceTraits_3 > .";

// CGAL::Union_of_balls_3
constexpr const char* CGAL_Union_of_balls_3__class__ = "The Union_of_balls_3 is used to represent a skin surface with shrink factor equal to one, which is the boundary of the union of the input balls.";

// SkinSurface_3
constexpr const char* SkinSurface_3__class__ = "The concept SkinSurface_3 defines a skin surface and provides an interface for the dedicated skin surface mesher. The concept requires a constructor from an iterator range of weighted points and a shrink factor. By default the input balls are grown in such that the skin surface wraps around the input balls.";

constexpr const char* SkinSurface_3_Geometric_traits = "The geometric traits used for the construction of the regular triangulation.

Returns: unspecified_type";
constexpr const char* SkinSurface_3_Weighted_point = "The Weighted_point type.

Returns: Geometric_traits::Weighted_point_3";
constexpr const char* SkinSurface_3_Bare_point = "The Bare_point type.

Returns: Geometric_traits::Point_3";
constexpr const char* SkinSurface_3_FT = "The FT type defined by the Geometric_traits .

This is the number type used by the weighted points.

Returns: unspecified_type";
constexpr const char* SkinSurface_3_Skin_surface_3 = "The mandatory arguments to the constructor are an iterator range [begin,end) of weighted points and a shrink factor between 0 and 1.

Parameters
----------
begin : WP_iterator
end : WP_iterator
shrink_factor : RT";
constexpr const char* SkinSurface_3_mesh_skin_surface_3 = "Constructs a coarse mesh in p .

Polyhedron must be an instance of Polyhedron_3 . Polyhedron::HDS can be used
as the template argument of the CGAL::Polyhedron_incremental_builder_3<HDS> .

Parameters
----------
p : Polyhedron &";
constexpr const char* SkinSurface_3_subdivide_skin_surface_mesh_3 = "Subdivides the skin surface using nSubdiv 1-4 split operations (each triangle is split into four sub-triangles) and the new vertices are moved towards the skin surface.

Polyhedron must be an instance of Polyhedron_3 .

Parameters
----------
p : Polyhedron &
nSubdiv : int";

// SkinSurfaceTraits_3
constexpr const char* SkinSurfaceTraits_3__class__ = "Required types and member functions for the SkinSurfaceTraits_3 concept. This geometric traits concept is used for the construction of a polyhedral mesh approximating a skin surface CGAL::Skin_surface_3 .";

constexpr const char* SkinSurfaceTraits_3_RT = "The number type.

Returns: unspecified_type";
constexpr const char* SkinSurfaceTraits_3_Construct_anchor_point_3 = "A constructor object which provides the following function operator:

Point operator()(const Point &center_del, const Point &center_vor); Constructs
the anchor point in between the Delaunay and Voronoi centers, i.e., the point
$ (1-s)\\cdot$ center_del + $ s\\cdot$ center_vor , where $ s$ is the shrink
factor.

Returns: unspecified_type";
constexpr const char* SkinSurfaceTraits_3_SkinSurfaceTraits_3 = "Constructor that takes the shrink factor as argument.

For meshing the boundary of the union of a set of balls, the shrink factor is
discarded.

Parameters
----------
s : RT";
constexpr const char* SkinSurfaceTraits_3_shrink_factor = "Returns the shrink factor.

Returns: Regular_RT";
constexpr const char* SkinSurfaceTraits_3_construct_anchor_point_3_object = "Returns a Construct_anchor_point_3 object.

Returns: Construct_anchor_point_3";

// std
constexpr const char* std__class__ = "STL namespace.";

} // namespace Skin_surface_3
} // namespace docstrings
} // namespace cgalpy

#endif // CGAL_PYTHON_DOCSTRINGS_SKIN_SURFACE_3_H
