// AUTO-GENERATED by cpp_docstrings_from_json.py — DO NOT EDIT
// Package: Surface_mesh_deformation
#ifndef CGAL_PYTHON_DOCSTRINGS_SURFACE_MESH_DEFORMATION_H
#define CGAL_PYTHON_DOCSTRINGS_SURFACE_MESH_DEFORMATION_H

namespace cgalpy {
namespace docstrings {
namespace Surface_mesh_deformation {

// CGAL::Deformation_Eigen_closest_rotation_traits_3
constexpr const char* Deformation_Eigen_closest_rotation_traits_3__class__ = "A class to compute the closest rotation in Frobenius norm to a 3x3 Matrix using the Eigen library .";

// CGAL::Deformation_Eigen_polar_closest_rotation_traits_3
constexpr const char* Deformation_Eigen_polar_closest_rotation_traits_3__class__ = "A class to compute the closest rotation in Frobenius norm to a 3x3 Matrix using the Eigen library .";

// CGAL::Surface_mesh_deformation
constexpr const char* Surface_mesh_deformation__class__ = "Class providing the functionalities for deforming a triangulated surface mesh.";

constexpr const char* Surface_mesh_deformation_Triangle_mesh = "Triangle mesh type.

Returns: TM";
constexpr const char* Surface_mesh_deformation_Vertex_index_map = "vertex index map type

Returns: VIM";
constexpr const char* Surface_mesh_deformation_Hedge_index_map = "halfedge index map type

Returns: HIM";
constexpr const char* Surface_mesh_deformation_Sparse_linear_solver = "sparse linear solver type

Returns: ST";
constexpr const char* Surface_mesh_deformation_Closest_rotation_traits = "closest rotation traits type

Returns: CR";
constexpr const char* Surface_mesh_deformation_Vertex_point_map = "vertex point map type

Returns: VPM";
constexpr const char* Surface_mesh_deformation_Weight_calculator = "weight calculator functor type

Returns: WC";
constexpr const char* Surface_mesh_deformation_vertex_descriptor = "The type for vertex descriptor.

Returns: boost::graph_traits< Triangle_mesh >::vertex_descriptor";
constexpr const char* Surface_mesh_deformation_halfedge_descriptor = "The type for halfedge descriptor.

Returns: boost::graph_traits< Triangle_mesh >::halfedge_descriptor";
constexpr const char* Surface_mesh_deformation_Point = "The 3D point type, model of RawPoint_3 .

Returns: boost::property_traits< Vertex_point_map >::value_type";
constexpr const char* Surface_mesh_deformation_Roi_vertex_range = "A constant iterator range over the vertices of the region-of-interest.

It is a model of ConstRange with vertex_descriptor as iterator value type.

Returns: std::vector< vertex_descriptor >";
constexpr const char* Surface_mesh_deformation_Surface_mesh_deformation = "The constructor of a deformation object.

triangle_mesh consists of only triangular facets triangle_mesh triangulated
surface mesh to deform vertex_index_map a property map which associates a
unique id to each vertex, between 0 to num_vertices(triangle_mesh)-1 .
hedge_index_map property map which associates a unique id to each halfedge,
between 0 to 2*num_edges( triangle_mesh )-1 . vertex_point_map property map
which associates a point to each vertex of the triangle mesh.
weight_calculator function object or pointer for weight calculation

Parameters
----------
triangle_mesh : Triangle_mesh &
vertex_index_map : Vertex_index_map
hedge_index_map : Hedge_index_map
vertex_point_map : Vertex_point_map
weight_calculator : Weight_calculator";
constexpr const char* Surface_mesh_deformation_clear_roi_vertices = "Erases all the vertices from the region-of-interest (control vertices included).";
constexpr const char* Surface_mesh_deformation_clear_control_vertices = "Erases all the vertices from the set of control vertices.";
constexpr const char* Surface_mesh_deformation_insert_control_vertex = "Inserts a vertex in the set of control vertices.

The vertex is also inserted in the region-of-interest if it is not already in
it. vd the vertex to be inserted true if vd is not already a control vertex.

Parameters
----------
vd : vertex_descriptor

Returns: bool";
constexpr const char* Surface_mesh_deformation_insert_control_vertices = "Inserts a range of vertices in the set of control vertices.

The vertices are also inserted in the region-of-interest if they are not
already in it. InputIterator input iterator type with vertex_descriptor as
value type begin first iterator of the range of vertices end past-the-end
iterator of the range of vertices

Parameters
----------
begin : InputIterator
end : InputIterator";
constexpr const char* Surface_mesh_deformation_erase_control_vertex = "Erases a vertex from the set of control vertices.

vd the vertex to be erased true if vd was a control vertex.

Parameters
----------
vd : vertex_descriptor

Returns: bool";
constexpr const char* Surface_mesh_deformation_insert_roi_vertices = "Inserts a range of vertices in the region-of-interest.

InputIterator input iterator with vertex_descriptor as value type begin first
iterator of the range of vertices end past-the-end iterator of the range of
vertices

Parameters
----------
begin : InputIterator
end : InputIterator";
constexpr const char* Surface_mesh_deformation_insert_roi_vertex = "Inserts a vertex in the region-of-interest.

vd the vertex to be inserted true if vd is not already in the
region-of-interest.

Parameters
----------
vd : vertex_descriptor

Returns: bool";
constexpr const char* Surface_mesh_deformation_erase_roi_vertex = "Erases a vertex from the region-of-interest and the set of control vertices.

At the next call to preprocess() , any vertex that is no longer in the
region-of-interest will be assigned to its original position (that is the
position of the vertex at the time of construction or after the last call to
overwrite_initial_geometry() ). vd the vertex to be erased true vd was a
vertex from the region-of-interest.

Parameters
----------
vd : vertex_descriptor

Returns: bool";
constexpr const char* Surface_mesh_deformation_preprocess = "Preprocessing function that need to be called each time the region-of-interest or the set of control vertices are changed before calling deform() .

If not already done, deform() first calls this function. Advanced Collects the
vertices not in the region-of-interest that are adjacent to a vertex from the
region-of-interest (these vertices are internally considered as fixed control
vertices). Then assembles and factorizes the Laplacian matrix used in the
function deform() . A modification of the set of control vertices or the
region-of-interest invalidates the preprocessing data. true if successful. A
common reason for failure is that the system is rank deficient, which happens
for example when all the vertices are in the region-of-interest and no control
vertices are set, or if the weighting scheme used features too many zero and
breaks the connectivity information.

Returns: bool";
constexpr const char* Surface_mesh_deformation_set_target_position = "Sets the target position of a control vertex.

vd the control vertex the target position is set target_position the new
target position

Parameters
----------
vd : vertex_descriptor
target_position : const Point &";
constexpr const char* Surface_mesh_deformation_translate = "Updates the target position of vd by applying a translation of vector t .

Vect is a 3D vector class, with Vect(double x,double y, double z) being a
constructor from its Cartesian coordinates and double Vect::operator[](int i)
with i=0,1 or 2 returning its Cartesian coordinates. vd a control vertex t
translation vector is_control_vertex(vd)

Parameters
----------
vd : vertex_descriptor
t : const Vect &";
constexpr const char* Surface_mesh_deformation_translate_1 = "Equivalent to calling the overload taking only one control vertex, for each vertex in the range [begin,end[ .

InputIterator input iterator type with vertex_descriptor as value type Vect is
a 3D vector class, with Vect(double x,double y, double z) being a constructor
from its Cartesian coordinates and double Vect::operator[](int i) with i=0,1
or 2 returning its Cartesian coordinates. begin first iterator of the range of
vertices end past-the-end iterator of the range of vertices t translation
vector

Parameters
----------
begin : InputIterator
end : InputIterator
t : const Vect &";
constexpr const char* Surface_mesh_deformation_rotate = "Updates the target position of vd by applying to its last target position a rotation defined by the quaternion quat , the center of the rotation being the origin translated by to_rotation_center .

Quaternion is a quaternion class with Vect operator*(Quaternion, Vect)
returning the product of a quaternion with a vector Vect is a 3D vector class,
with Vect(double x,double y, double z) being a constructor from its Cartesian
coordinates and double Vect::operator[](int i) with i=0,1 or 2 returning its
Cartesian coordinates. vd a control vertex to_rotation_center the vector to
translate the origin to the center of the rotation quat quaternion of the
rotation is_control_vertex(vd) quad represents a rotation

Parameters
----------
vd : vertex_descriptor
to_rotation_center : const Vect &
quat : const Quaternion &";
constexpr const char* Surface_mesh_deformation_rotate_1 = "Equivalent to calling the overload taking only one control vertex, for each vertex in the range [begin,end[ .

InputIterator input iterator type with vertex_descriptor as value type
Quaternion is a quaternion class with Vect operator*(Quaternion, Vect)
returning the product of a quaternion with a vector Vect is a 3D vector class,
with Vect(double x,double y, double z) being a constructor from its Cartesian
coordinates and double Vect::operator[](int i) with i=0,1 or 2 returning its
Cartesian coordinates. begin first iterator of the range of vertices end
past-the-end iterator of the range of vertices to_rotation_center the vector
to translate the origin to the center of the rotation quat quaternion of the
rotation quad represents a rotation

Parameters
----------
begin : InputIterator
end : InputIterator
to_rotation_center : const Vect &
quat : const Quaternion &";
constexpr const char* Surface_mesh_deformation_target_position = "Returns the target position of a control vertex.

vd a control vertex is_control_vertex(vd)

Parameters
----------
vd : vertex_descriptor

Returns: const Point &";
constexpr const char* Surface_mesh_deformation_deform = "Deforms the region-of-interest according to the deformation algorithm, using the target positions of each control vertex set by using rotate() , translate() , or set_target_position() .

The points associated to each vertex of the input triangle mesh that are
inside the region-of-interest are updated. Nothing happens if preprocess()
returns false . set_iterations(unsigned int iterations) , set_tolerance(double
tolerance) , deform(unsigned int iterations, double tolerance)";
constexpr const char* Surface_mesh_deformation_deform_1 = "Same as deform() but the number of iterations and the tolerance are one-time parameters.

iterations number of iterations for optimization procedure tolerance tolerance
of convergence (see explanations set_tolerance(double tolerance) )

Parameters
----------
iterations : unsigned int
tolerance : double";
constexpr const char* Surface_mesh_deformation_reset = "Resets the points associated to the vertices of the region-of-interest at their initial positions at time of the functor construction or after the last call to overwrite_initial_geometry() .

if the region-of-interest or the set of control vertices have been modified
since the last call to preprocess() , it will be called prior to the reset.";
constexpr const char* Surface_mesh_deformation_overwrite_initial_geometry = "Sets the initial positions of the vertices from the region-of-interest to the current positions.

Calling this function has the same effect as creating a new deformation object
with the current deformed triangle mesh, keeping the region-of-interest and
the set of control vertices. if the region-of-interest or the set of control
vertices have been modified since the last call to preprocess() , it will be
called prior to the overwrite. Advanced This function might have a
non-negligible effect on the result. The Laplacian matrix of the free vertices
and the optimal rotations are computed using the original positions of the
points associated to the vertices. Thus, if a deformed version of the surface
mesh is used as reference, the surface mesh properties the algorithm tries to
preserve are those of an altered version (which are already degraded).";
constexpr const char* Surface_mesh_deformation_iterations = "Gets the default number of iterations (5) or the value passed to the function set_iterations() .

Returns: unsigned int";
constexpr const char* Surface_mesh_deformation_tolerance = "Gets the default tolerance parameter (1e-4) or the value passed to the function set_tolerance() .

Returns: double";
constexpr const char* Surface_mesh_deformation_set_iterations = "Sets the maximum number of iterations ran by deform() .

Parameters
----------
iterations : unsigned int";
constexpr const char* Surface_mesh_deformation_set_tolerance = "Sets the tolerance of the convergence used in deform() .

If tolerance ==0 , no energy based termination criteria is used (preventing to
do the energy computation at each iteration step) tolerance >
$|\\mathrm{energy}(m_i) - \\mathrm{energy}(m_{i-1})| / \\mathrm{energy}(m_i)$
will be used as a termination criterium.

Parameters
----------
tolerance : double";
constexpr const char* Surface_mesh_deformation_roi_vertices = "Returns the range of vertices in the region-of-interest.

Returns: const Roi_vertex_range &";
constexpr const char* Surface_mesh_deformation_is_roi_vertex = "Tests whether a vertex is inside the region-of-interest.

vd the query vertex true if vd has been inserted to (and not erased from) the
region-of-interest.

Parameters
----------
vd : vertex_descriptor

Returns: bool";
constexpr const char* Surface_mesh_deformation_is_control_vertex = "Tests whether a vertex is a control vertex.

vd the query vertex true if vd has been inserted to (and not erased from) the
set of control vertices.

Parameters
----------
vd : vertex_descriptor

Returns: bool";
constexpr const char* Surface_mesh_deformation_triangle_mesh = "Provides access to the triangle mesh being deformed.

Returns: const Triangle_mesh &";
constexpr const char* Surface_mesh_deformation_set_sre_arap_alpha = "Sets the alpha coefficient that determines the weight of the bending term (rotation smoothness) for the SRE-ARAP deformation technique.

The range of values can be from 0 to infinity. When alpha=0, the method
reverts to ARAP. When alpha is increased, neighboring rotations become similar
to each other, where alpha=infinity results in a global rigid transformation
of the ROI. The value of alpha depends on the surface area and shape. Since
alpha is not too sensitive, it can be tweaked in most cases by multiplying it
by powers of 10. The default value for alpha is 0.02.

Parameters
----------
a : double";
constexpr const char* Surface_mesh_deformation_m_triangle_mesh = "Source triangulated surface mesh for modeling.

Returns: Triangle_mesh &";
constexpr const char* Surface_mesh_deformation_original = "original positions of roi (size: ros + boundary_of_ros)

Returns: std::vector< Point >";
constexpr const char* Surface_mesh_deformation_solution = "storing position of ros vertices during iterations (size: ros + boundary_of_ros)

Returns: std::vector< Point >";
constexpr const char* Surface_mesh_deformation_vertex_index_map = "storing indices of all vertices

Returns: Vertex_index_map";
constexpr const char* Surface_mesh_deformation_hedge_index_map = "storing indices of all halfedges

Returns: Hedge_index_map";
constexpr const char* Surface_mesh_deformation_roi = "region of interest

Returns: std::vector< vertex_descriptor >";
constexpr const char* Surface_mesh_deformation_ros = "region of solution, including roi and hard constraints on boundary of roi

Returns: std::vector< vertex_descriptor >";
constexpr const char* Surface_mesh_deformation_ros_id_map = "(size: num vertices)

Returns: std::vector< std::size_t >";
constexpr const char* Surface_mesh_deformation_is_roi_map = "(size: num vertices)

Returns: std::vector< bool >";
constexpr const char* Surface_mesh_deformation_is_ctrl_map = "(size: num vertices)

Returns: std::vector< bool >";
constexpr const char* Surface_mesh_deformation_hedge_weight = "all halfedge weights

Returns: std::vector< double >";
constexpr const char* Surface_mesh_deformation_rot_mtr = "rotation matrices of ros vertices (size: ros)

Returns: std::vector< CR_matrix >";
constexpr const char* Surface_mesh_deformation_m_solver = "linear sparse solver

Returns: Sparse_linear_solver";
constexpr const char* Surface_mesh_deformation_m_iterations = "number of maximal iterations

Returns: unsigned int";
constexpr const char* Surface_mesh_deformation_m_tolerance = "tolerance of convergence

Returns: double";
constexpr const char* Surface_mesh_deformation_need_preprocess_factorization = "is there any need to compute L and factorize

Returns: bool";
constexpr const char* Surface_mesh_deformation_need_preprocess_region_of_solution = "is there any need to compute region of solution

Returns: bool";
constexpr const char* Surface_mesh_deformation_last_preprocess_successful = "stores the result of last call to preprocess()

Returns: bool";
constexpr const char* Surface_mesh_deformation_assign_ros_id_to_one_ring = "Assigns id to one ring neighbor of vd, and also push them into push_vector.

Parameters
----------
vd : vertex_descriptor
next_id : std::size_t &
push_vector : std::vector< vertex_descriptor > &";
constexpr const char* Surface_mesh_deformation_region_of_solution = "Find region of solution, including roi and hard constraints, which is the 1-ring vertices out roi Contains four parts:

if there is any vertex which is no longer roi, set its position back to
original position assign a ros id to vertices inside ros + ros-boundary
reinitialize rotation matrices, if a vertex is previously ros, use its
previous matrix, otherwise set zero reinitialize original, and solution, if a
vertex is previously roi, then use its original position in old_original, else
use point(). In both case we are using \"original position\" of the vertex. same
for solution (it is required to prevent jumping effects)";
constexpr const char* Surface_mesh_deformation_assemble_laplacian_and_factorize = "Assemble Laplacian matrix A of linear system A*X=B.";
constexpr const char* Surface_mesh_deformation_assemble_laplacian_and_factorize_arap = "Construct matrix that corresponds to left-hand side of eq:lap_ber in user manual Also constraints are integrated as eq:lap_energy_system in user manual.";
constexpr const char* Surface_mesh_deformation_assemble_laplacian_and_factorize_spokes_and_rims = "Construct matrix that corresponds to left-hand side of eq:lap_ber_rims in user manual Also constraints are integrated as eq:lap_energy_system in user manual.";
constexpr const char* Surface_mesh_deformation_optimal_rotations = "Local step of iterations, computing optimal rotation matrices.";
constexpr const char* Surface_mesh_deformation_update_solution = "Global step of iterations, updating solution.";
constexpr const char* Surface_mesh_deformation_update_solution_arap = "calculate right-hand side of eq:lap_ber in user manual and solve the system";
constexpr const char* Surface_mesh_deformation_update_solution_spokes_and_rims = "calculate right-hand side of eq:lap_ber_rims in user manual and solve the system";
constexpr const char* Surface_mesh_deformation_assign_solution = "Assign solution to target surface mesh.";
constexpr const char* Surface_mesh_deformation_energy = "Compute modeling energy.

Returns: double";
constexpr const char* Surface_mesh_deformation_sub_to_CR_vector = "p1 - p2, return CR_vector

Parameters
----------
p1 : const Point &
p2 : const Point &

Returns: CR_vector";
constexpr const char* Surface_mesh_deformation_id = "shorthand of get(vertex_index_map, v)

Parameters
----------
vd : vertex_descriptor

Returns: std::size_t";
constexpr const char* Surface_mesh_deformation_id_1 = "shorthand of get(hedge_index_map, e)

Parameters
----------
e : halfedge_descriptor

Returns: std::size_t";

// DeformationClosestRotationTraits_3
constexpr const char* DeformationClosestRotationTraits_3__class__ = "Concept describing the set of requirements for computing a 3x3 rotation matrix that is close to a given 3x3 matrix, together with basic computations used in the class CGAL::Surface_mesh_deformation . The definition of close depends on the model. The fact that some basic operations are hidden behind a function is to allow to benefit from optimizations like expression template from libraries used to implement models of this concept.";

constexpr const char* DeformationClosestRotationTraits_3_Matrix = "3x3 matrix type having a copy constructor and an assignment operator

Returns: unspecified_type";
constexpr const char* DeformationClosestRotationTraits_3_Vector = "3D vector type having a copy constructor

Returns: unspecified_type";
constexpr const char* DeformationClosestRotationTraits_3_add_scalar_t_vector_t_vector_transpose = "Equivalent to result = result + w * (v1*v2^t) .

Parameters
----------
result : Matrix &
w : double
v1 : const Vector &
v2 : const Vector &";
constexpr const char* DeformationClosestRotationTraits_3_add_scalar_t_matrix_p_scalar_t_matrix_t_vector = "Equivalent to result = result + (w1*m1 + w2*m2) * v .

Parameters
----------
result : Vector &
w1 : double
m1 : const Matrix &
w2 : double
m2 : const Matrix &
v : const Vector &";
constexpr const char* DeformationClosestRotationTraits_3_add_scalar_t_matrix_sum_t_vector = "Equivalent to result = result + w1 * (m1 + m2 + m3) * v .

Parameters
----------
result : Vector &
w1 : double
m1 : const Matrix &
m2 : const Matrix &
m3 : const Matrix &
v : const Vector &";
constexpr const char* DeformationClosestRotationTraits_3_squared_norm_vector_scalar_vector_subs = "Returns the squared norm of v1 - m*v2 .

Parameters
----------
v1 : const Vector &
m : const Matrix &
v2 : const Vector &

Returns: double";
constexpr const char* DeformationClosestRotationTraits_3_identity_matrix = "Returns an identity matrix.

Returns: Matrix";
constexpr const char* DeformationClosestRotationTraits_3_zero_matrix = "Returns a matrix initialized with zeros.

Returns: Matrix";
constexpr const char* DeformationClosestRotationTraits_3_vector = "Returns the vector (x,y,z).

Parameters
----------
x : double
y : double
z : double

Returns: Vector";
constexpr const char* DeformationClosestRotationTraits_3_vector_coordinate = "Returns i -th coefficient of a vector.

Parameters
----------
v : const Vector &
i : int

Returns: double";
constexpr const char* DeformationClosestRotationTraits_3_compute_close_rotation = "Computes a rotation matrix close to m and places it into R .

Parameters
----------
m : const Matrix &
R : Matrix &";

constexpr const char* RawPoint_3_RawPoint_3 = "constructor from Cartesian coordinates

Parameters
----------
x : double
y : double
z : double";
constexpr const char* RawPoint_3_operator = "i<=0 && i<3

Parameters
----------
i : int

Returns: double";

// SurfaceMeshDeformationWeights
constexpr const char* SurfaceMeshDeformationWeights__class__ = "Concept describing the set of requirements for calculating weights for halfedges.";

constexpr const char* SurfaceMeshDeformationWeights_Triangle_mesh = "a model of HalfedgeGraph

Returns: unspecified_type";
constexpr const char* SurfaceMeshDeformationWeights_SurfaceMeshDeformationWeights = "Default constructor. Required only if the default parameter is used in the constructor of CGAL::Surface_mesh_deformation .";
constexpr const char* SurfaceMeshDeformationWeights_operator = "Function computing the halfedge weight of halfedge he .

VertexPointMap a model of ReadWritePropertyMap with
boost::graph_traits<Triangle_mesh>::vertex_descriptor as key and a 3D point
from a CGAL Kernel as value type

Parameters
----------
he : boost::graph_traits< Triangle_mesh >::halfedge_descriptor
triangle_mesh : const Triangle_mesh &
vpm : VertexPointMap

Returns: double";

// std
constexpr const char* std__class__ = "STL namespace.";

} // namespace Surface_mesh_deformation
} // namespace docstrings
} // namespace cgalpy

#endif // CGAL_PYTHON_DOCSTRINGS_SURFACE_MESH_DEFORMATION_H
