// AUTO-GENERATED by cpp_docstrings_from_json.py — DO NOT EDIT
// Package: PMP_Remeshing
#ifndef CGAL_PYTHON_DOCSTRINGS_PMP_REMESHING_H
#define CGAL_PYTHON_DOCSTRINGS_PMP_REMESHING_H

namespace cgalpy {
namespace docstrings {
namespace PMP_Remeshing {

// CGAL::Polygon_mesh_processing::Adaptive_sizing_field
constexpr const char* CGAL_Polygon_mesh_processing_Adaptive_sizing_field__class__ = "A sizing field describing variable target mesh edge lengths for CGAL::Polygon_mesh_processing::isotropic_remeshing() .";

constexpr const char* CGAL_Polygon_mesh_processing_Adaptive_sizing_field_Adaptive_sizing_field = "Constructor.

FaceRange range of boost::graph_traits<PolygonMesh>::face_descriptor , model
of Range . Its iterator type is ForwardIterator . NamedParameters a sequence
of Named Parameters tol the error tolerance, used together with curvature to
derive target edge length. Lower tolerance values will result in shorter mesh
edges. edge_len_min_max contains the bounds for minimum and maximum edge
lengths face_range the range of triangular faces defining one or several
surface patches to be remeshed. It should be the same as the range of faces
passed to isotropic_remeshing() . pmesh a polygon mesh with triangulated
surface patches to be remeshed. It should be the same mesh as the one passed
to isotropic_remeshing() . np an optional sequence of Named Parameters among
the ones listed below Optional Named Parameters <button class=\"collapsible\">
vertex_point_map </button> a property map associating points to the vertices
of pmesh Type: a class model of ReadWritePropertyMap with
boost::graph_traits<PolygonMesh>::vertex_descriptor as key type and Point_3 as
value type Default: boost::get(CGAL::vertex_point, pmesh) Extra: If this
parameter is omitted, an internal property map for CGAL::vertex_point_t must
be available in PolygonMesh . <button class=\"collapsible\"> ball_radius
</button> ball_radius parameter passed to interpolated_corrected_curvatures()

Parameters
----------
tol : const FT
edge_len_min_max : const std::pair< FT, FT > &
face_range : const FaceRange &
pmesh : PolygonMesh &
np : const NamedParameters &";













// CGAL::Polygon_mesh_processing::Triangulate_faces::Default_visitor
constexpr const char* CGAL_Polygon_mesh_processing_Triangulate_faces_Default_visitor__class__ = "Default visitor model for the functions triangulate_face() and triangulate_faces() , model of PMPTriangulateFaceVisitor .";

constexpr const char* CGAL_Polygon_mesh_processing_Triangulate_faces_Default_visitor_face_descriptor = "face descriptor type

Returns: boost::graph_traits< PolygonMesh >::face_descriptor";
constexpr const char* CGAL_Polygon_mesh_processing_Triangulate_faces_Default_visitor_vertex_descriptor = "vertex descriptor type

Returns: boost::graph_traits< PolygonMesh >::vertex_descriptor";


// CGAL::Polygon_mesh_processing::Triangulate_polygons::Default_visitor
constexpr const char* CGAL_Polygon_mesh_processing_Triangulate_polygons_Default_visitor__class__ = "Default visitor for the function triangulate_polygons() , model of PMPTriangulateFaceVisitor .";

constexpr const char* CGAL_Polygon_mesh_processing_Triangulate_polygons_Default_visitor_face_descriptor = "face id type, referring to the position of the polygon in the input range

Returns: std::size_t";
constexpr const char* CGAL_Polygon_mesh_processing_Triangulate_polygons_Default_visitor_vertex_descriptor = "vertex id type

Returns: std::size_t";

// CGAL::Polygon_mesh_processing::Uniform_sizing_field
constexpr const char* CGAL_Polygon_mesh_processing_Uniform_sizing_field__class__ = "A sizing field describing a uniform target edge length for CGAL::Polygon_mesh_processing::isotropic_remeshing() .";

constexpr const char* CGAL_Polygon_mesh_processing_Uniform_sizing_field_Uniform_sizing_field = "Constructor.

size the target edge length for isotropic remeshing. If set to 0, the
criterion for edge length is ignored and edges are neither split nor
collapsed. vpmap is the input vertex point map that associates points to the
vertices of the input mesh.

Parameters
----------
size : const FT
vpmap : const VPMap &";
constexpr const char* CGAL_Polygon_mesh_processing_Uniform_sizing_field_Uniform_sizing_field_1 = "Constructor using internal vertex point map of the input polygon mesh.

size the target edge length for isotropic remeshing. If set to 0, the
criterion for edge length is ignored and edges are neither split nor
collapsed. pmesh a polygon mesh with triangulated surface patches to be
remeshed. The default vertex point map of pmesh is used to construct the
class.

Parameters
----------
size : const FT
pmesh : const PolygonMesh &";

constexpr const char* CGAL_Mesh_facet_topology = "The enum Mesh_facet_topology is designed to tell which constraints have to be checked on each surface facet during the mesh refinement process.

CGAL::Mesh_criteria_3<Tr> , CGAL::Mesh_facet_criteria_3<Tr> .";

constexpr const char* CGAL_Polygon_mesh_processing_smooth_mesh = "
Deprecated This function is deprecated since CGAL 5.5,
CGAL::Polygon_mesh_processing::angle_and_area_smoothing() should be used
instead.

Parameters
----------
faces : const FaceRange &
tmesh : TriangleMesh &
np : const NamedParameters &";



// std
constexpr const char* std__class__ = "STL namespace.";

} // namespace PMP_Remeshing
} // namespace docstrings
} // namespace cgalpy

#endif // CGAL_PYTHON_DOCSTRINGS_PMP_REMESHING_H
