// AUTO-GENERATED by cpp_docstrings_from_json.py — DO NOT EDIT
// Package: Periodic_2_triangulation_2
#ifndef CGAL_PYTHON_DOCSTRINGS_PERIODIC_2_TRIANGULATION_2_H
#define CGAL_PYTHON_DOCSTRINGS_PERIODIC_2_TRIANGULATION_2_H

namespace cgalpy {
namespace docstrings {
namespace Periodic_2_triangulation_2 {

// CGAL::Graphics_scene_options_periodic_2_triangulation_2
constexpr const char* Graphics_scene_options_periodic_2_triangulation_2__class__ = "The class Graphics_scene_options_periodic_2_triangulation_2 defines data and methods used to tune the way that the cells of a Periodic_2_triangulation_2 are considered for drawing or to be added into a graphics scene.";

// CGAL::Periodic_2_Delaunay_triangulation_2
constexpr const char* Periodic_2_Delaunay_triangulation_2__class__ = "The class Periodic_2_Delaunay_triangulation_2 represents a Delaunay triangulation in two-dimensional periodic space.";

constexpr const char* Periodic_2_Delaunay_triangulation_2_Periodic_2_Delaunay_triangulation_2 = "Creates an empty periodic Delaunay triangulation dt , with domain as original domain and possibly specifying a traits class traits .

domain is a square.

Parameters
----------
domain : const Iso_rectangle &
traits : const Geom_traits &";
constexpr const char* Periodic_2_Delaunay_triangulation_2_Periodic_2_Delaunay_triangulation_2_1 = "Copy constructor.

Parameters
----------
dt1 : const Periodic_2_Delaunay_triangulation_2 &";
constexpr const char* Periodic_2_Delaunay_triangulation_2_Periodic_2_Delaunay_triangulation_2_2 = "Equivalent to constructing an empty triangulation with the optional domain and traits class arguments and calling insert(first,last) .

The value_type of first and last are Point s lying inside domain and domain is
a square.

Parameters
----------
first : InputIterator
last : InputIterator
domain : const Iso_rectangle &
traits : const Geom_traits &";
constexpr const char* Periodic_2_Delaunay_triangulation_2_insert = "Inserts point p in the triangulation and returns the corresponding vertex.

The optional argument start is used as a starting place for the point
location. p lies in the original domain domain .

Parameters
----------
p : const Point &
start : Face_handle

Returns: Vertex_handle";
constexpr const char* Periodic_2_Delaunay_triangulation_2_insert_1 = "Inserts point p in the triangulation and returns the corresponding vertex.

Similar to the above insert() function, but takes as additional parameter the
return values of a previous location query. See description of
Periodic_2_triangulation_2::locate() . p lies in the original domain domain .

Parameters
----------
p : const Point &
lt : Locate_type
loc : Face_handle
li : int
lj : int

Returns: Vertex_handle";
constexpr const char* Periodic_2_Delaunay_triangulation_2_push_back = "Equivalent to insert(p) .

Parameters
----------
p : const Point &

Returns: Vertex_handle";
constexpr const char* Periodic_2_Delaunay_triangulation_2_insert_2 = "Inserts the points in the iterator range [first, last) .

Returns the number of inserted points. This function uses spatial sorting (cf.
chapter secspatial_sorting) and therefore is not guaranteed to insert the
points following the order of InputIterator . If the third argument
is_large_point_set is set to true a heuristic for optimizing the insertion of
large point sets is applied. The value_type of first and last are Point s and
all points in the range lie inside domain .

Parameters
----------
first : InputIterator
last : InputIterator
is_large_point_set : bool

Returns: std::ptrdiff_t";
constexpr const char* Periodic_2_Delaunay_triangulation_2_remove = "Removes the vertex from the triangulation.

Parameters
----------
v : Vertex_handle";
constexpr const char* Periodic_2_Delaunay_triangulation_2_move_if_no_collision = "if there is not already another vertex placed on p , the triangulation is modified such that the new position of vertex v is p , and v is returned.

Otherwise, the triangulation is not modified and the vertex at point p is
returned. p lies in the original domain domain .

Parameters
----------
v : Vertex_handle
p : const Point &

Returns: Vertex_handle";
constexpr const char* Periodic_2_Delaunay_triangulation_2_move_point = "Moves the point stored in v to p , while preserving the Delaunay property.

This performs an action semantically equivalent to remove(v) followed by
insert(p) , but is supposedly faster to performing these two operations
separately when the point has not moved much. Returns the handle to the new
vertex. p lies in the original domain domain .

Parameters
----------
v : Vertex_handle
p : const Point &

Returns: Vertex_handle";
constexpr const char* Periodic_2_Delaunay_triangulation_2_nearest_vertex = "Returns any nearest vertex to the point p , or the default constructed handle if the triangulation is empty.

The optional argument f is a hint specifying where to start the search. It
always returns a vertex corresponding to a point inside domain even if
computing in a multiply sheeted covering space. f is a face of dt and p lies
in the original domain domain .

Parameters
----------
p : Point
f : Face_handle

Returns: Vertex_handle";
constexpr const char* Periodic_2_Delaunay_triangulation_2_side_of_oriented_circle = "Returns on which side of the circumcircle of face f lies the point p .

The circle is assumed to be counterclockwise oriented, so its positive side
correspond to its bounded side. This predicate is available only if the
corresponding predicates on points is provided in the geometric traits class.

Parameters
----------
f : Face_handle
p : const Point &

Returns: Oriented_side";
constexpr const char* Periodic_2_Delaunay_triangulation_2_get_conflicts_and_boundary = "OutputItFaces is an output iterator with Face_handle as value type.

OutputItBoundaryEdges stands for an output iterator with Edge as value type.
This members function outputs in the container pointed to by fit the faces
which are in conflict with point p i. e. the faces whose circumcircle contains
p . It outputs in the container pointed to by eit the boundary of the zone in
conflict with p . The boundary edges of the conflict zone are output in
counterclockwise order and each edge is described through its incident face
which is not in conflict with p . The function returns in a std::pair the
resulting output iterators. start is in conflict with p and p lies in the
original domain domain .

Parameters
----------
p : const Point &
fit : OutputItFaces
eit : OutputItBoundaryEdges
start : Face_handle

Returns: std::pair< OutputItFaces, OutputItBoundaryEdges >";
constexpr const char* Periodic_2_Delaunay_triangulation_2_get_conflicts = "same as above except that only the faces in conflict with p are output.

The function returns the resulting output iterator. start is in conflict with
p and p lies in the original domain domain .

Parameters
----------
p : const Point &
fit : OutputItFaces
start : Face_handle

Returns: OutputItFaces";
constexpr const char* Periodic_2_Delaunay_triangulation_2_get_boundary_of_conflicts = "OutputItBoundaryEdges stands for an output iterator with Edge as value type.

This function outputs in the container pointed to by eit , the boundary of the
zone in conflict with p . The boundary edges of the conflict zone are output
in counterclockwise order and each edge is described through the incident face
which is not in conflict with p . The function returns the resulting output
iterator. start is in conflict with p and p lies in the original domain domain
.

Parameters
----------
p : const Point &
eit : OutputItBoundaryEdges
start : Face_handle

Returns: OutputItBoundaryEdges";
constexpr const char* Periodic_2_Delaunay_triangulation_2_circumcenter = "Compute the circumcenter of the face pointed to by f.

This function is available only if the corresponding function is provided in
the geometric traits.

Parameters
----------
f : Face_handle

Returns: Point";
constexpr const char* Periodic_2_Delaunay_triangulation_2_dual = "Returns the center of the circle circumscribed to face f .

Parameters
----------
f : const Face_handle &

Returns: Point";
constexpr const char* Periodic_2_Delaunay_triangulation_2_dual_1 = "returns a segment whose endpoints are the duals of both incident faces.

Parameters
----------
e : const Edge &

Returns: Segment";
constexpr const char* Periodic_2_Delaunay_triangulation_2_dual_2 = "Idem.

Parameters
----------
ec : const Edge_circulator &

Returns: Segment";
constexpr const char* Periodic_2_Delaunay_triangulation_2_dual_3 = "Idem.

Parameters
----------
ei : const Edge_iterator &

Returns: Segment";
constexpr const char* Periodic_2_Delaunay_triangulation_2_draw_dual = "output the dual Voronoi diagram to stream ps .

Parameters
----------
ps : Stream &

Returns: Stream &";
constexpr const char* Periodic_2_Delaunay_triangulation_2_side_of_oriented_circle_1 = "Returns the side of p with respect to the circle circumscribing the triangle associated with f .

Periodic copies are checked if necessary.

Parameters
----------
f : Face_handle
p : const Point &
perturb : bool

Returns: Oriented_side";
constexpr const char* Periodic_2_Delaunay_triangulation_2_is_valid = "This is an advanced function.

Advanced Checks the combinatorial validity of the triangulation and the
validity of its geometric embedding (see Section Representation ). Also checks
that all the circumscribing circles of faces are empty. When verbose is set to
true, messages describing the first invalidity encountered are printed.

Parameters
----------
verbose : bool

Returns: bool";
constexpr const char* Periodic_2_Delaunay_triangulation_2_is_valid_1 = "This is an advanced function.

Advanced Checks the combinatorial and geometric validity of the face (see
Section Representation ). Also checks that the circumscribing circle of faces
is empty. When verbose is set to true, messages are printed to give a precise
indication of the kind of invalidity encountered.

Parameters
----------
f : Face_handle
verbose : bool

Returns: bool";

// CGAL::Periodic_2_Delaunay_triangulation_traits_2
constexpr const char* Periodic_2_Delaunay_triangulation_traits_2__class__ = "The class Periodic_2_Delaunay_triangulation_traits_2 is designed as a default traits class for the class Periodic_2_Delaunay_triangulation_2 <Traits, Tds> .";

// CGAL::Periodic_2_offset_2
constexpr const char* Periodic_2_offset_2__class__ = "The class Periodic_2_offset_2 is a model of the concept Periodic_2Offset_2 .";

// CGAL::Periodic_2_triangulation_2
constexpr const char* Periodic_2_triangulation_2__class__ = "The class Periodic_2_triangulation_2 represents a 2-dimensional triangulation of a point set in $ \\mathbb T_c^2$ .";

constexpr const char* Periodic_2_triangulation_2_Geom_traits = "the traits class.

Returns: Traits";
constexpr const char* Periodic_2_triangulation_2_Triangulation_data_structure = "the triangulation data structure type.

Returns: Tds";
constexpr const char* Periodic_2_triangulation_2_Offset = "the offset type.

Returns: Geom_traits::Periodic_2_offset_2";
constexpr const char* Periodic_2_triangulation_2_Iso_rectangle = "the iso rectangle type.

Returns: Geom_traits::Iso_rectangle_2";
constexpr const char* Periodic_2_triangulation_2_Covering_sheets = "integer tuple to store the number of sheets in each direction of space.

Returns: array< int, 2 >";
constexpr const char* Periodic_2_triangulation_2_Point = "the point type.

Returns: Geom_traits::Point_2";
constexpr const char* Periodic_2_triangulation_2_Segment = "the segment type.

Returns: Geom_traits::Segment_2";
constexpr const char* Periodic_2_triangulation_2_Triangle = "the triangle type.

Returns: Geom_traits::Triangle_2";
constexpr const char* Periodic_2_triangulation_2_Periodic_point = "represents a point-offset pair.

The point in the pair lies in the original domain.

Returns: std::pair< Point , Offset >";
constexpr const char* Periodic_2_triangulation_2_Periodic_segment = "a pair of periodic points representing a segment in the periodic domain.

Returns: array< Periodic_point , 2 >";
constexpr const char* Periodic_2_triangulation_2_Periodic_triangle = "a triple of periodic points representing a triangle in the periodic domain.

Returns: array< Periodic_point , 3 >";
constexpr const char* Periodic_2_triangulation_2_Vertex = "the vertex type.

Returns: Tds::Vertex";
constexpr const char* Periodic_2_triangulation_2_Face = "the face type.

Returns: Tds::Face";
constexpr const char* Periodic_2_triangulation_2_Edge = "the edge type.

Returns: Tds::Edge";
constexpr const char* Periodic_2_triangulation_2_size_type = "size type (an unsigned integral type).

Returns: Tds::size_type";
constexpr const char* Periodic_2_triangulation_2_difference_type = "difference type (a signed integral type).

Returns: Tds::difference_type";
constexpr const char* Periodic_2_triangulation_2_Vertex_handle = "handle to a vertex.

Returns: Tds::Vertex_handle";
constexpr const char* Periodic_2_triangulation_2_Face_handle = "handle to a face.

Returns: Tds::Face_handle";
constexpr const char* Periodic_2_triangulation_2_Face_iterator = "iterator over all faces.

Returns: Tds::Face_iterator";
constexpr const char* Periodic_2_triangulation_2_Edge_iterator = "iterator over all edges.

Returns: Tds::Edge_iterator";
constexpr const char* Periodic_2_triangulation_2_Vertex_iterator = "iterator over all vertices.

Returns: Tds::Vertex_iterator";
constexpr const char* Periodic_2_triangulation_2_Unique_vertex_iterator = "iterator over the vertices whose corresponding points lie in the original domain, i.e.

for each set of periodic copies the Unique_vertex_iterator iterates over
exactly one representative.

Returns: unspecified_type";
constexpr const char* Periodic_2_triangulation_2_Face_circulator = "circulator over all faces incident to a given vertex.

Returns: unspecified_type";
constexpr const char* Periodic_2_triangulation_2_Edge_circulator = "circulator over all edges incident to a given vertex.

Returns: unspecified_type";
constexpr const char* Periodic_2_triangulation_2_Vertex_circulator = "circulator over all vertices adjacent to a given vertex.

Returns: unspecified_type";
constexpr const char* Periodic_2_triangulation_2_Periodic_triangle_iterator = "iterator over the triangles corresponding to faces of the triangulation.

Returns: unspecified_type";
constexpr const char* Periodic_2_triangulation_2_Periodic_segment_iterator = "iterator over the segments corresponding to edges of the triangulation.

Returns: unspecified_type";
constexpr const char* Periodic_2_triangulation_2_Periodic_point_iterator = "iterator over the points corresponding to vertices of the triangulation.

Returns: unspecified_type";
constexpr const char* Periodic_2_triangulation_2_Triangulation_2 = "Introduces an empty triangulation t with domain as original domain.

domain is a square.

Parameters
----------
domain : const Iso_rectangle &
traits : const Geom_traits &";
constexpr const char* Periodic_2_triangulation_2_Triangulation_2_1 = "Copy constructor.

All the vertices and faces are duplicated. After the copy, this and tr refer
to different triangulations: if tr is modified, this is not.

Parameters
----------
tr : const Triangulation_2 &";
constexpr const char* Periodic_2_triangulation_2_operator = "Assignment.

All the vertices and faces are duplicated. After the assignment, this and tr
refer to different triangulations: if tr is modified, this is not.

Parameters
----------
tr : const Triangulation_2 < Traits, Tds > &

Returns: Triangulation_2";
constexpr const char* Periodic_2_triangulation_2_swap = "The triangulations tr and this are swapped.

t.swap(tr) should be preferred to this = tr or to t(tr) if tr is deleted after
that.

Parameters
----------
tr : Triangulation_2 &";
constexpr const char* Periodic_2_triangulation_2_clear = "Deletes all faces and vertices resulting in an empty triangulation.";
constexpr const char* Periodic_2_triangulation_2_geom_traits = "Returns a const reference to the triangulation traits object.

Returns: const Geom_traits &";
constexpr const char* Periodic_2_triangulation_2_tds = "Returns a const reference to the triangulation data structure.

Returns: const Triangulation_data_structure_2 &";
constexpr const char* Periodic_2_triangulation_2_domain = "Returns the original domain.

Returns: Iso_rectangle";
constexpr const char* Periodic_2_triangulation_2_number_of_sheets = "Returns the number of sheets of the covering space the triangulation is currently computed in.

Returns: Covering_sheets";
constexpr const char* Periodic_2_triangulation_2_dimension = "Returns the dimension of the convex hull.

The dimension is zero if the triangulation is empty and two otherwise.

Returns: int";
constexpr const char* Periodic_2_triangulation_2_number_of_vertices = "Returns the number of vertices.

Counts all vertices that are representatives of the same point in $ \\mathbb
T_c^2$ as one vertex.

Returns: size_type";
constexpr const char* Periodic_2_triangulation_2_number_of_faces = "Returns the number of faces.

Counts all faces that are representatives of the same triangle in $ \\mathbb
T_c^2$ as one face.

Returns: size_type";
constexpr const char* Periodic_2_triangulation_2_number_of_stored_vertices = "Returns the number of vertices in the data structure.

This is the same as the number of sheets times number_of_vertices() .

Returns: size_type";
constexpr const char* Periodic_2_triangulation_2_number_of_stored_faces = "Returns the number of faces in the data structure.

This is the same as the number of sheets times number_of_faces() .

Returns: size_type";
constexpr const char* Periodic_2_triangulation_2_tds_1 = "This is an advanced function.

Advanced Returns a reference to the triangulation data structure.

Returns: Triangulation_data_structure_2 &";
constexpr const char* Periodic_2_triangulation_2_number_of_edges = "Returns the number of edges.

Counts all edges that are representatives of the same segment in $ \\mathbb
T_c^2$ as one edge.

Returns: size_type";
constexpr const char* Periodic_2_triangulation_2_number_of_stored_edges = "Returns the number of edges in the data structure.

This is the same as the number of sheets times number_of_edges() .

Returns: size_type";
constexpr const char* Periodic_2_triangulation_2_is_extensible_triangulation_in_1_sheet_h1 = "This is an advanced function.

Advanced The current triangulation remains a triangulation in the 1-sheeted
covering space even after adding points if this method returns true . This
test relies on a heuristic, i.e. if it answers false nothing is known. This
test runs in constant-time when not computing in the 1-sheeted covering space.
(This test uses the length of the longest edge in the triangulation as a
criterion [1] .)

Returns: bool";
constexpr const char* Periodic_2_triangulation_2_is_extensible_triangulation_in_1_sheet_h2 = "This is an advanced function.

Advanced The same as is_extensible_triangulation_in_1_sheet_h1() but with a
more precise heuristic, i.e. it might answer true in cases in which
is_extensible_triangulation_in_1_sheet_h1() would not. However, it is much
less time efficient when not computing in the 1-sheeted covering space. (This
test uses the diameter of the largest empty circle in the input point set as a
criterion [1] .)

Returns: bool";
constexpr const char* Periodic_2_triangulation_2_is_triangulation_in_1_sheet = "This is an advanced function.

Advanced Returns true if the current triangulation would still be a
triangulation in the 1-sheeted covering space, returns false otherwise.

Returns: bool";
constexpr const char* Periodic_2_triangulation_2_convert_to_1_sheeted_covering = "This is an advanced function.

Advanced Converts the current triangulation into the same periodic
triangulation in the 1-sheeted covering space. is_triangulation_in_1_sheet()";
constexpr const char* Periodic_2_triangulation_2_convert_to_9_sheeted_covering = "This is an advanced function.

Advanced Converts the current triangulation into the same periodic
triangulation in the 9-sheeted covering space.";
constexpr const char* Periodic_2_triangulation_2_periodic_point = "Returns the periodic point given by vertex v .

If this is represented in the 1-sheeted covering space, the offset is always
zero. Otherwise v can correspond to a periodic copy outside the domain of an
input point.

Parameters
----------
v : const Vertex_handle

Returns: Periodic_point";
constexpr const char* Periodic_2_triangulation_2_periodic_point_1 = "If this is represented in the 1-sheeted covering space, this function returns the periodic point given by the $ i$ -th vertex of face f , that is the point in the original domain and the offset of the vertex in f .

If this is represented in the 9-sheeted covering space, this offset is
possibly added to another offset determining the periodic copy. $ i
\\in\\{0,1,2\\}$

Parameters
----------
f : const Face_handle
i : int

Returns: Periodic_point";
constexpr const char* Periodic_2_triangulation_2_periodic_segment = "Returns the periodic segment formed by the two point-offset pairs corresponding to the two vertices of edge (f,i) .

$ i \\in\\{0,1,2\\}$

Parameters
----------
f : const Face_handle
i : int

Returns: Periodic_segment";
constexpr const char* Periodic_2_triangulation_2_periodic_segment_1 = "Same as the previous method for edge e .

Parameters
----------
e : const Edge &

Returns: Periodic_segment";
constexpr const char* Periodic_2_triangulation_2_periodic_triangle = "Returns the periodic triangle formed by the three point-offset pairs corresponding to the three vertices of facet f .

Parameters
----------
f : const Face_handle

Returns: Periodic_triangle";
constexpr const char* Periodic_2_triangulation_2_point = "Converts the Periodic_point pp (point-offset pair) to the corresponding Point in $ \\mathbb R^2$ .

Parameters
----------
pp : const Periodic_point &

Returns: Point";
constexpr const char* Periodic_2_triangulation_2_segment = "Converts the Periodic_segment s to a Segment .

Parameters
----------
s : const Periodic_segment &

Returns: Segment";
constexpr const char* Periodic_2_triangulation_2_triangle = "Converts the Periodic_triangle this to a Triangle .

Parameters
----------
t : const Periodic_triangle &

Returns: Triangle";
constexpr const char* Periodic_2_triangulation_2_point_1 = "Equivalent to the call t.point(t.periodic_point(fh,i)); .

Parameters
----------
fh : Face_handle
i : int

Returns: Point";
constexpr const char* Periodic_2_triangulation_2_point_2 = "Equivalent to the call t.point(t.periodic_point(v)); .

Parameters
----------
v : Vertex_handle

Returns: Point";
constexpr const char* Periodic_2_triangulation_2_segment_1 = "Equivalent to the call t.segment(t.periodic_segment(f,i)); .

Parameters
----------
f : Face_handle
i : int

Returns: Segment";
constexpr const char* Periodic_2_triangulation_2_segment_2 = "Equivalent to the call t.segment(t.periodic_segment(e)); .

Parameters
----------
e : const Edge &

Returns: Segment";
constexpr const char* Periodic_2_triangulation_2_segment_3 = "Equivalent to the call t.segment(t.periodic_segment(ec->first, ec->second)); .

Parameters
----------
ec : const Edge_circulator &

Returns: Segment";
constexpr const char* Periodic_2_triangulation_2_segment_4 = "Equivalent to the call t.segment(t.periodic_segment(ei->first, ei->second)); .

Parameters
----------
ei : const Edge_iterator &

Returns: Segment";
constexpr const char* Periodic_2_triangulation_2_triangle_1 = "Equivalent to the call t.triangle(t.periodic_triangle(f)); .

Parameters
----------
f : Face_handle

Returns: Triangle";
constexpr const char* Periodic_2_triangulation_2_is_edge = "true if there is an edge having va and vb as vertices.

Parameters
----------
va : Vertex_handle
vb : Vertex_handle

Returns: bool";
constexpr const char* Periodic_2_triangulation_2_is_edge_1 = "as above.

In addition, if true is returned, the edge with vertices va and vb is the edge
e=(fr,i) where fr is a handle to the face incident to e and on the right side
of e oriented from va to vb .

Parameters
----------
va : Vertex_handle
vb : Vertex_handle
fr : Face_handle &
i : int &

Returns: bool";
constexpr const char* Periodic_2_triangulation_2_is_face = "true if there is a face having v1 , v2 and v3 as vertices.

Parameters
----------
v1 : Vertex_handle
v2 : Vertex_handle
v3 : Vertex_handle

Returns: bool";
constexpr const char* Periodic_2_triangulation_2_is_face_1 = "as above.

In addition, if true is returned, fr is a handle to the face with v1 , v2 and
v3 as vertices.

Parameters
----------
v1 : Vertex_handle
v2 : Vertex_handle
v3 : Vertex_handle
fr : Face_handle &

Returns: bool";
constexpr const char* Periodic_2_triangulation_2_locate = "If the triangulation is not empty, a face that contains the query in its interior or on its boundary is returned.

If the triangulation is empty, the default constructed Face_handle is
returned.

Parameters
----------
query : const Point &
f : Face_handle

Returns: Face_handle";
constexpr const char* Periodic_2_triangulation_2_locate_1 = "Same as above.

Additionally, the parameters lt and li describe where the query point is
located. The variable lt is set to the locate type of the query. If lt==
VERTEX the variable li is set to the index of the vertex, and if lt== EDGE li
is set to the index of the vertex opposite to the edge. Be careful that li has
no meaning when the query type is FACE or when the triangulation is $ 0$
-dimensional.

Parameters
----------
query : const Point &
lt : Locate_type &
li : int &
h : Face_handle

Returns: Face_handle";
constexpr const char* Periodic_2_triangulation_2_oriented_side = "Returns on which side of the oriented boundary of f the point p lies.

Parameters
----------
f : Face_handle
p : const Point &

Returns: Oriented_side";
constexpr const char* Periodic_2_triangulation_2_vertices_begin = "Starts at an arbitrary vertex.

Returns: Vertex_iterator";
constexpr const char* Periodic_2_triangulation_2_vertices_end = "Past-the-end iterator.

Returns: Vertex_iterator";
constexpr const char* Periodic_2_triangulation_2_edges_begin = "Starts at an arbitrary edge.

Returns: Edge_iterator";
constexpr const char* Periodic_2_triangulation_2_edges_end = "Past-the-end iterator.

Returns: Edge_iterator";
constexpr const char* Periodic_2_triangulation_2_faces_begin = "Starts at an arbitrary face.

Returns: Face_iterator";
constexpr const char* Periodic_2_triangulation_2_faces_end = "Past-the-end iterator.

Returns: Face_iterator";
constexpr const char* Periodic_2_triangulation_2_periodic_points_begin = "Iterates over the points of the triangulation.

Its behavior is defined by the Iterator_type it as described on
CGAL::Periodic_2_triangulation_2::Iterator_type .

Parameters
----------
it : Iterator_type

Returns: Periodic_point_iterator";
constexpr const char* Periodic_2_triangulation_2_periodic_points_end = "Past-the-end iterator.

Note that to match another Periodic_point_iterator both must have the same
Iterator_type it .

Parameters
----------
it : Iterator_type

Returns: Periodic_point_iterator";
constexpr const char* Periodic_2_triangulation_2_periodic_segments_begin = "Iterates over the segments of the triangulation.

Its behavior is defined by the Iterator_type it as described on
CGAL::Periodic_2_triangulation_2::Iterator_type .

Parameters
----------
it : Iterator_type

Returns: Periodic_segment_iterator";
constexpr const char* Periodic_2_triangulation_2_periodic_segments_end = "Past-the-end iterator.

Note that to match another Periodic_segment_iterator both must have the same
Iterator_type it .

Parameters
----------
it : Iterator_type

Returns: Periodic_segment_iterator";
constexpr const char* Periodic_2_triangulation_2_periodic_triangles_begin = "Iterates over the triangles of the triangulation.

Its behavior is defined by the Iterator_type it as described on
CGAL::Periodic_2_triangulation_2::Iterator_type .

Parameters
----------
it : Iterator_type

Returns: Periodic_triangle_iterator";
constexpr const char* Periodic_2_triangulation_2_periodic_triangles_end = "Past-the-end iterator.

Note that to match another Periodic_triangle_iterator both must have the same
Iterator_type it .

Parameters
----------
it : Iterator_type

Returns: Periodic_triangle_iterator";
constexpr const char* Periodic_2_triangulation_2_incident_faces = "Starts at an arbitrary face incident to v .

Parameters
----------
v : Vertex_handle

Returns: Face_circulator";
constexpr const char* Periodic_2_triangulation_2_incident_faces_1 = "Starts at face f .

Face f is incident to vertex v .

Parameters
----------
v : Vertex_handle
f : Face_handle

Returns: Face_circulator";
constexpr const char* Periodic_2_triangulation_2_incident_edges = "Starts at an arbitrary edge incident to v .

Parameters
----------
v : Vertex_handle

Returns: Edge_circulator";
constexpr const char* Periodic_2_triangulation_2_incident_edges_1 = "Starts at the first edge of f incident to v , in counterclockwise order around v .

Face f is incident to vertex v .

Parameters
----------
v : Vertex_handle
f : Face_handle

Returns: Edge_circulator";
constexpr const char* Periodic_2_triangulation_2_adjacent_vertices = "Starts at an arbitrary vertex adjacent to v .

Parameters
----------
v : Vertex_handle

Returns: Vertex_circulator";
constexpr const char* Periodic_2_triangulation_2_adjacent_vertices_1 = "Starts at the first vertex of f adjacent to v in counterclockwise order around v .

Face f is incident to vertex v .

Parameters
----------
v : Vertex_handle
f : Face_handle

Returns: Vertex_circulator";
constexpr const char* Periodic_2_triangulation_2_mirror_vertex = "returns the vertex of the $ i^{th}$ neighbor of f that is opposite to f .

$ 0 \\leq i \\leq 2$ .

Parameters
----------
f : Face_handle
i : int

Returns: Vertex_handle";
constexpr const char* Periodic_2_triangulation_2_mirror_index = "returns the index of f in its $ i^{th}$ neighbor.

$0 \\leq i \\leq 2$ .

Parameters
----------
f : Face_handle
i : int

Returns: int";
constexpr const char* Periodic_2_triangulation_2_insert_first = "This is an advanced function.

Advanced Inserts the first vertex.

Parameters
----------
p : const Point &

Returns: Vertex_handle";
constexpr const char* Periodic_2_triangulation_2_insert_in_face = "This is an advanced function.

Advanced Inserts vertex v in face f . Face f is modified, two new faces are
created. If the triangulation contains periodic copies, a point is inserted in
all periodic copies. The point in vertex v lies inside face f .

Parameters
----------
p : const Point &
f : Face_handle

Returns: Vertex_handle";
constexpr const char* Periodic_2_triangulation_2_remove_degree_3 = "This is an advanced function.

Advanced Removes a vertex of degree three. Two of the incident faces are
destroyed, the third one is modified. Vertex v is a vertex with degree three.

Parameters
----------
v : Vertex_handle";
constexpr const char* Periodic_2_triangulation_2_remove_first = "This is an advanced function.

Advanced Removes the unique vertex in the triangulation.

Parameters
----------
v : Vertex_handle";
constexpr const char* Periodic_2_triangulation_2_star_hole = "This is an advanced function.

Advanced creates a new vertex v and use it to star the hole whose boundary is
described by the sequence of edges [edge_begin, edge_end] . Returns a handle
to the new vertex. The triangulation is a triangulation of 1 sheet

Parameters
----------
p : Point
edge_begin : EdgeIt
edge_end : EdgeIt

Returns: Vertex_handle";
constexpr const char* Periodic_2_triangulation_2_star_hole_1 = "This is an advanced function.

Advanced same as above, except that the algorithm first recycles faces in the
sequence [face_begin, face_end] and create new ones only when the sequence is
exhausted. The triangulation is a triangulation of 1 sheet

Parameters
----------
p : Point
edge_begin : EdgeIt
edge_end : EdgeIt
face_begin : FaceIt
face_end : FaceIt

Returns: Vertex_handle";
constexpr const char* Periodic_2_triangulation_2_set_domain = "This is an advanced function.

Advanced Changes the domain. Note that this function calls clear() , i.e., it
erases the existing triangulation.

Parameters
----------
dom : const Iso_rectangle";
constexpr const char* Periodic_2_triangulation_2_ccw = "Returns $ i+1$ modulo 3.

$0 \\leq i \\leq 2$ .

Parameters
----------
i : int

Returns: int";
constexpr const char* Periodic_2_triangulation_2_cw = "Returns $ i+2$ modulo 3.

$0 \\leq i \\leq 2$ .

Parameters
----------
i : int

Returns: int";
constexpr const char* Periodic_2_triangulation_2_degree = "Returns the degree of the vertex v .

Parameters
----------
v : Vertex_handle

Returns: size_t";
constexpr const char* Periodic_2_triangulation_2_is_valid = "This is an advanced function.

Advanced Checks the combinatorial validity of the triangulation and also the
validity of its geometric embedding. This method is mainly a debugging help
for the users of advanced features.

Parameters
----------
verbose : bool
level : int

Returns: bool";
constexpr const char* Periodic_2_triangulation_2_Iterator_type = "The enum Iterator_type is defined by Periodic_2_triangulation_2 to specify the behavior of geometric iterators.";
constexpr const char* Periodic_2_triangulation_2_Locate_type = "The enum Locate_type is defined by Periodic_2_triangulation_2 to specify which case occurs when locating a point in the triangulation.

If the triangulation does not contain any points EMPTY is returned.";
constexpr const char* Periodic_2_triangulation_2_operator_1 = "Writes the triangulation t into the stream os .

The output operator must be defined for Point .

Parameters
----------
os : ostream &
t : const Periodic_2_triangulation_2 < Traits, Tds > &

Returns: ostream &";
constexpr const char* Periodic_2_triangulation_2_operator_2 = "Reads a triangulation from stream is and assigns it to t .

The input operator must be defined for Point .

Parameters
----------
is : istream &
t : Triangulation_2 < Traits, Tds > &

Returns: istream &";

// CGAL::Periodic_2_triangulation_face_base_2
constexpr const char* Periodic_2_triangulation_face_base_2__class__ = "The class Periodic_2_triangulation_face_base_2 is a model of the concept Periodic_2TriangulationFaceBase_2 to be used by Triangulation_data_structure_2 to represent faces of a periodic triangulation.";

// CGAL::Periodic_2_triangulation_hierarchy_2
constexpr const char* Periodic_2_triangulation_hierarchy_2__class__ = "The class Periodic_2_triangulation_hierarchy_2 implements a triangulation augmented with a data structure which allows fast point location queries.";

// CGAL::Periodic_2_triangulation_traits_2
constexpr const char* Periodic_2_triangulation_traits_2__class__ = "The class Periodic_2_triangulation_traits_2 is designed as a default traits class for the class CGAL::Periodic_2_triangulation_2 < Periodic_2TriangulationTraits_2 ,TriangulationDataStructure_2> .";

// CGAL::Periodic_2_triangulation_vertex_base_2
constexpr const char* Periodic_2_triangulation_vertex_base_2__class__ = "The class Periodic_2_triangulation_vertex_base_2 is a model of the concept Periodic_2TriangulationVertexBase_2 to be used by Triangulation_data_structure_2 to represent vertices of a periodic triangulation.";

// GraphicsSceneOptionsPeriodic2Triangulation2
constexpr const char* GraphicsSceneOptionsPeriodic2Triangulation2__class__ = "The concept GraphicsSceneOptionsPeriodic2Triangulation2 defines data and methods used to tune the way that the cells of a Periodic_2_triangulation_2 are considered for drawing or to be added into a graphics scene.";

constexpr const char* GraphicsSceneOptionsPeriodic2Triangulation2_draw_domain = "returns true if the domain of the Periodic_2_triangulation_2 must be drawn, false otherwise.

Returns false by default.

Returns: bool";
constexpr const char* GraphicsSceneOptionsPeriodic2Triangulation2_draw_domain_1 = "sets the draw domain value to b .

Parameters
----------
b : bool";
constexpr const char* GraphicsSceneOptionsPeriodic2Triangulation2_toggle_draw_domain = "toggles the draw domain value.";
constexpr const char* GraphicsSceneOptionsPeriodic2Triangulation2_display_type = "returns the type of the display (STORED, UNIQUE, STORED_COVER_DOMAIN or UNIQUE_COVER_DOMAIN).

Returns: DS::Iterator_type";
constexpr const char* GraphicsSceneOptionsPeriodic2Triangulation2_increase_display_type = "set the display type to the next type (in the ordered circular list STORED, UNIQUE, STORED_COVER_DOMAIN, UNIQUE_COVER_DOMAIN).";
constexpr const char* GraphicsSceneOptionsPeriodic2Triangulation2_domain_color = "returns the color used to draw the domain.

Returns: const CGAL::IO::Color &";

// Periodic_2DelaunayTriangulationTraits_2
constexpr const char* Periodic_2DelaunayTriangulationTraits_2__class__ = "The concept Periodic_2DelaunayTriangulationTraits_2 is the first template parameter of the class CGAL::Periodic_2_Delaunay_triangulation_2 . It refines the concepts Periodic_2TriangulationTraits_2 and DelaunayTriangulationTraits_2 . It redefines the geometric objects, predicates and constructions to work with point-offset pairs. In most cases the offsets will be (0,0) and the predicates from DelaunayTriangulationTraits_2 can be used directly. For efficiency reasons we maintain for each functor the version without offsets.";

constexpr const char* Periodic_2DelaunayTriangulationTraits_2_Side_of_oriented_circle_2 = "Predicate object.

Must provide the operators Oriented_side operator()(Point p, Point q, Point r,
Point s) which takes four points $ p, q, r, s$ as arguments and returns
ON_POSITIVE_SIDE , ON_NEGATIVE_SIDE or, ON_ORIENTED_BOUNDARY according to the
position of points s with respect to the oriented circle through $ p,q$ and $
r$ and Oriented_side operator()( Point p, Point q, Point r, Point s,
Periodic_2_offset_2 o_p, Periodic_2_offset_2 o_q Periodic_2_offset_2 o_r,
Periodic_2_offset_2 o_s) which takes four points $ (p, o_p), (q, o_q), (r,
o_r), (s, o_s)$ as arguments and returns ON_POSITIVE_SIDE , ON_NEGATIVE_SIDE
or, ON_ORIENTED_BOUNDARY according to the position of points (s, o_s) with
respect to the oriented circle through (p, o_p), (q, o_q) and (r, o_r) . This
type is required only if the function side_of_oriented_circle(Face_handle f,
Point p) is called.

Returns: unspecified_type";
constexpr const char* Periodic_2DelaunayTriangulationTraits_2_Construct_circumcenter_2 = "Constructor object.

Provides the operators: Point operator()(Point p, Point q, Point r) which
returns the circumcenter of the three points p, q and r . Point
operator()(Point p, Point q, Point r, Periodic_2_offset_2 o_p,
Periodic_2_offset_2 o_q Periodic_2_offset_2 o_r) which returns the
circumcenter of the three points (p, o_p), (q, o_q) and (r, o_r) . This type
is required only if the function Point circumcenter(Face_handle f) is called.

Returns: unspecified_type";
constexpr const char* Periodic_2DelaunayTriangulationTraits_2_Compare_distance_2 = "Predicate type.

Provides the operators: Comparison_result operator()(Point_2 p, Point_2 q,
Point_2 r) which returns SMALLER , EQUAL or LARGER according to the distance
between p and q being smaller, equal or larger than the distance between p and
r. Comparison_result operator()(Point_2 p, Point_2 q, Point_2 r,
Periodic_2_offset_2 o_p, Periodic_2_offset_2 o_q Periodic_2_offset_2 o_r)
which returns SMALLER , EQUAL or LARGER according to the distance between (p,
o_p) , and (q, o_q) being smaller, equal or larger than the distance between
(p, o_p) and (r, o_r) . This type is only require if nearest_vertex queries
are issued.

Returns: unspecified_type";
constexpr const char* Periodic_2DelaunayTriangulationTraits_2_side_of_oriented_circle_2_object = "Required only if side_of_oriented_circle is called called.

Returns: Side_of_oriented_circle_2";
constexpr const char* Periodic_2DelaunayTriangulationTraits_2_construct_circumcenter_2_object = "Required only if circumcenter is called.

Returns: Construct_circumcenter_2";
constexpr const char* Periodic_2DelaunayTriangulationTraits_2_compare_distance_2_object = "Required only if compare_distance is called.

Returns: Compare_distance_2";

// Periodic_2Offset_2
constexpr const char* Periodic_2Offset_2__class__ = "The concept Periodic_2Offset_2 describes a two-/dimensional integer vector with some specialized access functions and operations.";

constexpr const char* Periodic_2Offset_2_Periodic_2Offset_2 = "Default constructor.";
constexpr const char* Periodic_2Offset_2_Periodic_2Offset_2_1 = "Constructs the offset (x,y).

Parameters
----------
x : int
y : int";
constexpr const char* Periodic_2Offset_2_operator = "Return the vector sum of this and o .

Parameters
----------
o : const Periodic_2Offset_2 &

Returns: Periodic_2Offset_2";
constexpr const char* Periodic_2Offset_2_operator_1 = "Return the vector difference of this and o .

Parameters
----------
o : const Periodic_2Offset_2 &

Returns: Periodic_2Offset_2";
constexpr const char* Periodic_2Offset_2_operator_2 = "Return the negative vector of this .

Returns: Periodic_2Offset_2";
constexpr const char* Periodic_2Offset_2_operator_3 = "Add o to this using vector addition.

Parameters
----------
o : const Periodic_2Offset_2 &";
constexpr const char* Periodic_2Offset_2_operator_4 = "Subtract o from this using vector subtraction.

Parameters
----------
o : const Periodic_2Offset_2 &";
constexpr const char* Periodic_2Offset_2_operator_5 = "Return true if o and this represent the same vector.

Parameters
----------
o : const Periodic_2Offset_2 &

Returns: bool";
constexpr const char* Periodic_2Offset_2_operator_6 = "Return true if o and this do not represent the same vector.

Parameters
----------
o : const Periodic_2Offset_2 &

Returns: bool";
constexpr const char* Periodic_2Offset_2_operator_7 = "Compare this and o lexicographically.

Parameters
----------
o : const Periodic_2Offset_2 &

Returns: bool";
constexpr const char* Periodic_2Offset_2_operator_8 = "Return the $ i$ -th entry of this .

$ i\\in\\{0,1\\}$

Parameters
----------
i : int

Returns: int";
constexpr const char* Periodic_2Offset_2_x = "Return the $ x$ -entry of this .

Returns: int";
constexpr const char* Periodic_2Offset_2_y = "Return the $ y$ -entry of this .

Returns: int";
constexpr const char* Periodic_2Offset_2_is_null = "Returns true if this is equal to (0,0).

Returns: bool";
constexpr const char* Periodic_2Offset_2_is_zero = "Returns true if this is equal to (0,0).

Returns: bool";
constexpr const char* Periodic_2Offset_2_operator_9 = "Inputs an offset from is .

Parameters
----------
is : istream &
off : Periodic_2Offset_2 &

Returns: istream &";
constexpr const char* Periodic_2Offset_2_operator_10 = "Outputs an offset from os .

Parameters
----------
os : ostream &
off : Periodic_2Offset_2 &

Returns: ostream &";

// Periodic_2TriangulationFaceBase_2
constexpr const char* Periodic_2TriangulationFaceBase_2__class__ = "At the base level (see Section Section_2D_Triangulations_Software_Design), a face stores handles to its four vertices and to its four neighbor faces. The vertices and neighbors are indexed 0, 1 and 2. Neighbor $ i$ lies opposite to vertex $ i$ .";

constexpr const char* Periodic_2TriangulationFaceBase_2_offset = "Returns the offset of vertex i .

$ i \\in\\{0, 1, 2\\}$ .

Parameters
----------
i : int

Returns: int";
constexpr const char* Periodic_2TriangulationFaceBase_2_has_zero_offsets = "Returns true if the offset of vertex i is zero for $ i \\in\\{0, 1, 2\\}$ .

Returns: bool";
constexpr const char* Periodic_2TriangulationFaceBase_2_set_offsets = "Sets the vertex offsets according to off0 to off2 .

Parameters
----------
off0 : int
off1 : int
off2 : int";

// Periodic_2TriangulationTraits_2
constexpr const char* Periodic_2TriangulationTraits_2__class__ = "The concept Periodic_2TriangulationTraits_2 is the first template parameter of the classes CGAL::Periodic_2_triangulation_2 <Traits, Tds> . This concept provides the types of the geometric primitives used in the triangulation and some function object types for the required predicates on those primitives.";

constexpr const char* Periodic_2TriangulationTraits_2_Point_2 = "The point type.

It must be a model of Kernel::Point_2 .

Returns: unspecified_type";
constexpr const char* Periodic_2TriangulationTraits_2_Segment_2 = "The segment type.

It must be a model of Kernel::Segment_2 .

Returns: unspecified_type";
constexpr const char* Periodic_2TriangulationTraits_2_Vector_2 = "The vector type.

It must be a model of Kernel::Vector_2 .

Returns: unspecified_type";
constexpr const char* Periodic_2TriangulationTraits_2_Triangle_2 = "The triangle type.

It must be a model of Kernel::Triangle_2 .

Returns: unspecified_type";
constexpr const char* Periodic_2TriangulationTraits_2_Iso_rectangle_2 = "A type representing an axis-aligned rectangle.

It must be a model of Kernel::IsoRectangle_2 .

Returns: unspecified_type";
constexpr const char* Periodic_2TriangulationTraits_2_Periodic_2_offset_2 = "The offset type.

It must be a model of the concept Periodic_2Offset_2 .

Returns: unspecified_type";
constexpr const char* Periodic_2TriangulationTraits_2_Compare_x_2 = "A predicate object that must provide the function operators.

Comparison_result operator()(Point_2 p, Point_2 q) , which returns EQUAL if
the $ x$ -coordinates of the two points are equal and Comparison_result
operator()(Point_2 p, Point_2 q, Periodic_2_offset_2 o_p, Periodic_2_offset_2
o_q) , which returns EQUAL if the $ x$ -coordinates and $ x$ -offsets of the
two point-offset pairs are equal. Otherwise it must return a consistent order
for any two points. p , q lie inside the domain.

Returns: unspecified_type";
constexpr const char* Periodic_2TriangulationTraits_2_Compare_y_2 = "A predicate object that must provide the function operators.

Comparison_result operator()(Point_2 p, Point_2 q) , which returns EQUAL if
the $ y$ -coordinates of the two points are equal and Comparison_result
operator()(Point_2 p, Point_2 q, Periodic_2_offset_2 o_p, Periodic_2_offset_2
o_q) , which returns EQUAL if the $ y$ -coordinates and $ y$ -offsets of the
two point-offset pairs are equal. Otherwise it must return a consistent order
for any two points. p , q lie inside the domain.

Returns: unspecified_type";
constexpr const char* Periodic_2TriangulationTraits_2_Less_x_2 = "Predicate object.

Provides the operators: bool operator()(Point p, Point q) and bool
operator()(Point p, Point q, Periodic_2_offset_2 o_p, Periodic_2_offset_2 o_q)
which returns true if p is before q according to the $ x$ -ordering of points.
This predicate is only necessary if the insert function with a range of points
(using Hilbert sorting) is used.

Returns: unspecified_type";
constexpr const char* Periodic_2TriangulationTraits_2_Less_y_2 = "Predicate object.

Provides the operators: bool operator()(Point p, Point q) and bool
operator()(Point p, Point q, Periodic_2_offset_2 o_p, Periodic_2_offset_2 o_q)
which returns true if p is before q according to the $ y$ -ordering of points.
This predicate is only necessary if the insert function with a range of points
(using Hilbert sorting) is used.

Returns: unspecified_type";
constexpr const char* Periodic_2TriangulationTraits_2_Orientation_2 = "A predicate object that must provide the function operators.

Orientation operator()(Point_2 p, Point_2 q, Point_2 r) , which returns
LEFT_TURN , RIGHT_TURN or COLLINEAR depending on $ r$ being, with respect to
the oriented line pq , on the left side, on the right side or on the line. and
Orientation operator()(Point_2 p, Point_2 q, Point_2 r, Periodic_2_offset_2
o_p, Periodic_2_offset_2 o_q, Periodic_2_offset_2 o_r) , which returns
LEFT_TURN , RIGHT_TURN or COLLINEAR depending on (r,o_r) being, with respect
to the oriented line defined by (p,o_p)(q,o_q) on the left side, on the right
side or on the line.

Returns: unspecified_type";
constexpr const char* Periodic_2TriangulationTraits_2_Construct_point_2 = "A constructor object for Point_2 .

Provides: Point_2 operator()(Point_2 p,Periodic_2_offset_2 p_o) , which
constructs a point from a point-offset pair. p lies inside the domain.

Returns: unspecified_type";
constexpr const char* Periodic_2TriangulationTraits_2_Construct_segment_2 = "A constructor object for Segment_2 .

Provides: Segment_2 operator()(Point_2 p,Point_2 q) , which constructs a
segment from two points and Segment_2 operator()(Point_2 p,Point_2 q,
Periodic_2_offset_2 o_p, Periodic_2_offset_2 o_q) , which constructs a segment
from the points (p,o_p) and (q,o_q) .

Returns: unspecified_type";
constexpr const char* Periodic_2TriangulationTraits_2_Construct_triangle_2 = "A constructor object for Triangle_2 .

Provides: Triangle_2 operator()(Point_2 p,Point_2 q,Point_2 r ) , which
constructs a triangle from three points and Triangle_2 operator()(Point_2
p,Point_2 q,Point_2 r, Periodic_2_offset_2 o_p, Periodic_2_offset_2 o_q,
Periodic_2_offset_2 o_r) , which constructs a triangle from the three points
(p,o_p) , (q,o_q) and (r,o_r) .

Returns: unspecified_type";
constexpr const char* Periodic_2TriangulationTraits_2_Periodic_2_triangulation_traits_2 = "Default constructor.";
constexpr const char* Periodic_2TriangulationTraits_2_Periodic_2_triangulation_traits_2_1 = "Copy constructor.

Parameters
----------
tr : const Periodic_2_triangulation_traits_2 &";
constexpr const char* Periodic_2TriangulationTraits_2_set_domain = "Sets the fundamental domain.

This is necessary to evaluate predicates correctly. domain represents a
square.

Parameters
----------
domain : Iso_rectangle_2";
constexpr const char* Periodic_2TriangulationTraits_2_get_domain = "Returns the fundamental domain.

Returns: Iso_rectangle_2";

// Periodic_2TriangulationVertexBase_2
constexpr const char* Periodic_2TriangulationVertexBase_2__class__ = "A refinement of the concept TriangulationVertexBase_2 which adds an API for offset.";

constexpr const char* Periodic_2TriangulationVertexBase_2_Periodic_2_offset_2 = "A model of the concept Periodic_2Offset_2 .

Returns: unspecified_type";
constexpr const char* Periodic_2TriangulationVertexBase_2_offset = "Returns the offset stored in the vertex.

Returns: Periodic_2_offset_2";
constexpr const char* Periodic_2TriangulationVertexBase_2_get_offset_flag = "Returns true if the offset has been set, false otherwise.

Returns: bool";
constexpr const char* Periodic_2TriangulationVertexBase_2_set_offset = "Sets the offset and sets the offset flag to true .

Parameters
----------
o : Periodic_2_offset_2";
constexpr const char* Periodic_2TriangulationVertexBase_2_clear_offset = "Sets the offset flag to false and clears the offset.";

constexpr const char* Periodic_2_triangulation_2_operator_3 = "Writes the triangulation t into the stream os .

The output operator must be defined for Point .

Parameters
----------
os : ostream &
t : const Periodic_2_triangulation_2 < Traits, Tds > &

Returns: ostream &";
constexpr const char* Periodic_2_triangulation_2_operator_4 = "Reads a triangulation from stream is and assigns it to t .

The input operator must be defined for Point .

Parameters
----------
is : istream &
t : Triangulation_2< Traits, Tds > &

Returns: istream &";

// std
constexpr const char* std__class__ = "STL namespace.";

} // namespace Periodic_2_triangulation_2
} // namespace docstrings
} // namespace cgalpy

#endif // CGAL_PYTHON_DOCSTRINGS_PERIODIC_2_TRIANGULATION_2_H
