// AUTO-GENERATED by cpp_docstrings_from_json.py — DO NOT EDIT
// Package: Boolean_set_operations_2
#ifndef CGAL_PYTHON_DOCSTRINGS_BOOLEAN_SET_OPERATIONS_2_H
#define CGAL_PYTHON_DOCSTRINGS_BOOLEAN_SET_OPERATIONS_2_H

namespace cgalpy {
namespace docstrings {
namespace Boolean_set_operations_2 {

// AosDirectionalXMonotoneTraits_2
constexpr const char* AosDirectionalXMonotoneTraits_2__class__ = "This concept refines the basic arrangement $ x$ -monotone traits concept. A model of this concept is able to handle directed $ x$ -monotone curves that intersect in their interior. Namely, an instance of the X_monotone_curve_2 type defined by a model of the concept AosXMonotoneTraits_2 is only required to have a left (lexicographically smaller) endpoint and a right endpoint. If the traits class is also a model of AosDirectionalXMonotoneTraits_2 , the $ x$ -monotone curve is also required to have a direction, namely one of these two endpoint serves as its source and the other as its target .";

constexpr const char* AosDirectionalXMonotoneTraits_2_Compare_endpoints_xy_2 = "models the concept ArrDirectionalTraits::CompareEndpointsXy_2 .

Returns: unspecified_type";
constexpr const char* AosDirectionalXMonotoneTraits_2_Construct_opposite_2 = "models the concept ArrDirectionalTraits::ConstructOpposite_2 .

Returns: unspecified_type";
constexpr const char* AosDirectionalXMonotoneTraits_2_Intersect_2 = "models the concept ArrDirectionalTraits::Intersect_2 .

Returns: unspecified_type";
constexpr const char* AosDirectionalXMonotoneTraits_2_Split_2 = "models the concept ArrDirectionalTraits::Split_2 .

Returns: unspecified_type";
constexpr const char* AosDirectionalXMonotoneTraits_2_Are_mergeable_2 = "models the concept ArrDirectionalTraits::AreMergeable_2 .

Returns: unspecified_type";
constexpr const char* AosDirectionalXMonotoneTraits_2_Merge_2 = "models the concept ArrDirectionalTraits::Merge_2 .

Returns: unspecified_type";
constexpr const char* AosDirectionalXMonotoneTraits_2_AosDirectionalXMonotoneTraits_2 = "default constructor.";
constexpr const char* AosDirectionalXMonotoneTraits_2_AosDirectionalXMonotoneTraits_2_1 = "copy constructor

Parameters
----------
other : AosDirectionalXMonotoneTraits_2";
constexpr const char* AosDirectionalXMonotoneTraits_2_operator = "assignment operator.

Parameters
----------
 : other

Returns: AosDirectionalXMonotoneTraits_2";

constexpr const char* ArrDirectionalTraits_AreMergeable_2_operator = "accepts two $ x$ -monotone curves xc1 and xc2 and determines whether they can be merged to form a single $ x$ -monotone curve.

xc1 and xc2 are mergeable if their underlying curves are identical, they share
a common endpoint, and they do not bend to form a non- $ x$ -monotone curve.
The target point of xc1 and the source point xc2 coincide or the source point
of xc2 and the target point xc2 coincide.

Parameters
----------
xc1 : ArrDirectionalTraits::X_monotone_curve_2
xc2 : ArrDirectionalTraits::X_monotone_curve_2

Returns: bool";

constexpr const char* ArrDirectionalTraits_CompareEndpointsXy_2_operator = "accepts an input curve xc and compares its source and target points.

It returns SMALLER if the curve is directed from lexicographically left to
right, and LARGER if it is directed from lexicographically right to left.

Parameters
----------
xc : ArrDirectionalTraits::X_monotone_curve_2

Returns: Comparison_result";

constexpr const char* ArrDirectionalTraits_ConstructOpposite_2_operator = "accepts an $ x$ -monotone curve xc and returns its opposite curve, namely a curve whose graph is the same as xc 's, and whose source and target are swapped with respect to xc 's source and target.

Parameters
----------
xc : ArrDirectionalTraits::X_monotone_curve_2

Returns: ArrDirectionalTraits::X_monotone_curve_2";

constexpr const char* ArrDirectionalTraits_Intersect_2_operator = "computes the intersections of xc1 and xc2 and inserts them in an ascending lexicographic $ xy$ -order into a range beginning at oi .

The type OutputIterator dereferences a std::variant of either the type
pair<ArrDirectionalTraits::Point_2, ArrDirectionalTraits::Multiplicity> or the
type ArrDirectionalTraits::X_monotone_curve_2 . An object of the former type
represents an intersection point with its multiplicity (in case the
multiplicity is undefined or unknown, it is set to $ 0$ ). An object of the
latter type representing an overlapping subcurve of xc1 and xc2 . The
overlapping subcurves are given the direction of xc1 and xc2 if their
directions are identical. Otherwise, the overlapping subcurves are given an
arbitrary direction. The operator returns a past-the-end iterator of the
destination range.

Parameters
----------
xc1 : ArrDirectionalTraits::X_monotone_curve_2
xc2 : ArrDirectionalTraits::X_monotone_curve_2
oi : Output_iterator &

Returns: OutputIterator";

constexpr const char* ArrDirectionalTraits_Merge_2_operator = "accepts two mergeable $ x$ -monotone curves xc1 and xc2 and assigns xc with the merged curve.

If the target point of xc1 and the source point of xc2 coincide; then the
source point of xc1 and the target point of xc2 become the source and target
points of xc , respectively. If the target point of xc2 and the source point
of xc1 coincide; then the source point of xc2 and the target point of xc1
become the source and target points of xc , respectively. are_mergeable_2 (
xc1 , xc2 ) is true .

Parameters
----------
xc1 : ArrDirectionalTraits::X_monotone_curve_2
xc2 : ArrDirectionalTraits::X_monotone_curve_2
xc : ArrDirectionalTraits::X_monotone_curve_2 &";

constexpr const char* ArrDirectionalTraits_Split_2_operator = "accepts an input curve xc and a split point p in its interior.

It splits xc at the split point into two subcurves xc1 and xc2 , such that p
is xc1 's right endpoint and xc2 's left endpoint. The direction of xc is
preserved. That is, in case xc is directed from left to right, p becomes xc1
's target and c2 's source; otherwise, p becomes xc2 's target and xc1 's
source.

Parameters
----------
xc : ArrDirectionalTraits::X_monotone_curve_2
p : ArrDirectionalTraits::Point_2
xc1 : ArrDirectionalTraits::X_monotone_curve_2 &
xc2 : ArrDirectionalTraits::X_monotone_curve_2 &";

// CGAL::General_polygon_2
constexpr const char* CGAL_General_polygon_2__class__ = "The class General_polygon_2 models the concept GeneralPolygon_2 .";

constexpr const char* CGAL_General_polygon_2_Size = "number of edges size type.

Returns: unspecified_type";
constexpr const char* CGAL_General_polygon_2_Curve_2 = "a general planar curve.

Returns: ArrTraits::Curve_2";
constexpr const char* CGAL_General_polygon_2_General_polygon_2 = "constructs a General_polygon_2 from a $X$ -monotone curves.

Parameters
----------
begin : CurveIterator
end : CurveIterator";
constexpr const char* CGAL_General_polygon_2_size = "returns the number of edges of the general polygon.

Returns: Size";
constexpr const char* CGAL_General_polygon_2_clear = "clears the polygon.";
constexpr const char* CGAL_General_polygon_2_reverse_orientation = "reverses the orientation of the polygon.

is_simple() .";
constexpr const char* CGAL_General_polygon_2_is_empty = "returns true if the polygon is empty, and false otherwise.

Returns: bool";
constexpr const char* CGAL_General_polygon_2_orientation = "returns the orientation of the polygon.

is_simple() .

Returns: Orientation";
constexpr const char* CGAL_General_polygon_2_operator = "This operator imports a general polygon from the input stream in .

Both ASCII and binary formats are supported, and the format is automatically
detected. The format consists of the number of points of the outer boundary
followed by the points themselves in counterclockwise order, followed by the
number of holes, and for each hole, the number of points of the outer boundary
is followed by the points themselves in clockwise order.

Parameters
----------
in : std::istream &
P : CGAL::General_polygon_2 < ArrTraits > &

Returns: std::istream &";
constexpr const char* CGAL_General_polygon_2_operator_1 = "This operator exports a general polygon to the output stream out .

An ASCII and a binary format exist. The format can be selected with the CGAL
modifiers for streams, set_ascii_mode and set_binary_mode respectively. The
modifier set_pretty_mode can be used to allow for (a few) structuring comments
in the output. Otherwise, the output would be free of comments. The default
for writing is ASCII without comments. The number of curves of the outer
boundary is exported followed by the curves themselves in counterclockwise
order.

Parameters
----------
out : std::ostream &
P : CGAL::General_polygon_2 < ArrTraits > &

Returns: std::ostream &";

// CGAL::General_polygon_set_2
constexpr const char* CGAL_General_polygon_set_2__class__ = "An object of the General_polygon_set_2 class-template represents a point set in the plane bounded by $ x$ monotone curves.";

constexpr const char* CGAL_General_polygon_set_2_Traits_2 = "the traits class in use.

Returns: unspecified_type";
constexpr const char* CGAL_General_polygon_set_2_Polygon_2 = "the general polygon type.

Must model the GpsTraitsGeneralPolygon_2 concept.

Returns: unspecified_type";
constexpr const char* CGAL_General_polygon_set_2_Polygon_with_holes_2 = "the general polygon with holes type.

Must model the GpsTraitsGeneralPolygonWithHoles_2 concept.

Returns: unspecified_type";
constexpr const char* CGAL_General_polygon_set_2_Size = "number of polygons with holes size type.

Returns: unspecified_type";
constexpr const char* CGAL_General_polygon_set_2_Arrangement_2 = "the arrangement type used internally.

Returns: unspecified_type";
constexpr const char* CGAL_General_polygon_set_2_General_polygon_set_2 = "default constructor; constructs an empty set of polygons gps represented by an empty arrangement.";
constexpr const char* CGAL_General_polygon_set_2_General_polygon_set_2_1 = "copy constructor.

Parameters
----------
other : const Self &";
constexpr const char* CGAL_General_polygon_set_2_General_polygon_set_2_2 = "constructs an empty set of polygons that uses the given traits object for performing the geometric operations.

Parameters
----------
traits : const Traits &";
constexpr const char* CGAL_General_polygon_set_2_General_polygon_set_2_3 = "constructs a set of polygons that consists of the single polygon pgn .

Parameters
----------
pgn : const Polygon_2 &";
constexpr const char* CGAL_General_polygon_set_2_General_polygon_set_2_4 = "constructs a set of polygons that consists of the single polygon with holes pgn_with_holes .

Parameters
----------
pgn_with_holes : const Polygon_with_holes_2 &";
constexpr const char* CGAL_General_polygon_set_2_General_polygon_set_2_5 = "constructs a set of polygons that uses the given traits object and consists of the single polygon pgn .

Parameters
----------
pgn : const Polygon_2 &
traits : const Traits &";
constexpr const char* CGAL_General_polygon_set_2_General_polygon_set_2_6 = "constructs a set of polygons that uses the given traits object and consists of the single polygon with holes pgn_with_holes .

Parameters
----------
pgn_with_holes : const Polygon_with_holes_2 &
traits : const Traits &";
constexpr const char* CGAL_General_polygon_set_2_polygons_with_holes = "obtains the polygons with holes represented by gps .

Parameters
----------
out : OutputIterator

Returns: OutputIterator";
constexpr const char* CGAL_General_polygon_set_2_number_of_polygons_with_holes = "returns the total number of general polygons represented by gps .

Returns: Size";
constexpr const char* CGAL_General_polygon_set_2_is_empty = "returns true if gps represents an empty set.

Returns: bool";
constexpr const char* CGAL_General_polygon_set_2_is_plane = "returns true if gps represents the entire plane.

Returns: bool";
constexpr const char* CGAL_General_polygon_set_2_traits = "obtains an instance of the traits.

If the traits was passed as a parameter to the constructor of gps , it is
returned. Otherwise, a newly created instance is returned.

Returns: Traits &";
constexpr const char* CGAL_General_polygon_set_2_arrangement = "obtains the arrangement data structure that internally represents the general-polygon set.

Returns: const Arrangement_2 &";
constexpr const char* CGAL_General_polygon_set_2_clear = "clears gps .";
constexpr const char* CGAL_General_polygon_set_2_insert = "inserts pgn into gps .

pgn and the point set represented by gps are disjoint. This precondition
enables the use of very efficient insertion methods. Use the respective
overloaded method that inserts a polygon of type Polygon_with_holes_2 , if
only a relaxed precondition can be guaranteed. If even the relaxed
precondition cannot be guaranteed, use the join method.

Parameters
----------
pgn : Polygon_2 &";
constexpr const char* CGAL_General_polygon_set_2_insert_1 = "inserts pgn_with_holes into gps .

pgn_with_holes does not intersect with the point set represented by gps ,
except maybe at the vertices. If this relaxed precondition cannot be
guaranteed, use the join method.

Parameters
----------
pgn_with_holes : Polygon_with_holes_2 &";
constexpr const char* CGAL_General_polygon_set_2_insert_2 = "inserts the range of polygons (or polygons with holes) into gps .

(The value type of the input iterator is used to distinguish between the two.)
If the given range contains objects of type Polygon_with_holes_2 , then these
polygons and the point set represented by gps are pairwise disjoint, except
maybe at the vertices. If the given range contains objects of type Polygon_2 ,
then these polygons and the point set represented by gps are pairwise disjoint
without any exceptions.

Parameters
----------
begin : InputIterator
end : InputIterator";
constexpr const char* CGAL_General_polygon_set_2_insert_3 = "inserts the two ranges of polygons and polygons with holes into gps .

All polygons in the first range, all polygon with holes in the second range,
and the point set represented by gps are pairwise disjoint, except maybe at
the vertices

Parameters
----------
pgn_begin : InputIterator1
pgn_end : InputIterator1
pgn_with_holes_begin : InputIterator2
pgn_with_holes_end : InputIterator2";
constexpr const char* CGAL_General_polygon_set_2_complement = "computes the complement of gps .";
constexpr const char* CGAL_General_polygon_set_2_complement_1 = "computes the complement of other .

gps is overridden by the result.

Parameters
----------
other : const Polygon_set_2 &";
constexpr const char* CGAL_General_polygon_set_2_intersection = "computes the intersection of gps and other .

Parameters
----------
other : const General_polygon_set_2 &";
constexpr const char* CGAL_General_polygon_set_2_intersection_1 = "computes the intersection of gps and pgn .

Parameters
----------
pgn : const Polygon_2 &";
constexpr const char* CGAL_General_polygon_set_2_intersection_2 = "computes the intersection of gps and pgn .

Parameters
----------
pgn : const Polygon_with_holes_2 &";
constexpr const char* CGAL_General_polygon_set_2_intersection_3 = "computes the intersection of a collection of point sets.

The collection consists of the polygons (or polygons with holes) in the given
range and the point set represented by gps . (The value type of the input
iterator is used to distinguish between the two options.)

Parameters
----------
begin : InputIterator
end : InputIterator";
constexpr const char* CGAL_General_polygon_set_2_intersection_4 = "computes the intersection of a collection of point sets.

The collection consists of the polygons and polygons with holes in the given
two ranges and the point set represented by gps .

Parameters
----------
pgn_begin : InputIterator1
pgn_end : InputIterator1
pgn_with_holes_begin : InputIterator2
pgn_with_holes_end : InputIterator2";
constexpr const char* CGAL_General_polygon_set_2_join = "computes the union of gps and other .

Parameters
----------
other : const General_polygon_set_2 &";
constexpr const char* CGAL_General_polygon_set_2_join_1 = "computes the union of gps and pgn .

Parameters
----------
pgn : const Polygon_2 &";
constexpr const char* CGAL_General_polygon_set_2_join_2 = "computes the union of gps and pgn .

Parameters
----------
pgn : const Polygon_with_holes_2 &";
constexpr const char* CGAL_General_polygon_set_2_join_3 = "computes the union of the polygons (or polygons with holes) in the given range and the point set represented by gps .

(The value type of the input iterator is used to distinguish between the two
options.)

Parameters
----------
begin : InputIterator
end : InputIterator";
constexpr const char* CGAL_General_polygon_set_2_join_4 = "computes the union of the polygons and polygons with holes in the given two ranges and the point set represented by gps .

Parameters
----------
pgn_begin : InputIterator1
pgn_end : InputIterator1
pgn_with_holes_begin : InputIterator2
pgn_with_holes_end : InputIterator2";
constexpr const char* CGAL_General_polygon_set_2_difference = "computes the difference between gps and other .

Parameters
----------
other : const General_polygon_set_2 &";
constexpr const char* CGAL_General_polygon_set_2_difference_1 = "computes the difference between gps and pgn .

Parameters
----------
pgn : const Polygon_2 &";
constexpr const char* CGAL_General_polygon_set_2_difference_2 = "computes the difference between gps and pgn .

Parameters
----------
pgn : const Polygon_with_holes_2 &";
constexpr const char* CGAL_General_polygon_set_2_symmetric_difference = "computes the symmetric difference between gps and other .

Parameters
----------
other : const General_polygon_set_2 &";
constexpr const char* CGAL_General_polygon_set_2_symmetric_difference_1 = "computes the symmetric difference between gps and pgn .

Parameters
----------
pgn : const Polygon_2 &";
constexpr const char* CGAL_General_polygon_set_2_symmetric_difference_2 = "computes the symmetric difference between gps and pgn .

Parameters
----------
pgn : const Polygon_with_holes_2 &";
constexpr const char* CGAL_General_polygon_set_2_symmetric_difference_3 = "computes the symmetric difference (xor) of a collection of point sets.

The collection consists of the polygons (or polygons with holes) in the given
range and the point set represented by gps . (The value type of the input
iterator is used to distinguish between the two options.)

Parameters
----------
begin : InputIterator
end : InputIterator";
constexpr const char* CGAL_General_polygon_set_2_symmetric_difference_4 = "computes the symmetric difference (xor) of a collection of point sets.

The collection consists of the polygons and polygons with holes in the given
two ranges and the point set represented by gps .

Parameters
----------
pgn_begin : InputIterator1
pgn_end : InputIterator1
pgn_with_holes_begin : InputIterator2
pgn_with_holes_end : InputIterator2";
constexpr const char* CGAL_General_polygon_set_2_intersection_5 = "computes the intersection of gps1 and gps2 .

Parameters
----------
gps1 : const General_polygon_set_2 &
gps2 : const General_polygon_set_2 &";
constexpr const char* CGAL_General_polygon_set_2_join_5 = "computes the union of gps1 and gps2 .

Parameters
----------
gps1 : const General_polygon_set_2 &
gps2 : const General_polygon_set_2 &";
constexpr const char* CGAL_General_polygon_set_2_difference_3 = "computes the difference between gps1 and gps2 .

Parameters
----------
gps1 : const General_polygon_set_2 &
gps2 : const General_polygon_set_2 &";
constexpr const char* CGAL_General_polygon_set_2_symmetric_difference_5 = "computes the symmetric difference between gps1 and gps2 .

Parameters
----------
gps1 : const General_polygon_set_2 &
gps2 : const General_polygon_set_2 &";
constexpr const char* CGAL_General_polygon_set_2_do_intersect = "returns true if gps and other intersect in their interior, and false otherwise.

Parameters
----------
other : const General_polygon_set_2 &

Returns: bool";
constexpr const char* CGAL_General_polygon_set_2_do_intersect_1 = "returns true if gps and pgn intersect in their interior, and false otherwise.

Parameters
----------
pgn : const Polygon_2 &

Returns: bool";
constexpr const char* CGAL_General_polygon_set_2_do_intersect_2 = "returns true if gps and pgn intersect in their interior, and false otherwise.

Parameters
----------
pgn : const Polygon_with_holes_2 &

Returns: bool";
constexpr const char* CGAL_General_polygon_set_2_do_intersect_3 = "returns true if the interior of the point sets in a collection intersect, and false otherwise.

The collection consists of the polygons (or polygons with holes) in the given
range and the point set represented by gps . (The value type of the input
iterator is used to distinguish between the two options.)

Parameters
----------
begin : InputIterator
end : InputIterator";
constexpr const char* CGAL_General_polygon_set_2_do_intersect_4 = "returns true if the interior of the point sets in a collection intersect, and false otherwise.

The collection consists of the polygons and polygons with holes in the given
two ranges and the point set represented by gps .

Parameters
----------
pgn_begin : InputIterator1
pgn_end : InputIterator1
pgn_with_holes_begin : InputIterator2
pgn_with_holes_end : InputIterator2";
constexpr const char* CGAL_General_polygon_set_2_locate = "obtains a polygon with holes that contains the query point p , if exists, through pgn , and returns true .

Otherwise, returns false .

Parameters
----------
p : const Point_2 &
pgn : Polygon_with_holes_2 &

Returns: bool";
constexpr const char* CGAL_General_polygon_set_2_oriented_side = "returns either the constant ON_ORIENTED_BOUNDARY , ON_POSITIVE_SIDE , or ON_NEGATIVE_SIDE , iff p lies on the boundary, properly on the positive side, or properly on the negative side of gps respectively.

Parameters
----------
q : const Point_2 &

Returns: Oriented_side";
constexpr const char* CGAL_General_polygon_set_2_oriented_side_1 = "returns either the constant ON_NEGATIVE_SIDE , ON_ORIENTED_BOUNDARY , or ON_POSITIVE_SIDE , iff other and gps are completely disjoint, in contact, or intersect in their interior, respectively.

Parameters
----------
other : const General_polygon_set_2 &

Returns: Oriented_side";
constexpr const char* CGAL_General_polygon_set_2_oriented_side_2 = "returns either the constant ON_NEGATIVE_SIDE , ON_ORIENTED_BOUNDARY , or ON_POSITIVE_SIDE , iff pgn and gps are completely disjoint, in contact, or intersect in their interior, respectively.

Parameters
----------
pgn : const Polygon_2 &

Returns: Oriented_side";
constexpr const char* CGAL_General_polygon_set_2_oriented_side_3 = "returns either the constant ON_NEGATIVE_SIDE , ON_ORIENTED_BOUNDARY , or ON_POSITIVE_SIDE , iff pgn and gps are completely disjoint, in contact, or intersect in their interior, respectively.

Parameters
----------
pgn : const Polygon_with_holes_2 &

Returns: Oriented_side";
constexpr const char* CGAL_General_polygon_set_2_is_valid = "returns true if gps represents a valid point set.

Returns: bool";

// CGAL::Gps_circle_segment_traits_2
constexpr const char* CGAL_Gps_circle_segment_traits_2__class__ = "The traits class Gps_circle_segment_traits_2 models the GeneralPolygonSetTraits_2 concept.";

// CGAL::Gps_default_dcel
constexpr const char* CGAL_Gps_default_dcel__class__ = "The default DCEL class template used by the General_polygon_set_2 and General_polygon_with_holes_2 class templates.";

// CGAL::Gps_face_base
constexpr const char* CGAL_Gps_face_base__class__ = "An instance of this template serves as a basis type for any face record of the DCEL class used by instances of the General_polygon_set_2 and General_polygon_with_holes_2 class templates.";

// CGAL::Gps_halfedge_base
constexpr const char* CGAL_Gps_halfedge_base__class__ = "An instance of this template serves as a basis type for any halfedge record of the DCEL class used by instances of the General_polygon_set_2 and General_polygon_with_holes_2 class templates.";


// CGAL::Gps_traits_2
constexpr const char* CGAL_Gps_traits_2__class__ = "The traits class Gps_traits_2 models the concept GeneralPolygonSetTraits_2 .";

// CGAL::Graphics_scene_options_polygon_set_2
constexpr const char* CGAL_Graphics_scene_options_polygon_set_2__class__ = "The class Graphics_scene_options_polygon_set_2 defines data and methods used to tune the way that the cells of a Polygon_set_2 are considered for drawing or to be added into a graphics scene.";

// CGAL::Polygon_set_2
constexpr const char* CGAL_Polygon_set_2__class__ = "The class Polygon_set_2 represents sets of linear polygons with holes.";

constexpr const char* GeneralPolygon_2_X_monotone_curve_2 = "represents a planar (weakly) $ x$ -monotone curve.

The type of the geometric mapping of the polygonal edges. It must model the
concept ArrTraits::XMonotoneCurve_2.

Returns: unspecified_type";
constexpr const char* GeneralPolygon_2_Curve_iterator = "an iterator over the geometric mapping of the polygon edges.

Its value type is X_monotone_curve_2 .

Returns: unspecified_type";
constexpr const char* GeneralPolygon_2_Curve_const_iterator = "a const iterator over the geometric mapping of the polygon edges.

Its value type is X_monotone_curve_2 .

Returns: unspecified_type";
constexpr const char* GeneralPolygon_2_GeneralPolygon_2 = "default constructor.";
constexpr const char* GeneralPolygon_2_GeneralPolygon_2_1 = "copy constructor.

Parameters
----------
other : GeneralPolygon_2";
constexpr const char* GeneralPolygon_2_operator = "assignment operator.

Parameters
----------
 : other

Returns: GeneralPolygon_2";
constexpr const char* GeneralPolygon_2_GeneralPolygon_2_2 = "constructs a general polygon from a given range of curves.

Parameters
----------
begin : InputIterator
end : InputIterator";
constexpr const char* GeneralPolygon_2_curves_begin = "returns the begin iterator of the curves.

Returns: Curve_iterator";
constexpr const char* GeneralPolygon_2_curves_end = "returns the past-the-end iterator of the curves.

Returns: Curve_iterator";
constexpr const char* GeneralPolygon_2_curves_begin_1 = "returns the begin const iterator of the curves.

Returns: Curve_const_iterator";
constexpr const char* GeneralPolygon_2_curves_end_1 = "returns the past-the-end const iterator of the curves.

Returns: Curve_const_iterator";
constexpr const char* GeneralPolygon_2_init = "initializes the polygon with the polygonal chain given by the range.

The value type of Iterator must be X_monotone_curve_2 . The curves in the
range must define a simple polygon.

Parameters
----------
begin : Iterator
end : Iterator";

// GeneralPolygonSetDcel
constexpr const char* GeneralPolygonSetDcel__class__ = "A doubly-connected edge-list ( Dcel for short) data-structure. It consists of three containers of records: vertices $ V$ , halfedges $ E$ , and faces $ F$ . It maintains the incidence relation among them. The halfedges are ordered in pairs sometimes referred to as twins, such that each halfedge pair represent an edge.";

// GeneralPolygonSetDcelFace
constexpr const char* GeneralPolygonSetDcelFace__class__ = "A face record in a Dcel data structure used by the General_polygon_set_2 and Polygon_set_2 template classes to represent the underlying internal Arrangement_2 data structure.";

constexpr const char* GeneralPolygonSetDcelFace_contained = "returns true if the face is contained in the general-polygon set, and false otherwise.

Returns: bool";
constexpr const char* GeneralPolygonSetDcelFace_visited = "returns true if the face has been visited, and false otherwise.

This is used internally by the some of the operations of the
General_polygon_set_2 class that traverse the arrangement faces.

Returns: bool";
constexpr const char* GeneralPolygonSetDcelFace_id = "returns an id associated to the face using set_id() ; If no call to set_id() was done or if reset_id() was called, the returned value is not specified and id_not_set() must return true .

Returns: std::size_t";
constexpr const char* GeneralPolygonSetDcelFace_id_not_set = "returns true if set_id() was not called or if reset_id() was called, amd false otherwise.

Returns: bool";
constexpr const char* GeneralPolygonSetDcelFace_set_contained = "marks the face as contained (if flag is true ), or as a hole (if it is false ).

Parameters
----------
flag : bool";
constexpr const char* GeneralPolygonSetDcelFace_reset_id = "marks the face as visited (if flag is true ), or as not visited (if it is false ).

This is used internally by the some of the operations of the
General_polygon_set_2 class that traverse the arrangement faces. resets the id
associated to the face.";
constexpr const char* GeneralPolygonSetDcelFace_set_id = "sets the id associated to the face.

i should be different from the largest possible value that std::size_t can
store.

Parameters
----------
i : std::size_t";

// GeneralPolygonSetDcelHalfedge
constexpr const char* GeneralPolygonSetDcelHalfedge__class__ = "A halfedge record in a Dcel data structure used by the General_polygon_set_2 and Polygon_set_2 template classes to represent the underlying internal Arrangement_2 data structure.";

constexpr const char* GeneralPolygonSetDcelHalfedge_flag = "returns an integer passed to set_flag() , if the latter function was not called the output is not specified.

Returns: int";
constexpr const char* GeneralPolygonSetDcelHalfedge_set_flag = "set an integer flag for this halfedge.

Parameters
----------
i : int";

// GeneralPolygonSetTraits_2
constexpr const char* GeneralPolygonSetTraits_2__class__ = "This concept defines the minimal set of geometric predicates needed to perform the Boolean-set operations. It refines the directional $ x$ -monotone arrangement-traits concept. In addition to the Point_2 and X_monotone_curve_2 types defined in the generalized concept, it defines a type that represents a general polygon and another one that represents general polygon with holes. It also requires operations that operate on these types.";

constexpr const char* GeneralPolygonSetTraits_2_Polygon_2 = "represents a general polygon.

Must be a model of the GpsTraitsGeneralPolygon_2 concept.

Returns: unspecified_type";
constexpr const char* GeneralPolygonSetTraits_2_Polygon_with_holes_2 = "represents a general polygon with holes.

Must be a model of the GpsTraitsGeneralPolygonWithHoles_2 concept.

Returns: unspecified_type";
constexpr const char* GeneralPolygonSetTraits_2_Curve_const_iterator = "A const iterator of curves.

Its value type is const X_monotone_curve_2 .

Returns: unspecified_type";
constexpr const char* GeneralPolygonSetTraits_2_Construct_polygon_2 = "a functor that constructs a general polygon from a range of $ x$ -monotone curves.

It uses the operator void operator() (InputIterator begin, Input iterator end,
Polygon_2 & pgn) , parameterized by the InputIterator type.

Returns: unspecified_type";
constexpr const char* GeneralPolygonSetTraits_2_Construct_polygon_with_holes_2 = "a functor that constructs a general polygon with holes from a general polygon and, optionally, a range of holes.

It uses the operator void operator() (const Polygon_2 & pgn_boundary) or void
operator() (const Polygon_2 & pgn_boundary, HolesInputIterator h_begin,
HolesInputIterator h_end) parameterized by the HolesInputIterator type.

Returns: unspecified_type";
constexpr const char* GeneralPolygonSetTraits_2_Construct_outer_boundary = "A functor for constructing the outer boundary of a polygon with holes.

It uses the operator Polygon_2 operator()(const Polygon_with_holes_2 & pol_wh)
.

Returns: unspecified_type";
constexpr const char* GeneralPolygonSetTraits_2_Construct_holes = "A functor for constructing the container of holes of a polygon with holes.

It returns the begin/end iterators for the holes It uses the operator
std::pair<Hole_const_iterator, Hole_const_iterator> operator()(const
Polygon_with_holes_2 & pol_wh) .

Returns: unspecified_type";
constexpr const char* GeneralPolygonSetTraits_2_Is_unbounded = "A functor for checking if polygon with holes has no outer boundary.

It uses the operator bool operator()(const Polygon_with_holes_2 & pol_wh) .

Returns: unspecified_type";
constexpr const char* GeneralPolygonSetTraits_2_GeneralPolygonSetTraits_2 = "default constructor.";
constexpr const char* GeneralPolygonSetTraits_2_GeneralPolygonSetTraits_2_1 = "copy constructor

Parameters
----------
other : GeneralPolygonSetTraits_2";
constexpr const char* GeneralPolygonSetTraits_2_operator = "assignment operator.

Parameters
----------
 : other

Returns: GeneralPolygonSetTraits_2";
constexpr const char* GeneralPolygonSetTraits_2_construct_polygon_2_object = "returns a functor that constructs a polygon.

Returns: Construct_polygon_2";
constexpr const char* GeneralPolygonSetTraits_2_construct_curves_2_object = "returns a functor that obtains the curves of a polygon.

Returns: Construct_curves_2";
constexpr const char* GeneralPolygonSetTraits_2_construct_polygon_with_holes_2_object = "returns a functor that constructs a polygon with holes.

Returns: Construct_polygon_with_holes_2";
constexpr const char* GeneralPolygonSetTraits_2_construct_outer_boundary_object = "returns a functor that obtains the outer boundary of a polygon with holes.

Returns: Construct_outer_boundary";
constexpr const char* GeneralPolygonSetTraits_2_construct_holes_object = "returns a functor that obtains begin/end iterators over a container of holes.

Returns: Construct_holes";
constexpr const char* GeneralPolygonSetTraits_2_is_unbounded_object = "returns a functor that determines if the polygon with holes is unbounded

Returns: Is_unbounded";

// GpsTraitsGeneralPolygon_2
constexpr const char* GpsTraitsGeneralPolygon_2__class__ = "A model of this concept represents a simple general polygon.";

// GpsTraitsGeneralPolygonWithHoles_2
constexpr const char* GpsTraitsGeneralPolygonWithHoles_2__class__ = "A model of this concept represents a general polygon with holes.";

// GraphicsSceneOptionsPolygonSet2
constexpr const char* GraphicsSceneOptionsPolygonSet2__class__ = "The concept GraphicsSceneOptionsPolygonSet2 defines data and methods used to tune the way that the cells of a Polygon_set_2 are considered for drawing or to be added into a graphics scene.";

constexpr const char* GraphicsSceneOptionsPolygonSet2_unbounded_face_color = "returns the color of the unbounded face.

Returns: const CGAL::IO::Color &";
constexpr const char* GraphicsSceneOptionsPolygonSet2_unbounded_face_color_1 = "sets the color of the unbounded face to c .

Parameters
----------
c : const CGAL::IO::Color &";
constexpr const char* GraphicsSceneOptionsPolygonSet2_draw_unbounded = "returns true if the unbounded face must be drawn, false otherwise.

Returns false by default.

Returns: bool";
constexpr const char* GraphicsSceneOptionsPolygonSet2_draw_unbounded_1 = "sets the draw of unbounded face to b .

Parameters
----------
b : bool";
constexpr const char* GraphicsSceneOptionsPolygonSet2_toggle_draw_unbounded = "toggles the draw unbounded face value.";
constexpr const char* GraphicsSceneOptionsPolygonSet2_height = "returns the height of the box used to draw the unbounded face.

Returns: int";
constexpr const char* GraphicsSceneOptionsPolygonSet2_width = "returns the width of the box used to draw the unbounded face.

Returns: int";
constexpr const char* GraphicsSceneOptionsPolygonSet2_height_1 = "sets the height of the box used to draw the unbounded face to i .

Parameters
----------
i : int";
constexpr const char* GraphicsSceneOptionsPolygonSet2_width_1 = "sets the width of the box used to draw the unbounded face to i .

Parameters
----------
i : int";

// ArrDirectionalTraits
constexpr const char* ArrDirectionalTraits__class__ = "The namespace containing concepts specific to 2D Boolean Set Operations.";

// std
constexpr const char* std__class__ = "STL namespace.";

} // namespace Boolean_set_operations_2
} // namespace docstrings
} // namespace cgalpy

#endif // CGAL_PYTHON_DOCSTRINGS_BOOLEAN_SET_OPERATIONS_2_H
