// AUTO-GENERATED by cpp_docstrings_from_json.py — DO NOT EDIT
// Package: Orthtree
#ifndef CGAL_PYTHON_DOCSTRINGS_ORTHTREE_H
#define CGAL_PYTHON_DOCSTRINGS_ORTHTREE_H

namespace cgalpy {
namespace docstrings {
namespace Orthtree {

// CGAL::Orthtree
constexpr const char* CGAL_Orthtree__class__ = "A data structure using an axis-aligned hyperrectangle decomposition of dD space for efficient access and computation.";

constexpr const char* CGAL_Orthtree_Kernel = "Kernel type.

Returns: typename Traits::Kernel";
constexpr const char* CGAL_Orthtree_FT = "Number type.

Returns: typename Traits::FT";
constexpr const char* CGAL_Orthtree_Point = "Point type.

Returns: typename Traits::Point_d";
constexpr const char* CGAL_Orthtree_Bbox = "Bounding box type.

Returns: typename Traits::Bbox_d";
constexpr const char* CGAL_Orthtree_Sphere = "Sphere type.

Returns: typename Traits::Sphere_d";
constexpr const char* CGAL_Orthtree_Adjacency = "Adjacency type.

Returns: typename Traits::Adjacency";
constexpr const char* CGAL_Orthtree_Node_index = "Index of a given node in the tree; the root always has index 0.

Returns: typename Traits::Node_index";
constexpr const char* CGAL_Orthtree_has_data = "true if GeomTraits is a model of OrthtreeTraitsWithData and false otherwise.

Returns: bool";
constexpr const char* CGAL_Orthtree_supports_neighbor_search = "true if GeomTraits is a model of CollectionPartitioningOrthtreeTraits and false otherwise.

Returns: bool";
constexpr const char* CGAL_Orthtree_supports_ball_search = "true if GeomTraits provides a Has_on_bounded_side functor and false otherwise.

Returns: bool";
constexpr const char* CGAL_Orthtree_dimension = "Dimension of the tree.

Returns: int";
constexpr const char* CGAL_Orthtree_Self = "Self alias for convenience.

Returns: Orthtree < Traits >";
constexpr const char* CGAL_Orthtree_Local_coordinates = "Set of bits representing this node's relationship to its parent.

Equivalent to an array of Booleans, where index[0] is whether x is greater,
index[1] is whether y is greater, index[2] is whether z is greater, and so on
for higher dimensions if needed. Used to represent a node's relationship to
the center of its parent.

Returns: std::bitset< dimension >";
constexpr const char* CGAL_Orthtree_Global_coordinates = "Coordinates representing this node's relationship with the rest of the tree.

Each value (x, y, z, ...) of global coordinates is calculated by doubling the
parent's global coordinates and adding the local coordinates.

Returns: std::array< std::uint32_t, dimension >";
constexpr const char* CGAL_Orthtree_Split_predicate = "A predicate that determines whether a node must be split when refining a tree.

Returns: std::function< bool( Node_index , const Self &)>";
constexpr const char* CGAL_Orthtree_Node_index_range = "A model of ForwardRange whose value type is Node_index .

Returns: unspecified_type";
constexpr const char* CGAL_Orthtree_Property_map = "A model of LvaluePropertyMap with Node_index as key type and T as value type.

Returns: unspecified_type";
constexpr const char* CGAL_Orthtree_degree = "Degree of the tree (number of children of non-leaf nodes).

Returns: int";
constexpr const char* CGAL_Orthtree_Orthtree = "constructs an orthtree for a traits instance.

The constructed orthtree has a root node with no children, containing the
contents determined by Construct_root_node_contents from the traits class.
That root node has a bounding box determined by Construct_root_node_bbox from
the traits class, which typically encloses its contents. This single-node
orthtree is valid and compatible with all orthtree functionality, but any
performance benefits are unlikely to be realized until refine() is called.
traits the traits object.

Parameters
----------
traits : Traits";
constexpr const char* CGAL_Orthtree_Orthtree_1 = "constructs an orthtree from a set of arguments provided to the traits constructor

Parameters
----------
args : Args &&...";
constexpr const char* CGAL_Orthtree_Orthtree_2 = "copy constructor

Parameters
----------
other : const Orthtree &";
constexpr const char* CGAL_Orthtree_Orthtree_3 = "move constructor

Parameters
----------
other : Orthtree &&";
constexpr const char* CGAL_Orthtree_refine = "recursively subdivides the orthtree until it meets the given criteria.

The split predicate should return true if a leaf node should be split and
false otherwise. This function may be called several times with different
predicates: in that case, nodes already split are left unaltered, while nodes
that were not split and for which split_predicate returns true are split.
split_predicate determines whether or not a leaf node needs to be subdivided.

Parameters
----------
split_predicate : const Split_predicate &";
constexpr const char* CGAL_Orthtree_refine_1 = "convenience overload that refines an orthtree using a maximum depth and maximum number of contained elements in a node as split predicate.

This is equivalent to calling
refine(Orthtrees::Maximum_depth_and_maximum_contained_elements(max_depth,
bucket_size)) . The refinement is stopped as soon as one of the conditions is
violated: if a node contains more elements than bucket_size but is already at
max_depth , it is not split. Similarly, a node that is at a depth smaller than
max_depth but already contains fewer elements than bucket_size , it is not
split. This convenience method is only appropriate for trees with traits
classes where Node_data is a model of Range . RandomAccessRange is suggested
for performance. max_depth deepest a tree is allowed to be (nodes at this
depth will not be split). bucket_size maximum number of items a node is
allowed to contain.

Parameters
----------
max_depth : size_t
bucket_size : size_t

Returns: std::enable_if_t< Orthtree::has_data , void >";
constexpr const char* CGAL_Orthtree_grade = "refines the orthtree such that the difference of depth between two immediate neighbor leaves is never more than 1.

This is done only by adding nodes, nodes are never removed.";
constexpr const char* CGAL_Orthtree_traits = "provides direct read-only access to the tree traits.

Returns: const Traits &";
constexpr const char* CGAL_Orthtree_root = "provides access to the root node, and by extension the rest of the tree.

Returns: Node_index";
constexpr const char* CGAL_Orthtree_depth = "returns the deepest level reached by a leaf node in this tree (root being level 0).

Returns: std::size_t";
constexpr const char* CGAL_Orthtree_traverse = "constructs a node index range using a tree-traversal function.

This method allows iteration over the nodes of the tree with a user-selected
order (preorder, postorder, leaves-only, etc.). Traversal a model of
OrthtreeTraversal traversal class defining the traversal strategy a
ForwardRange over the node indices of the tree

Parameters
----------
traversal : Traversal

Returns: Node_index_range";
constexpr const char* CGAL_Orthtree_traverse_1 = "convenience method for using a traversal without constructing it yourself

Traversal a model of OrthtreeTraversal args Arguments to pass to the
traversal's constructor, excluding the first (always an orthtree reference) a
ForwardRange over the node indices of the tree

Parameters
----------
args : Args &&...

Returns: Node_index_range";
constexpr const char* CGAL_Orthtree_bbox = "constructs the bounding box of a node.

The object constructed is not the bounding box of the node's contents, but the
bounding box of the node itself. n node to generate a bounding box for the
bounding box of the node n

Parameters
----------
n : Node_index

Returns: Bbox";
constexpr const char* CGAL_Orthtree_add_property = "gets a property for nodes, adding it if it does not already exist.

T the type of the property to add name the name of the new property
default_value the default value assigned to nodes for this property pair of
the property map and a Boolean which is true if the property needed to be
created

Parameters
----------
name : const std::string &
default_value : const T

Returns: std::pair< Property_map < T >, bool >";
constexpr const char* CGAL_Orthtree_property = "gets a property of the nodes if it exists.

T the type of the property to retrieve name the name of the property an
optional containing the property map if it exists

Parameters
----------
name : const std::string &

Returns: std::optional< Property_map < T > >";
constexpr const char* CGAL_Orthtree_properties = "returns a vector of all property names.

Returns: std::vector< std::string >";
constexpr const char* CGAL_Orthtree_remove_property = "removes the node property from the tree.

T the type of the property to remove property the property to be removed from
the tree. true if property was a valid property of the tree.

Parameters
----------
property : Property_map < T >

Returns: bool";
constexpr const char* CGAL_Orthtree_locate = "finds the leaf node which contains a particular point in space.

Traverses the orthtree and finds the leaf cell that has a domain enclosing the
point passed. The point passed must be within the region enclosed by the
orthtree (bbox of the root node). The point is contained in the lower cell of
each direction if its coordinate is lower than the center. point query point.
the index of the node which contains the point.

Parameters
----------
point : const Point &

Returns: Node_index";
constexpr const char* CGAL_Orthtree_nearest_k_neighbors = "finds the k nearest neighbors of the point query .

Nearest neighbors are outputted in order of increasing distance to query .
OutputIterator a model of OutputIterator that accepts
GeomTraits::Node_data_element objects. query query point k number of neighbors
to find output output iterator Nearest neighbor searches requires GeomTraits
to be a model of CollectionPartitioningOrthtreeTraits .

Parameters
----------
query : const Point &
k : std::size_t
output : OutputIterator

Returns: std::enable_if_t< Orthtree::supports_neighbor_search , OutputIterator >";
constexpr const char* CGAL_Orthtree_neighbors_within_radius = "finds the elements in the sphere query .

Elements are outputted in order of increasing distance to the center of the
sphere. OutputIterator a model of OutputIterator that accepts
GeomTraits::Node_data_element objects. query query sphere output output
iterator Nearest neighbor searches requires GeomTraits to be a model of
CollectionPartitioningOrthtreeTraits .

Parameters
----------
query : const Sphere &
output : OutputIterator

Returns: std::enable_if_t< Orthtree::supports_neighbor_search , OutputIterator >";
constexpr const char* CGAL_Orthtree_nearest_k_neighbors_within_radius = "finds at most k elements within a specific radius that are nearest to the center of the sphere query : if query does not contain at least k elements, only contained elements will be returned.

This function is useful when the user already knows how sparse the elements
are, or if they do not care about elements that are too far away. Setting a
small radius may have performance benefits. OutputIterator must be a model of
OutputIterator that accepts GeomTraits::Node_data_element query the region to
search within k the number of elements to find output the output iterator to
add the found elements to (in order of increasing distance) Nearest neighbor
searches requires GeomTraits to be a model of
CollectionPartitioningOrthtreeTraits .

Parameters
----------
query : const Sphere &
k : std::size_t
output : OutputIterator

Returns: std::enable_if_t< Orthtree::supports_neighbor_search , OutputIterator >";
constexpr const char* CGAL_Orthtree_intersected_nodes = "finds the leaf nodes that intersect with any primitive.

this function requires the function bool CGAL::do_intersect(QueryType,
Traits::Bbox_d) to be defined. This function finds all the intersecting leaf
nodes and writes their indices to the output iterator. Query the primitive
class (e.g., plane, ray) OutputIterator a model of OutputIterator that accepts
Node_index types query the intersecting primitive. output output iterator. the
output iterator after writing

Parameters
----------
query : const Query &
output : OutputIterator

Returns: OutputIterator";
constexpr const char* CGAL_Orthtree_intersected_nodes_1 = "finds the leaf nodes that intersect with a ball.

This function finds all the intersecting leaf nodes and writes their indices
to the output iterator. Requires the Traits class to provide the functor via
has_on_bounded_side_object() with an operator: bool
operator()(Traits::Sphere_d, Traits::Bbox_d) Kernel::HasOnUnboundedSide_2 and
Kernel::HasOnUnboundedSide_3 are compatible concepts for dimensions 2 and 3.
OutputIterator a model of OutputIterator that accepts Node_index types center
the center of the ball squared_radius the squared radius of the ball output
output iterator. the output iterator after writing

Parameters
----------
center : const Point &
squared_radius : const FT
output : OutputIterator

Returns: std::enable_if_t< Orthtree::supports_ball_search , OutputIterator >";
constexpr const char* CGAL_Orthtree_intersected_nodes_2 = "finds the leaf nodes that intersect with any primitive.

This function finds all the intersecting leaf nodes and writes their indices
to the output iterator. Query the primitive class (e.g., sphere, ray)
OutputIterator a model of OutputIterator that accepts Node_index types
IntersectionFunctor a functor that is invoked on each node while traversing
the tree to determine intersection must be of type bool(const Query&, const
Traits::Bbox_d&) query the intersecting primitive. output output iterator.
func the intersection functor. the output iterator after writing

Parameters
----------
query : const Query &
output : OutputIterator
func : IntersectionFunctor &

Returns: OutputIterator";
constexpr const char* CGAL_Orthtree_operator = "compares the topology of the orthtree with that of rhs .

Trees may be considered equivalent even if they have different contents.
Equivalent trees must have the same root bounding box and the same node
structure. rhs the other orthtree true if the trees have the same topology,
and false otherwise

Parameters
----------
rhs : const Self &

Returns: bool";
constexpr const char* CGAL_Orthtree_operator_1 = "compares the topology of the orthtree with that of rhs .

rhs the other orthtree false if the trees have the same topology, and true
otherwise

Parameters
----------
rhs : const Self &

Returns: bool";
constexpr const char* CGAL_Orthtree_is_leaf = "determines whether the node specified by index n is a leaf node.

Parameters
----------
n : Node_index

Returns: bool";
constexpr const char* CGAL_Orthtree_is_root = "determines whether the node specified by index n is the root node.

Parameters
----------
n : Node_index

Returns: bool";
constexpr const char* CGAL_Orthtree_depth_1 = "determines the depth of the node specified.

The root node has depth 0, its children have depth 1, and so on. n index of
the node to check. the depth of the node n within its tree.

Parameters
----------
n : Node_index

Returns: std::size_t";
constexpr const char* CGAL_Orthtree_data = "retrieves a reference to the Node_data associated with the node specified by n if GeomTraits is a model of OrthtreeTraitswithData , and nullptr otherwise.

Parameters
----------
n : Node_index

Returns: std::conditional_t< has_data , Node_data &, void * > &";
constexpr const char* CGAL_Orthtree_data_1 = "retrieves a const reference to the Node_data associated with the node specified by n if GeomTraits is a model of OrthtreeTraitswithData , and nullptr otherwise.

Parameters
----------
n : Node_index

Returns: std::conditional_t< has_data , const Node_data &, void * >";
constexpr const char* CGAL_Orthtree_global_coordinates = "retrieves the global coordinates of the node.

Parameters
----------
n : Node_index

Returns: Global_coordinates";
constexpr const char* CGAL_Orthtree_local_coordinates = "retrieves the local coordinates of the node.

Parameters
----------
n : Node_index

Returns: Local_coordinates";
constexpr const char* CGAL_Orthtree_parent = "returns this n's parent.

!is_root() n index of the node to retrieve the parent of the index of the
parent of node n

Parameters
----------
n : Node_index

Returns: Node_index";
constexpr const char* CGAL_Orthtree_child = "returns a node's i th child.

!is_leaf() n index of the node to retrieve the child of i in [0, 2^D)
specifying the child to retrieve the index of the i th child of node n

Parameters
----------
n : Node_index
i : std::size_t

Returns: Node_index";
constexpr const char* CGAL_Orthtree_descendant = "retrieves an arbitrary descendant of the node specified by node .

Convenience function to avoid the need to call
orthtree.child(orthtree.child(node, 0), 1) . Each index in indices specifies
which child to enter as descending the tree from node down. Indices are
evaluated in the order they appear as parameters, so descendant(root, 0, 1)
returns the second child of the first child of the root. node the node to
descend indices the integer indices specifying the descent to perform the
index of the specified descendant node

Parameters
----------
node : Node_index
indices : Indices...

Returns: Node_index";
constexpr const char* CGAL_Orthtree_node = "convenience function for retrieving arbitrary nodes.

Equivalent to tree.descendant(tree.root(), indices...) . indices the integer
indices specifying the descent to perform, starting from the root the index of
the specified node

Parameters
----------
indices : Indices...

Returns: Node_index";
constexpr const char* CGAL_Orthtree_next_sibling = "finds the next sibling in the parent of the node specified by the index n .

Traverses the tree in increasing order of local index (e.g., 000, 001, 010,
etc.) n the index of the node to find the sibling of the index of the next
sibling of n if n is not the last node in its parent, otherwise std::nullopt .

Parameters
----------
n : Node_index

Returns: const std::optional< Node_index >";
constexpr const char* CGAL_Orthtree_next_sibling_up = "finds the next sibling of the parent of the node specified by n if it exists.

n the index node to find the sibling up of. The index of the next sibling of
the parent of n if n is not the root and its parent has a sibling, otherwise
nothing.

Parameters
----------
n : Node_index

Returns: const std::optional< Node_index >";
constexpr const char* CGAL_Orthtree_deepest_first_child = "finds the leaf node reached when descending the tree and always choosing child 0.

This is the starting point of a depth-first traversal. n the index of the node
to find the deepest first child of. the index of the deepest first child of
node n.

Parameters
----------
n : Node_index

Returns: Node_index";
constexpr const char* CGAL_Orthtree_first_child_at_depth = "finds node reached when descending the tree to a depth d and always choosing child 0.

Similar to deepest_first_child() , but does go to a fixed depth. n the index
of the node to find the d th first child of. d the depth to descend to. the
index of the d th first child, nothing if the tree is not deep enough.

Parameters
----------
n : Node_index
d : std::size_t

Returns: std::optional< Node_index >";
constexpr const char* CGAL_Orthtree_split = "splits a node into subnodes.

Only leaf nodes should be split. When a node is split it is no longer a leaf
node. The full set of degree children are constructed automatically, and their
values are set. Contents of this node are not propagated automatically, this
is responsibility of the distribute_node_contents_object in the traits class.
n index of the node to split

Parameters
----------
n : Node_index";
constexpr const char* CGAL_Orthtree_barycenter = "returns the center point of a node.

n index of the node to find the center point for the center point of node n

Parameters
----------
n : Node_index

Returns: Point";
constexpr const char* CGAL_Orthtree_adjacent_node = "finds the directly adjacent node in a specific direction

direction.to_ulong < 2 * dimension Adjacent nodes are found according to
several properties: adjacent nodes may be larger than the seek node, but never
smaller a node has at most 2 * dimension different adjacent nodes (in 3D:
left, right, up, down, front, back) adjacent nodes are not required to be leaf
nodes Here's a diagram demonstrating the concept for a quadtree:
+---------------+---------------+ | | | | | | | | | | A | | | | | | | | | | |
+-------+-------+---+---+-------+ | | | | | | | A | (S) +---A---+ | | | | | |
| +---+---+-------+---+---+-------+ | | | | | | +---+---+ A | | | | | | | | |
+---+---+-------+-------+-------+ (S) : Seek node A : Adjacent node Note how
the top adjacent node is larger than the seek node. The right adjacent node is
the same size, even though it contains further subdivisions. This
implementation returns the adjacent node if it's found. If there is no
adjacent node in that direction, it returns a null node. n index of the node
to find a neighbor of direction which way to find the adjacent node relative
to this one. Each successive bit selects the direction for the corresponding
dimension: for an octree in 3D, 010 means: negative direction in X, position
direction in Y, negative direction in Z. the index of the adjacent node if it
exists, nothing otherwise.

Parameters
----------
n : Node_index
direction : const Local_coordinates &

Returns: std::optional< Node_index >";
constexpr const char* CGAL_Orthtree_adjacent_node_1 = "equivalent to adjacent_node() , with an adjacency direction rather than a bitset.

n index of the node to find a neighbor of adjacency which way to find the
adjacent node relative to this one

Parameters
----------
n : Node_index
adjacency : Adjacency

Returns: std::optional< Node_index >";
constexpr const char* CGAL_Orthtree_is_topology_equal = "determines whether a pair of subtrees have the same topology.

lhsNode index of a node in lhsTree lhsTree an Orthtree rhsNode index of a node
in rhsTree rhsTree another Orthtree true if lhsNode and rhsNode have the same
topology, false otherwise

Parameters
----------
lhsNode : Node_index
lhsTree : const Self &
rhsNode : Node_index
rhsTree : const Self &

Returns: bool";
constexpr const char* CGAL_Orthtree_is_topology_equal_1 = "helper function for calling is_topology_equal() on the root nodes of two trees.

lhs an Orthtree rhs another Orthtree true if lhs and rhs have the same
topology, and false otherwise

Parameters
----------
lhs : const Self &
rhs : const Self &

Returns: bool";



// CGAL::Orthtree_traits
constexpr const char* CGAL_Orthtree_traits__class__ = "Traits class for defining an orthtree using the class CGAL::Orthtree without storing data in the nodes.";


// CGAL::Orthtree_traits_base
constexpr const char* CGAL_Orthtree_traits_base__class__ = "The class Orthtree_traits_base is a base class providing common choices for types and functors.";

constexpr const char* CGAL_Orthtree_traits_base_Adjacency = "Adjacency type.

This type is used to identify adjacency directions with easily understandable
keywords (left, right, up, down, ...) and is thus mainly useful in 2D and 3D.
In higher dimensions, such keywords do not exist and this type is simply an
integer. Conversions from this integer to bitsets still work but do not
provide any user-friendly API for adjacency selection. Two directions along
each axis in Cartesian space, relative to a node. Directions are mapped to
numbers as 3-bit integers in the 3D case or as 2-bit integers in the 2D case.
In the 3d case the numbers 6 and 7 are not used because there are only 6
different directions. The first two bits indicate the axis (00 = x, 01 = y, 10
= z), the third bit indicates the direction along that axis (0 = -, 1 = +).
The following diagram and table showing the 3D case may be a useful reference
(2D case is identical with one dimension less): 3 * | * 4 | / y+ |/ * 0
*------+------* 1 | /| | / | +-----* x+ 5 * | / * 2 / * z+ This lookup table
may also be helpful: Direction bitset number Enum -x 000 0 LEFT +x 001 1 RIGHT
-y 010 2 DOWN +y 011 3 UP -z 100 4 BACK +z 101 5 FRONT

Returns: int";




// CGAL::Orthtree_traits_face_graph
constexpr const char* CGAL_Orthtree_traits_face_graph__class__ = "Traits class for the Orthtree class to be used to construct a 3D octree around a triangulated surface mesh.";


// CGAL::Orthtree_traits_face_graph::Split_predicate_node_min_extent
constexpr const char* CGAL_Orthtree_traits_face_graph_Split_predicate_node_min_extent__class__ = "Recommended split predicate to pass to Orthtree::refine() function so that the octree is refined until a node is either empty or has an extent that would be smaller after split than the corresponding value provided to the constructor.";

constexpr const char* CGAL_Orthtree_traits_face_graph_Split_predicate_node_min_extent_Split_predicate_node_min_extent = "constructor with me being the minimal value a node extent could be (same value for all dimension).

Parameters
----------
me : const FT &";
constexpr const char* CGAL_Orthtree_traits_face_graph_Split_predicate_node_min_extent_Split_predicate_node_min_extent_1 = "constructor with me being the minimal value a node extent could be (one value per dimension).

Parameters
----------
me : const std::array< FT, 3 > &";
constexpr const char* CGAL_Orthtree_traits_face_graph_Split_predicate_node_min_extent_operator = "returns true if ni should be split, false otherwise.

Parameters
----------
ni : NodeIndex
tree : const Tree &

Returns: bool";

// CGAL::Orthtree_traits_point
constexpr const char* CGAL_Orthtree_traits_point__class__ = "Traits class for defining an orthtree of points using the class CGAL::Orthtree .";








// CGAL::Orthtrees::Leaves_traversal
constexpr const char* CGAL_Orthtrees_Leaves_traversal__class__ = "A class used for performing a traversal on leaves only.";


// CGAL::Orthtrees::Level_traversal
constexpr const char* CGAL_Orthtrees_Level_traversal__class__ = "A class used for performing a traversal of a specific depth level.";

constexpr const char* CGAL_Orthtrees_Level_traversal_Level_traversal = "constructs a depth -level traversal.

Parameters
----------
orthtree : const Tree &
depth : std::size_t";

// CGAL::Orthtrees::Maximum_contained_elements
constexpr const char* CGAL_Orthtrees_Maximum_contained_elements__class__ = "A class used to choose when a node should be split depending on the number of contained elements.";

constexpr const char* CGAL_Orthtrees_Maximum_contained_elements_Maximum_contained_elements = "creates a predicate based on the number of contained elements.

Parameters
----------
bucket_size : std::size_t";
constexpr const char* CGAL_Orthtrees_Maximum_contained_elements_operator = "returns true if the node with index i should be split, false otherwise.

Parameters
----------
i : typename Orthtree < GeomTraits >::Node_index
tree : const Orthtree < GeomTraits > &

Returns: bool";

// CGAL::Orthtrees::Maximum_depth
constexpr const char* CGAL_Orthtrees_Maximum_depth__class__ = "A class used to choose when a node should be split depending on the depth.";

constexpr const char* CGAL_Orthtrees_Maximum_depth_Maximum_depth = "creates a maximum depth predicate.

Parameters
----------
max_depth : std::size_t";
constexpr const char* CGAL_Orthtrees_Maximum_depth_operator = "returns true if the node with index i should be split, false otherwise.

Parameters
----------
i : typename Orthtree < GeomTraits >::Node_index
tree : const Orthtree < GeomTraits > &

Returns: bool";

// CGAL::Orthtrees::Maximum_depth_and_maximum_contained_elements
constexpr const char* CGAL_Orthtrees_Maximum_depth_and_maximum_contained_elements__class__ = "A class used to choose when a node should be split depending on the depth and the number of contained elements.";

constexpr const char* CGAL_Orthtrees_Maximum_depth_and_maximum_contained_elements_Maximum_depth_and_maximum_contained_elements = "creates a predicate using maximum depth or bucket size.

Parameters
----------
max_depth : std::size_t
bucket_size : std::size_t";
constexpr const char* CGAL_Orthtrees_Maximum_depth_and_maximum_contained_elements_operator = "returns true if the node with index i should be split, false otherwise.

Parameters
----------
i : typename Orthtree < GeomTraits >::Node_index
tree : const Orthtree < GeomTraits > &

Returns: bool";

// CGAL::Orthtrees::Postorder_traversal
constexpr const char* CGAL_Orthtrees_Postorder_traversal__class__ = "A class used for performing a postorder traversal.";


// CGAL::Orthtrees::Preorder_traversal
constexpr const char* CGAL_Orthtrees_Preorder_traversal__class__ = "A class used for performing a preorder traversal.";


// CollectionPartitioningOrthtreeTraits
constexpr const char* CollectionPartitioningOrthtreeTraits__class__ = "Refinement of the OrthtreeTraitsWithData concept, adding requirements for the traits class of a CGAL::Orthtree in order to supports nearest-neighbor searching.";

constexpr const char* CollectionPartitioningOrthtreeTraits_Sphere_d = "Sphere Type used for the shrinking-sphere approach for neighbor queries; needs to be copy assignable.

Returns: unspecified_type";
constexpr const char* CollectionPartitioningOrthtreeTraits_Node_data = "The data type contained by each node; must be a model of ForwardRange in addition to default constructible, copy constructible and copy assignable.

Returns: unspecified_type";
constexpr const char* CollectionPartitioningOrthtreeTraits_Node_data_element = "An element of the Node_data list-like type.

Must be constructible from the value type of a Node_data::iterator . Typically
the same as that type, but can also be an std::reference_wrapper<> if the type
is not copyable.

Returns: unspecified_type";
constexpr const char* CollectionPartitioningOrthtreeTraits_Squared_distance_of_element = "Functor with an operator that calculates the squared distance of a Node_data_element from a point.

Provides the operator: FT operator()(const Node_data_element &, const
Point_d&)

Returns: unspecified_type";
constexpr const char* CollectionPartitioningOrthtreeTraits_Construct_sphere_d = "Functor with an operator that constructs a Sphere_d from a provided center and squared radius.

Provides the operator: Sphere_d operator()(const Point_d&, const FT&)

Returns: unspecified_type";
constexpr const char* CollectionPartitioningOrthtreeTraits_Construct_center_d = "Functor with an operator that provides the center of a Sphere_d .

Provides the operator: Point_d operator()(const Sphere_d &)

Returns: unspecified_type";
constexpr const char* CollectionPartitioningOrthtreeTraits_Compute_squared_radius_d = "Functor with an operator that provides the squared radius of a Sphere_d .

Provides the operator: FT operator()(const Sphere_d &)

Returns: unspecified_type";
constexpr const char* CollectionPartitioningOrthtreeTraits_construct_sphere_d_object = "constructs an object of type ConstructSphere_d .

Returns: Construct_sphere_d";
constexpr const char* CollectionPartitioningOrthtreeTraits_construct_center_d_object = "constructs an object of type ConstructCenter_d .

Returns: Construct_center_d";
constexpr const char* CollectionPartitioningOrthtreeTraits_compute_squared_radius_d_object = "constructs an object of type ComputeSquaredRadius_d .

Returns: Compute_squared_radius_d";
constexpr const char* CollectionPartitioningOrthtreeTraits_squared_distance_of_element_object = "constructs an object of type Squared_distance_of_element .

Returns: Squared_distance_of_element";

// OrthtreeTraits
constexpr const char* OrthtreeTraits__class__ = "The concept OrthtreeTraits defines the requirements for the template parameter of the CGAL::Orthtree class.";

constexpr const char* OrthtreeTraits_Node_index = "An integer type for nodes.

Returns: unspecified_type";
constexpr const char* OrthtreeTraits_FT = "The number type of the Cartesian coordinates of types Point_d .

Returns: unspecified_type";
constexpr const char* OrthtreeTraits_Point_d = "Point type.

Returns: unspecified_type";
constexpr const char* OrthtreeTraits_Bbox_d = "Bounding box type. Must be constructible from a pair of Point_d objects.

Returns: unspecified_type";
constexpr const char* OrthtreeTraits_Cartesian_const_iterator_d = "A random access iterator type to enumerate the Cartesian coordinates of a point of type Point_d .

Returns: unspecified_type";
constexpr const char* OrthtreeTraits_Adjacency = "Integral number type which can take on values indicating adjacency directions.

Must be able to take on values ranging from 0 to the number of faces of the
(hyper)rectangle type, equivalent to 2 * D. Specify the adjacency directions

Returns: unspecified_type";
constexpr const char* OrthtreeTraits_Construct_root_node_bbox = "Functor with an operator to create the bounding box of the root node.

Provides the operator: Bbox_d operator()() The bounding box must enclose all
elements contained by the tree. It may be tight-fitting. The orthtree
constructor produces a bounding box surrounding this region. For traits which
assign no data to each node, this can be defined to return a fixed region.

Returns: unspecified_type";
constexpr const char* OrthtreeTraits_Construct_point_d = "Functor with an operator to construct a Point_d from an initializer list of type FT .

Provides the operator: Point_d operator()(arg1, arg2,...) For trees which use
a different kernel for the bounding box type, the return type of this functor
must match the kernel used by the bounding box type and not that of the
contents.

Returns: unspecified_type";
constexpr const char* OrthtreeTraits_dimension = "Dimension.

Returns: int";
constexpr const char* OrthtreeTraits_construct_root_node_bbox_object = "constructs an object of type Construct_root_node_bbox .

Returns: Construct_root_node_bbox";
constexpr const char* OrthtreeTraits_construct_point_d_object = "constructs an object of type Construct_point_d .

Returns: Construct_point_d";

// OrthtreeTraitsWithData
constexpr const char* OrthtreeTraitsWithData__class__ = "The concept OrthtreeTraitsWithData defines the requirements for the template parameter of the CGAL::Orthtree class for a node type that stores data.";

constexpr const char* OrthtreeTraitsWithData_Node_data = "The data type contained by each node.

Must be default constructible, copy constructible and copy assignable.

Returns: unspecified_type";
constexpr const char* OrthtreeTraitsWithData_Construct_root_node_contents = "Functor which initializes elements contained by the root node.

Each node of a tree has an associated Node_data value. This functor
initializes the Node_data of the root node. It takes no arguments, and returns
an instance of Node_data . Provides the operator: Node_data operator()()
Typically, the Node_data of the root node contains all the elements in the
tree. For a tree in which each node contains a span (such as std::span() )
this function would return the span containing all items.

Returns: unspecified_type";
constexpr const char* OrthtreeTraitsWithData_Distribute_node_contents = "Functor which fills the contents of the nodes children.

Provides the operator: void operator()(Node_index, Orthtree<Traits>&, const
Point_d&) The functor is called during refinement of the Orthtree on a node
after it has been split. The purpose of the functor is to distribute the
Node_data , accessible via tree.data() , to the data of the nodes children,
accessible via tree.children() . The first parameter is the Node_index of the
node. The second parameter provides the instance of the Orthtree and the last
parameter is the barycenter of the node which will be used as shared corner
amongst the children of the node. For a tree in which each node contains a
span, this may mean rearranging the contents of the original node and
producing spans containing a subset of its contents for each of its children.
For compatibility with locate, the center of the node is considered to be part
of the upper half.

Returns: unspecified_type";
constexpr const char* OrthtreeTraitsWithData_construct_root_node_contents_object = "constructs an object of type Construct_root_node_contents .

Returns: Construct_root_node_contents";
constexpr const char* OrthtreeTraitsWithData_distribute_node_contents_object = "constructs an object of type Distribute_node_contents .

Returns: Distribute_node_contents";

// OrthtreeTraversal
constexpr const char* OrthtreeTraversal__class__ = "Requirements for defining a traversal strategy of an orthtree.";

constexpr const char* OrthtreeTraversal_Node_index = "Index type of the orthtree to be traversed.

Returns: unspecified_type";
constexpr const char* OrthtreeTraversal_OrthtreeTraversal = "constructible from the orthtree it is meant to be used with.

Parameters
----------
o : const Orthtree &";
constexpr const char* OrthtreeTraversal_first_index = "returns the first node of the traversal.

Returns: Node_index";
constexpr const char* OrthtreeTraversal_next = "returns the next node to be traversed given the previous node n .

Parameters
----------
n : Node_index

Returns: Node_index";


// std
constexpr const char* std__class__ = "STL namespace.";

} // namespace Orthtree
} // namespace docstrings
} // namespace cgalpy

#endif // CGAL_PYTHON_DOCSTRINGS_ORTHTREE_H
