// AUTO-GENERATED by cpp_docstrings_from_json.py — DO NOT EDIT
// Package: Minkowski_sum_2
#ifndef CGAL_PYTHON_DOCSTRINGS_MINKOWSKI_SUM_2_H
#define CGAL_PYTHON_DOCSTRINGS_MINKOWSKI_SUM_2_H

namespace cgalpy {
namespace docstrings {
namespace Minkowski_sum_2 {

// CGAL::Greene_convex_decomposition_2
constexpr const char* Greene_convex_decomposition_2__class__ = "The Greene_convex_decomposition_2 class implements the approximation algorithm of Greene for the decomposition of an input polygon into convex sub-polygons [6] .";


// CGAL::Hertel_Mehlhorn_convex_decomposition_2
constexpr const char* Hertel_Mehlhorn_convex_decomposition_2__class__ = "The Hertel_Mehlhorn_convex_decomposition_2 class implements the approximation algorithm of Hertel and Mehlhorn for decomposing a polygon into convex sub-polygons [8] .";


// CGAL::Optimal_convex_decomposition_2
constexpr const char* Optimal_convex_decomposition_2__class__ = "The Optimal_convex_decomposition_2 class provides an implementation of Greene's dynamic programming algorithm for optimal decomposition of a polygon into convex sub-polygons [6] .";


// CGAL::Polygon_nop_decomposition_2
constexpr const char* Polygon_nop_decomposition_2__class__ = "The Polygon_nop_decomposition_2 class implements a convex decomposition of a polygon, which merely passes the input polygon to the list of output convex polygons.";

// CGAL::Polygon_triangulation_decomposition_2
constexpr const char* Polygon_triangulation_decomposition_2__class__ = "The Polygon_triangulation_decomposition_2 class implements a convex decomposition of a polygon or a polygon with holes into triangles using the Delaunay constrained triangulation functionality of the 2D Triangulation package.";

// CGAL::Polygon_vertical_decomposition_2
constexpr const char* Polygon_vertical_decomposition_2__class__ = "The Polygon_vertical_decomposition_2 class implements a convex decomposition of a polygon or a polygon with holes into pseudo trapezoids utilizing the CGAL::decompose() free function of the 2D Arrangements package.";

// CGAL::Small_side_angle_bisector_decomposition_2
constexpr const char* Small_side_angle_bisector_decomposition_2__class__ = "The Small_side_angle_bisector_decomposition_2 class implements a simple yet efficient heuristic for decomposing an input polygon into convex sub-polygons.";

// PolygonConvexDecomposition_2
constexpr const char* PolygonConvexDecomposition_2__class__ = "A model of the PolygonConvexDecomposition_2 concept is capable of decomposing an input polygon $ P$ into a set of convex sub-polygons $ P_1, \\ldots, P_k$ , such that $ \\cup_{i=1}^{k}{P_k} = P$ .";

constexpr const char* PolygonConvexDecomposition_2_Kernel = "the geometric kernel type.

Returns: unspecified_type";
constexpr const char* PolygonConvexDecomposition_2_Container = "the container of points type.

By default it is std::vector<typename Kernel::Point_2> .

Returns: unspecified_type";
constexpr const char* PolygonConvexDecomposition_2_Point_2 = "the point type, used to represent polygon vertices.

Returns: unspecified_type";
constexpr const char* PolygonConvexDecomposition_2_Polygon_2 = "the polygon type, defined as Polygon_2 < Kernel , Container > .

Returns: unspecified_type";
constexpr const char* PolygonConvexDecomposition_2_PolygonConvexDecomposition_2 = "default constructor.";
constexpr const char* PolygonConvexDecomposition_2_operator = "decomposes the input polygon P into convex sub-polygons, and writes them to the output iterator oi .

The value-type of the output iterator must be Polygon_2 . The function returns
a past-the-end iterator for the convex sub-polygons.

Parameters
----------
P : const Polygon_2 &
oi : OutputIterator

Returns: OutputIterator";

// PolygonWithHolesConvexDecomposition_2
constexpr const char* PolygonWithHolesConvexDecomposition_2__class__ = "A model of the PolygonWithHolesConvexDecomposition_2 concept is capable of decomposing an input polygon $ P$ , which may have holes, into a set of convex sub-polygons $ P_1, \\ldots, P_k$ , such that $ \\cup_{i=1}^{k}{P_k} = P$ .";

constexpr const char* PolygonWithHolesConvexDecomposition_2_Polygon_with_holes_2 = "the polygon with holes type, defined as Polygon_with_holes_2 <Kernel,Container> .

Returns: unspecified_type";
constexpr const char* PolygonWithHolesConvexDecomposition_2_PolygonWithHolesConvexDecomposition_2 = "default constructor.";
constexpr const char* PolygonWithHolesConvexDecomposition_2_operator = "decomposes the input polygon with holes P into convex sub-polygons, and writes them to the output iterator oi .

The value-type of the output iterator must be Polygon_2 . The function returns
a past-the-end iterator for the convex sub-polygons.

Parameters
----------
P : const Polygon_with_holes_2 &
oi : OutputIterator

Returns: OutputIterator";

// std
constexpr const char* std__class__ = "STL namespace.";

} // namespace Minkowski_sum_2
} // namespace docstrings
} // namespace cgalpy

#endif // CGAL_PYTHON_DOCSTRINGS_MINKOWSKI_SUM_2_H
