// AUTO-GENERATED by cpp_docstrings_from_json.py — DO NOT EDIT
// Package: HalfedgeDS
#ifndef CGAL_PYTHON_DOCSTRINGS_HALFEDGEDS_H
#define CGAL_PYTHON_DOCSTRINGS_HALFEDGEDS_H

namespace cgalpy {
namespace docstrings {
namespace HalfedgeDS {

// CGAL::HalfedgeDS_const_decorator
constexpr const char* CGAL_HalfedgeDS_const_decorator__class__ = "The class CGAL::HalfedgeDS_items_decorator <HDS> provides additional functions for vertices, halfedges, and faces of a halfedge data structure without knowing the containing halfedge data structure.";

constexpr const char* CGAL_HalfedgeDS_const_decorator_HalfedgeDS_const_decorator = "keeps internally a const reference to hds .

Parameters
----------
hds : const HDS &";
constexpr const char* CGAL_HalfedgeDS_const_decorator_is_valid = "returns true if the halfedge data structure hds is valid with respect to the level value as defined above.

If verbose is true , statistics are written to cerr .

Parameters
----------
verbose : bool
level : int

Returns: bool";
constexpr const char* CGAL_HalfedgeDS_const_decorator_normalized_border_is_valid = "returns true if the border halfedges are in normalized representation, which is when enumerating all halfedges with the halfedge iterator the following holds: The non-border edges precede the border edges.

For border edges, the second halfedge is a border halfedge. (The first
halfedge may or may not be a border halfedge.) The halfedge iterator
HalfedgeDS::border_halfedges_begin() denotes the first border edge. If verbose
is true , statistics are written to cerr .

Parameters
----------
verbose : bool

Returns: bool";

// CGAL::HalfedgeDS_decorator
constexpr const char* CGAL_HalfedgeDS_decorator__class__ = "The class CGAL::HalfedgeDS_items_decorator <HDS> provides additional functions for vertices, halfedges, and faces of a halfedge data structure without knowing the containing halfedge data structure.";

constexpr const char* CGAL_HalfedgeDS_decorator_HalfedgeDS_decorator = "keeps internally a reference to hds .

Parameters
----------
hds : HDS &";
constexpr const char* CGAL_HalfedgeDS_decorator_vertices_push_back = "appends a copy of v to hds if vertices are supported.

Returns a handle of the new vertex, or Vertex_handle() otherwise.

Parameters
----------
v : const Vertex &

Returns: Vertex_handle";
constexpr const char* CGAL_HalfedgeDS_decorator_faces_push_back = "appends a copy of f to hds if faces are supported.

Returns a handle of the new face, or Face_handle() otherwise.

Parameters
----------
f : const Face &

Returns: Face_handle";
constexpr const char* CGAL_HalfedgeDS_decorator_create_loop = "returns handle of a halfedge from a newly created loop in hds consisting of a single closed edge, one vertex and two faces (if supported respectively).

Returns: Halfedge_handle";
constexpr const char* CGAL_HalfedgeDS_decorator_create_segment = "returns a halfedge from a newly created segment in hds consisting of a single open edge, two vertices and one face (if supported respectively).

Returns: Halfedge_handle";
constexpr const char* CGAL_HalfedgeDS_decorator_vertices_pop_front = "removes the first vertex if vertices are supported.

Supports_removal must be CGAL::Tag_true .";
constexpr const char* CGAL_HalfedgeDS_decorator_vertices_pop_back = "removes the last vertex if vertices are supported.";
constexpr const char* CGAL_HalfedgeDS_decorator_vertices_erase = "removes the vertex v if vertices are supported.

Supports_removal must be CGAL::Tag_true .

Parameters
----------
v : Vertex_handle";
constexpr const char* CGAL_HalfedgeDS_decorator_vertices_erase_1 = "removes the range [first,last) if vertices are supported.

Supports_removal must be CGAL::Tag_true .

Parameters
----------
first : Vertex_handle
last : Vertex_handle";
constexpr const char* CGAL_HalfedgeDS_decorator_faces_pop_front = "removes the first face if faces are supported.

Supports_removal must be CGAL::Tag_true .";
constexpr const char* CGAL_HalfedgeDS_decorator_faces_pop_back = "removes the last face if faces are supported.";
constexpr const char* CGAL_HalfedgeDS_decorator_faces_erase = "removes the face f if faces are supported.

Supports_removal must be CGAL::Tag_true .

Parameters
----------
f : Face_handle";
constexpr const char* CGAL_HalfedgeDS_decorator_faces_erase_1 = "removes the range [first,last) if faces are supported.

Supports_removal must be CGAL::Tag_true .

Parameters
----------
first : Face_handle
last : Face_handle";
constexpr const char* CGAL_HalfedgeDS_decorator_erase_face = "removes the face incident to h from hds and changes all halfedges incident to the face into border edges or removes them from the halfedge data structure if they were already border edges.

If this creates isolated vertices they get removed as well. See make_hole()
for a more specialized variant. h->is_border() == false . If faces are
supported, Supports_removal must be CGAL::Tag_true .

Parameters
----------
h : Halfedge_handle";
constexpr const char* CGAL_HalfedgeDS_decorator_erase_connected_component = "removes the vertices, halfedges, and faces that belong to the connected component of h .

For all halfedges g in the connected component g.next() != Halfedge_handle() .
Supports_removal must be CGAL::Tag_true .

Parameters
----------
h : Halfedge_handle";
constexpr const char* CGAL_HalfedgeDS_decorator_keep_largest_connected_components = "Erases the small connected components and the isolated vertices.

Keep nb_components_to_keep largest connected components. Returns the number of
connected components erased (ignoring isolated vertices). Supports_removal
must be CGAL::Tag_true , Supports_vertex_halfedge must be CGAL::Tag_true and
Supports_halfedge_vertex must be CGAL::Tag_true .

Parameters
----------
nb_components_to_keep : unsigned int

Returns: unsigned int";
constexpr const char* CGAL_HalfedgeDS_decorator_make_hole = "removes the face incident to h from hds and creates a hole.

h != Halfedge_handle() and !(h->is_border()) . If faces are supported,
Supports_removal must be CGAL::Tag_true .

Parameters
----------
h : Halfedge_handle";
constexpr const char* CGAL_HalfedgeDS_decorator_fill_hole = "fills the hole incident to h with a new face from hds .

Returns h . h != Halfedge_handle() and h->is_border() .

Parameters
----------
h : Halfedge_handle

Returns: Halfedge_handle";
constexpr const char* CGAL_HalfedgeDS_decorator_fill_hole_1 = "fills the hole incident to h with a copy of face f .

Returns h . h != Halfedge_handle() and h->is_border() .

Parameters
----------
h : Halfedge_handle
f : const Face &

Returns: Halfedge_handle";
constexpr const char* CGAL_HalfedgeDS_decorator_add_face_to_border = "extends the surface with a new face from hds into the hole incident to h and g .

It creates a new edge connecting the vertex denoted by g with the vertex
denoted by h and fills this separated part of the hole with a new face, such
that the new face is incident to g . Returns the new halfedge that is incident
to the new face. h != Halfedge_handle() , g != Halfedge_handle() ,
h->is_border() , g->is_border() and g can be reached along the hole starting
with h .

Parameters
----------
h : Halfedge_handle
g : Halfedge_handle

Returns: Halfedge_handle";
constexpr const char* CGAL_HalfedgeDS_decorator_add_face_to_border_1 = "extends the surface with a copy of face f into the hole incident to h and g .

It creates a new edge connecting the tip of g with the tip of h and fills this
separated part of the hole with a copy of face f , such that the new face is
incident to g . Returns the new halfedge that is incident to the new face. h
!= Halfedge_handle() , g != Halfedge_handle() , h->is_border() ,
g->is_border() and g can be reached along the hole starting with h .

Parameters
----------
h : Halfedge_handle
g : Halfedge_handle
f : const Face &

Returns: Halfedge_handle";
constexpr const char* CGAL_HalfedgeDS_decorator_split_face = "splits the face incident to h and g into two faces with a new diagonal between the two vertices denoted by h and g respectively.

The second (new) face obtained from hds is a copy of the first face. Returns
h->next() after the operation, i.e., the new diagonal. The new face is to the
right of the new diagonal, the old face is to the left. The time is
proportional to the distance from h to g around the face.

Parameters
----------
h : Halfedge_handle
g : Halfedge_handle

Returns: Halfedge_handle";
constexpr const char* CGAL_HalfedgeDS_decorator_join_face = "joins the two faces incident to h .

The face incident to h->opposite() gets removed from hds . Both faces might be
holes. Returns the predecessor of h around the face. The invariant join_face(
split_face( h, g)) returns h and keeps the data structure unchanged. The time
is proportional to the size of the face removed and the time to compute
h->prev() . Supports_removal must be CGAL::Tag_true .

Parameters
----------
h : Halfedge_handle

Returns: Halfedge_handle";
constexpr const char* CGAL_HalfedgeDS_decorator_split_vertex = "splits the vertex incident to h and g into two vertices and connects them with a new edge.

The second (new) vertex obtained from hds is a copy of the first vertex.
Returns h->next()->opposite() after the operation, i.e., the new edge in the
orientation towards the new vertex. The time is proportional to the distance
from h to g around the vertex.

Parameters
----------
h : Halfedge_handle
g : Halfedge_handle

Returns: Halfedge_handle";
constexpr const char* CGAL_HalfedgeDS_decorator_join_vertex = "joins the two vertices incident to h .

The vertex denoted by h->opposite() gets removed by hds . Returns the
predecessor of h around the vertex, i.e., h->opposite()->prev() . The
invariant join_vertex( split_vertex( h, g)) returns h and keeps the polyhedron
unchanged. The time is proportional to the degree of the vertex removed and
the time to compute h->prev() and h->opposite()->prev() . Supports_removal
must be CGAL::Tag_true .

Parameters
----------
h : Halfedge_handle

Returns: Halfedge_handle";
constexpr const char* CGAL_HalfedgeDS_decorator_create_center_vertex = "barycentric triangulation of h->face() .

Creates a new vertex, a copy of h->vertex() , and connects it to each vertex
incident to h->face() splitting h->face() into triangles. h remains incident
to the original face, all other triangles are copies of this face. Returns the
halfedge h->next() after the operation, i.e., a halfedge pointing to the new
vertex. The time is proportional to the size of the face. h is not a border
halfedge.

Parameters
----------
h : Halfedge_handle

Returns: Halfedge_handle";
constexpr const char* CGAL_HalfedgeDS_decorator_erase_center_vertex = "reverses create_center_vertex .

Erases the vertex pointed to by g and all incident halfedges thereby merging
all incident faces. Only g->face() remains. The neighborhood of g->vertex()
may not be triangulated, it can have larger faces. Returns the halfedge
g->prev() . Thus, the invariant h == erase_center_vertex(
create_center_vertex(h)) holds if h is not a border halfedge. The time is
proportional to the sum of the size of all incident faces. None of the
incident faces of g->vertex() is a hole. There are at least two distinct faces
incident to the faces that are incident to g->vertex() . (This prevents the
operation from collapsing a volume into two faces glued together with opposite
orientations, such as would happen with any vertex of a tetrahedron.)
Supports_removal must be CGAL::Tag_true .

Parameters
----------
g : Halfedge_handle

Returns: Halfedge_handle";
constexpr const char* CGAL_HalfedgeDS_decorator_split_loop = "cuts the halfedge data structure into two parts along the cycle (h,i,j) .

Three new vertices (one copy for each vertex in the cycle) and three new
halfedges (one copy for each halfedge in the cycle), and two new triangles are
created. h,i,j will be incident to the first new triangle. The return value
will be the halfedge incident to the second new triangle which is the copy of
h-opposite() . h,i,j denote distinct, consecutive vertices of the halfedge
data structure and form a cycle: i.e., h->vertex() == i->opposite()->vertex()
, $\\ldots$ , j->vertex() == h->opposite()->vertex() .

Parameters
----------
h : Halfedge_handle
i : Halfedge_handle
j : Halfedge_handle

Returns: Halfedge_handle";
constexpr const char* CGAL_HalfedgeDS_decorator_join_loop = "glues the boundary of the two faces denoted by h and g together and returns h .

Both faces and the vertices along the face denoted by g gets removed. Both
faces may be holes. The invariant join_loop( h, split_loop( h, i, j)) returns
h and keeps the data structure unchanged. The faces denoted by h and g are
different and have equal degree (i.e., number of edges). Supports_removal must
be CGAL::Tag_true .

Parameters
----------
h : Halfedge_handle
g : Halfedge_handle

Returns: Halfedge_handle";
constexpr const char* CGAL_HalfedgeDS_decorator_inside_out = "reverses face orientations.

is_valid() of level three.";

// CGAL::HalfedgeDS_default
constexpr const char* CGAL_HalfedgeDS_default__class__ = "The class HalfedgeDS_default is a model for the HalfedgeDS concept.";


// CGAL::HalfedgeDS_face_base
constexpr const char* CGAL_HalfedgeDS_face_base__class__ = "The class HalfedgeDS_face_base is a model of the HalfedgeDSFace concept.";

constexpr const char* CGAL_HalfedgeDS_face_base_Plane = "plane type for three argument version.

Returns: unspecified_type";
constexpr const char* CGAL_HalfedgeDS_face_base_HalfedgeDS_face_base = "default constructor.";
constexpr const char* CGAL_HalfedgeDS_face_base_HalfedgeDS_face_base_1 = "initialized with plane pln .

Parameters
----------
pln : const Plane &";

// CGAL::HalfedgeDS_face_min_base
constexpr const char* CGAL_HalfedgeDS_face_min_base__class__ = "The class HalfedgeDS_face_min_base is a model of the HalfedgeDSFace concept.";

constexpr const char* CGAL_HalfedgeDS_face_min_base_HalfedgeDS_face_min_base = "default constructor.";

// CGAL::HalfedgeDS_halfedge_base
constexpr const char* CGAL_HalfedgeDS_halfedge_base__class__ = "The class HalfedgeDS_halfedge_base is a model of the HalfedgeDSHalfedge concept.";

constexpr const char* CGAL_HalfedgeDS_halfedge_base_HalfedgeDS_halfedge_base = "default constructor.";

// CGAL::HalfedgeDS_halfedge_min_base
constexpr const char* CGAL_HalfedgeDS_halfedge_min_base__class__ = "The class HalfedgeDS_halfedge_min_base is a model of the HalfedgeDSHalfedge concept.";

constexpr const char* CGAL_HalfedgeDS_halfedge_min_base_HalfedgeDS_halfedge_min_base = "default constructor.";

// CGAL::HalfedgeDS_items_2
constexpr const char* CGAL_HalfedgeDS_items_2__class__ = "The class HalfedgeDS_items_2 is a model of the HalfedgeDSItems concept.";

// CGAL::HalfedgeDS_items_decorator
constexpr const char* CGAL_HalfedgeDS_items_decorator__class__ = "The class CGAL::HalfedgeDS_items_decorator <HDS> provides additional functions for vertices, halfedges, and faces of a halfedge data structure without knowing the containing halfedge data structure.";

constexpr const char* CGAL_HalfedgeDS_items_decorator_HalfedgeDS = "halfedge data structure.

Returns: unspecified_type";
constexpr const char* CGAL_HalfedgeDS_items_decorator_Vertex = "vertex type of HalfedgeDS .

Returns: unspecified_type";
constexpr const char* CGAL_HalfedgeDS_items_decorator_Halfedge = "halfedge type of HalfedgeDS .

Returns: unspecified_type";
constexpr const char* CGAL_HalfedgeDS_items_decorator_Face = "face type of HalfedgeDS .

Returns: unspecified_type";
constexpr const char* CGAL_HalfedgeDS_items_decorator_HalfedgeDS_items_decorator = "default constructor.";
constexpr const char* CGAL_HalfedgeDS_items_decorator_get_vertex_halfedge = "returns the incident halfedge of v if supported, Halfedge_handle() otherwise.

Parameters
----------
v : Vertex_handle

Returns: Halfedge_handle";
constexpr const char* CGAL_HalfedgeDS_items_decorator_get_vertex = "returns the incident vertex of h if supported, Vertex_handle() otherwise.

Parameters
----------
h : Halfedge_handle

Returns: Vertex_handle";
constexpr const char* CGAL_HalfedgeDS_items_decorator_get_prev = "returns the previous halfedge of h if supported, Halfedge_handle() otherwise.

Parameters
----------
h : Halfedge_handle

Returns: Halfedge_handle";
constexpr const char* CGAL_HalfedgeDS_items_decorator_find_prev = "returns the previous halfedge of h .

Uses the prev() method if supported or performs a search around the face using
next() .

Parameters
----------
h : Halfedge_handle

Returns: Halfedge_handle";
constexpr const char* CGAL_HalfedgeDS_items_decorator_find_prev_around_vertex = "returns the previous halfedge of h .

Uses the prev() method if supported or performs a search around the vertex
using next() .

Parameters
----------
h : Halfedge_handle

Returns: Halfedge_handle";
constexpr const char* CGAL_HalfedgeDS_items_decorator_get_face = "returns the incident face of h if supported, Face_handle() otherwise.

Parameters
----------
h : Halfedge_handle

Returns: Face_handle";
constexpr const char* CGAL_HalfedgeDS_items_decorator_get_face_halfedge = "returns the incident halfedge of f if supported, Halfedge_handle() otherwise.

Parameters
----------
f : Face_handle

Returns: Halfedge_handle";
constexpr const char* CGAL_HalfedgeDS_items_decorator_close_tip = "makes h->opposite() the successor of h .

Parameters
----------
h : Halfedge_handle";
constexpr const char* CGAL_HalfedgeDS_items_decorator_close_tip_1 = "makes h->opposite() the successor of h and sets the incident vertex of h to v .

Parameters
----------
h : Halfedge_handle
v : Vertex_handle";
constexpr const char* CGAL_HalfedgeDS_items_decorator_insert_tip = "inserts the tip of the edge h into the halfedges around the vertex pointed to by v .

Halfedge h->opposite() is the new successor of v and h->next() will be set to
v->next() . The vertex of h will be set to the vertex v refers to if vertices
are supported.

Parameters
----------
h : Halfedge_handle
v : Halfedge_handle";
constexpr const char* CGAL_HalfedgeDS_items_decorator_remove_tip = "removes the edge h->next()->opposite() from the halfedge circle around the vertex referred to by h .

The new successor halfedge of h will be h->next()->opposite()->next() .

Parameters
----------
h : Halfedge_handle";
constexpr const char* CGAL_HalfedgeDS_items_decorator_insert_halfedge = "inserts the halfedge h between f and f->next() .

The face of h will be the one f refers to if faces are supported.

Parameters
----------
h : Halfedge_handle
f : Halfedge_handle";
constexpr const char* CGAL_HalfedgeDS_items_decorator_remove_halfedge = "removes edge h->next() from the halfedge circle around the face referred to by h .

The new successor of h will be h->next()->next() .

Parameters
----------
h : Halfedge_handle";
constexpr const char* CGAL_HalfedgeDS_items_decorator_set_vertex_in_vertex_loop = "loops around the vertex incident to h and sets all vertex pointers to v .

h != Halfedge_handle() .

Parameters
----------
h : Halfedge_handle
v : Vertex_handle";
constexpr const char* CGAL_HalfedgeDS_items_decorator_set_face_in_face_loop = "loops around the face incident to h and sets all face pointers to f .

h != Halfedge_handle() .

Parameters
----------
h : Halfedge_handle
f : Face_handle";
constexpr const char* CGAL_HalfedgeDS_items_decorator_flip_edge = "performs an edge flip.

It returns h after rotating the edge h one vertex in the direction of the face
orientation. h != Halfedge_handle() and both incident faces of h are
triangles.

Parameters
----------
h : Halfedge_handle

Returns: Halfedge_handle";
constexpr const char* CGAL_HalfedgeDS_items_decorator_set_vertex_halfedge = "sets the incident halfedge of v to g .

Parameters
----------
v : Vertex_handle
g : Halfedge_handle";
constexpr const char* CGAL_HalfedgeDS_items_decorator_set_vertex_halfedge_1 = "sets the incident halfedge of the vertex v to h .

Parameters
----------
h : Halfedge_handle";
constexpr const char* CGAL_HalfedgeDS_items_decorator_set_vertex = "sets the incident vertex of h to v .

Parameters
----------
h : Halfedge_handle
v : Vertex_handle";
constexpr const char* CGAL_HalfedgeDS_items_decorator_set_prev = "sets the previous link of h to g .

Parameters
----------
h : Halfedge_handle
g : Halfedge_handle";
constexpr const char* CGAL_HalfedgeDS_items_decorator_set_face = "sets the incident face of h to f .

Parameters
----------
h : Halfedge_handle
f : Face_handle";
constexpr const char* CGAL_HalfedgeDS_items_decorator_set_face_halfedge = "sets the incident halfedge of f to g .

Parameters
----------
f : Face_handle
g : Halfedge_handle";
constexpr const char* CGAL_HalfedgeDS_items_decorator_set_face_halfedge_1 = "sets the incident halfedge of the face f to h .

Parameters
----------
h : Halfedge_handle";

// CGAL::HalfedgeDS_list
constexpr const char* CGAL_HalfedgeDS_list__class__ = "The class HalfedgeDS_list is a model for the HalfedgeDS concept.";

constexpr const char* CGAL_HalfedgeDS_list_vertices_splice = "inserts elements in the range [ first, last ) before position target and removes the elements from source .

It takes constant time if &source == &``hds ; otherwise, it takes linear time
in the size of the range. [ first, last ) is a valid range in source . target
is not in the range [ first, last ).

Parameters
----------
target : Vertex_iterator
source : Self &
first : Vertex_iterator
last : Vertex_iterator";
constexpr const char* CGAL_HalfedgeDS_list_halfedges_splice = "inserts elements in the range [ first, last ) before position target and removes the elements from source .

It takes constant time if &source == &``hds ; otherwise, it takes linear time
in the size of the range. [ first, last ) is a valid range in source . target
is not in the range [ first, last ).

Parameters
----------
target : Halfedge_iterator
source : Self &
first : Halfedge_iterator
last : Halfedge_iterator";
constexpr const char* CGAL_HalfedgeDS_list_faces_splice = "inserts elements in the range [ first, last ) before position target and removes the elements from source .

It takes constant time if &source == &``hds ; otherwise, it takes linear time
in the size of the range. [ first, last ) is a valid range in source . target
is not in the range [ first, last ).

Parameters
----------
target : Face_iterator
source : Self &
first : Face_iterator
last : Face_iterator";

// CGAL::HalfedgeDS_min_items
constexpr const char* CGAL_HalfedgeDS_min_items__class__ = "The class HalfedgeDS_min_items is a model of the HalfedgeDSItems concept.";

// CGAL::HalfedgeDS_vector
constexpr const char* CGAL_HalfedgeDS_vector__class__ = "The class HalfedgeDS_vector is a model for the HalfedgeDS concept.";


// CGAL::HalfedgeDS_vertex_base
constexpr const char* CGAL_HalfedgeDS_vertex_base__class__ = "The class HalfedgeDS_vertex_base is a model of the HalfedgeDSVertex concept.";

constexpr const char* CGAL_HalfedgeDS_vertex_base_Point = "point type for three argument version.

Returns: unspecified_type";
constexpr const char* CGAL_HalfedgeDS_vertex_base_HalfedgeDS_vertex_base = "default constructor.";
constexpr const char* CGAL_HalfedgeDS_vertex_base_HalfedgeDS_vertex_base_1 = "initialized with point p .

Parameters
----------
p : const Point &";

// CGAL::HalfedgeDS_vertex_min_base
constexpr const char* CGAL_HalfedgeDS_vertex_min_base__class__ = "The class HalfedgeDS_vertex_min_base is a model of the HalfedgeDSVertex concept.";

constexpr const char* CGAL_HalfedgeDS_vertex_min_base_HalfedgeDS_vertex_min_base = "default constructor.";

// HalfedgeDS
constexpr const char* HalfedgeDS__class__ = "The concept of a halfedge data structure (abbreviated as HalfedgeDS , or HDS for template parameters) defines an edge-centered data structure capable of maintaining incidence information of vertices, edges, and faces, for example for planar maps or polyhedral surfaces. It is a combinatorial data structure, geometric interpretation is added by classes built on top of the halfedge data structure.";

constexpr const char* HalfedgeDS_Items = "model of HalfedgeDSItems concept.

Returns: unspecified_type";
constexpr const char* HalfedgeDS_size_type = "size type.

Returns: unspecified_type";
constexpr const char* HalfedgeDS_difference_type = "difference type.

Returns: unspecified_type";
constexpr const char* HalfedgeDS_iterator_category = "iterator category for all iterators.

Returns: unspecified_type";
constexpr const char* HalfedgeDS_allocator_type = "allocator type Alloc .

Returns: unspecified_type";
constexpr const char* HalfedgeDS_Vertex = "model of HalfedgeDSVertex concept.

Returns: unspecified_type";
constexpr const char* HalfedgeDS_Halfedge = "model of HalfedgeDSHalfedge concept.

Returns: unspecified_type";
constexpr const char* HalfedgeDS_Face = "model of HalfedgeDSFace concept.

Returns: unspecified_type";
constexpr const char* HalfedgeDS_Vertex_handle = "handle to vertex.

Returns: unspecified_type";
constexpr const char* HalfedgeDS_Halfedge_handle = "handle to halfedge.

Returns: unspecified_type";
constexpr const char* HalfedgeDS_Face_handle = "handle to face.

Returns: unspecified_type";
constexpr const char* HalfedgeDS_Vertex_iterator = "iterator over all vertices.

Returns: unspecified_type";
constexpr const char* HalfedgeDS_Halfedge_iterator = "iterator over all halfedges.

Returns: unspecified_type";
constexpr const char* HalfedgeDS_Face_iterator = "iterator over all faces.

Returns: unspecified_type";
constexpr const char* HalfedgeDS_Vertex_handles = "range type for iterating over the vertices, with a nested type iterator that has as value type Vertex_handle

Returns: Iterator_range< unspecified_type >";
constexpr const char* HalfedgeDS_Halfedge_handles = "range type for iterating over the halfedges, with a nested type iterator that has as value type Halfedge_handle

Returns: Iterator_range< unspecified_type >";
constexpr const char* HalfedgeDS_Face_handles = "range type for iterating over the faces, with a nested type iterator that has as value type Face_handle

Returns: Iterator_range< unspecified_type >";
constexpr const char* HalfedgeDS_Supports_vertex_halfedge = "Vertex::halfedge() .

Returns: unspecified_type";
constexpr const char* HalfedgeDS_Supports_halfedge_prev = "Halfedge::prev() .

Returns: unspecified_type";
constexpr const char* HalfedgeDS_Supports_halfedge_vertex = "Halfedge::vertex() .

Returns: unspecified_type";
constexpr const char* HalfedgeDS_Supports_halfedge_face = "Halfedge::face() .

Returns: unspecified_type";
constexpr const char* HalfedgeDS_Supports_face_halfedge = "Face::halfedge() .

Returns: unspecified_type";
constexpr const char* HalfedgeDS_Supports_removal = "removal of individual elements.

Returns: unspecified_type";
constexpr const char* HalfedgeDS_HalfedgeDS = "empty halfedge data structure.";
constexpr const char* HalfedgeDS_HalfedgeDS_1 = "storage reserved for v vertices, h halfedges, and f faces.

Parameters
----------
v : size_type
h : size_type
f : size_type";
constexpr const char* HalfedgeDS_HalfedgeDS_2 = "copy constructor.

hds2 contains no dangling handles.

Parameters
----------
hds2 : const HalfedgeDS < Traits, Items , Alloc > &";
constexpr const char* HalfedgeDS_operator = "assignment operator.

hds2 contains no dangling handles.

Parameters
----------
hds2 : const HalfedgeDS < Traits, Items , Alloc > &

Returns: HalfedgeDS < Traits, Items , Alloc > &";
constexpr const char* HalfedgeDS_reserve = "reserves storage for v vertices, h halfedges, and f faces.

If all capacities are already greater or equal than the requested sizes
nothing happens. Otherwise, the halfedge data structure will be resized and
all handles, iterators and circulators are invalid. If resizing is necessary
the halfedge data structure contains no dangling handles.

Parameters
----------
v : size_type
h : size_type
f : size_type";
constexpr const char* HalfedgeDS_size_of_vertices = "number of vertices.

Returns: size_type";
constexpr const char* HalfedgeDS_size_of_halfedges = "number of halfedges.

Returns: size_type";
constexpr const char* HalfedgeDS_size_of_faces = "number of faces.

Returns: size_type";
constexpr const char* HalfedgeDS_capacity_of_vertices = "space reserved for vertices.

Returns: size_type";
constexpr const char* HalfedgeDS_capacity_of_halfedges = "space reserved for halfedges.

Returns: size_type";
constexpr const char* HalfedgeDS_capacity_of_faces = "space reserved for faces.

Returns: size_type";
constexpr const char* HalfedgeDS_bytes = "bytes used for the halfedge data structure.

Returns: size_t";
constexpr const char* HalfedgeDS_bytes_reserved = "bytes reserved for the halfedge data structure.

Returns: size_t";
constexpr const char* HalfedgeDS_get_allocator = "allocator object.

Returns: allocator_type";
constexpr const char* HalfedgeDS_vertices_begin = "iterator over all vertices.

Returns: Vertex_iterator";
constexpr const char* HalfedgeDS_vertex_handles = "returns a range of handles over the vertices.

The value type of Vertex_handles::iterator is Vertex_handle .

Returns: Vertex_handles";
constexpr const char* HalfedgeDS_halfedges_begin = "iterator over all halfedges

Returns: Halfedge_iterator";
constexpr const char* HalfedgeDS_halfedge_handles = "returns a range of handles over the halfedges.

The value type of Halfedge_handles::iterator is Halfedge_handle .

Returns: Halfedge_handles";
constexpr const char* HalfedgeDS_faces_begin = "iterator over all faces.

Returns: Face_iterator";
constexpr const char* HalfedgeDS_face_handles = "returns a range of handles over the faces.

The value type of Face_handles::iterator is Face_handle .

Returns: Face_handles";
constexpr const char* HalfedgeDS_vertices_push_back = "appends a copy of v to the halfedge data structure.

Returns a handle of the new vertex.

Parameters
----------
v : const Vertex &

Returns: Vertex_handle";
constexpr const char* HalfedgeDS_edges_push_back = "appends a copy of h and a copy of g to the halfedge data structure and makes them opposite to each other.

Returns a handle of the copy of h .

Parameters
----------
h : const Halfedge &
g : const Halfedge &

Returns: Halfedge_handle";
constexpr const char* HalfedgeDS_edges_push_back_1 = "appends a copy of h and a copy of h->opposite() to the halfedge data structure and makes them opposite to each other.

Returns a handle of the copy of h . h->opposite() denotes a halfedge.

Parameters
----------
h : const Halfedge &

Returns: Halfedge_handle";
constexpr const char* HalfedgeDS_faces_push_back = "appends a copy of f to the halfedge data structure.

Returns a handle of the new face.

Parameters
----------
f : const Face &

Returns: Face_handle";
constexpr const char* HalfedgeDS_vertices_pop_front = "removes the first vertex if vertices are supported and Supports_removal $ \\equiv$ CGAL::Tag_true .";
constexpr const char* HalfedgeDS_vertices_pop_back = "removes the last vertex.";
constexpr const char* HalfedgeDS_vertices_erase = "removes the vertex v if vertices are supported and Supports_removal $ \\equiv$ CGAL::Tag_true .

Parameters
----------
v : Vertex_handle";
constexpr const char* HalfedgeDS_vertices_erase_1 = "removes the range of vertices [first,last) if vertices are supported and Supports_removal $ \\equiv$ CGAL::Tag_true .

Parameters
----------
first : Vertex_handle
last : Vertex_handle";
constexpr const char* HalfedgeDS_edges_pop_front = "removes the first two halfedges if Supports_removal $ \\equiv$ CGAL::Tag_true .";
constexpr const char* HalfedgeDS_edges_pop_back = "removes the last two halfedges.";
constexpr const char* HalfedgeDS_edges_erase = "removes the pair of halfedges h and h->opposite() if Supports_removal $ \\equiv$ CGAL::Tag_true .

Parameters
----------
h : Halfedge_handle";
constexpr const char* HalfedgeDS_edges_erase_1 = "removes the range of edges [first},last) if Supports_removal $ \\equiv$ CGAL::Tag_true .

Parameters
----------
first : Halfedge_handle
last : Halfedge_handle";
constexpr const char* HalfedgeDS_faces_pop_front = "removes the first face if faces are supported and Supports_removal $ \\equiv$ CGAL::Tag_true .";
constexpr const char* HalfedgeDS_faces_pop_back = "removes the last face.";
constexpr const char* HalfedgeDS_faces_erase = "removes the face f if faces are supported and Supports_removal $ \\equiv$ CGAL::Tag_true .

Parameters
----------
f : Face_handle";
constexpr const char* HalfedgeDS_faces_erase_1 = "removes the range of faces [first,last) if faces are supported and Supports_removal $ \\equiv$ CGAL::Tag_true .

Parameters
----------
first : Face_handle
last : Face_handle";
constexpr const char* HalfedgeDS_vertices_clear = "removes all vertices.";
constexpr const char* HalfedgeDS_edges_clear = "removes all halfedges.";
constexpr const char* HalfedgeDS_faces_clear = "removes all faces.";
constexpr const char* HalfedgeDS_clear = "removes all elements.";
constexpr const char* HalfedgeDS_normalize_border = "sorts halfedges such that the non-border edges precede the border edges.

For each border edge that is incident to a face, the halfedge iterator will
reference the halfedge incident to the face right before the halfedge incident
to the open region.";
constexpr const char* HalfedgeDS_size_of_border_halfedges = "number of border halfedges.

An edge with no incident face counts as two border halfedges.
normalize_border() has been called and no halfedge insertion or removal and no
change in border status of the halfedges have occurred since then.

Returns: size_type";
constexpr const char* HalfedgeDS_size_of_border_edges = "number of border edges.

If size_of_border_edges() is equal to size_of_border_halfedges() all border
edges are incident to a face on one side and to an open region on the other
side. normalize_border() has been called and no halfedge insertion or removal
and no change in border status of the halfedges have occurred since then.

Returns: size_type";
constexpr const char* HalfedgeDS_border_halfedges_begin = "halfedge iterator starting with the border edges.

The range [ halfedges_begin() , border_halfedges_begin() ) denotes all
non-border edges. The range [ border_halfedges_begin() , halfedges_end() )
denotes all border edges. normalize_border() has been called and no halfedge
insertion or removal and no change in border status of the halfedges have
occurred since then.

Returns: Halfedge_iterator";

// HalfedgeDSFace
constexpr const char* HalfedgeDSFace__class__ = "The concept HalfedgeDSFace defines the requirements for the local Face type in the HalfedgeDS concept. It is also required in the Face_wrapper<Refs,Traits> member class template of an items class, see the HalfedgeDSItems concept.";

constexpr const char* HalfedgeDSFace_HalfedgeDS = "instantiated HalfedgeDS ( $ \\equiv$ Refs ).

Returns: unspecified_type";
constexpr const char* HalfedgeDSFace_Base = "base class that allows modifications.

Returns: unspecified_type";
constexpr const char* HalfedgeDSFace_Vertex = "model of HalfedgeDSVertex .

Returns: unspecified_type";
constexpr const char* HalfedgeDSFace_Halfedge = "model of HalfedgeDSHalfedge .

Returns: unspecified_type";
constexpr const char* HalfedgeDSFace_Vertex_handle = "handle to vertex.

Returns: unspecified_type";
constexpr const char* HalfedgeDSFace_Halfedge_handle = "handle to halfedge.

Returns: unspecified_type";
constexpr const char* HalfedgeDSFace_Face_handle = "handle to face.

Returns: unspecified_type";
constexpr const char* HalfedgeDSFace_Supports_face_halfedge = "CGAL::Tag_true or CGAL::Tag_false .

Returns: unspecified_type";
constexpr const char* HalfedgeDSFace_Face = "default constructor.";
constexpr const char* HalfedgeDSFace_halfedge = "incident halfedge that points to the face.

Returns: Halfedge_const_handle";
constexpr const char* HalfedgeDSFace_set_halfedge = "sets incident halfedge to h .

Parameters
----------
h : Halfedge_handle";

// HalfedgeDSHalfedge
constexpr const char* HalfedgeDSHalfedge__class__ = "The concept HalfedgeDSHalfedge defines the requirements for the local Halfedge type in the HalfedgeDS concept. It is also required in the Halfedge_wrapper<Refs,Traits> member class template of an items class, see the HalfedgeDSItems concept.";

constexpr const char* HalfedgeDSHalfedge_HalfedgeDS = "instantiated HalfedgeDS ( $ \\equiv$ Refs ).

Returns: unspecified_type";
constexpr const char* HalfedgeDSHalfedge_Base = "base class that allows modifications.

Returns: unspecified_type";
constexpr const char* HalfedgeDSHalfedge_Base_base = "base class to access set_opposite() .

Returns: unspecified_type";
constexpr const char* HalfedgeDSHalfedge_Vertex = "model of HalfedgeDSVertex .

Returns: unspecified_type";
constexpr const char* HalfedgeDSHalfedge_Face = "model of HalfedgeDSFace .

Returns: unspecified_type";
constexpr const char* HalfedgeDSHalfedge_Vertex_handle = "handle to vertex.

Returns: unspecified_type";
constexpr const char* HalfedgeDSHalfedge_Halfedge_handle = "handle to halfedge.

Returns: unspecified_type";
constexpr const char* HalfedgeDSHalfedge_Face_handle = "handle to face.

Returns: unspecified_type";
constexpr const char* HalfedgeDSHalfedge_Supports_halfedge_prev = "CGAL::Tag_true or CGAL::Tag_false .

Returns: unspecified_type";
constexpr const char* HalfedgeDSHalfedge_Supports_halfedge_vertex = "CGAL::Tag_true or CGAL::Tag_false .

Returns: unspecified_type";
constexpr const char* HalfedgeDSHalfedge_Supports_halfedge_face = "CGAL::Tag_true or CGAL::Tag_false .

Returns: unspecified_type";
constexpr const char* HalfedgeDSHalfedge_Halfedge = "default constructor.";
constexpr const char* HalfedgeDSHalfedge_opposite = "the opposite halfedge.

Returns: Halfedge_const_handle";
constexpr const char* HalfedgeDSHalfedge_set_opposite = "sets opposite halfedge to h .

Parameters
----------
h : Halfedge_handle";
constexpr const char* HalfedgeDSHalfedge_next = "the next halfedge around the face.

Returns: Halfedge_const_handle";
constexpr const char* HalfedgeDSHalfedge_set_next = "sets next halfedge to h .

Parameters
----------
h : Halfedge_handle";
constexpr const char* HalfedgeDSHalfedge_is_border = "is true if the halfedge is a border halfedge.

Returns: bool";
constexpr const char* HalfedgeDSHalfedge_prev = "the previous halfedge around the face.

Returns: Halfedge_const_handle";
constexpr const char* HalfedgeDSHalfedge_set_prev = "sets prev halfedge to h .

Parameters
----------
h : Halfedge_handle";
constexpr const char* HalfedgeDSHalfedge_vertex = "the incident vertex of h .

Returns: Vertex_const_handle";
constexpr const char* HalfedgeDSHalfedge_set_vertex = "sets incident vertex to v .

Parameters
----------
v : Vertex_handle";
constexpr const char* HalfedgeDSHalfedge_face = "the incident face of the halfedge.

If the halfedge is a border halfedge the result is default construction of the
handle.

Returns: Face_const_handle";
constexpr const char* HalfedgeDSHalfedge_set_face = "sets incident face to f .

Parameters
----------
f : Face_handle";

// HalfedgeDSItems
constexpr const char* HalfedgeDSItems__class__ = "The concept HalfedgeDSItems wraps the three item types - vertex, halfedge, and face - for a halfedge data structure. A HalfedgeDSItems contains three member class templates named Vertex_wrapper , Halfedge_wrapper , and Face_wrapper , each with two template parameters, Refs and Traits . Refs requires an instantiated halfedge data structure HalfedgeDS as argument, Traits is a geometric traits class supplied by the class that uses the halfedge data structure as internal representation. Traits is not used by the halfedge data structure itself. These three member class templates provide a local type named Vertex , Halfedge , and Face respectively. The requirements on these types are described on the manual pages of the concepts HalfedgeDSVertex , HalfedgeDSHalfedge , and HalfedgeDSFace respectively.";

constexpr const char* HalfedgeDSItems_Vertex = "model of HalfedgeDSVertex .

Returns: Vertex_wrapper< Refs, Traits >::Vertex";
constexpr const char* HalfedgeDSItems_Halfedge = "model of HalfedgeDSHalfedge .

Returns: Halfedge_wrapper< Refs, Traits >::Halfedge";
constexpr const char* HalfedgeDSItems_Face = "model of HalfedgeDSFace .

Returns: Face_wrapper< Refs, Traits >::Face";

// HalfedgeDSVertex
constexpr const char* HalfedgeDSVertex__class__ = "The concept HalfedgeDSVertex defines the requirements for the local Vertex type in the HalfedgeDS concept. It is also required in the Vertex_wrapper<Refs,Traits> member class template of an items class, see the HalfedgeDSItems concept.";

constexpr const char* HalfedgeDSVertex_HalfedgeDS = "instantiated HalfedgeDS ( $ \\equiv$ Refs ).

Returns: unspecified_type";
constexpr const char* HalfedgeDSVertex_Base = "base class that allows modifications.

Returns: unspecified_type";
constexpr const char* HalfedgeDSVertex_Halfedge = "model of HalfedgeDSHalfedge .

Returns: unspecified_type";
constexpr const char* HalfedgeDSVertex_Face = "model of HalfedgeDSFace .

Returns: unspecified_type";
constexpr const char* HalfedgeDSVertex_Vertex_handle = "handle to vertex.

Returns: unspecified_type";
constexpr const char* HalfedgeDSVertex_Halfedge_handle = "handle to halfedge.

Returns: unspecified_type";
constexpr const char* HalfedgeDSVertex_Face_handle = "handle to face.

Returns: unspecified_type";
constexpr const char* HalfedgeDSVertex_Supports_vertex_halfedge = "CGAL::Tag_true or CGAL::Tag_false .

Returns: unspecified_type";
constexpr const char* HalfedgeDSVertex_Vertex = "default constructor.";
constexpr const char* HalfedgeDSVertex_halfedge = "incident halfedge that points to the vertex.

Returns: Halfedge_const_handle";
constexpr const char* HalfedgeDSVertex_set_halfedge = "sets incident halfedge to h .

Parameters
----------
h : Halfedge_handle";

// std
constexpr const char* std__class__ = "STL namespace.";

} // namespace HalfedgeDS
} // namespace docstrings
} // namespace cgalpy

#endif // CGAL_PYTHON_DOCSTRINGS_HALFEDGEDS_H
