if(NOT ARRANGEMENT_ON_SURFACE_2_OPTIONS_FILE_INCLUDED)
set(ARRANGEMENT_ON_SURFACE_2_OPTIONS_FILE_INCLUDED)

# Arrangement type options
set(CGALPY_AOS2_ARRANGEMENT                         0)
set(CGALPY_AOS2_ARRANGEMENT_ON_SURFACE              1)

# Arrangement type name
set(CGALPY_AOS2_TYPE_SHORT_NAMES arr aos)
set(CGALPY_AOS2_TYPE_NAMES arrangement arrangementOnSurface)

# Arrangement type default
SET(CGALPY_AOS2_TYPE_NAME "arrangement" CACHE STRING "The arrangement type to use")
set(CGALPY_AOS2_TYPE ${CGALPY_AOS2_ARRANGEMENT} CACHE INTERNAL "")
set_property(CACHE CGALPY_AOS2_TYPE_NAME PROPERTY STRINGS arrangement arrangementOnSurface)

# Geometry Traits Options
set(CGALPY_AOS2_LINEAR_GEOMETRY_TRAITS              0)
set(CGALPY_AOS2_SEGMENT_GEOMETRY_TRAITS             1)
set(CGALPY_AOS2_NON_CACHING_SEGMENT_GEOMETRY_TRAITS 2)
set(CGALPY_AOS2_CONIC_GEOMETRY_TRAITS               3)
set(CGALPY_AOS2_ALGEBRAIC_SEGMENT_GEOMETRY_TRAITS   4)
set(CGALPY_AOS2_CIRCLE_SEGMENT_GEOMETRY_TRAITS      5)
set(CGALPY_AOS2_BEZIER_GEOMETRY_TRAITS              6)
set(CGALPY_AOS2_RATIONAL_FUNCTION_GEOMETRY_TRAITS   7)
set(CGALPY_AOS2_GEODESIC_ARC_ON_SPHERE_TRAITS       8)

# Geometry Traits Names
set(CGALPY_AOS2_GEOMETRY_TRAITS_SHORT_NAMES linear seg ncseg conic alg cs bez rat gos)
set(CGALPY_AOS2_GEOMETRY_TRAITS_NAMES linear segment nonCachingSegment conic algebraic circleSegment bezier rational geodesicOnSphere)

# Geometry Traits Default
SET(CGALPY_AOS2_GEOMETRY_TRAITS_NAME "segment" CACHE STRING "The geometry traits to use")
set(CGALPY_AOS2_GEOMETRY_TRAITS ${CGALPY_AOS2_SEGMENT_GEOMETRY_TRAITS} CACHE INTERNAL "")
set_property(CACHE CGALPY_AOS2_GEOMETRY_TRAITS_NAME PROPERTY STRINGS linear segment nonCachingSegment conic algebraic circleSegment bezier rational geodesicOnSphere)

# DCEL

option(CGALPY_AOS2_VERTEX_EXTENDED "Extend the Vertex record")
option(CGALPY_AOS2_HALFEDGE_EXTENDED "Extend the Halfedge record")
option(CGALPY_AOS2_FACE_EXTENDED "Extend the Face record")

# Selection
function(select_arrangement_type)
  if     ("${CGALPY_AOS2_TYPE_NAME}" STREQUAL "arrangement")
    set(CGALPY_AOS2_TYPE ${CGALPY_AOS2_ARRANGEMENT} CACHE INTERNAL "")
  elseif ("${CGALPY_AOS2_TYPE_NAME}" STREQUAL "arrangementOnSurface")
    set(CGALPY_AOS2_TYPE ${CGALPY_AOS2_ARRANGEMENT_ON_SURFACE} CACHE INTERNAL "")
  endif()
  add_definitions(-DCGALPY_AOS2_TYPE=${CGALPY_AOS2_TYPE})
endfunction()

function(select_aos2_geometry_traits)
  if     ("${CGALPY_AOS2_GEOMETRY_TRAITS_NAME}" STREQUAL "linear")
    set(CGALPY_AOS2_GEOMETRY_TRAITS ${CGALPY_AOS2_LINEAR_GEOMETRY_TRAITS} CACHE INTERNAL "")
  elseif ("${CGALPY_AOS2_GEOMETRY_TRAITS_NAME}" STREQUAL "segment")
    set(CGALPY_AOS2_GEOMETRY_TRAITS ${CGALPY_AOS2_SEGMENT_GEOMETRY_TRAITS} CACHE INTERNAL "")
  elseif ("${CGALPY_AOS2_GEOMETRY_TRAITS_NAME}" STREQUAL "nonCachingSegment")
    set(CGALPY_AOS2_GEOMETRY_TRAITS ${CGALPY_AOS2_NON_CACHING_SEGMENT_GEOMETRY_TRAITS} CACHE INTERNAL "")
  elseif ("${CGALPY_AOS2_GEOMETRY_TRAITS_NAME}" STREQUAL "conic")
    set(CGALPY_AOS2_GEOMETRY_TRAITS ${CGALPY_AOS2_CONIC_GEOMETRY_TRAITS} CACHE INTERNAL "")
  elseif ("${CGALPY_AOS2_GEOMETRY_TRAITS_NAME}" STREQUAL "algebraic")
    set(CGALPY_AOS2_GEOMETRY_TRAITS ${CGALPY_AOS2_ALGEBRAIC_SEGMENT_GEOMETRY_TRAITS} CACHE INTERNAL "")
  elseif ("${CGALPY_AOS2_GEOMETRY_TRAITS_NAME}" STREQUAL "circleSegment")
    set(CGALPY_AOS2_GEOMETRY_TRAITS ${CGALPY_AOS2_CIRCLE_SEGMENT_GEOMETRY_TRAITS} CACHE INTERNAL "")
  elseif ("${CGALPY_AOS2_GEOMETRY_TRAITS_NAME}" STREQUAL "bezier")
    set(CGALPY_AOS2_GEOMETRY_TRAITS ${CGALPY_AOS2_BEZIER_GEOMETRY_TRAITS} CACHE INTERNAL "")
  elseif ("${CGALPY_AOS2_GEOMETRY_TRAITS_NAME}" STREQUAL "rational")
    set(CGALPY_AOS2_GEOMETRY_TRAITS ${CGALPY_AOS2_RATIONAL_FUNCTION_GEOMETRY_TRAITS} CACHE INTERNAL "")
  elseif ("${CGALPY_AOS2_GEOMETRY_TRAITS_NAME}" STREQUAL "geodesicOnSphere")
    set(CGALPY_AOS2_GEOMETRY_TRAITS ${CGALPY_AOS2_GEODESIC_ARC_ON_SPHERE_TRAITS} CACHE INTERNAL "")
  endif()
  add_definitions(-DCGALPY_AOS2_GEOMETRY_TRAITS=${CGALPY_AOS2_GEOMETRY_TRAITS})
endfunction()

function(select_aos2_dcel)
  if (${CGALPY_AOS2_VERTEX_EXTENDED})
    add_definitions(-DCGALPY_AOS2_VERTEX_EXTENDED=)
  endif()
  if (${CGALPY_AOS2_HALFEDGE_EXTENDED})
    add_definitions(-DCGALPY_AOS2_HALFEDGE_EXTENDED=)
  endif()
  if (${CGALPY_AOS2_FACE_EXTENDED})
    add_definitions(-DCGALPY_AOS2_FACE_EXTENDED=)
  endif()
endfunction()

function(select_aos2_point_location)
  if(${CGALPY_AOS2_POINT_LOCATION_BINDINGS})
    add_definitions(-DCGALPY_AOS2_POINT_LOCATION_BINDINGS=)
  endif()
endfunction()

function(select_arrangement_2)
  if (CGALPY_ARRANGEMENT_ON_SURFACE_2_BINDINGS)
    select_arrangement_type()
    select_aos2_geometry_traits()
    select_aos2_dcel()
    select_aos2_point_location()
    add_definitions(-DCGALPY_ARRANGEMENT_ON_SURFACE_2_BINDINGS=)
  endif()
endfunction()

function(get_arrangement_on_surface_2_lib_name ret)
  list(GET CGALPY_AOS2_TYPE_SHORT_NAMES ${CGALPY_AOS2_TYPE} part1)
  capitalize_first(part1)
  list(GET CGALPY_AOS2_GEOMETRY_TRAITS_SHORT_NAMES ${CGALPY_AOS2_GEOMETRY_TRAITS} part2)
  capitalize_first(part2)
  if(${CGALPY_AOS2_VERTEX_EXTENDED})
    set(part3 "Ve")
  endif()
  if(${CGALPY_AOS2_HALFEDGE_EXTENDED})
    set(part4 "He")
  endif()
  if(${CGALPY_AOS2_FACE_EXTENDED})
    set(part5 "Fe")
  endif()
  if(${CGALPY_AOS2_POINT_LOCATION_BINDINGS})
    set(part6 "Pl")
  endif()
  set(${ret} "aos2${part1}${part2}${part3}${part4}${part5}${part6}" PARENT_SCOPE)
endfunction()

endif()
