if(NOT ARRANGEMENT_ON_SURFACE_2_OPTIONS_FILE_INCLUDED)
set(ARRANGEMENT_ON_SURFACE_2_OPTIONS_FILE_INCLUDED)

# Geometry Traits Options
set(CGALPY_AOS2_ALGEBRAIC_SEGMENT_GEOMETRY_TRAITS       0)
set(CGALPY_AOS2_BEZIER_GEOMETRY_TRAITS                  1)
set(CGALPY_AOS2_CIRCLE_SEGMENT_GEOMETRY_TRAITS          2)
set(CGALPY_AOS2_CONIC_GEOMETRY_TRAITS                   3)
set(CGALPY_AOS2_GEODESIC_ARC_ON_SPHERE_TRAITS           4)
set(CGALPY_AOS2_LINEAR_GEOMETRY_TRAITS                  5)
set(CGALPY_AOS2_NON_CACHING_SEGMENT_GEOMETRY_TRAITS     6)
set(CGALPY_AOS2_POLYLINE_OF_SEGMENTS_GEOMETRY_TRAITS    7)
set(CGALPY_AOS2_SEGMENT_GEOMETRY_TRAITS                 8)
set(CGALPY_AOS2_RATIONAL_FUNCTION_GEOMETRY_TRAITS       9)

# Geometry Traits Names
set(CGALPY_AOS2_GEOMETRY_TRAITS_SHORT_NAMES alg bez cs conic gos linear ncseg pos seg rat)
set(CGALPY_AOS2_GEOMETRY_TRAITS_NAMES algebraic bezier circleSegment conic geodesicOnSphere linear nonCachingSegment polylineOfSegments segment rational)

# Geometry Traits Default
SET(CGALPY_AOS2_GEOMETRY_TRAITS_NAME "segment" CACHE STRING "The geometry traits to use")
set(CGALPY_AOS2_GEOMETRY_TRAITS ${CGALPY_AOS2_SEGMENT_GEOMETRY_TRAITS} CACHE INTERNAL "")
set_property(CACHE CGALPY_AOS2_GEOMETRY_TRAITS_NAME PROPERTY STRINGS algebraic bezier circleSegment conic geodesicOnSphere linear nonCachingSegment polylineOfSegments segment rational)

# Curve data
set(CGALPY_AOS2_CURVE_DATA false CACHE BOOL "The curve data option")

# Consolidated urve data
set(CGALPY_AOS2_CONSOLIDATED_CURVE_DATA false CACHE BOOL "The consolidated curve data option")

# Counting & tracing
set(CGALPY_AOS2_COUNTING_TRAITS false CACHE BOOL "Enable counting traits")
set(CGALPY_AOS2_TRACING_TRAITS false CACHE BOOL "Enable tracing traits")

# DCEL

option(CGALPY_AOS2_VERTEX_EXTENDED "Extend the Vertex record")
option(CGALPY_AOS2_HALFEDGE_EXTENDED "Extend the Halfedge record")
option(CGALPY_AOS2_FACE_EXTENDED "Extend the Face record")

# With history

option(CGALPY_AOS2_WITH_HISTORY "Support arrangement with history")

# Selection
function(select_aos2_curve_data)
  if(${CGALPY_AOS2_CURVE_DATA})
    add_definitions(-DCGALPY_AOS2_CURVE_DATA=)
  endif()
endfunction()

function(select_aos2_consolidated_curve_data)
  if(${CGALPY_AOS2_CONSOLIDATED_CURVE_DATA})
    add_definitions(-DCGALPY_AOS2_CONSOLIDATED_CURVE_DATA=)
  endif()
endfunction()

function(select_aos2_geometry_traits)
  if     ("${CGALPY_AOS2_GEOMETRY_TRAITS_NAME}" STREQUAL "algebraic")
    set(CGALPY_AOS2_GEOMETRY_TRAITS ${CGALPY_AOS2_ALGEBRAIC_SEGMENT_GEOMETRY_TRAITS} CACHE INTERNAL "")
  elseif ("${CGALPY_AOS2_GEOMETRY_TRAITS_NAME}" STREQUAL "bezier")
    set(CGALPY_AOS2_GEOMETRY_TRAITS ${CGALPY_AOS2_BEZIER_GEOMETRY_TRAITS} CACHE INTERNAL "")
  elseif ("${CGALPY_AOS2_GEOMETRY_TRAITS_NAME}" STREQUAL "circleSegment")
    set(CGALPY_AOS2_GEOMETRY_TRAITS ${CGALPY_AOS2_CIRCLE_SEGMENT_GEOMETRY_TRAITS} CACHE INTERNAL "")
  elseif ("${CGALPY_AOS2_GEOMETRY_TRAITS_NAME}" STREQUAL "conic")
    set(CGALPY_AOS2_GEOMETRY_TRAITS ${CGALPY_AOS2_CONIC_GEOMETRY_TRAITS} CACHE INTERNAL "")
  elseif ("${CGALPY_AOS2_GEOMETRY_TRAITS_NAME}" STREQUAL "geodesicOnSphere")
    set(CGALPY_AOS2_GEOMETRY_TRAITS ${CGALPY_AOS2_GEODESIC_ARC_ON_SPHERE_TRAITS} CACHE INTERNAL "")
  elseif ("${CGALPY_AOS2_GEOMETRY_TRAITS_NAME}" STREQUAL "linear")
    set(CGALPY_AOS2_GEOMETRY_TRAITS ${CGALPY_AOS2_LINEAR_GEOMETRY_TRAITS} CACHE INTERNAL "")
  elseif ("${CGALPY_AOS2_GEOMETRY_TRAITS_NAME}" STREQUAL "nonCachingSegment")
    set(CGALPY_AOS2_GEOMETRY_TRAITS ${CGALPY_AOS2_NON_CACHING_SEGMENT_GEOMETRY_TRAITS} CACHE INTERNAL "")
  elseif ("${CGALPY_AOS2_GEOMETRY_TRAITS_NAME}" STREQUAL "polylineOfSegments")
    set(CGALPY_AOS2_GEOMETRY_TRAITS ${CGALPY_AOS2_POLYLINE_OF_SEGMENTS_GEOMETRY_TRAITS} CACHE INTERNAL "")
  elseif ("${CGALPY_AOS2_GEOMETRY_TRAITS_NAME}" STREQUAL "segment")
    set(CGALPY_AOS2_GEOMETRY_TRAITS ${CGALPY_AOS2_SEGMENT_GEOMETRY_TRAITS} CACHE INTERNAL "")
  elseif ("${CGALPY_AOS2_GEOMETRY_TRAITS_NAME}" STREQUAL "rational")
    set(CGALPY_AOS2_GEOMETRY_TRAITS ${CGALPY_AOS2_RATIONAL_FUNCTION_GEOMETRY_TRAITS} CACHE INTERNAL "")
  endif()
  add_definitions(-DCGALPY_AOS2_GEOMETRY_TRAITS=${CGALPY_AOS2_GEOMETRY_TRAITS})
endfunction()

function(select_aos2_counting_traits)
  if(${CGALPY_AOS2_COUNTING_TRAITS})
    add_definitions(-DCGALPY_AOS2_COUNTING_TRAITS=)
  endif()
endfunction()

function(select_aos2_tracing_traits)
  if(${CGALPY_AOS2_TRACING_TRAITS})
    add_definitions(-DCGALPY_AOS2_TRACING_TRAITS=)
  endif()
endfunction()

function(select_aos2_dcel)
  if (${CGALPY_AOS2_VERTEX_EXTENDED})
    add_definitions(-DCGALPY_AOS2_VERTEX_EXTENDED=)
  endif()
  if (${CGALPY_AOS2_HALFEDGE_EXTENDED})
    add_definitions(-DCGALPY_AOS2_HALFEDGE_EXTENDED=)
  endif()
  if (${CGALPY_AOS2_FACE_EXTENDED})
    add_definitions(-DCGALPY_AOS2_FACE_EXTENDED=)
  endif()
endfunction()

function(select_aos2_with_history)
  if(${CGALPY_AOS2_WITH_HISTORY})
    add_definitions(-DCGALPY_AOS2_WITH_HISTORY=)
  endif()
endfunction()

function(select_aos2_point_location)
  if(${CGALPY_AOS2_POINT_LOCATION_BINDINGS})
    add_definitions(-DCGALPY_AOS2_POINT_LOCATION_BINDINGS=)
  endif()
endfunction()

function(select_arrangement_2)
  if (CGALPY_ARRANGEMENT_ON_SURFACE_2_BINDINGS)
    select_aos2_geometry_traits()
    select_aos2_counting_traits()
    select_aos2_tracing_traits()
    select_aos2_curve_data()
    select_aos2_consolidated_curve_data()
    select_aos2_dcel()
    select_aos2_with_history()
    select_aos2_point_location()
    add_definitions(-DCGALPY_ARRANGEMENT_ON_SURFACE_2_BINDINGS=)
  endif()
endfunction()

function(get_arrangement_on_surface_2_lib_name ret)
  list(GET CGALPY_AOS2_GEOMETRY_TRAITS_SHORT_NAMES ${CGALPY_AOS2_GEOMETRY_TRAITS} pasrt1)
  capitalize_first(pasrt1)
  set(part2 "")
  if(${CGALPY_AOS2_COUNTING_TRAITS})
    set(part2 "Cnt")
  endif()
  set(part3 "")
  if(${CGALPY_AOS2_TRACING_TRAITS})
    set(part3 "Trc")
  endif()
  set(part4 "")
  if(${CGALPY_AOS2_CURVE_DATA})
    set(part4 "Cd")
  endif()
  set(part5 "")
  if(${CGALPY_AOS2_CONSOLIDATED_CURVE_DATA})
    set(part5 "Ccd")
  endif()
  set(part6 "")
  if(${CGALPY_AOS2_VERTEX_EXTENDED})
    set(part6 "Ve")
  endif()
  set(part7 "")
  if(${CGALPY_AOS2_HALFEDGE_EXTENDED})
    set(part7 "He")
  endif()
  set(part8 "")
  if(${CGALPY_AOS2_FACE_EXTENDED})
    set(part8 "Fe")
  endif()
  set(part9 "")
  if(${CGALPY_AOS2_WITH_HISTORY})
    set(part9 "Wh")
  endif()
  set(part10 "")
  if(${CGALPY_AOS2_POINT_LOCATION_BINDINGS})
    set(part10 "Pl")
  endif()
  set(${ret} "aos2${pasrt1}${part2}${part3}${part4}${part5}${part6}${part7}${part8}${part9}${part10}" PARENT_SCOPE)
endfunction()

endif()
