if(NOT ARRANGEMENT_ON_SURFACE_2_OPTIONS_FILE_INCLUDED)
set(ARRANGEMENT_ON_SURFACE_2_OPTIONS_FILE_INCLUDED)

# Geometry Traits Options
set(CGALPY_AOS2_LINEAR_GEOMETRY_TRAITS              0)
set(CGALPY_AOS2_SEGMENT_GEOMETRY_TRAITS             1)
set(CGALPY_AOS2_NON_CACHING_SEGMENT_GEOMETRY_TRAITS 2)
set(CGALPY_AOS2_CONIC_GEOMETRY_TRAITS               3)
set(CGALPY_AOS2_ALGEBRAIC_SEGMENT_GEOMETRY_TRAITS   4)
set(CGALPY_AOS2_CIRCLE_SEGMENT_GEOMETRY_TRAITS      5)
set(CGALPY_AOS2_BEZIER_GEOMETRY_TRAITS              6)
set(CGALPY_AOS2_RATIONAL_GEOMETRY_TRAITS            7)

# Geometry Traits Names
set(CGALPY_AOS2_GEOMETRY_TRAITS_SHORT_NAMES linear seg ncseg conic alg cs bez rat)
set(CGALPY_AOS2_GEOMETRY_TRAITS_NAMES linear segment nonCachingSegment conic algebraic circleSegment bezier rational)

# Geometry Traits Default
SET(CGALPY_AOS2_GEOMETRY_TRAITS_NAME "segment" CACHE STRING "The geometry traits to use")
set(CGALPY_AOS2_GEOMETRY_TRAITS ${CGALPY_AOS2_SEGMENT_GEOMETRY_TRAITS} CACHE INTERNAL "")
set_property(CACHE CGALPY_AOS2_GEOMETRY_TRAITS_NAME PROPERTY STRINGS linear segment nonCachingSegment conic algebraic circleSegment)

# DCEL Options
set(CGALPY_AOS2_PLAIN_DCEL 0)
set(CGALPY_AOS2_FACE_EXTENDED_DCEL 1)
set(CGALPY_AOS2_HALFEDGE_EXTENDED_DCEL 2)
set(CGALPY_AOS2_VERTEX_EXTENDED_DCEL 3)
set(CGALPY_AOS2_ALL_EXTENDED_DCEL 4)

# DCEL Names
set(CGALPY_AOS2_DCEL_SHORT_NAMES "plain" "fex" "hex" "vex" "ex")
set(CGALPY_AOS2_DCEL_NAMES plain faceExtended halfedgeExtended vertexExtended allExtended)

# DCEL Default
SET(CGALPY_AOS2_DCEL_NAME "plain" CACHE STRING "The DCEL to use")
set(CGALPY_AOS2_DCEL ${CGALPY_AOS2_PLAIN_DCEL} CACHE INTERNAL "")
set_property(CACHE CGALPY_AOS2_DCEL_NAME PROPERTY STRINGS plain faceExtended halfedgeExtended vertexExtended allExtended)

# Selection
function(select_arr_2_geometry_traits)
  if     ("${CGALPY_AOS2_GEOMETRY_TRAITS_NAME}" STREQUAL "linear")
    set(CGALPY_AOS2_GEOMETRY_TRAITS ${CGALPY_AOS2_LINEAR_GEOMETRY_TRAITS} CACHE INTERNAL "")
  elseif ("${CGALPY_AOS2_GEOMETRY_TRAITS_NAME}" STREQUAL "segment")
    set(CGALPY_AOS2_GEOMETRY_TRAITS ${CGALPY_AOS2_SEGMENT_GEOMETRY_TRAITS} CACHE INTERNAL "")
  elseif ("${CGALPY_AOS2_GEOMETRY_TRAITS_NAME}" STREQUAL "nonCachingSegment")
    set(CGALPY_AOS2_GEOMETRY_TRAITS ${CGALPY_AOS2_NON_CACHING_SEGMENT_GEOMETRY_TRAITS} CACHE INTERNAL "")
  elseif ("${CGALPY_AOS2_GEOMETRY_TRAITS_NAME}" STREQUAL "conic")
    set(CGALPY_AOS2_GEOMETRY_TRAITS ${CGALPY_AOS2_CONIC_GEOMETRY_TRAITS} CACHE INTERNAL "")
  elseif ("${CGALPY_AOS2_GEOMETRY_TRAITS_NAME}" STREQUAL "algebraic")
    set(CGALPY_AOS2_GEOMETRY_TRAITS ${CGALPY_AOS2_ALGEBRAIC_SEGMENT_GEOMETRY_TRAITS} CACHE INTERNAL "")
  elseif ("${CGALPY_AOS2_GEOMETRY_TRAITS_NAME}" STREQUAL "circleSegment")
    set(CGALPY_AOS2_GEOMETRY_TRAITS ${CGALPY_AOS2_CIRCLE_SEGMENT_GEOMETRY_TRAITS} CACHE INTERNAL "")
  endif()
  add_definitions(-DCGALPY_AOS2_GEOMETRY_TRAITS=${CGALPY_AOS2_GEOMETRY_TRAITS})
endfunction()

function(select_arr_2_dcel)
  if     ("${CGALPY_AOS2_DCEL_NAME}" STREQUAL "plain")
    set(CGALPY_AOS2_DCEL ${CGALPY_AOS2_PLAIN_DCEL} CACHE INTERNAL "")
  elseif ("${CGALPY_AOS2_DCEL_NAME}" STREQUAL "faceExtended")
    set(CGALPY_AOS2_DCEL ${CGALPY_AOS2_FACE_EXTENDED_DCEL} CACHE INTERNAL "")
  elseif ("${CGALPY_AOS2_DCEL_NAME}" STREQUAL "halfedgeExtended")
    set(CGALPY_AOS2_DCEL ${CGALPY_AOS2_HALFEDGE_EXTENDED_DCEL} CACHE INTERNAL "")
  elseif ("${CGALPY_AOS2_DCEL_NAME}" STREQUAL "vertexExtended")
    set(CGALPY_AOS2_DCEL ${CGALPY_AOS2_VERTEX_EXTENDED_DCEL} CACHE INTERNAL "")
  elseif ("${CGALPY_AOS2_DCEL_NAME}" STREQUAL "allExtended")
    set(CGALPY_AOS2_DCEL ${CGALPY_AOS2_ALL_EXTENDED_DCEL} CACHE INTERNAL "")
  endif()
  add_definitions(-DCGALPY_AOS2_DCEL=${CGALPY_AOS2_DCEL})
endfunction()

function(select_arr_2_point_location)
  if(${CGALPY_AOS2_POINT_LOCATION_BINDINGS})
    add_definitions(-DCGALPY_AOS2_POINT_LOCATION_BINDINGS)
  endif()
endfunction()

function(select_arrangement_2)
  if (CGALPY_ARRANGEMENT_ON_SURFACE_2_BINDINGS)
    select_arr_2_geometry_traits()
    select_arr_2_dcel()
    select_arr_2_point_location()
    add_definitions(-DCGALPY_ARRANGEMENT_ON_SURFACE_2_BINDINGS)
  endif()
endfunction()

function(get_arrangement_on_surface_2_lib_name ret)
  list(GET CGALPY_AOS2_GEOMETRY_TRAITS_SHORT_NAMES ${CGALPY_AOS2_GEOMETRY_TRAITS} part1)
  capitalize_first(part1)
  list(GET CGALPY_AOS2_DCEL_SHORT_NAMES ${CGALPY_AOS2_DCEL} part2)
  capitalize_first(part2)
  if(${CGALPY_AOS2_POINT_LOCATION_BINDINGS})
    set(part3 "Pl")
  endif()
  set(${ret} "arr2${part1}${part2}${part3}" PARENT_SCOPE)
endfunction()

endif()
