if(NOT POLYHEDRON_3_OPTIONS_FILE_INCLUDED)
set(POLYHEDRON_3_OPTIONS_FILE_INCLUDED)

# HDS
option(CGALPY_POL3_VERTEX_WITH_ID "Extend the Vertex record with an id")
option(CGALPY_POL3_HALFEDGE_WITH_ID "Extend the Halfedge record with an id")
option(CGALPY_POL3_FACE_WITH_ID "Extend the Facet record with an id")

option(CGALPY_POL3_VERTEX_EXTENDED "Extend the Vertex record")
option(CGALPY_POL3_HALFEDGE_EXTENDED "Extend the Halfedge record")
option(CGALPY_POL3_FACE_EXTENDED "Extend the Facet record")

# Selection
function(select_pol3_hds)
  if (${CGALPY_POL3_VERTEX_WITH_ID})
    add_definitions(-DCGALPY_POL3_VERTEX_WITH_ID=)
  endif()
  if (${CGALPY_POL3_HALFEDGE_WITH_ID})
    add_definitions(-DCGALPY_POL3_HALFEDGE_WITH_ID=)
  endif()
  if (${CGALPY_POL3_FACE_WITH_ID})
    add_definitions(-DCGALPY_POL3_FACE_WITH_ID=)
  endif()

  if (${CGALPY_POL3_VERTEX_EXTENDED})
    add_definitions(-DCGALPY_POL3_VERTEX_EXTENDED=)
  endif()
  if (${CGALPY_POL3_HALFEDGE_EXTENDED})
    add_definitions(-DCGALPY_POL3_HALFEDGE_EXTENDED=)
  endif()
  if (${CGALPY_POL3_FACE_EXTENDED})
    add_definitions(-DCGALPY_POL3_FACE_EXTENDED=)
  endif()
endfunction()

function(select_polyhedron_3)
  if(${CGALPY_POLYHEDRON_3_BINDINGS})
    select_pol3_hds()
    add_definitions(-DCGALPY_POLYHEDRON_3_BINDINGS=)
  endif()
endfunction()

# Library name
function(get_polyhedron_3_lib_name ret)
  if(${CGALPY_POL3_VERTEX_WITH_ID})
    set(part1 "Vid")
  endif()
  if(${CGALPY_POL3_HALFEDGE_WITH_ID})
    set(part2 "Hid")
  endif()
  if(${CGALPY_POL3_FACE_WITH_ID})
    set(part3 "Fid")
  endif()
  if(${CGALPY_POL3_VERTEX_EXTENDED})
    set(part4 "Ve")
  endif()
  if(${CGALPY_POL3_HALFEDGE_EXTENDED})
    set(part5 "He")
  endif()
  if(${CGALPY_POL3_FACE_EXTENDED})
    set(part6 "Fe")
  endif()
  set(${ret} "pol3${part1}${part2}${part3}${part4}${part5}${part6}" PARENT_SCOPE)
endfunction()

endif()
