if(NOT SPATIAL_SEARCHING_OPTIONS_FILE_INCLUDED)
set(SPATIAL_SEARCHING_OPTIONS_FILE_INCLUDED)

# Dimension
SET(CGALPY_SPATIAL_SEARCHING_DIMENSION 4 CACHE STRING "The dimension of spatial search objects")

function(select_spatial_searching)
  # Select dimension
  add_definitions(-DCGALPY_SPATIAL_SEARCHING_DIMENSION=${CGALPY_SPATIAL_SEARCHING_DIMENSION})

  if(${CGALPY_SPATIAL_SEARCHING_BINDINGS})
    add_definitions(-DCGALPY_SPATIAL_SEARCHING_BINDINGS)
  endif()
endfunction()

endif()
