if(NOT SURFACE_MESH_PARAMETERIZATION_OPTIONS_FILE_INCLUDED)
set(SURFACE_MESH_PARAMETERIZATION_OPTIONS_FILE_INCLUDED)

function(select_surface_mesh_parameterization)
  if (CGALPY_SURFACE_MESH_PARAMETERIZATION_BINDINGS)
    add_definitions(-DCGALPY_SURFACE_MESH_PARAMETERIZATION_BINDINGS=)
  endif()
endfunction()

endif()
