if(NOT SURFACE_MESH_DEFORMATION_OPTIONS_FILE_INCLUDED)
set(SURFACE_MESH_DEFORMATION_OPTIONS_FILE_INCLUDED)

function(select_surface_mesh_deformation)
  if (CGALPY_SURFACE_MESH_DEFORMATION_BINDINGS)
    add_definitions(-DCGALPY_SURFACE_MESH_DEFORMATION_BINDINGS=)
  endif()
endfunction()

endif()
