if(NOT SURFACE_MESH_SHORTEST_PATH_OPTIONS_FILE_INCLUDED)
set(SURFACE_MESH_SHORTEST_PATH_OPTIONS_FILE_INCLUDED)

function(select_surface_mesh_shortest_path)
  if (CGALPY_SURFACE_MESH_SHORTEST_PATH_BINDINGS)
    add_definitions(-DCGALPY_SURFACE_MESH_SHORTEST_PATH_BINDINGS=)
  endif()
endfunction()

endif()
