if(NOT SURFACE_MESH_DECOMPOSITION_OPTIONS_FILE_INCLUDED)
set(SURFACE_MESH_DECOMPOSITION_OPTIONS_FILE_INCLUDED)

function(select_surface_mesh_decomposition)
  if (CGALPY_SURFACE_MESH_DECOMPOSITION_BINDINGS)
    add_definitions(-DCGALPY_SURFACE_MESH_DECOMPOSITION_BINDINGS=)
  endif()
endfunction()

endif()
