if(NOT SURFACE_MESH_APPROXIMATION_OPTIONS_FILE_INCLUDED)
set(SURFACE_MESH_APPROXIMATION_OPTIONS_FILE_INCLUDED)

function(select_surface_mesh_approximation)
  if (CGALPY_SURFACE_MESH_APPROXIMATION_BINDINGS)
    add_definitions(-DCGALPY_SURFACE_MESH_APPROXIMATION_BINDINGS=)
  endif()
endfunction()

endif()
