if(NOT TRIANGULATION_2_OPTIONS_FILE_INCLUDED)
set(TRIANGULATION_2_OPTIONS_FILE_INCLUDED)

######## 2D Triangulations intersection tag
set(CGALPY_TRI2_INTERSECTION_TAG_NCI                            0)
set(CGALPY_TRI2_INTERSECTION_TAG_NCI_REQUIRING_CONSTRUCTIONS    1)
set(CGALPY_TRI2_INTERSECTION_TAG_EXACT_PREDICATES               2)
set(CGALPY_TRI2_INTERSECTION_TAG_EXACT_INTERSECTIONS            3)

set(CGALPY_TRI2_INTERSECTION_TAG_SHORT_NAMES nci ncirc ep ei)
set(CGALPY_TRI2_INTERSECTION_TAG_NAMES nci nciRequiringConstructions exactPredicates exactIntersections)

# Default
SET(CGALPY_TRI2_INTERSECTION_TAG ${CGALPY_TRI2_INTERSECTION_TAG_NCI} CACHE INTERNAL "")
SET(CGALPY_TRI2_INTERSECTION_TAG_NAME "nci" CACHE STRING "Intersection tag")
set_property(CACHE CGALPY_TRI2_INTERSECTION_TAG_NAME PROPERTY STRINGS nci nciRequiringConstructions exactPredicates exactIntersections)

######## 2D Triangulations types
set(CGALPY_TRI2_PLAIN                0)
set(CGALPY_TRI2_REGULAR              1)
set(CGALPY_TRI2_DELAUNAY             2)
set(CGALPY_TRI2_CONSTRAINED          3)
set(CGALPY_TRI2_CONSTRAINED_DELAUNAY 4)
set(CGALPY_TRI2_PERIODIC_PLAIN       5)
set(CGALPY_TRI2_PERIODIC_DELAUNAY    6)

set(CGALPY_TRI2_SHORT_NAMES plain reg del con cdel pp pdel)
set(CGALPY_TRI2_NAMES plain regular delaunay constrained constrainedDelaunay periodicPlain periodicDelaunay)

# Default
SET(CGALPY_TRI2 ${CGALPY_TRI2_PLAIN} CACHE INTERNAL "")
SET(CGALPY_TRI2_NAME "plain" CACHE STRING "The 2D Triangulation")
set_property(CACHE CGALPY_TRI2_NAME PROPERTY STRINGS plain regular delaunay constrained constrainedDelaunay periodicPlain periodicDelaunay)

######## 2D Triangulation traits
set(CGALPY_TRI2_TRAITS_KERNEL            0)
set(CGALPY_TRI2_TRAITS_PERIODIC_PLAIN    1)
set(CGALPY_TRI2_TRAITS_PERIODIC_DELAUNAY 2)

set(CGALPY_TRI2_TRAITS_SHORT_NAMES ker p2d)
set(CGALPY_TRI2_TRAITS_NAMES kernel periodicPlain periodicDelaunay)

# Default (depends on the selected triangulation)
if("${CGALPY_TRI2}" EQUAL ${CGALPY_TRI2_PERIODIC_PLAIN})
  SET(CGALPY_TRI2_TRAITS ${CGALPY_TRI2_TRAITS_PERIODIC_PLAIN} CACHE INTERNAL "")
  SET(CGALPY_TRI2_TRAITS_NAME "periodicPlain" CACHE STRING "The 2D Triangulation traits")
elseif("${CGALPY_TRI2}" EQUAL ${CGALPY_TRI2_PERIODIC_DELAUNAY})
  SET(CGALPY_TRI2_TRAITS ${CGALPY_TRI2_TRAITS_DELAUNAY} CACHE INTERNAL "")
  SET(CGALPY_TRI2_TRAITS_NAME "periodicDelaunay" CACHE STRING "The 2D Triangulation traits")
else()
  SET(CGALPY_TRI2_TRAITS ${CGALPY_TRI2_TRAITS_KERNEL} CACHE INTERNAL "")
  SET(CGALPY_TRI2_TRAITS_NAME "kernel" CACHE STRING "The 2D Triangulation traits")
endif()

set_property(CACHE CGALPY_TRI2_TRAITS_NAME PROPERTY STRINGS kernel periodicPlain periodicDelaunay)

######## 2D Triangulation Vertex Base
set(CGALPY_TRI2_VERTEX_BASE_PLAIN                                0)
set(CGALPY_TRI2_VERTEX_BASE_REGULAR                              1)

set(CGALPY_TRI2_VERTEX_BASE_SHORT_NAMES plain reg)
set(CGALPY_TRI2_VERTEX_BASE_NAMES plain regular)

# Default
SET(CGALPY_TRI2_VERTEX_BASE ${CGALPY_TRI2_VERTEX_BASE_PLAIN} CACHE INTERNAL "")
SET(CGALPY_TRI2_VERTEX_BASE_NAME "plain" CACHE STRING "The 2D Triangulation vertex base")
set_property(CACHE CGALPY_TRI2_VERTEX_BASE_NAME PROPERTY STRINGS plain regular)

######## 2D Triangulation Face Base
set(CGALPY_TRI2_FACE_BASE_PLAIN                                0)
set(CGALPY_TRI2_FACE_BASE_REGULAR                              1)

set(CGALPY_TRI2_FACE_BASE_SHORT_NAMES plain reg)
set(CGALPY_TRI2_FACE_BASE_NAMES plain regular)

# Default
SET(CGALPY_TRI2_FACE_BASE ${CGALPY_TRI2_FACE_BASE_PLAIN} CACHE INTERNAL "")
SET(CGALPY_TRI2_FACE_BASE_NAME "plain" CACHE STRING "The 2D Triangulation vertex base")
set_property(CACHE CGALPY_TRI2_FACE_BASE_NAME PROPERTY STRINGS plain regular)

########
function(select_tri2)
  if    ("${CGALPY_TRI2_NAME}" STREQUAL "plain")
    set(CGALPY_TRI2 ${CGALPY_TRI2_PLAIN} CACHE INTERNAL "")
  elseif("${CGALPY_TRI2_NAME}" STREQUAL "regular")
    set(CGALPY_TRI2 ${CGALPY_TRI2_REGULAR} CACHE INTERNAL "")
  elseif("${CGALPY_TRI2_NAME}" STREQUAL "delaunay")
    set(CGALPY_TRI2 ${CGALPY_TRI2_DELAUNAY} CACHE INTERNAL "")
  elseif("${CGALPY_TRI2_NAME}" STREQUAL "constrained")
    set(CGALPY_TRI2 ${CGALPY_TRI2_CONSTRAINED} CACHE INTERNAL "")
  elseif("${CGALPY_TRI2_NAME}" STREQUAL "constrainedDelaunay")
    set(CGALPY_TRI2 ${CGALPY_TRI2_CONSTRAINED_DELAUNAY} CACHE INTERNAL "")
  elseif("${CGALPY_TRI2_NAME}" STREQUAL "periodicPlain")
    set(CGALPY_TRI2 ${CGALPY_TRI2_PERIODIC_PLAIN} CACHE INTERNAL "")
  elseif("${CGALPY_TRI2_NAME}" STREQUAL "periodicDelaunay")
    set(CGALPY_TRI2 ${CGALPY_TRI2_PERIODIC_DELAUNAY} CACHE INTERNAL "")
  endif()
  add_definitions(-DCGALPY_TRI2=${CGALPY_TRI2})
endfunction()

function(select_tri2_intersection_tag)
  if    ("${CGALPY_TRI2_INTERSECTION_TAG_NAME}" STREQUAL "nci")
    set(CGALPY_TRI2 ${CGALPY_TRI2_INTERSECTION_TAG_NCI} CACHE INTERNAL "")
  elseif("${CGALPY_TRI2_INTERSECTION_TAG_NAME}" STREQUAL "nciRequiringConstructions")
    set(CGALPY_TRI2 ${CGALPY_TRI2_INTERSECTION_TAG_NCI_REQUIRING_CONSTRUCTIONS} CACHE INTERNAL "")
  elseif("${CGALPY_TRI2_INTERSECTION_TAG_NAME}" STREQUAL "exactPredicates")
    set(CGALPY_TRI2 ${CGALPY_TRI2_INTERSECTION_TAG_EXACT_PREDICATES} CACHE INTERNAL "")
  elseif("${CGALPY_TRI2_INTERSECTION_TAG_NAME}" STREQUAL "exactIntersections")
    set(CGALPY_TRI2 ${CGALPY_TRI2_INTERSECTION_TAG_EXACT_INTERSECTIONS} CACHE INTERNAL "")
  endif()
  add_definitions(-DCGALPY_TRI2_INTERSECTION_TAG=${CGALPY_TRI2_INTERSECTION_TAG})
endfunction()

function(select_tri2_traits)
  if     ("${CGALPY_TRI2_TRAITS_NAME}" STREQUAL "kernel")
    set(CGALPY_TRI2_TRAITS ${CGALPY_TRI2_TRAITS_KERNEL} CACHE INTERNAL "")
  elseif ("${CGALPY_TRI2_TRAITS_NAME}" STREQUAL "periodicPlain")
    set(CGALPY_TRI2_TRAITS ${CGALPY_TRI2_TRAITS_PERIODIC_PLAIN} CACHE INTERNAL "")
  elseif ("${CGALPY_TRI2_TRAITS_NAME}" STREQUAL "periodicDelaunay")
    set(CGALPY_TRI2_TRAITS ${CGALPY_TRI2_TRAITS_PERIODIC_DELAUNAY} CACHE INTERNAL "")
  endif()
  add_definitions(-DCGALPY_TRI2_TRAITS=${CGALPY_TRI2_TRAITS})
endfunction()

function(select_tri2_vertex_base)
  if     ("${CGALPY_TRI2_VERTEX_BASE_NAME}" STREQUAL "plain")
    set(CGALPY_TRI2_VERTEX_BASE ${CGALPY_TRI2_VERTEX_BASE_PLAIN} CACHE INTERNAL "")
  elseif ("${CGALPY_TRI2_VERTEX_BASE_NAME}" STREQUAL "regular")
    set(CGALPY_TRI2_VERTEX_BASE ${CGALPY_TRI2_VERTEX_BASE_REGULAR} CACHE INTERNAL "")
  else()
    message(ERROR, "Invalid setting of CGALPY_TRI2_VERTEX_BASE_NAME ${CGALPY_TRI2_VERTEX_BASE_NAME}!")
  endif()
  add_definitions(-DCGALPY_TRI2_VERTEX_BASE=${CGALPY_TRI2_VERTEX_BASE})
endfunction()

function(select_tri2_face_base)
  if     ("${CGALPY_TRI2_FACE_BASE_NAME}" STREQUAL "plain")
    set(CGALPY_TRI2_FACE_BASE ${CGALPY_TRI2_FACE_BASE_PLAIN} CACHE INTERNAL "")
  elseif ("${CGALPY_TRI2_FACE_BASE_NAME}" STREQUAL "regular")
    set(CGALPY_TRI2_FACE_BASE ${CGALPY_TRI2_FACE_BASE_REGULAR} CACHE INTERNAL "")
  else()
    message(ERROR, "Invalid setting of CGALPY_TRI2_FACE_BASE_NAME ${CGALPY_TRI2_FACE_BASE_NAME}!")
  endif()
  add_definitions(-DCGALPY_TRI2_FACE_BASE=${CGALPY_TRI2_FACE_BASE})
endfunction()

function(select_triangulation_2)
  if (${CGALPY_TRIANGULATION_2_BINDINGS})
    select_tri2()
    select_tri2_intersection_tag()
    select_tri2_traits()
    select_tri2_vertex_base()
    select_tri2_face_base()
    if (${CGALPY_TRI2_VERTEX_WITH_INFO})
      add_definitions(-DCGALPY_TRI2_VERTEX_WITH_INFO)
    endif()
    if (${CGALPY_TRI2_FACE_WITH_INFO})
      add_definitions(-DCGALPY_TRI2_FACE_WITH_INFO)
    endif()
    if (${CGALPY_TRI2_HIERARCHY})
      add_definitions(-DCGALPY_TRI2_HIERARCHY)
    endif()
    add_definitions(-DCGALPY_TRIANGULATION_2_BINDINGS)
  endif()
endfunction()

function(get_triangulation_2_lib_name ret)
  list(GET CGALPY_TRI2_SHORT_NAMES ${CGALPY_TRI2} part1)
  capitalize_first(part1)
  list(GET CGALPY_TRI2_INTERSECTION_TAG_NAMES ${CGALPY_TRI2_INTERSECTION_TAG} part2)
  capitalize_first(part2)
  list(GET CGALPY_TRI2_TRAITS_SHORT_NAMES ${CGALPY_TRI2_TRAITS} part3)
  capitalize_first(part3)
  list(GET CGALPY_TRI2_VERTEX_BASE_SHORT_NAMES ${CGALPY_TRI2_VERTEX_BASE} part4)
  capitalize_first(part4)
  set(part5 "")
  if(${CGALPY_TRI2_VERTEX_WITH_INFO})
    set(part5 "Wi")
  endif()
  list(GET CGALPY_TRI2_FACE_BASE_SHORT_NAMES ${CGALPY_TRI2_FACE_BASE} part6)
  capitalize_first(part6)
  set(part7 "")
  if(${CGALPY_TRI2_FACE_WITH_INFO})
    set(part7 "Wi")
  endif()
  set(part8 "")
  if(${CGALPY_TRI2_HIERARCHY})
    set(part8 "Hi")
  endif()
  set(${ret} "tri2${part1}${part2}${part3}${part4}${part5}${part6}${part7}${part8}" PARENT_SCOPE)
endfunction()

endif()
