// AUTO-GENERATED by cpp_docstrings_from_json.py — DO NOT EDIT
// Package: Surface_mesh_parameterization
#ifndef CGAL_PYTHON_DOCSTRINGS_SURFACE_MESH_PARAMETERIZATION_H
#define CGAL_PYTHON_DOCSTRINGS_SURFACE_MESH_PARAMETERIZATION_H

namespace cgalpy {
namespace docstrings {
namespace Surface_mesh_parameterization {

// CGAL::Surface_mesh_parameterization::ARAP_parameterizer_3
constexpr const char* Surface_mesh_parameterization_ARAP_parameterizer_3__class__ = "The class ARAP_parameterizer_3 implements the Local/Global Approach to Mesh Parameterization [9] .";

constexpr const char* Surface_mesh_parameterization_ARAP_parameterizer_3_Border_parameterizer = "Border parameterizer type.

Returns: Border_parameterizer_";
constexpr const char* Surface_mesh_parameterization_ARAP_parameterizer_3_Solver_traits = "Solver traits type.

Returns: SolverTraits_";
constexpr const char* Surface_mesh_parameterization_ARAP_parameterizer_3_NT = "Number type, deduced from the internal vertex point map of Triangle_mesh .

Returns: unspecified_type";
constexpr const char* Surface_mesh_parameterization_ARAP_parameterizer_3_Triangle_mesh = "Triangle mesh type.

Returns: TriangleMesh_";
constexpr const char* Surface_mesh_parameterization_ARAP_parameterizer_3_halfedge_descriptor = "Mesh halfedge type.

Returns: boost::graph_traits< Triangle_mesh >::halfedge_descriptor";
constexpr const char* Surface_mesh_parameterization_ARAP_parameterizer_3_is_one_to_one_mapping = "returns whether the 3D -> 2D mapping is one-to-one.

Parameters
----------
mesh : const Triangle_mesh &
faces : const FaceRange &
uvmap : const VertexUVMap

Returns: bool";
constexpr const char* Surface_mesh_parameterization_ARAP_parameterizer_3_parameterize = "computes a mapping from a triangular 3D surface mesh to a piece of the 2D space.

The mapping is piecewise linear (linear in each triangle). The result is the
(u,v) pair image of each vertex of the 3D surface. VertexUVmap must be a model
of ReadWritePropertyMap with boost::graph_traits< Triangle_mesh
>::vertex_descriptor as key type and Point_2 (type deduced from Triangle_mesh
using Kernel_traits ) as value type. VertexIndexMap must be a model of
ReadablePropertyMap with boost::graph_traits< Triangle_mesh
>::vertex_descriptor as key type and a unique integer as value type.
VertexParameterizedMap must be a model of ReadWritePropertyMap with
boost::graph_traits< Triangle_mesh >::vertex_descriptor as key type and a
Boolean as value type. mesh a triangulated surface. bhd a halfedge descriptor
on the boundary of mesh . uvmap an instantiation of the class VertexUVmap .
vimap an instantiation of the class VertexIndexMap . vpmap an instantiation of
the class VertexParameterizedMap . mesh must be a triangular mesh. The
vertices must be indexed (vimap must be initialized).

Parameters
----------
mesh : Triangle_mesh &
bhd : halfedge_descriptor
uvmap : VertexUVMap
vimap : VertexIndexMap
vpmap : VertexParameterizedMap

Returns: Error_code";
constexpr const char* Surface_mesh_parameterization_ARAP_parameterizer_3_ARAP_parameterizer_3 = "Constructor taking only the parameter $\\lambda$ .

Parameters
----------
lambda : NT";
constexpr const char* Surface_mesh_parameterization_ARAP_parameterizer_3_ARAP_parameterizer_3_1 = "Default Constructor.

border_param Object that maps the surface's border to the 2D space. sparse_la
Traits object to access a sparse linear system. lambda Parameter to give
importance to shape or angle preservation. iterations Maximal number of
iterations in the energy minimization process. tolerance Minimal energy
difference between two iterations for the minimization process to continue.

Parameters
----------
border_param : Border_parameterizer
sparse_la : Solver_traits
lambda : NT
iterations : unsigned int
tolerance : NT";

// CGAL::Surface_mesh_parameterization::Barycentric_mapping_parameterizer_3
constexpr const char* Surface_mesh_parameterization_Barycentric_mapping_parameterizer_3__class__ = "The class Barycentric_mapping_parameterizer_3 implements Tutte Barycentric Mapping algorithm .";

constexpr const char* Surface_mesh_parameterization_Barycentric_mapping_parameterizer_3_Border_parameterizer = "Border parameterizer type.

Returns: Border_parameterizer_";
constexpr const char* Surface_mesh_parameterization_Barycentric_mapping_parameterizer_3_Solver_traits = "Solver traits type.

Returns: SolverTraits_";
constexpr const char* Surface_mesh_parameterization_Barycentric_mapping_parameterizer_3_Triangle_mesh = "Triangle mesh type.

Returns: TriangleMesh_";
constexpr const char* Surface_mesh_parameterization_Barycentric_mapping_parameterizer_3_vertex_descriptor = "Mesh vertex type.

Returns: boost::graph_traits< Triangle_mesh >::vertex_descriptor";
constexpr const char* Surface_mesh_parameterization_Barycentric_mapping_parameterizer_3_halfedge_descriptor = "Mesh halfedge type.

Returns: boost::graph_traits< Triangle_mesh >::halfedge_descriptor";
constexpr const char* Surface_mesh_parameterization_Barycentric_mapping_parameterizer_3_Barycentric_mapping_parameterizer_3 = "Constructor.

Parameters
----------
border_param : Border_parameterizer  —  Object that maps the surface's border to 2D space.
sparse_la : Solver_traits  —  Traits object to access a sparse linear system.";
constexpr const char* Surface_mesh_parameterization_Barycentric_mapping_parameterizer_3_is_one_to_one_mapping = "returns whether the 3D -> 2D mapping is one-to-one.

Parameters
----------
mesh : const Triangle_mesh &
bhd : halfedge_descriptor
uvmap : const VertexUVMap

Returns: bool";
constexpr const char* Surface_mesh_parameterization_Barycentric_mapping_parameterizer_3_compute_w_ij = "computes w_ij , the coefficient of matrix A for j neighbor vertex of i .

Parameters
----------
 : const Triangle_mesh &
 : vertex_descriptor
 : Vertex_around_target_circulator< Triangle_mesh >

Returns: NT";

// CGAL::Surface_mesh_parameterization::Circular_border_arc_length_parameterizer_3
constexpr const char* Surface_mesh_parameterization_Circular_border_arc_length_parameterizer_3__class__ = "This class parameterizes the border of a 3D surface onto a circle, with an arc-length parameterization: the (u,v) values are proportional to the length of border edges.";

constexpr const char* Surface_mesh_parameterization_Circular_border_arc_length_parameterizer_3_compute_edge_length = "computes the length of an edge.

Parameters
----------
mesh : const Triangle_mesh &
source : vertex_descriptor
target : vertex_descriptor

Returns: NT";

// CGAL::Surface_mesh_parameterization::Circular_border_parameterizer_3
constexpr const char* Surface_mesh_parameterization_Circular_border_parameterizer_3__class__ = "This is the base class of strategies that parameterize the border of a 3D surface onto a circle.";

constexpr const char* Surface_mesh_parameterization_Circular_border_parameterizer_3_Triangle_mesh = "Triangle mesh type.

Returns: TriangleMesh_";
constexpr const char* Surface_mesh_parameterization_Circular_border_parameterizer_3_vertex_descriptor = "Mesh vertex type.

Returns: boost::graph_traits< Triangle_mesh >::vertex_descriptor";
constexpr const char* Surface_mesh_parameterization_Circular_border_parameterizer_3_halfedge_descriptor = "Mesh halfedge type.

Returns: boost::graph_traits< Triangle_mesh >::halfedge_descriptor";
constexpr const char* Surface_mesh_parameterization_Circular_border_parameterizer_3_parameterize = "assigns to the mesh's border vertices a 2D position (i.e. a (u,v) pair) on the circle.

Mark them as parameterized . The distribution of vertices over the circle
depends on the function compute_edge_length() . VertexUVmap must be a model of
ReadWritePropertyMap with boost::graph_traits< Triangle_mesh
>::vertex_descriptor as key type and Point_2 (type deduced from Triangle_mesh
using Kernel_traits ) as value type. VertexIndexMap must be a model of
ReadablePropertyMap with boost::graph_traits< Triangle_mesh
>::vertex_descriptor as key type and a unique integer as value type.
VertexParameterizedMap must be a model of ReadWritePropertyMap with
boost::graph_traits< Triangle_mesh >::vertex_descriptor as key type and a
Boolean as value type. mesh a triangulated surface. bhd a halfedge descriptor
on the boundary of mesh . uvmap an instantiation of the class VertexUVmap .
vpmap an instantiation of the class VertexParameterizedMap . mesh must be a
triangular mesh. The vertices must be indexed (vimap must be initialized).

Parameters
----------
mesh : const Triangle_mesh &
bhd : halfedge_descriptor
uvmap : VertexUVmap
 : VertexIndexMap
vpmap : VertexParameterizedMap

Returns: Error_code";
constexpr const char* Surface_mesh_parameterization_Circular_border_parameterizer_3_is_border_convex = "indicates if border's shape is convex.

Returns: bool";

// CGAL::Surface_mesh_parameterization::Circular_border_uniform_parameterizer_3
constexpr const char* Surface_mesh_parameterization_Circular_border_uniform_parameterizer_3__class__ = "This class parameterizes the border of a 3D surface onto a circle in a uniform manner: points are equally spaced.";

constexpr const char* Surface_mesh_parameterization_Circular_border_uniform_parameterizer_3_compute_edge_length = "computes the length of an edge.

Parameters
----------
 : const Triangle_mesh &
 : vertex_descriptor
 : vertex_descriptor

Returns: NT";

// CGAL::Surface_mesh_parameterization::Discrete_authalic_parameterizer_3
constexpr const char* Surface_mesh_parameterization_Discrete_authalic_parameterizer_3__class__ = "The class Discrete_authalic_parameterizer_3 implements the Discrete Authalic Parameterization algorithm.";

constexpr const char* Surface_mesh_parameterization_Discrete_authalic_parameterizer_3_Border_parameterizer = "Border parameterizer type.

Returns: Border_parameterizer_";
constexpr const char* Surface_mesh_parameterization_Discrete_authalic_parameterizer_3_Solver_traits = "Solver traits type.

Returns: SolverTraits_";
constexpr const char* Surface_mesh_parameterization_Discrete_authalic_parameterizer_3_Triangle_mesh = "Triangle mesh type.

Returns: TriangleMesh_";
constexpr const char* Surface_mesh_parameterization_Discrete_authalic_parameterizer_3_vertex_descriptor = "Mesh vertex type.

Returns: boost::graph_traits< Triangle_mesh >::vertex_descriptor";
constexpr const char* Surface_mesh_parameterization_Discrete_authalic_parameterizer_3_Discrete_authalic_parameterizer_3 = "Constructor.

Parameters
----------
border_param : Border_parameterizer  —  Object that maps the surface's border to 2D space.
sparse_la : Solver_traits  —  Traits object to access a sparse linear system.";
constexpr const char* Surface_mesh_parameterization_Discrete_authalic_parameterizer_3_compute_w_ij = "computes w_ij , the (i,j), coefficient of matrix A for j neighbor vertex of i .

mesh a triangulated surface. main_vertex_v_i the vertex of mesh with index i
neighbor_vertex_v_j the vertex of mesh with index j

Parameters
----------
mesh : const Triangle_mesh &
main_vertex_v_i : vertex_descriptor
neighbor_vertex_v_j : Vertex_around_target_circulator< Triangle_mesh >

Returns: NT";

// CGAL::Surface_mesh_parameterization::Discrete_conformal_map_parameterizer_3
constexpr const char* Surface_mesh_parameterization_Discrete_conformal_map_parameterizer_3__class__ = "The class Discrete_conformal_map_parameterizer_3 implements the Discrete Conformal Map (DCM) parameterization.";

constexpr const char* Surface_mesh_parameterization_Discrete_conformal_map_parameterizer_3_Border_parameterizer = "Border parameterizer type.

Returns: Border_parameterizer_";
constexpr const char* Surface_mesh_parameterization_Discrete_conformal_map_parameterizer_3_Solver_traits = "Solver traits type.

Returns: SolverTraits_";
constexpr const char* Surface_mesh_parameterization_Discrete_conformal_map_parameterizer_3_Triangle_mesh = "Triangle mesh type.

Returns: TriangleMesh_";
constexpr const char* Surface_mesh_parameterization_Discrete_conformal_map_parameterizer_3_Discrete_conformal_map_parameterizer_3 = "Constructor.

Parameters
----------
border_param : Border_parameterizer  —  Object that maps the surface's border to 2D space.
sparse_la : Solver_traits  —  Traits object to access a sparse linear system.";
constexpr const char* Surface_mesh_parameterization_Discrete_conformal_map_parameterizer_3_compute_w_ij = "computes w_ij , the (i,j) -coefficient of matrix A , for j neighbor vertex of i .

mesh a triangulated surface. main_vertex_v_i the vertex of mesh with index i
neighbor_vertex_v_j the vertex of mesh with index j

Parameters
----------
mesh : const Triangle_mesh &
main_vertex_v_i : vertex_descriptor
neighbor_vertex_v_j : Vertex_around_target_circulator< Triangle_mesh >

Returns: NT";

// CGAL::Surface_mesh_parameterization::Fixed_border_parameterizer_3
constexpr const char* Surface_mesh_parameterization_Fixed_border_parameterizer_3__class__ = "The class Fixed_border_parameterizer_3 is the base class of fixed border parameterization methods (Tutte, Floater, ...).";

constexpr const char* Surface_mesh_parameterization_Fixed_border_parameterizer_3_Border_parameterizer = "Border parameterizer type.

Returns: Border_parameterizer_";
constexpr const char* Surface_mesh_parameterization_Fixed_border_parameterizer_3_Solver_traits = "Solver traits type.

Returns: SolverTraits_";
constexpr const char* Surface_mesh_parameterization_Fixed_border_parameterizer_3_Triangle_mesh = "Triangle mesh type.

Returns: TriangleMesh_";
constexpr const char* Surface_mesh_parameterization_Fixed_border_parameterizer_3_vertex_descriptor = "Mesh vertex type.

Returns: boost::graph_traits< Triangle_mesh >::vertex_descriptor";
constexpr const char* Surface_mesh_parameterization_Fixed_border_parameterizer_3_halfedge_descriptor = "Mesh halfedge type.

Returns: boost::graph_traits< Triangle_mesh >::halfedge_descriptor";
constexpr const char* Surface_mesh_parameterization_Fixed_border_parameterizer_3_Vector = "Solver vector type.

Returns: Solver_traits::Vector";
constexpr const char* Surface_mesh_parameterization_Fixed_border_parameterizer_3_Matrix = "Solver matrix type.

Returns: Solver_traits::Matrix";
constexpr const char* Surface_mesh_parameterization_Fixed_border_parameterizer_3_Fixed_border_parameterizer_3 = "Constructor.

Parameters
----------
border_param : Border_parameterizer  —  Object that maps the surface's border to 2D space
sparse_la : Solver_traits  —  Traits object to access a sparse linear system";
constexpr const char* Surface_mesh_parameterization_Fixed_border_parameterizer_3_Fixed_border_parameterizer_3_1 = "Destructor of base class should be virtual.";
constexpr const char* Surface_mesh_parameterization_Fixed_border_parameterizer_3_parameterize = "computes a one-to-one mapping from a triangular 3D surface mesh to a piece of the 2D space.

The mapping is piecewise linear (linear in each triangle). The result is the
(u,v) pair image of each vertex of the 3D surface. VertexUVmap must be a model
of ReadWritePropertyMap with boost::graph_traits< Triangle_mesh
>::vertex_descriptor as key type and Point_2 (type deduced from Triangle_mesh
using Kernel_traits ) as value type. VertexIndexMap must be a model of
ReadablePropertyMap with boost::graph_traits< Triangle_mesh
>::vertex_descriptor as key type and a unique integer as value type.
VertexParameterizedMap must be a model of ReadWritePropertyMap with
boost::graph_traits< Triangle_mesh >::vertex_descriptor as key type and a
Boolean as value type. mesh a triangulated surface. bhd a halfedge descriptor
on the boundary of mesh . uvmap an instantiation of the class VertexUVmap .
vimap an instantiation of the class VertexIndexMap . vpmap an instantiation of
the class VertexParameterizedMap . mesh must be a triangular mesh. The mesh
border must be mapped onto a convex polygon. The vertices must be indexed (
vimap must be initialized)

Parameters
----------
mesh : Triangle_mesh &
bhd : halfedge_descriptor
uvmap : VertexUVmap
vimap : VertexIndexMap
vpmap : VertexParameterizedMap

Returns: Error_code";
constexpr const char* Surface_mesh_parameterization_Fixed_border_parameterizer_3_initialize_system_from_mesh_border = "initializes A , Bu and Bv after border parameterization.

Fill the border vertices' lines in both linear systems: \"u = constant\" and \"v
= constant\". VertexUVmap must be a model of ReadWritePropertyMap with
boost::graph_traits< Triangle_mesh >::vertex_descriptor as key type and
Point_2 (type deduced from Triangle_mesh using Kernel_traits ) as value type.
VertexIndexMap must be a model of ReadablePropertyMap with
boost::graph_traits< Triangle_mesh >::vertex_descriptor as key type and a
unique integer as value type. A the matrix in both linear system Bu the right
hand side vector in the linear system of x coordinates Bv the right hand side
vector in the linear system of y coordinates mesh a triangulated surface. bhd
a halfedge descriptor on the boundary of mesh . uvmap an instantiation of the
class VertexUVmap . vimap an instantiation of the class VertexIndexMap .
Vertices must be indexed ( vimap must be initialized). A , Bu , and Bv must be
allocated. Border vertices must be parameterized.

Parameters
----------
A : Matrix &
Bu : Vector &
Bv : Vector &
mesh : const Triangle_mesh &
bhd : halfedge_descriptor
uvmap : VertexUVmap
vimap : VertexIndexMap";
constexpr const char* Surface_mesh_parameterization_Fixed_border_parameterizer_3_compute_w_ij = "computes w_ij , coefficient of matrix A for j neighbor vertex of i .

Implementation note: Subclasses must at least implement compute_w_ij() . mesh
a triangulated surface. main_vertex_v_i the vertex of mesh with index i
neighbor_vertex_v_j the vertex of mesh with index j

Parameters
----------
mesh : const Triangle_mesh &
main_vertex_v_i : vertex_descriptor
neighbor_vertex_v_j : Vertex_around_target_circulator< Triangle_mesh >

Returns: NT";
constexpr const char* Surface_mesh_parameterization_Fixed_border_parameterizer_3_setup_inner_vertex_relations = "Compute the line i of matrix A for i inner vertex:

call compute_w_ij() to compute the A coefficient w_ij for each neighbor v_j.
compute w_ii = - sum of w_ijs. Vertices must be indexed. Vertex i mustn't be
already parameterized. Line i of A must contain only zeros.

Parameters
----------
A : Matrix &
 : Vector &
 : Vector &
mesh : const Triangle_mesh &
vertex : vertex_descriptor
vimap : VertexIndexMap

Returns: Error_code";
constexpr const char* Surface_mesh_parameterization_Fixed_border_parameterizer_3_get_border_parameterizer = "Get the object that maps the surface's border onto a 2D space.

Returns: Border_parameterizer &";
constexpr const char* Surface_mesh_parameterization_Fixed_border_parameterizer_3_get_linear_algebra_traits = "Get the sparse linear algebra (traits object to access the linear system).

Returns: Solver_traits &";

// CGAL::Surface_mesh_parameterization::Iterative_authalic_parameterizer_3
constexpr const char* Surface_mesh_parameterization_Iterative_authalic_parameterizer_3__class__ = "The class Iterative_authalic_parameterizer_3 implements the Iterative Parameterization algorithm, as described by Jain et al.";

constexpr const char* Surface_mesh_parameterization_Iterative_authalic_parameterizer_3_Border_parameterizer = "Border parameterizer type.

Returns: Border_parameterizer_";
constexpr const char* Surface_mesh_parameterization_Iterative_authalic_parameterizer_3_Solver_traits = "Solver traits type.

Returns: SolverTraits_";
constexpr const char* Surface_mesh_parameterization_Iterative_authalic_parameterizer_3_Triangle_mesh = "Triangle mesh type.

Returns: TriangleMesh_";
constexpr const char* Surface_mesh_parameterization_Iterative_authalic_parameterizer_3_get_border_parameterizer = "Get the object that maps the surface's border onto a 2D space.

Returns: Border_parameterizer &";
constexpr const char* Surface_mesh_parameterization_Iterative_authalic_parameterizer_3_get_linear_algebra_traits = "Get the sparse linear algebra (traits object to access the linear system).

Returns: Solver_traits &";
constexpr const char* Surface_mesh_parameterization_Iterative_authalic_parameterizer_3_Iterative_authalic_parameterizer_3 = "Constructor.

border_parameterizer Object that maps the surface's border to 2D space
sparse_la Traits object to access a sparse linear system

Parameters
----------
border_parameterizer : Border_parameterizer
sparse_la : Solver_traits";
constexpr const char* Surface_mesh_parameterization_Iterative_authalic_parameterizer_3_initialize_system_from_mesh_border = "initializes A , Bu , and Bv after border parameterization.

Fill the border vertices' lines in both linear systems: \"u = constant\" and \"v
= constant\". VertexUVmap must be a model of ReadWritePropertyMap with
boost::graph_traits< Triangle_mesh >::vertex_descriptor as key type and
Point_2 (type deduced from Triangle_mesh using Kernel_traits ) as value type.
VertexIndexMap must be a model of ReadablePropertyMap with
boost::graph_traits< Triangle_mesh >::vertex_descriptor as key type and a
unique integer as value type. A the matrix in both linear system Bu the right
hand side vector in the linear system of x coordinates Bv the right hand side
vector in the linear system of y coordinates tmesh a triangulated surface bhd
a halfedge descriptor on the boundary of mesh uvmap an instantiation of the
class VertexUVmap vimap an instantiation of the class VertexIndexMap Vertices
must be indexed ( vimap must be initialized). A , Bu , and Bv must be
allocated. Border vertices must be parameterized.

Parameters
----------
A : Matrix &
Bu : Vector &
Bv : Vector &
tmesh : const Triangle_mesh &
bhd : halfedge_descriptor
uvmap : VertexUVmap
vimap : VertexIndexMap";
constexpr const char* Surface_mesh_parameterization_Iterative_authalic_parameterizer_3_parameterize = "computes a one-to-one mapping from a triangular 3D surface mesh to a piece of the 2D space.

The mapping is piecewise linear (linear in each triangle). The result is the
(u,v) pair image of each vertex of the 3D surface. VertexUVmap must be a model
of ReadWritePropertyMap with boost::graph_traits< Triangle_mesh
>::vertex_descriptor as key type and Point_2 (type deduced from Triangle_mesh
using Kernel_traits ) as value type. VertexIndexMap must be a model of
ReadablePropertyMap with boost::graph_traits< Triangle_mesh
>::vertex_descriptor as key type and a unique integer as value type.
VertexParameterizedMap must be a model of ReadWritePropertyMap with
boost::graph_traits< Triangle_mesh >::vertex_descriptor as key type and a
Boolean as value type. tmesh a triangulated surface bhd a halfedge descriptor
on the boundary of mesh uvmap an instantiation of the class VertexUVmap vimap
an instantiation of the class VertexIndexMap vpmap an instantiation of the
class VertexParameterizedMap iterations an integer number of iterations to run
the parameterization tmesh must be a triangular mesh. The mesh border must be
mapped onto a convex polygon. The vertices must be indexed ( vimap must be
initialized).

Parameters
----------
tmesh : Triangle_mesh &
bhd : halfedge_descriptor
uvmap : VertexUVmap
vimap : VertexIndexMap
vpmap : VertexParameterizedMap
iterations : const unsigned int &

Returns: Error_code";
constexpr const char* Surface_mesh_parameterization_Iterative_authalic_parameterizer_3_compute_w_ij = "computes w_ij , coefficient of matrix A for j neighbor vertex of i .

tmesh a triangulated surface. main_vertex_v_i the vertex of mesh with index i
neighbor_vertex_v_j the vertex of mesh with index j

Parameters
----------
tmesh : const Triangle_mesh &
main_vertex_v_i : vertex_descriptor
neighbor_vertex_v_j : Vertex_around_target_circulator< Triangle_mesh >

Returns: NT";


// CGAL::Surface_mesh_parameterization::LSCM_parameterizer_3
constexpr const char* Surface_mesh_parameterization_LSCM_parameterizer_3__class__ = "The class LSCM_parameterizer_3 implements the Least Squares Conformal Maps (LSCM) parameterization [8] .";

constexpr const char* Surface_mesh_parameterization_LSCM_parameterizer_3_Border_parameterizer = "The border parameterizer.

Returns: Border_parameterizer_";
constexpr const char* Surface_mesh_parameterization_LSCM_parameterizer_3_Solver_traits = "Solver traits type.

Returns: SolverTraits_";
constexpr const char* Surface_mesh_parameterization_LSCM_parameterizer_3_Triangle_mesh = "Triangle mesh type.

Returns: TriangleMesh_";
constexpr const char* Surface_mesh_parameterization_LSCM_parameterizer_3_halfedge_descriptor = "Mesh halfedge type.

Returns: boost::graph_traits< Triangle_mesh >::halfedge_descriptor";
constexpr const char* Surface_mesh_parameterization_LSCM_parameterizer_3_LSCM_parameterizer_3 = "Constructor.

Parameters
----------
border_param : Border_parameterizer  —  Object that maps the surface's border to 2D space
sparse_la : Solver_traits  —  Traits object to access a sparse linear system";
constexpr const char* Surface_mesh_parameterization_LSCM_parameterizer_3_is_one_to_one_mapping = "returns whether the 3D -> 2D mapping is one-to-one.

Parameters
----------
mesh : const Triangle_mesh &
bhd : halfedge_descriptor
uvmap : const VertexUVMap

Returns: bool";
constexpr const char* Surface_mesh_parameterization_LSCM_parameterizer_3_parameterize = "computes a one-to-one mapping from a triangular 3D surface mesh to a piece of the 2D space.

The mapping is piecewise linear (linear in each triangle). The result is the
(u,v) pair image of each vertex of the 3D surface. VertexUVmap must be a model
of ReadWritePropertyMap with boost::graph_traits< Triangle_mesh
>::vertex_descriptor as key type and Point_2 (type deduced from Triangle_mesh
using Kernel_traits ) as value type. VertexIndexMap must be a model of
ReadablePropertyMap with boost::graph_traits< Triangle_mesh
>::vertex_descriptor as key type and a unique integer as value type.
VertexParameterizedMap must be a model of ReadWritePropertyMap with
boost::graph_traits< Triangle_mesh >::vertex_descriptor as key type and a
Boolean as value type. mesh a triangulated surface. bhd a halfedge descriptor
on the boundary of mesh . uvmap an instantiation of the class VertexUVmap .
vimap an instantiation of the class VertexIndexMap . vpmap an instantiation of
the class VertexParameterizedMap . mesh must be a triangular mesh. The
vertices must be indexed ( vimap must be initialized).

Parameters
----------
mesh : Triangle_mesh &
bhd : halfedge_descriptor
uvmap : VertexUVmap
vimap : VertexIndexMap
vpmap : VertexParameterizedMap

Returns: Error_code";

// CGAL::Surface_mesh_parameterization::Mean_value_coordinates_parameterizer_3
constexpr const char* Surface_mesh_parameterization_Mean_value_coordinates_parameterizer_3__class__ = "The class Mean_value_coordinates_parameterizer_3 implements Floater Mean Value Coordinates parameterization.";

constexpr const char* Surface_mesh_parameterization_Mean_value_coordinates_parameterizer_3_Border_parameterizer = "The border parameterizer.

Returns: Border_parameterizer_";
constexpr const char* Surface_mesh_parameterization_Mean_value_coordinates_parameterizer_3_Solver_traits = "Solver traits type.

Returns: SolverTraits_";
constexpr const char* Surface_mesh_parameterization_Mean_value_coordinates_parameterizer_3_Triangle_mesh = "Triangle mesh type.

Returns: TriangleMesh_";
constexpr const char* Surface_mesh_parameterization_Mean_value_coordinates_parameterizer_3_vertex_descriptor = "Mesh vertex type.

Returns: boost::graph_traits< Triangle_mesh >::vertex_descriptor";
constexpr const char* Surface_mesh_parameterization_Mean_value_coordinates_parameterizer_3_halfedge_descriptor = "Mesh halfedge type.

Returns: boost::graph_traits< Triangle_mesh >::halfedge_descriptor";
constexpr const char* Surface_mesh_parameterization_Mean_value_coordinates_parameterizer_3_Mean_value_coordinates_parameterizer_3 = "Constructor.

Parameters
----------
border_param : Border_parameterizer  —  Object that maps the surface's border to 2D space.
sparse_la : Solver_traits  —  Traits object to access a sparse linear system.";
constexpr const char* Surface_mesh_parameterization_Mean_value_coordinates_parameterizer_3_is_one_to_one_mapping = "returns whether the 3D -> 2D mapping is one-to-one.

Parameters
----------
mesh : const Triangle_mesh &
bhd : halfedge_descriptor
uvmap : const VertexUVMap

Returns: bool";
constexpr const char* Surface_mesh_parameterization_Mean_value_coordinates_parameterizer_3_compute_w_ij = "computes w_ij , the (i, j) -coefficient of matrix A for j neighbor vertex of i.

mesh a triangulated surface. main_vertex_v_i the vertex of mesh with index i
neighbor_vertex_v_j the vertex of mesh with index j

Parameters
----------
mesh : const Triangle_mesh &
main_vertex_v_i : vertex_descriptor
neighbor_vertex_v_j : Vertex_around_target_circulator< Triangle_mesh >

Returns: NT";

// CGAL::Surface_mesh_parameterization::MVC_post_processor_3
constexpr const char* Surface_mesh_parameterization_MVC_post_processor_3__class__ = "The class MVC_post_processor_3 implements the Free boundary linear Parameterization algorithm [7] .";

constexpr const char* Surface_mesh_parameterization_MVC_post_processor_3_Solver_traits = "Solver traits type.

Returns: SolverTraits_";
constexpr const char* Surface_mesh_parameterization_MVC_post_processor_3_Triangle_mesh = "Triangle mesh type.

Returns: TriangleMesh_";
constexpr const char* Surface_mesh_parameterization_MVC_post_processor_3_parameterize = "computes a one-to-one mapping from a triangular 2D surface mesh that is not necessarily embedded to a piece of the 2D space.

VertexUVmap must be a model of ReadWritePropertyMap with boost::graph_traits<
Triangle_mesh >::vertex_descriptor as key type and Point_2 (type deduced from
Triangle_mesh using Kernel_traits ) as value type. VertexIndexMap must be a
model of ReadablePropertyMap with boost::graph_traits< Triangle_mesh
>::vertex_descriptor as key type and a unique integer as value type. mesh a
triangulated surface. bhd a halfedge descriptor on the boundary of mesh .
uvmap an instantiation of the class VertexUVmap . vimap an instantiation of
the class VertexIndexMap .

Parameters
----------
mesh : const Triangle_mesh &
bhd : halfedge_descriptor
uvmap : VertexUVMap
vimap : const VertexIndexMap

Returns: Error_code";
constexpr const char* Surface_mesh_parameterization_MVC_post_processor_3_MVC_post_processor_3 = "Constructor.

sparse_la Traits object to access a sparse linear system.

Parameters
----------
sparse_la : Solver_traits";

// CGAL::Surface_mesh_parameterization::Orbifold_Tutte_parameterizer_3
constexpr const char* Surface_mesh_parameterization_Orbifold_Tutte_parameterizer_3__class__ = "The class Orbifold_Tutte_parameterizer_3 implements Orbifold Tutte Planar Embeddings [1] .";

constexpr const char* Surface_mesh_parameterization_Orbifold_Tutte_parameterizer_3_Solver_traits = "Solver traits type.

Returns: SolverTraits_";
constexpr const char* Surface_mesh_parameterization_Orbifold_Tutte_parameterizer_3_halfedge_descriptor = "Mesh halfedge type.

Returns: boost::graph_traits< SeamMesh >::halfedge_descriptor";
constexpr const char* Surface_mesh_parameterization_Orbifold_Tutte_parameterizer_3_parameterize = "computes a one-to-one mapping from a triangular 3D surface mesh to a piece of the 2D space.

The mapping is piecewise linear (linear in each triangle). The result is the
(u,v) pair image of each vertex of the 3D surface. ConeMap must be a model of
AssociativeContainer with key type
boost::graph_traits<Seam_mesh>::vertex_descriptor and Cone_type as value type.
VertexUVmap must be a model of ReadWritePropertyMap with
boost::graph_traits<Seam_mesh>::vertex_descriptor as key type and Point_2
(type deduced from Seam_mesh using Kernel_traits ) as value type.
VertexIndexMap must be a model of ReadablePropertyMap with
boost::graph_traits<Seam_mesh>::vertex_descriptor as key type and a unique
integer as value type. mesh a Seam_mesh parameterized by any model of a
FaceListGraph and HalfedgeListGraph bhd a halfedge on the border of the seam
mesh cmap a mapping of the vertex_descriptor s of mesh that are cones to their
respective Cone_type classification. uvmap an instantiation of the class
VertexUVmap . vimap an instantiation of the class VertexIndexMap . mesh must
be a triangular mesh. The underlying mesh of mesh is a topological ball. The
vertices must be indexed (vimap must be initialized). The cones are vertices
of mesh and their number is adapted to the orbifold type (4 for types I, II or
III and 6 for type IV). The seam edges form a set of segments that contains
the different cones, and starts and ends at two different cones. The seam
edges form a set of segments that is homotopic to a line. Specifically, the
paths between cones must not self intersect or intersect other paths (see
Figure below). fig__Surface_mesh_parameterizationfigorbifold Invalid (left)
and valid (right) seam paths. Seam edges are drawn in teal. Cones are marked
in yellow and blue.

Parameters
----------
mesh : SeamMesh &
bhd : halfedge_descriptor
cmap : const ConeMap &
uvmap : VertexUVMap
vimap : VertexIndexMap

Returns: Error_code";
constexpr const char* Surface_mesh_parameterization_Orbifold_Tutte_parameterizer_3_Orbifold_Tutte_parameterizer_3 = "Constructor of the parameterizer.

The arguments allow to select the desired orbifold and weight types.

Parameters
----------
orb_type : const Orbifold_type
weight_type : const Weight_type";

// CGAL::Surface_mesh_parameterization::Square_border_arc_length_parameterizer_3
constexpr const char* Surface_mesh_parameterization_Square_border_arc_length_parameterizer_3__class__ = "This class parameterizes the border of a 3D surface onto a square, with an arc-length parameterization: (u,v) values are proportional to the length of border edges.";

constexpr const char* Surface_mesh_parameterization_Square_border_arc_length_parameterizer_3_Square_border_arc_length_parameterizer_3 = "Constructor.";
constexpr const char* Surface_mesh_parameterization_Square_border_arc_length_parameterizer_3_Square_border_arc_length_parameterizer_3_1 = "Constructor with user-defined corners: the user provides four vertices of the border of the mesh, which will be parameterized to the corners of the square.

The given vertices must be on the border.

Parameters
----------
v0 : vertex_descriptor
v1 : vertex_descriptor
v2 : vertex_descriptor
v3 : vertex_descriptor";
constexpr const char* Surface_mesh_parameterization_Square_border_arc_length_parameterizer_3_compute_edge_length = "Compute the length of an edge.

Parameters
----------
mesh : const Triangle_mesh &
source : vertex_descriptor
target : vertex_descriptor

Returns: NT";

// CGAL::Surface_mesh_parameterization::Square_border_parameterizer_3
constexpr const char* Surface_mesh_parameterization_Square_border_parameterizer_3__class__ = "This is the base class of strategies that parameterize the border of a 3D surface onto a square.";

constexpr const char* Surface_mesh_parameterization_Square_border_parameterizer_3_Triangle_mesh = "Triangle mesh type.

Returns: TriangleMesh_";
constexpr const char* Surface_mesh_parameterization_Square_border_parameterizer_3_vertex_descriptor = "Mesh vertex type.

Returns: boost::graph_traits< Triangle_mesh >::vertex_descriptor";
constexpr const char* Surface_mesh_parameterization_Square_border_parameterizer_3_halfedge_descriptor = "Mesh halfedge type.

Returns: boost::graph_traits< Triangle_mesh >::halfedge_descriptor";
constexpr const char* Surface_mesh_parameterization_Square_border_parameterizer_3_parameterize = "assigns to the vertices of the border of the mesh a 2D position (i.e. a (u,v) pair) on the border's shape.

Mark them as parameterized . VertexUVmap must be a model of
ReadWritePropertyMap with boost::graph_traits< Triangle_mesh
>::vertex_descriptor as key type and Point_2 (type deduced from Triangle_mesh
using Kernel_traits ) as value type. VertexIndexMap must be a model of
ReadablePropertyMap with boost::graph_traits< Triangle_mesh
>::vertex_descriptor as key type and a unique integer as value type.
VertexParameterizedMap must be a model of ReadWritePropertyMap with
boost::graph_traits< Triangle_mesh >::vertex_descriptor as key type and a
Boolean as value type. mesh a triangulated surface. bhd a halfedge descriptor
on the boundary of mesh . uvmap an instantiation of the class VertexUVmap .
vpmap an instantiation of the class VertexParameterizedMap . mesh must be a
triangular mesh. The vertices must be indexed (vimap must be initialized).

Parameters
----------
mesh : const Triangle_mesh &
bhd : halfedge_descriptor
uvmap : VertexUVMap
 : VertexIndexMap
vpmap : VertexParameterizedMap

Returns: Error_code";
constexpr const char* Surface_mesh_parameterization_Square_border_parameterizer_3_is_border_convex = "indicates if the border's shape is convex.

Returns: bool";
constexpr const char* Surface_mesh_parameterization_Square_border_parameterizer_3_Square_border_parameterizer_3 = "Constructor.";
constexpr const char* Surface_mesh_parameterization_Square_border_parameterizer_3_Square_border_parameterizer_3_1 = "Constructor with user-defined corners: the user provides four vertices of the border of the mesh, which will be parameterized to the corners of the square.

The given vertices must be on the border.

Parameters
----------
v0 : vertex_descriptor
v1 : vertex_descriptor
v2 : vertex_descriptor
v3 : vertex_descriptor";

// CGAL::Surface_mesh_parameterization::Square_border_uniform_parameterizer_3
constexpr const char* Surface_mesh_parameterization_Square_border_uniform_parameterizer_3__class__ = "This class parameterizes the border of a 3D surface onto a square in a uniform manner: points are equally spaced.";

constexpr const char* Surface_mesh_parameterization_Square_border_uniform_parameterizer_3_Square_border_uniform_parameterizer_3 = "Constructor.";
constexpr const char* Surface_mesh_parameterization_Square_border_uniform_parameterizer_3_Square_border_uniform_parameterizer_3_1 = "Constructor with user-defined corners: the user provides four vertices of the border of the mesh, which will be parameterized to the corners of the square.

The given vertices must be on the border.

Parameters
----------
v0 : vertex_descriptor
v1 : vertex_descriptor
v2 : vertex_descriptor
v3 : vertex_descriptor";
constexpr const char* Surface_mesh_parameterization_Square_border_uniform_parameterizer_3_compute_edge_length = "computes the length of an edge.

Parameters
----------
 : const Triangle_mesh &
 : vertex_descriptor
 : vertex_descriptor

Returns: NT";

// CGAL::Surface_mesh_parameterization::Two_vertices_parameterizer_3
constexpr const char* Surface_mesh_parameterization_Two_vertices_parameterizer_3__class__ = "The class Two_vertices_parameterizer_3 parameterizes two extreme vertices of a 3D surface.";

constexpr const char* Surface_mesh_parameterization_Two_vertices_parameterizer_3_Triangle_mesh = "Triangle mesh type.

Returns: TriangleMesh_";
constexpr const char* Surface_mesh_parameterization_Two_vertices_parameterizer_3_vertex_descriptor = "Mesh vertex type.

Returns: boost::graph_traits< Triangle_mesh >::vertex_descriptor";
constexpr const char* Surface_mesh_parameterization_Two_vertices_parameterizer_3_halfedge_descriptor = "Mesh halfedge type.

Returns: boost::graph_traits< Triangle_mesh >::halfedge_descriptor";
constexpr const char* Surface_mesh_parameterization_Two_vertices_parameterizer_3_Two_vertices_parameterizer_3 = "Constructor.";
constexpr const char* Surface_mesh_parameterization_Two_vertices_parameterizer_3_Two_vertices_parameterizer_3_1 = "Constructor where fixed vertices are provided.

Parameters
----------
v1 : vertex_descriptor
v2 : vertex_descriptor";
constexpr const char* Surface_mesh_parameterization_Two_vertices_parameterizer_3_parameterize = "maps two extreme vertices of the 3D mesh and mark them as parameterized .

VertexUVmap must be a model of ReadWritePropertyMap with boost::graph_traits<
Triangle_mesh >::vertex_descriptor as key type and Point_2 (type deduced from
Triangle_mesh using Kernel_traits ) as value type. VertexIndexMap must be a
model of ReadablePropertyMap with boost::graph_traits< Triangle_mesh
>::vertex_descriptor as key type and a unique integer as value type.
VertexParameterizedMap must be a model of ReadWritePropertyMap with
boost::graph_traits< Triangle_mesh >::vertex_descriptor as key type and a
Boolean as value type. mesh a triangulated surface. bhd a halfedge descriptor
on the boundary of mesh . uvmap an instantiation of the class VertexUVmap .
vimap an instantiation of the class VertexIndexMap . vpmap an instantiation of
the class VertexParameterizedMap . mesh must be a triangular mesh. The
vertices must be indexed (vimap must be initialized).

Parameters
----------
mesh : const Triangle_mesh &
bhd : halfedge_descriptor
uvmap : VertexUVmap
vimap : VertexIndexMap
vpmap : VertexParameterizedMap

Returns: Error_code";
constexpr const char* Surface_mesh_parameterization_Two_vertices_parameterizer_3_is_border_convex = "indicates if the border's shape is convex.

Meaningless for free border parameterization algorithms.

Returns: bool";

// Parameterizer_3
constexpr const char* Parameterizer_3__class__ = "Parameterizer_3 is a concept of parameterization object for a given type of mesh, TriangleMesh , which must be a model of the FaceGraph concept.";

constexpr const char* Parameterizer_3_TriangleMesh = "A given polygon mesh type, TriangleMesh , which is a model of the FaceGraph concept.

Returns: unspecified_type";
constexpr const char* Parameterizer_3_parameterize = "Assign a 2D position (i.e. a (u, v) pair) on the shape to (some of) the vertices of the mesh.

Mark them as parameterized . VertexUVmap must be a model of
ReadWritePropertyMap with boost::graph_traits< TriangleMesh
>::vertex_descriptor as key type and Point_2 (type deduced from TriangleMesh
using Kernel_traits ) as value type. VertexIndexMap must be a model of
ReadablePropertyMap with boost::graph_traits< TriangleMesh
>::vertex_descriptor as key type and a unique integer as value type.
VertexParameterizedMap must be a model of ReadWritePropertyMap with
boost::graph_traits< TriangleMesh >::vertex_descriptor as key type and a
Boolean as value type. mesh a triangulated surface. bhd a halfedge descriptor
on the boundary of mesh . uvmap an instantiation of the class VertexUVmap .
vimap an instantiation of the class VertexIndexMap . vpmap an instantiation of
the class VertexParameterizedMap . mesh must be a triangular mesh. The
vertices must be indexed ( vimap must be initialized)

Parameters
----------
mesh : const TriangleMesh &
bhd : halfedge_descriptor
uvmap : VertexUVMap
vimap : VertexIndexMap
vpmap : VertexParameterizedMap

Returns: Error_code";


// std
constexpr const char* std__class__ = "STL namespace.";

} // namespace Surface_mesh_parameterization
} // namespace docstrings
} // namespace cgalpy

#endif // CGAL_PYTHON_DOCSTRINGS_SURFACE_MESH_PARAMETERIZATION_H
