#!/usr/bin/env python3
"""
cpp_docstrings_from_json.py
Generate C++ docstring header (.hpp) and definition (.cpp) files from a JSON docstring file.

Usage:
    python3 cpp_docstrings_from_json.py <input.json> <module_name> <out_dir_include> <out_dir_lib>
"""

import json
import sys
from pathlib import Path

_CPP_KEYWORDS = {
    "alignas","alignof","and","and_eq","asm","auto","bitand","bitor","bool",
    "break","case","catch","char","char8_t","char16_t","char32_t","class","compl",
    "concept","const","consteval","constexpr","constinit","const_cast","continue",
    "co_await","co_return","co_yield","decltype","default","delete","do","double",
    "dynamic_cast","else","enum","explicit","export","extern","false","float","for",
    "friend","goto","if","inline","int","long","mutable","namespace","new","noexcept",
    "not","not_eq","nullptr","operator","or","or_eq","private","protected","public",
    "reinterpret_cast","requires","return","short","signed","sizeof","static",
    "static_assert","static_cast","struct","switch","template","this","thread_local",
    "throw","true","try","typedef","typeid","typename","union","unsigned","using",
    "virtual","void","volatile","wchar_t","while","xor","xor_eq",
    "override","final","import","module","type",
}

def sanitize_cpp_identifier(name: str) -> str:
    """Append '_' if name is a C++ reserved keyword."""
    return (name + "_") if name in _CPP_KEYWORDS else name

def make_identifier(class_name: str, member_name, overload_index: int) -> str:
    safe_class = sanitize_cpp_identifier(class_name)
    if member_name is None:
        return f"{safe_class}__class__"
    safe_member = sanitize_cpp_identifier(member_name)
    if overload_index == 0:
        return f"{safe_class}_{safe_member}"
    return f"{safe_class}_{safe_member}_{overload_index}"

def build_docstring(entry: dict) -> str:
    parts = []
    brief = (entry.get("brief") or "").strip()
    if brief:
        parts.append(brief)
    ret = (entry.get("return_type") or "").strip()
    if ret:
        parts.append(f"Returns: {ret}")
    text = " ".join(parts)
    text = text.replace("\\", "\\\\").replace('"', '\\"')
    return text

def collect_entries(data: dict) -> list:
    entries = []
    for class_name, class_obj in data.items():
        if not isinstance(class_obj, dict):
            continue
        class_doc = (class_obj.get("brief") or "").strip()
        class_doc = class_doc.replace("\\", "\\\\").replace('"', '\\"')
        entries.append((make_identifier(class_name, None, 0), class_doc))
        members = class_obj.get("members") or []
        seen: dict = {}
        for member in members:
            mname = (member.get("name") or "").strip()
            if not mname:
                continue
            count = seen.get(mname, 0)
            seen[mname] = count + 1
            entries.append((make_identifier(class_name, mname, count),
                            build_docstring(member)))
    return entries

def generate_hpp(module: str, entries: list) -> str:
    guard = f"CGALPY_{module.upper()}_DOCSTRINGS_HPP"
    lines = [
        f"// AUTO-GENERATED by cpp_docstrings_from_json.py \u2014 DO NOT EDIT",
        f"// Library: cgalpy  Module: {module}",
        f"#ifndef {guard}",
        f"#define {guard}",
        "",
        "namespace cgalpy {",
        "namespace docstrings {",
        f"namespace {module} {{",
        "",
    ]
    for ident, _ in entries:
        lines.append(f"extern const char* const {ident};")
    lines += [
        "",
        f"}} // namespace {module}",
        "} // namespace docstrings",
        "} // namespace cgalpy",
        "",
        f"#endif // {guard}",
        "",
    ]
    return "\n".join(lines)

def generate_cpp(module: str, entries: list) -> str:
    lines = [
        f"// AUTO-GENERATED by cpp_docstrings_from_json.py \u2014 DO NOT EDIT",
        f"// Library: cgalpy  Module: {module}",
        f'#include "{module}_docstrings.hpp"',
        "",
        "namespace cgalpy {",
        "namespace docstrings {",
        f"namespace {module} {{",
        "",
    ]
    for ident, doc in entries:
        lines.append(f'const char* const {ident} = "{doc}";')
    lines += [
        "",
        f"}} // namespace {module}",
        "} // namespace docstrings",
        "} // namespace cgalpy",
        "",
    ]
    return "\n".join(lines)

def main() -> None:
    if len(sys.argv) != 5:
        print(__doc__)
        sys.exit(1)
    json_path   = Path(sys.argv[1])
    module      = sys.argv[2]
    out_include = Path(sys.argv[3])
    out_lib     = Path(sys.argv[4])
    data = json.loads(json_path.read_text(encoding="utf-8"))
    entries = collect_entries(data)
    out_include.mkdir(parents=True, exist_ok=True)
    out_lib.mkdir(parents=True, exist_ok=True)
    hpp_path = out_include / f"{module}_docstrings.hpp"
    cpp_path = out_lib     / f"{module}_docstrings.cpp"
    hpp_path.write_text(generate_hpp(module, entries), encoding="utf-8")
    cpp_path.write_text(generate_cpp(module, entries), encoding="utf-8")
    print(f"[OK] {hpp_path}")
    print(f"[OK] {cpp_path}")

if __name__ == "__main__":
    main()
