#!/usr/bin/env python3
"""
cpp_docstrings_from_json.py
Generate C++ docstring header (.hpp) and definition (.cpp) from a JSON docstring file.

Usage:
    python3 cpp_docstrings_from_json.py <json_file> <module_name> <include_out_dir> <lib_out_dir>
"""

import json
import re
import sys
from collections import Counter
from pathlib import Path

CPP_KEYWORDS = {
    "alignas","alignof","and","and_eq","asm","auto","bitand","bitor","bool",
    "break","case","catch","char","char8_t","char16_t","char32_t","class",
    "compl","concept","const","consteval","constexpr","constinit","const_cast",
    "continue","co_await","co_return","co_yield","decltype","default","delete",
    "do","double","dynamic_cast","else","enum","explicit","export","extern",
    "false","float","for","friend","goto","if","inline","int","long","mutable",
    "namespace","new","noexcept","not","not_eq","nullptr","or","or_eq",
    "private","protected","public","register","reinterpret_cast","requires",
    "return","short","signed","sizeof","static","static_assert","static_cast",
    "struct","switch","template","this","thread_local","throw","true","try",
    "typedef","typeid","typename","union","unsigned","using","virtual","void",
    "volatile","wchar_t","while","xor","xor_eq",
}
# NOTE: "operator" is NOT in CPP_KEYWORDS.
# "SomeClass_operator" is a valid C++ identifier.

def strip_namespace(name):
    result = name.replace("::", "_")
    if result.startswith("CGAL_"):
        result = result[len("CGAL_"):]
    return result

def sanitize_member_name(name):
    name = re.sub(r"<.*", "", name)
    if name.startswith("operator") and len(name) > len("operator"):
        rest = name[len("operator"):]
        if not re.match(r"^[A-Za-z0-9_]", rest):
            name = "operator"
    name = re.sub(r"[^A-Za-z0-9_]", "", name)
    if name in CPP_KEYWORDS:
        name = name + "_"
    return name

def make_identifier(class_id, member_name, overload_idx):
    base = f"{class_id}_{member_name}"
    return base if overload_idx == 0 else f"{base}_{overload_idx}"

def escape_string(s):
    return s.replace("\\", "\\\\").replace('"', '\\"')

def generate(json_path, module_name, include_out, lib_out):
    data = json.loads(json_path.read_text())
    declarations = []
    definitions  = []

    for raw_class_name, class_info in data.items():
        class_id = strip_namespace(raw_class_name)
        brief    = escape_string(class_info.get("brief", "").strip())
        detailed = escape_string(class_info.get("detailed", "").strip())
        doc_text = (brief + (" " + detailed if detailed else "")).strip()
        cid = f"{class_id}___class__"
        declarations.append(f'extern const char* const {cid};')
        definitions.append(f'const char* const {cid} = "{doc_text}";')

        name_seen = Counter()
        for m in class_info.get("members", []):
            sname = sanitize_member_name(m["name"])
            idx   = name_seen[sname]; name_seen[sname] += 1
            ident = make_identifier(class_id, sname, idx)
            m_brief = escape_string(m.get("brief", "").strip())
            ret     = m.get("return_type", "").strip()
            m_doc   = m_brief
            if ret and ret not in ("void", "", "unspecified_type"):
                m_doc += (f" Returns: {ret}" if m_doc else f"Returns: {ret}")
            declarations.append(f'extern const char* const {ident};')
            definitions.append(f'const char* const {ident} = "{m_doc.strip()}";')

    guard    = f"CGALPY_{module_name.upper()}_DOCSTRINGS_HPP"
    hpp_name = f"{module_name}_docstrings.hpp"
    cpp_name = f"{module_name}_docstrings.cpp"

    hpp_lines = [
        f"// AUTO-GENERATED by cpp_docstrings_from_json.py — DO NOT EDIT",
        f"// Library: cgalpy  Module: {module_name}",
        f"#ifndef {guard}", f"#define {guard}", "",
        "namespace cgalpy {", "namespace docstrings {",
        f"namespace {module_name} {{", "",
    ] + declarations + [
        "", f"}} // namespace {module_name}",
        "} // namespace docstrings", "} // namespace cgalpy", "",
        f"#endif // {guard}", "",
    ]
    cpp_lines = [
        f"// AUTO-GENERATED by cpp_docstrings_from_json.py — DO NOT EDIT",
        f"// Library: cgalpy  Module: {module_name}",
        f'#include "{hpp_name}"', "",
        "namespace cgalpy {", "namespace docstrings {",
        f"namespace {module_name} {{", "",
    ] + definitions + [
        "", f"}} // namespace {module_name}",
        "} // namespace docstrings", "} // namespace cgalpy", "",
    ]

    include_out.mkdir(parents=True, exist_ok=True)
    lib_out.mkdir(parents=True, exist_ok=True)
    (include_out / hpp_name).write_text("\n".join(hpp_lines))
    (lib_out     / cpp_name).write_text("\n".join(cpp_lines))
    print(f"[OK] {include_out / hpp_name}  ({len(declarations)} declarations)")
    print(f"[OK] {lib_out / cpp_name}  ({len(definitions)} definitions)")

if __name__ == "__main__":
    if len(sys.argv) != 5:
        print(__doc__); sys.exit(1)
    generate(Path(sys.argv[1]), sys.argv[2], Path(sys.argv[3]), Path(sys.argv[4]))
