# Assuming circle segment traits - should be determined by cmake...
import Basic_traits
import XMonotoneTraits

Geometry_traits_2 = Circle_segment_traits_2

class Circle_segment_traits_2(XMonotoneTraits._XMonotoneTraits):
    class CoordNT():
        def is_extended(self) -> bool: ...
    class Point_2(Basic_traits._Basic_traits.Point_2):
        def x(self) -> Geometry_traits_2.CoordNT: ...
        def y(self) -> Geometry_traits_2.CoordNT: ...
    def Is_in_x_range_2(self, p: Geometry_traits_2.Point_2) -> bool: ...