from typing import overload

class _Basic_traits():
    class Point_2():
        def __init__(self): ...
    class X_monotone_curve_2():
        def __init__(self): ...
    class Equal_2(): 
        @overload
        def __call__(self, p: _Basic_traits.Point_2, q: _Basic_traits.Point_2) -> bool: ...
        @overload
        def __call__(self, p: _Basic_traits.X_monotone_curve_2, q: _Basic_traits.X_monotone_curve_2) -> bool: ...
    def equal_2_object(self) -> _Basic_traits.Equal_2: ...