#define CGAL_HEADER_ONLY 1

#define CGALPY_EPEC_KERNEL 0
#define CGALPY_EPIEC_KERNEL 1

#ifndef CGALPY_KERNEL
#define CGALPY_KERNEL 0
#endif

#define CGALPY_DEFAULT_DCEL 0
#define CGALPY_EXTENDED_DCEL 1

#ifndef CGALPY_DCEL
#define CGALPY_DCEL 0
#endif

#define CGALPY_ARR_LINEAR_TRAITS 0
#define CGALPY_ARR_SEGMENT_TRAITS 1
#define CGALPY_ARR_NON_CACHING_SEGMENT_TRAITS 2
#define CGALPY_ARR_CONIC_TRAITS 3
#define CGALPY_ARR_ALGEBRAIC_SEGMENT_TRAITS 4
#define CGALPY_ARR_CIRCLE_SEGMENT_TRAITS 5

#ifndef CGALPY_TRAITS
#define CGALPY_TRAITS 0
#endif